### ISSUE TITLE
EARTH_GRID_COMP should be named UFSDriver

### ISSUE THREAD

**Issue by rsdunlapiv** [ufs-community/ufs-weather-model#1017]
## Description
In ESMF, "gridded components" or "gridcomps" are plain ESMF components (no NUOPC).  The UFS Driver is a NUOPC Driver, and so the term "EARTH_GRID_COMP" is not as precise as it could be, and does not communicate that the top-level component has NUOPC interfaces.  

This goes along with recent efforts to remove the NEMS repository and clean up the fv3 cap.

Some possibilities for this name:
- UFSDriver
- UFS_Driver
- UFSEarthDriver

**Comment by rsdunlapiv** [comment]
relates to #998

**Comment by arunchawla-NOAA** [comment]
@rsdunlapiv is this really a bug ? or a discussion ?

**Comment by junwang-noaa** [comment]
We discussed this issue, we will go with the name UFSDriver.
