### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [ufs-community/ufs-weather-model#1021]
I suggest adding the topics `nwp`, `numerical-weather-prediction`, `weather` in the About section.

I have added your repo to the Climate and Weather section of a [list of Fortran codes](https://github.com/Beliavsky/Fortran-code-on-GitHub) that I maintain.

**Comment by junwang-noaa** [comment]
@Beliavsky It's great  to hear that you added the repo to your list. For your suggestion, can you clarify which "About section" you are referring to? Thanks

**Comment by Beliavsky** [comment]
See for example the topics `meteorology` `nwp` `numerical-weather-prediction` in the About section at https://github.com/ECCC-ASTD-MRD/librmn .
How to add topics is described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by junwang-noaa** [comment]
@Beliavsky The topics were added.  Please let me know if you have any comments/suggestions. Thanks.

**Comment by Beliavsky** [comment]
Very good, thanks.
