### ISSUE TITLE
unify the filled_value in atmosphere history fiels

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1031]
## Description
Current UFS output uses different missing values (FillValue) in atmosphere 3D field files and the surface files. In the project of unifying the post interfaces for all the applications, we need to first update those files to use a unified missing value in all the history files for all the applications.   

## Solution
Use a unified missing value so that POST processing can use the single missing value to identify grid points with missing value.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by DeniseWorthen** [comment]
@junwang-noaa Can we close this issue? I thought it had been resolved.
