### ISSUE TITLE
IAU in MOM6 is broken

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-weather-model#1046]
## Description
When I turn on the IAU in the ocean ( but setting ODA_INCUPD = True and other associated namelist varibles)

I get:

FATAL from PE   XXX: Attempted to register oda_incupd_ncount but the restart registry is locked.

## Additional context
Since the regression test for the ocean IAU was with the nems mediator, it was removed several months ago, and this change of behavior was not caught.

**Comment by arunchawla-NOAA** [comment]
@pjpegion has an issue been opened in the MOM6 repository ?

**Comment by pjpegion** [comment]
This issue is closed with https://github.com/ufs-community/ufs-weather-model/pull/1135
