### ISSUE TITLE
Enable Thompson microphysics when coupling with UFS-Aerosols

### ISSUE THREAD

**Issue by rmontuoro** [ufs-community/ufs-weather-model#1047]
## Description
Due to legacy settings implemented for GEFS-Aerosols, the Thompson microphysics scheme cannot be selected when the UFS weather model is run with prognostic aerosols (UFS-Aerosols).

This update is required to perform prototype 8 experiments.

## Solution
The Thompson MP scheme should be enabled when coupling with UFS-Aerosols, making sure that both microphysics and aerosol tracers are properly processed and diffused by PBL schemes.

**Comment by yangfanglin** [comment]
@rmontuoro UFS prototype p8b is not using the aerosol aware version of Thompson MP.  Only rain_nc and ice_nc are added as two extra tracers for transport. Are you planning to activate the aerosol-aware version of Thompson MP and use GOCART aerosols to determine water and ice friendly aerosol number concentrations used by Thompson MP ?

**Comment by rmontuoro** [comment]
@yangfanglin - This PR is only meant to enable Thompson MP when UFS-Aerosols is coupled for future prototype development. Connecting prognostic aerosols with the aerosol-aware Thompson MP has not been planned for prototype 8.
