### ISSUE TITLE
Update GOCART to version 2.0.2

### ISSUE THREAD

**Issue by rmontuoro** [ufs-community/ufs-weather-model#1048]
## Description
The GOCART submodule needs to be updated to point to a more recent GOCART version (2.0.2). This change also requires updating GOCART's resource files (`*.rc`) used in regression tests.

This update is required for prototype 8 experiments.

**Comment by yangfanglin** [comment]
@rmontuoro  Is there a document describing the updates included in GOCART version (2.0.2) ?

**Comment by rmontuoro** [comment]
@yangfanglin - A summary of the updates introduced between release 2.0.0-rc.1 (the GOCART version currently in the UFS weather model) and 2.0.2 is available here: https://github.com/GEOS-ESM/GOCART/blob/develop/CHANGELOG.md.
