### ISSUE TITLE
Regional hi-res, small domain new regression test

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [ufs-community/ufs-weather-model#1054]
## Description
Regional group asked to test 3km resolution regional application.

## Solution
Since full domain would take a lot of time and CPU resources, we came up with very small domain (350x200 points) with 6 hours run in ~4.5 minutes real time.

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA You can also set up a full domain 3km parallel test and run it in our weekly test, which is running on weekends. Please see https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt_weekly.conf.

**Comment by RatkoVasic-NOAA** [comment]
Great, we'll put large domain in weekly tests, and small domain in regular tests.
