### ISSUE TITLE
Add vertical dimension to certain surface fields

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [ufs-community/ufs-weather-model#1055]
## Description
This discussion started in https://github.com/ufs-community/ufs-weather-model/issues/1052 but continuing it here.

Many of the fields in the `sfcfNNN.nc` files look like so:
```
	float soilt1(time, tile, grid_yt, grid_xt) ;
	float soilt2(time, tile, grid_yt, grid_xt) ;
	float soilt3(time, tile, grid_yt, grid_xt) ;
	float soilt4(time, tile, grid_yt, grid_xt) ;
```
Which is 4 layers of soil temperature. 

I think it would make more sense for these fields to be instead like so:
```
	float soilt(time, tile, zsoil, grid_yt, grid_xt) ;
```
or something like that.

This would greatly simplify I/O routines as it would be a few variables with a vertical dimension rather than k*variables where k is the number of layers. I also suspect that the total file size would decrease with fewer variables being defined (but not sure by how much).

## Solution
Update fields that should have a vertical component to include one in the write-grid component output.

## Alternatives
Keep the files as is.

## Related to
The UPP and other downstream users may depend on this change?

**Comment by DusanJovic-NOAA** [comment]
I updated the write grid component to allow 3d soil variables to be written out in history files. 
I saved a set of surface history files from two tests (control_CubedSphereGrid and  control_CubedSphereGrid_parallel) in this directory on hera:

/scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/zsoil_test_files

@CoryMartin-NOAA Please take a look and let us know if this is what you need.

The code changes are in this branch:

https://github.com/DusanJovic-NOAA/fv3atm/tree/zsoil

**Comment by CoryMartin-NOAA** [comment]
Thanks @DusanJovic-NOAA , @davidnew-noaa and I will take a look and get back to you soon.

**Comment by junwang-noaa** [comment]
@CoryMartin-NOAA May I ask if you have looked at the updates? Thanks

**Comment by CoryMartin-NOAA** [comment]
Sorry @junwang-noaa we have not yet, let us do that today/tomorrow and get back to you midweek.

**Comment by CoryMartin-NOAA** [comment]
@junwang-noaa @DusanJovic-NOAA is it easy enough to make this an option or would we need to switch from separate variables to z dimension for the surface fields? I ask because I suspect if this changes for the gaussian output, for GFSv17 we will need to make modifications to GSI and other software (UPP?) to handle this change, and it may be something we want to discuss with other groups/parties before making that change as it would be added work.

**Comment by DusanJovic-NOAA** [comment]
To enable 3d soil fields one would need to update `diag_table` file by adding:

```
"gfs_sfc",     "soilt",       "soilt"      "fv3_history2d",  "all",  .false.,  "none",  2    
```
and removing:

```
"gfs_sfc",     "soilt1",      "soilt1"     "fv3_history2d",  "all",  .false.,  "none",  2
"gfs_sfc",     "soilt2",      "soilt2"     "fv3_history2d",  "all",  .false.,  "none",  2
"gfs_sfc",     "soilt3",      "soilt3"     "fv3_history2d",  "all",  .false.,  "none",  2
"gfs_sfc",     "soilt4",      "soilt4"     "fv3_history2d",  "all",  .false.,  "none",  2

```
Similar for 'soilw' and 'soill'.

So it is optional (opt-in) feature. We can continue to write out a set of 2d soil variables, switch to 3d soil variables, or even write out both, which I did while testing to make sure the values are identical.

**Comment by CoryMartin-NOAA** [comment]
That's perfect, thanks @DusanJovic-NOAA ! 

I just did a quick cursory look and I think the sample sfcf006 files look good to me but want @davidnew-noaa to do a bit closer look before we 100% give the thumbs up. Thanks again for doing this!

**Comment by DavidNew-NOAA** [comment]
Surface files look good to me. I will start getting JEDI ready to read multi-level soil variables. Thank you!

**Comment by CoryMartin-NOAA** [comment]
Looks like you can start the PR process, thanks again @DusanJovic-NOAA and @junwang-noaa !

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA When you start the PR to output 3D land fields, would you like to include the corresponding changes in the interface of inline post? such as:
https://github.com/NOAA-EMC/fv3atm/blob/develop/io/post_fv3.F90#L1595

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA When you start the PR to output 3D land fields, would you like to include the corresponding changes in the interface of inline post? such as: https://github.com/NOAA-EMC/fv3atm/blob/develop/io/post_fv3.F90#L1595

I added support for 3d soil variables in inline post. See:

https://github.com/NOAA-EMC/fv3atm/commit/899c24d1b72928273c950786c20b2d2d888830ca
