### ISSUE TITLE
Mixed mode FMS for coupled runs

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1062]

**Comment by DeniseWorthen** [comment]
Need a new CMake flag to use -DConstants=GFS (default is GFDL). HPC-stack issue is open. We can put the change on Acorn (NCEP-libs); EPIC will need to take care of RDHPCS machines. Need WCOSS2 updated in the 2month rotation.

**Comment by jkbk2004** [comment]
@junwang-noaa @DeniseWorthen I agree that this is a good timing to make a transition of RDHPCs hpc-stack maintenance to EPIC. I will coordinate on EPIC side.

**Comment by DeniseWorthen** [comment]
Need code update to dy-core. fms2022.03 was installed acorn. version currently on wcoss2 may have wrong -dconstants present. Need compile fixed on wcoss2; the commit update to dycore for fms 2022.03 asap. 

Still no RT for mixed-mode.

Updates for chunking will require 2022.04. 

Issue of maintaining different constants vs what is default for FMS; Physics group would need to evaluate change in the values. There is a cross-agency project to use a dictionary to share constant constants.

**Comment by DeniseWorthen** [comment]
target install is 2022.04 on wcoss2; no current update on when this will actually be installed on wcoss2. in progress.

Moorthi reports that mixed-mode is working fine as you don't care about BL changes due to constants used (C3072 10day case).

**Comment by DeniseWorthen** [comment]
@binli2337 has opened the PR a test using mixed-model for coupled model. FV3 will be 32-bit but MOM6 will be 64-bit in the new test. ORTs with mixed-mode feature applicable  passes. 

The coupled model, depending on implementation, will run either 32/64 or 64/64 so we will need to maintain tests for both configurations.

**Comment by junwang-noaa** [comment]
The code was committed, close issue.
