### ISSUE TITLE
Integrate WW3 CMake build

### ISSUE THREAD

**Issue by kgerheiser** [ufs-community/ufs-weather-model#1074]
## Description

A CMake build was recently added to WW3 and this build should be integrated in the UFS. This will significantly simplify the build because it will integrate directly into UFS with `add_subdirectory`.

This block of code:

https://github.com/ufs-community/ufs-weather-model/blob/34a5895b847f276335bd40f03321011d05d1b328/CMakeLists.txt#L157-L179

becomes:

```
  set(SWITCH "multi_esmf")
  set(MULTI_ESMF ON)
  add_subdirectory(WW3)
```

And linking the library is:

```
target_link_libraries(ufs PUBLIC WW3::WW3)
```

A working branch can be found here:  https://github.com/jessicameixner-noaa/ufs-weather-model/tree/feature/ww3-cmake

@JessicaMeixner-NOAA did some Initial testing and tests pass, but there is an error on WCOSS-Dell related to #1072

**Comment by DeniseWorthen** [comment]
@kgerheiser There will be an alternate nuopc cap which runs on a mesh added to the WW3 dev/ufs-weather-model branch. I am building with an alternate switch file, source file list and a different ``FRONT_WW3`` definition in the CMakeLists.txt. 

The mesh cap will be used w/in UWM for the S2SW and HAFSW apps. The ATMW application will continue to use the current build configuration (switch, file list and ``FRONT_WW3``).  

What changes will be required to have two alternate WW3 builds in UWM?

**Comment by kgerheiser** [comment]
Setting a different switch file based on some other option is pretty simple, and would be something like 

```
if(S2SW)
  set(switch xxxx)
else()
  set(switch multi_esmf`
endif
```

Different source files will have to be handled on the WW3 side through a new CMake option or something.

**Comment by DeniseWorthen** [comment]
At the app level, would I define a second ``WW3`` option here, 

```
set(WW3             OFF CACHE BOOL "Enable WW3")
```

and here 

```
if(WW3)
  add_dependencies(ufs ww3_nems)
  list(APPEND _ufs_defs_private FRONT_WW3=WMESMFMD)
```
Will I need a dependency other than ``ww3_nems`` here?

Then  in ``cmake/configure_apps.cmake``, I'd define the alternate ``WW3``. 

```
  if(APP MATCHES "S2SW")
    set(WW3      ON  CACHE BOOL "Enable WAVEWATCH III"       FORCE)
    message("Configuring UFS app in S2S with Waves mode")
  else()
```

**Comment by junwang-noaa** [comment]
@kgerheiser I am curious, I assume there is no change on FV3 side with the ww3 cmake, why is there an issue compiling the code on dell? Is the ww3 cmake build taking more memory? The current ufs-weather-model develop branch can be built with ww3.

**Comment by kgerheiser** [comment]
*  I assume there is no change on FV3 side with the ww3 cmake

No change there, only the build system changes

* Why is there an issue compiling the code on dell?

The build runs out of memory on WOCSS-Dell. For whatever reason the build must take more memory to compile than the current build.

**Comment by junwang-noaa** [comment]
@kgerheiser @JessicaMeixner-NOAA Would you please try with the latest develop branch to see if you still have issue compiling the code on dell? After we added the compile option change to O0 for GFS_typedefs.F90, the compile issue was resolved for PR#1032. Thanks.

**Comment by JessicaMeixner-NOAA** [comment]
I'm running on wcoss-dell now to see if this and updates from @kgerheiser helped.

**Comment by kgerheiser** [comment]
The compile issue has been fixed
