### ISSUE TITLE
ufs-weather-model/fv3atm/upp 2D decomposed inline post

### ISSUE THREAD

**Issue by JesseMeng-NOAA** [ufs-community/ufs-weather-model#1078]
## Description

The community upp is currently decomposed on latitudes (y-direction) only. As the ufs-weather-model is making 2D decomposition in both latitudes and longitudes (Y and X), one of the upp refactoring tasks is to support ufs-weather-model inline post 2D decomposition functionality.

## Solution

A ufs-weather-model feature post_2d_decomp is created for this test with inline post turned on in the control_2dwrtdecomp and regional_control_2dwrtdecomp tests,
https://github.com/JesseMeng-NOAA/ufs-weather-model/tree/feature/post_2d_decomp
PR https://github.com/ufs-community/ufs-weather-model/pull/1077

A fv3atm feature post_2d_decomp is created with modified io drivers to call upp/post_2d_decomp,
https://github.com/JesseMeng-NOAA/fv3atm/tree/feature/post_2d_decomp
PR https://github.com/NOAA-EMC/fv3atm/pull/494

The upp/post_2d_decomp branch can be found at
https://github.com/WenMeng-NOAA/UPP/tree/post_2d_decomp

**Comment by junwang-noaa** [comment]
The corresponding PR is #1211

**Comment by junwang-noaa** [comment]
The code was merged in PR#1211. The issue will be closed.
