### ISSUE TITLE
ufs-weather-model upp error when using llvm-clang on macOS

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#1080]
## Description
Provide a clear and concise description of what the bug is.
Also give a description of what behavior you expected to happen.

### To Reproduce:
1. Use llvm-clang on macOS instead of native apple-clang (this uses llvm-ranlib)
2. Compile ufs-weather-model
```
...
Files/upp.dir/ZENSUN.f.o
/usr/local/opt/llvm/bin/llvm-ranlib -c libupp.a
/usr/local/opt/llvm/bin/llvm-ranlib: error: Invalid option: '-c'
make[2]: *** [FV3/upp/sorc/ncep_post.fd/libupp.a] Error 1
make[2]: *** Deleting file `FV3/upp/sorc/ncep_post.fd/libupp.a'
make[1]: *** [FV3/upp/sorc/ncep_post.fd/CMakeFiles/upp.dir/all] Error 2
make: *** [all] Error 2
```

## Additional context
This is a known bug in UPP for which I have submitted a bugfix PR a few weeks ago:
https://github.com/NOAA-EMC/NCEPLIBS-bufr/issues/188
https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/189

The same issue also exists in the ufs-weather-model itself:
https://github.com/ufs-community/ufs-weather-model/blob/38aa6340894bd6320fde87ffe1dcee3c0d393c08/cmake/Intel.cmake#L51

**Comment by zach1221** [comment]
@climbfuji can this issue be closed? I see both the below have been closed a while back.
 https://github.com/NOAA-EMC/NCEPLIBS-bufr/issues/188
https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/189

**Comment by climbfuji** [comment]
I think yes. We use recent versions of bufr that have the bug fix included.

**Comment by zach1221** [comment]
> I think yes. We use recent versions of bufr that have the bug fix included.

Ok, great. I'll go ahead and close
