### ISSUE TITLE
RRTMGP in Prototype 8

### ISSUE THREAD

**Issue by dustinswales** [ufs-community/ufs-weather-model#1093]
## Description
Changes to RRTMGP enabled ccpp-physics for prototype 8.

## Related to
- https://github.com/ufs-community/ufs-weather-model/pull/1090
- https://github.com/NOAA-EMC/fv3atm/pull/498
- https://github.com/NCAR/ccpp-physics/pull/871

**Comment by junwang-noaa** [comment]
PR#1090 was committed.
