### ISSUE TITLE
land surface upgrades for prototype P8

### ISSUE THREAD

**Issue by HelinWei-NOAA** [ufs-community/ufs-weather-model#1094]
To address some biases found in PT7

- consistent surface coupling with GFS surface layer scheme
- add stability subroutine call to inside NoahMP
- add thermal roughness length options
- changes to snow parameters for thermal conductivity and compaction
- modification to soil thermal conductivity
- diagnostics

**Comment by junwang-noaa** [comment]
The code is merged, the issue will be closed,
