### ISSUE TITLE
Add UFS-AQM regression test 

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1099]
## Description
A UFS-AQM regression test will be set up and added to ufs-weather-model regression test suite. It will work on the ufs-weather-model supported platforms.  

## Solution
Once the UFS-AQM build system is set up, a UFS-AQM regression test will be set up and run in the ufs-weather-model regression test suite.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by BrianCurtis-NOAA** [comment]
Issue i'm running into:
```
91: forrtl: severe (19): invalid reference to variable in NAMELIST input, unit -5, file Internal Formatted NML Read, 
line -1, position 20
```
using: https://github.com/BrianCurtis-NOAA/ufs-weather-model/tree/feature/aqm_test

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA Where is your run directory?

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa /scratch1/NCEPDEV/stmp2/Brian.Curtis/FV3_RT/rt_148153/control_atmaq

I'm using # to mark the variables I do not see in https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/regional.nml.IN

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA The lndp_each_step is not an valid variable in gfs_physics_nml any more. Also you need to have the cires_ugwp_nml in the input.nml. Please see /scratch1/NCEPDEV/stmp2/Jun.Wang/control_atmaq/input.nml as example.
