### ISSUE TITLE
is the build script necessary?

### ISSUE THREAD

**Issue by edwardhartnett** [ufs-community/ufs-weather-model#110]
There is a build script that calls cmake.

Seems like CMakeLists.txt is the build script, and another is not needed. By adding the build script you are removing the user's ability to easily control the build, for example by setting an install directory with a -D option on the cmake invokation.

Seems like everything done in the script can be done by cmake instead. I can submit a PR with these changes, if there is agreement...

**Comment by DusanJovic-NOAA** [comment]
Ability to control cmake invocation is not removed.

You can pass any -D option to cmake by setting CMAKE_FLAGS variable before you invoke build.sh. build.sh is a small wrapper around cmake/make provided for convenience. 

You can still run everything manually, if you know how to do it:

```
mkdir <build_dir>
cd <build_dir>
cmake .......
make .......
```
and have (full) ability to control the build process. 

You do not have to use build.sh.

**Comment by edwardhartnett** [comment]
OK thanks, I'll give that a try.

**Comment by edwardhartnett** [comment]
OK, but what about all this. Are these extra steps, done in the build script, not necessary? For example, to run ccpp_prebuild.py?

```
set +e
echo "Calling ccpp_prebuild.py ..."
python2 ./FV3/ccpp/framework/scripts/ccpp_prebuild.py \
    --config=FV3/ccpp/config/ccpp_prebuild_config.py \
    --static \
    --suites=${CCPP_SUITES} \
    --builddir=${BUILD_DIR}/FV3 > ${BUILD_DIR}/ccpp_prebuild.log 2>&1
if [ $? -ne 0 ]; then
  echo "Call to ccpp_prebuild.py failed, check ${BUILD_DIR}/ccpp_prebuild.log"
  exit 1
fi
set -e

source ${BUILD_DIR}/FV3/ccpp/physics/CCPP_SCHEMES.sh
source ${BUILD_DIR}/FV3/ccpp/physics/CCPP_CAPS.sh
source ${BUILD_DIR}/FV3/ccpp/physics/CCPP_STATIC_API.sh

CMAKE_FLAGS+=" -DCCPP=ON -DSTATIC=ON -DSUITES=${CCPP_SUITES} -DNETCDF_DIR=${NETCDF}"
```

**Comment by DusanJovic-NOAA** [comment]
They are necessary.

**Comment by edwardhartnett** [comment]
What I meant by this ticket is that this necessary functionality might be rolled into the cmake build. In that case, there would be no need for a build.sh. 

In other cmake builds, for example NCEPLIBS and NCEPLIBS-external (as well as the vast majority of cmake builds for science software), cmake is invoked directly and executes the build. It seems that it could be the same with ufs-weather-model.

**Comment by DusanJovic-NOAA** [comment]
I see. In your first comment you asked about not being able to control cmake and not being able to pass -D flags to cmake. 

For the Short-Range Weather Application the build team is discussing that option. We will probably do something like that for the next release.

**Comment by edwardhartnett** [comment]
I'm looking at the entire build system, and attempting to set up CI for it. Hence all my recent questions. ;-)

Do I understand you correctly that you are discussing the removal of the build.sh script, and the transfer of that functionality to the cmake build? 

I would strongly recommend this course of action, to bring this build into accordance with standard practice.

**Comment by DusanJovic-NOAA** [comment]
No. At this moment we are not discussing removal of build.sh. But some people asked about moving the execution of ccpp_prebuild.py to cmake configure step.

**Comment by edwardhartnett** [comment]
OK, I suggest you move all functionality to the cmake script. This is the kind of thing that cmake is for. ;-)

**Comment by DusanJovic-NOAA** [comment]
See: https://github.com/DusanJovic-NOAA/ufs-weather-model/tree/cmake_ccpp_prebuild
