### ISSUE TITLE
HAFS related moving-nesting capability

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#1100]
## Description
Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Develop the moving-nesting capability needed by the UFS hurricane application (HAFS). And the storm-following moving-nesting (including ocean coupling for the moving nesting configuration) capability is one of the crucial development needed for high-resolution hurricane research and forecasting.

## Solution
Add a clear and concise description of what you want to happen.

- FV3dycore and FMS based moving-nesting (including for both global and regional configuration with one moving nest) capability is under development inside FV3atm and FV3dycore with collaborations among AOML/HRD, EMC, and GFDL. Both prescribed and storm-following moving nesting will be supported. And the internal vortex tracker (based on the HWRF version of the internal vortex tracker adapted from the GFDL vortex tracker) is added so that the moving nest can follow a specific storm (hurricane).

- Although the HAFS FV3ATM-HYCOM ocean coupling already works for the regional standalone HAFS FV3ATM configuration previously, it does not yet support the moving-nesting configuration. With the collaboration among the ESMF team, EMC and AOML, the HYCOM ocean coupling capability is expanded to also support the FV3ATM nesting configuration. With this development, the HYCOM ocean component will communicate through CMEPS with the FV3ATM parent domain, while the coupling variables (e.g., SST) received by the FV3ATM parent will be passed/downscaled to its nested domain within the FV3dycore.

- Expand the write grid component to support outputting the moving nest domain properly (more details can be seen in issue #1053). This is an collaborative effort among the ESMF Team, EMC and AOML. 

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

Not applicable. The above mentioned developments are ongoing and almost ready to be merged back to ufs-weather-model develop branch and the corresponding authoritative submodule branches. 

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- addressed by ufs-community/ufs-weather-model/pull/1104
- associated with noaa-emc/fv3atm/pull/501
- associated with NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/179

**Comment by DusanJovic-NOAA** [comment]
Merged in https://github.com/ufs-community/ufs-weather-model/commit/c2e6b223232a7e304f37059ad63f5c36b7b4317e
