### ISSUE TITLE
Naming of physics suites is a hodgepodge

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-weather-model#1106]
I'd like to propose the implementation of a [new naming convention for the suites](https://github.com/NCAR/ccpp-physics/wiki/Draft:-Naming-convention-for-CCPP-suites). We have previously received feedback that the suite names are a hodgepodge and need to be standardized. This new naming convention was discussed this week internally at DTC multi-institutional CCPP Code Management group meeting (with @yangfanglin, @grantfirl  and others). In both venues there was support for it. 

Please take a look at this proposal and let me know if you have any feedback. Unless we hear concerns, we'd like to implement these changes in the fv3atm for use in the upcoming UFS SRW and MRW releases (with corresponding changed to be made in the CCPP SIngle-Column Model). I believe changing the names will also require updates on the RTs and workflows.
Attn: @JacobCarley-NOAA @gsketefian

**Comment by AvichalMehra-NOAA** [comment]
@ligiabernardet will HAFS physics options be considered only in context of future plans for a UFS HAFS release?

**Comment by ligiabernardet** [comment]
@AvichalMehra-NOAA Thank you for your question. Your question made me realize that I need to provide more information. 

In order to have the suites/names proposed for the upcoming releases, the following actions will be needed:

- **dev_GFSv17_alpha** (developmental suite planned for GFS v17, first instantiation - alpha; uncoupled version): A new suite needs to be added (corresponds to p8c)
- **dev_GFSv17_coupled_alpha** (developmental suite planned for GFS v17, first instantiation - alpha; coupled version): A new suite needs to be added (corresponds to p8c coupled)
- **dev_RRFSv1_beta** (developmental suite planned for RRFS v1, second instantiation - beta): this suite already exists but name needs to change
- **dev_WoFSv1_alpha** (developmental suite planned for WoFS v1, first instantiation; alpha): A new suite needs to be added (similar to RRFS_v1nssl but with Noah LSM instead of NoahMP LSM)
- **dev_HRRR** (developmental suite analogous to the NOAA operational HRRR model): this suite already exists but name needs to change
- **dev_RAP** (developmental suite analogous to the NOAA operational RAP model): this suite already exists but name needs to change

For now I am just proposing to change the names of the suites that will be part of the releases. Since there is no public release planned for HAFS this year, this would not affect HAFS for now.

**Comment by ligiabernardet** [comment]
We have received feedback from @arunchawla-NOAA and the team working on the UFS SRW App release (planned for May 2022) that it is not feasible to implement the changes in suite names in time for that release. While we would like to go forward with these changes in suite names, we will likely postpone them.

**Comment by junwang-noaa** [comment]
@ligiabernardet The SRW release is out, do you want to leave this issue open or close this issue and open a new one when someone is working on it? Thanks.

**Comment by ligiabernardet** [comment]
We will start a new issue once we are ready to work on this.
