### ISSUE TITLE
P8c ICs

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1108]
## Description
This issue is to track the P8c ICs that will be used by the ufs-weather-model RT. It includes:
1. Ocean mask data
2. Oro data
3. Fixed files
4. ATM ICs created from the oro data/Fixed files with resolution: C48, C96. C192, C384, C768 and C1152
- The ATM ICs include aerosol ICs created from MERRA2 Reanalysis data
6. WW3 tripolar grid
7. WW3 ICs
8. Aerosol ICs

**Comment by junwang-noaa** [comment]
@DeniseWorthen @shansun6 @bingfu-NOAA @HelinWei-NOAA @aliabdolali If you have the data ready, would you please list the location in the issue? Thanks.

@yangfanglin @AvichalMehra-NOAA  @arunchawla-NOAA FYI.

**Comment by junwang-noaa** [comment]
Here is the location of oro data from @shansun6: 

/scratch1/BMC/gsd-fv3-dev/fv3data/lake_p8_modis/

**Comment by HelinWei-NOAA** [comment]
The new surface fixed fields using Shan's new oro data:
/scratch1/NCEPDEV/global/Helin.Wei/sfc_fixed_mar2022

**Comment by DeniseWorthen** [comment]
I've used the following staged input directory to test the j=1 feature:

INPUTDATA_ROOT="/scratch1/NCEPDEV/stmp4/Denise.Worthen/input-data-20211130

The following files from that directory will need to be used in the new input-data directory:

1) MOM6_FIX/100: ufs.topo_edits_011818.nc
2) CICE_FIX/100: mesh.mx100.nc, grid_cice_NEMS_mx100.nc, kmtu_cice_NEMS_mx100.nc
3) CICE_IC/100: cice_model_1.00.cpc.res_2011100100.nc, cice_model_1.00.cpc.res_20210322.nc

**Comment by bingfu-NOAA** [comment]
> @DeniseWorthen @shansun6 @bingfu-NOAA @HelinWei-NOAA @aliabdolali If you have the data ready, would you please list the location in the issue? Thanks.
> 
> @yangfanglin @AvichalMehra-NOAA @arunchawla-NOAA FYI.

@junwang-noaa  Can you confirm the case for regression test is still 20210322 06Z ?

**Comment by junwang-noaa** [comment]
@bingfu-NOAA The non-benchmark regression tests are using 20210222 06Z, cpld_bmark_p8 is using 2013040100. The RT weekly test cpld_bmark_p8_35d runs with [the 8 ICs ](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt_weekly.conf#L11)including the 4 seasons in 2012 and 2013.

**Comment by bingfu-NOAA** [comment]
@junwang-noaa The oro data are being updated with a fix, I will create the ICs after the updated oro data and sfc fix files are available.

**Comment by bbakernoaa** [comment]
@junwang-noaa This list should also include the aerosol initial conditions which are created using the MERRA2 Reanalysis data

**Comment by junwang-noaa** [comment]
@bbakernoaa Good point, I added an item under 4) as I think the ATM ICs contains the aerosol fields, please let me know if you'd like to change it. Thanks

**Comment by bingfu-NOAA** [comment]
@bbakernoaa @junwang-noaa Anyone can help me on how to create atm IC with aerosol initial conditions?

**Comment by bingfu-NOAA** [comment]
@junwang-noaa Just FYI the oro data I used is from Shan with the fix of alignment issue. 
oro data location on Hera: /scratch1/BMC/gsd-fv3-dev/fv3data/lake_p8_water_fraction2020/
Helin's sfc fix files are located here on Hera: /scratch1/NCEPDEV/global/Helin.Wei/sfc_fixed_mar2022

**Comment by bbakernoaa** [comment]
@junwang-noaa 

I've made a copy of the ICs as I didn't want to overwrite the original ones created by @bingfu-NOAA. They can be found here  on HERA 

`/scratch2/NCEPDEV/stmp3/Barry.Baker/C384_025/MERRA2_UFS_ICS/20*`

**Comment by junwang-noaa** [comment]
@bbakernoaa Thanks.
@bingfu-NOAA  May I ask if you have the RT 2021032206 ICs with different resolutions ready? Thanks

**Comment by bingfu-NOAA** [comment]
@junwang-noaa @bbakernoaa Yes, it is ready. 
 on Hera: /scratch2/NCEPDEV/stmp3/Bing.Fu/o/p8crts/com/gens/dev/merge

**Comment by junwang-noaa** [comment]
@bingfu-NOAA Thank you!
@bbakernoaa Would you please let me know if you can add aerosol fields to the ICs under /scratch2/NCEPDEV/stmp3/Bing.Fu/o/p8crts/com/gens/dev/merge? Thanks

**Comment by bbakernoaa** [comment]
@junwang-noaa I can yes.  It shouldn't be a problem.

**Comment by junwang-noaa** [comment]
@bbakernoaa May I ask if you have the RT aerosol ICs ready? Thank you!

**Comment by bbakernoaa** [comment]
@junwang-noaa you should be able to get them here: /scratch2/NCEPDEV/stmp3/Barry.Baker/C384_025/MERRA2_UFS_ICS/C*

The C1152 is finishing up now but should be done within the hour.

**Comment by ChunxiZhang-NOAA** [comment]
@shansun6 @bingfu-NOAA @HelinWei-NOAA. Are the ocean (water?) mask data consistent with the other fixed data? For example, if the grid is water in soil data, is it also water in the mask data?

**Comment by yangfanglin** [comment]
@ChunxiZhang-NOAA Please see https://docs.google.com/document/d/1dPirkrZfvqlVi4GgdVRYVvdjd8BeVPlRg6irI9hH_c0/edit for the procedures for making UFS global model boundary conditions and ICs. Hope it helps.   @shansun6 @bingfu-NOAA @HelinWei-NOAA @barlage  Please update this document if the information is out of date

**Comment by yangfanglin** [comment]
@bbakernoaa Barry, it would be great if you can add the steps to this [document ](https://docs.google.com/document/d/1dPirkrZfvqlVi4GgdVRYVvdjd8BeVPlRg6irI9hH_c0/edit )taken to create add aerosol ICs.

**Comment by bbakernoaa** [comment]
Will do @yangfanglin

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA Please see https://docs.google.com/document/d/1dPirkrZfvqlVi4GgdVRYVvdjd8BeVPlRg6irI9hH_c0/edit for the procedures for making UFS global model boundary conditions and ICs. Hope it helps. @shansun6 @bingfu-NOAA @HelinWei-NOAA @barlage Please update this document if the information is out of date

@yangfanglin  Thank you.

**Comment by junwang-noaa** [comment]
We will stage 1-4 and 8 in ufs-weather-model RT input data location for PR#909. When ww3 data is ready, it will be staged for upcoming ww3 cap PR.

**Comment by DeniseWorthen** [comment]
To summarize, the following locations will be used to update the input-data used for the RTS. 

- [x] Close j=1 on MOM6 1deg: /scratch1/NCEPDEV/stmp4/Denise.Worthen/input-data-20211130 
MOM6_FIX/100: ufs.topo_edits_011818.nc
CICE_FIX/100: mesh.mx100.nc, grid_cice_NEMS_mx100.nc, kmtu_cice_NEMS_mx100.nc
CICE_IC/100: cice_model_1.00.cpc.res_2011100100.nc, cice_model_1.00.cpc.res_20210322.nc

- [x] Fix files: /scratch1/NCEPDEV/global/Helin.Wei/sfc_fixed_mar2022 @HelinWei-NOAA 

- [x] Oro data:  /scratch1/BMC/gsd-fv3-dev/fv3data/lake_p8_water_fraction2020 @shansun6

- [x] ICs for RTs with aerosols added: /scratch2/NCEPDEV/stmp3/Barry.Baker/C384_025/MERRA2_UFS_ICS/C*  @bbakernoaa

- [x] ICs for 8 test dates : /scratch2/NCEPDEV/climate/climpara/S2S/IC/GEFS-NoahMP-aerosols-p8c for 2012/2013 -01,04,07,10). These will be added to the current BM_IC input data in subdirectories gfs_p8c @JessicaMeixner-NOAA 


If I've tagged you, please confirm by adding a check mark.

**Comment by JessicaMeixner-NOAA** [comment]
For the prototype IC dates, we have ICs with aerosols and land-spin-up on hera here: /scratch2/NCEPDEV/climate/climpara/S2S/IC/GEFS-NoahMP-aerosols-p8c

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA These will need to be updated in a new ``gfs_p8c/`` directory under each IC date in the current ``BM_IC-20220207`` directories, correct?

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen correct.  Just wanted to make sure you saw those ICs with the land-spin up as the ones from @bbakernoaa for the same dates do not include the updated src files (the gfs files are the same ones from Barry)

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Could you say that again? I'm not sure I understand.

**Comment by JessicaMeixner-NOAA** [comment]
For the BM-ICs which go in the BM_IC-20220207 directories.  The files should be taken from: 
/scratch2/NCEPDEV/climate/climpara/S2S/IC/GEFS-NoahMP-aerosols-p8c 
which combine the gfs* files that come from /scratch2/NCEPDEV/stmp3/Barry.Baker/C384_025/MERRA2_UFS_ICS/20* directories with sfc* files from the land-spin-up.

**Comment by DeniseWorthen** [comment]
Yes,  from the time line above I understood that Barry copied the ICs from Bing and added Aerosols, so we should use those from Barry's directory.

**Comment by JessicaMeixner-NOAA** [comment]
And then we need the sfc files from @barlage which is done in /scratch2/NCEPDEV/climate/climpara/S2S/IC/GEFS-NoahMP-aerosols-p8c but for the RT-IC dates we don't have the extra spin-up.  Just in the BM_ICs.

**Comment by bbakernoaa** [comment]
@DeniseWorthen I can't check that box for whatever reason but yes I approve (CHECK)

**Comment by HelinWei-NOAA** [comment]
@DeniseWorthen I can't check the box either. Yes. They are right one.

**Comment by DeniseWorthen** [comment]
Thanks for the confirmations. Those who could not check the boxes should have an invitation to join the ufs-weather-model as a collaborator.
