### ISSUE TITLE
HAFS moving nest development

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1109]
The EPIC includes issues/PRs for the HAFS moving nest capability in UFS.

**Comment by DeniseWorthen** [comment]
No update on HAFS moving-nest development. However, there is a project to move the moving-nest code from dycore to FV3-atm repo; details of how this it should be implemented under discussion (GFDL recommends that communication be done through the publicly accessible APIs).

**Comment by junwang-noaa** [comment]
The model infrastructure development will be managed by github projects. Close issue
