### ISSUE TITLE
Update intel/impi compiler to 2022

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1113]
## Description
Intel compiler versions 2019 and 2018 will not be supported on hera/orion. The ufs-weather-model will be updated to use new intel 2022 version.
 
## Solution
Add a clear and concise description of what you want to happen.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- https://github.com/NOAA-EMC/hpc-stack/issues/378

**Comment by junwang-noaa** [comment]
@jkbk2004 Please add the test results in this issue. Thanks

**Comment by jkbk2004** [comment]
Butterfly test and intel-2022.1.2 results are compared on Orion for various model fields against control case. mean and stdv are comparable. cpld_control_p8 case was used to compare SST and ice fields as well. Statistical impact from intel-2022.1.2 is compared with butterfly test case. The experimental results are identical for the choice of Intel-2021 and intel-2022: hera help desk confirms only bug fixes added to inel-2022 from intel-2021. 
[control-intel2022.pptx](https://github.com/ufs-community/ufs-weather-model/files/8280968/control-intel2022.pptx)

**Comment by junwang-noaa** [comment]
The butterfly test and intel-2022.1.2 are compared on hera. The results are shown [here](https://docs.google.com/presentation/d/1hWrAlm86wqQEA8i1wxAB6KhBgjjdiC2skrIOZG65Tkw/edit#slide=id.g11d7081b01f_0_12).
The results show the differences between Intel 2022.1 and control are compatible with the differences between butterfly test and control. 
Along with the results from @jkbk2004, we will start to update intel compiler to 2022.1.2 on all the platforms.
