### ISSUE TITLE
Replace w3nco with w3emc/2.9.1

### ISSUE THREAD

**Issue by aerorahul** [ufs-community/ufs-weather-model#1125]
## Description
`w3nco` has been merged with `w3emc` and the latter is preferred going forward.
`w3emc/2.9.1+` contains identical code as `w3nco` with the exception of `gblevents`.
This project does not depend on `gblevents`.

## Solution
Replace dependency of `w3nco` with `w3emc` in the modulefile as well as in the build system.

## Alternatives
None.

**Comment by junwang-noaa** [comment]
@aerorahul Do you know if the w3emc/2.9.1 is available on the ufs-weather-model supported platforms? Do we need to submit a ticket to the hpc-stack repo to get it installed? Thanks

**Comment by aerorahul** [comment]
@junwang-noaa 
No I don't know for sure, but I would imagine it to be there, and if not easy to do.
@kgerheiser @Hang-Lei-NOAA

**Comment by kgerheiser** [comment]
Looking at the status of that now

**Comment by junwang-noaa** [comment]
@kgerheiser May I ask the status of the w3emc/2.9.1?

**Comment by kgerheiser** [comment]
I just looked at this, and I think it's everywhere (only machine I don't have access to is Cheyenne),but I'm going to double check real quick.

**Comment by aerorahul** [comment]
I know it is on Orion, Hera, Dell and wcoss2.

**Comment by WenMeng-NOAA** [comment]
@aerorahul Will there be a plan to install w3emc/2.9.1 on WCOSS1-Cray?

**Comment by aerorahul** [comment]
> @aerorahul Will there be a plan to install w3emc/2.9.1 on WCOSS1-Cray? 

I am not sure. You will have to ask @kgerheiser @Hang-Lei-NOAA 
Possibly open an install request in the hpc-stack repo.

**Comment by Hang-Lei-NOAA** [comment]
@Wen Meng - NOAA Federal ***@***.***> The w3emc/2.9.1 has been added
on wcoss cray

**Comment by WenMeng-NOAA** [comment]
@Hang-Lei-NOAA I saw it. Thanks!

**Comment by junwang-noaa** [comment]
I tested the w3emc/2.9.2 with the latest UPP and code changes in the cmake in fv3/ccpp. The standalone control test produces identical results as baseline. Code changes are required in ww3 to use w3emc in the coupled tests in UFS.

**Comment by junwang-noaa** [comment]
Change this tasks to EPIC regression test Q4fy2022.

**Comment by aerorahul** [comment]
@junwang-noaa @WenMeng-NOAA @DusanJovic-NOAA 
Also note that nemsio/2.5.2 has a dependency on w3nco.  If we use a higher release of nemsio, w3nco can completely be eliminated from the dependency list.
Just a note for future.

**Comment by WenMeng-NOAA** [comment]
@aerorahul and @Hang-Lei-NOAA The UPP already upgraded nemsio/2.5.4 on hera and orion. Will you send the request to GDIT for installing nemsio/2.5.4 on WCOSS2?

**Comment by DusanJovic-NOAA** [comment]
> @junwang-noaa @WenMeng-NOAA @DusanJovic-NOAA Also note that nemsio/2.5.2 has a dependency on w3nco. If we use a higher release of nemsio, w3nco can completely be eliminated from the dependency list. Just a note for future.

ufs-weather-model does not depend on nemsio.
