### ISSUE TITLE
Remove the regional_hafs regression test

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#1140]
## Description
Remove the regional_hafs regression test, since the HAFS related RTs are under the "HAFS tests" section.

## Solution
Remove the regional_hafs regression test, and modify an existing HAFS RT to test the write_dopost capability for HAFS.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- addressed by ufs-community/ufs-weather-model/pull/1104

**Comment by DusanJovic-NOAA** [comment]
Merged in https://github.com/ufs-community/ufs-weather-model/commit/c2e6b223232a7e304f37059ad63f5c36b7b4317e
