### ISSUE TITLE
update MOM6 20220329

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#1148]
Marshall and Niki have created a PR to dev/emc with code updating in infra/FMS1 and infra/FMS2, this is aimed for UFS FMS mixed mode. See detail at https://github.com/NOAA-EMC/MOM6/pull/88

**Comment by jiandewang** [comment]
the commit to UFS will be combined with https://github.com/ufs-community/ufs-weather-model/pull/1137

**Comment by junwang-noaa** [comment]
Code was committed. The issue will be committed.
