### ISSUE TITLE
Add documentation about cellular automata in stochastic_physics and ccpp/physics submodules for public release

### ISSUE THREAD

**Issue by lisa-bengtsson** [ufs-community/ufs-weather-model#1155]
## Description
Asked to provide documentation regarding CA for MRW public release 

## Solution
Providing documentation using doxygen in stochastic_physics and ccpp/physics submodules

**Comment by lisa-bengtsson** [comment]
@mzhangw I think we can close this issue correct?

**Comment by mzhangw** [comment]
I think so. But I would like to let @ligiabernardet chip in.

**Comment by ligiabernardet** [comment]
Yes. If needed we can open issues in the ccpp-physics and stochastic-physics repos.
