### ISSUE TITLE
current develop branch fails in ccpp_prebuild.py

### ISSUE THREAD

**Issue by edwardhartnett** [ufs-community/ufs-weather-model#116]
Sorry to be asking so many questions. ;-(

I'm trying to build the current develop branch. When I do so, I get this error. Is this expected?

```
python2 ./FV3/ccpp/framework/scripts/ccpp_prebuild.py --config=FV3/ccpp/config/ccpp_prebuild_config.py --suites=FV3_GFS_v15p2,FV3_GFS_v15p2_no_nsst --builddir=/home/ed/u2/build/FV3
INFO: Logging level set to INFO
INFO: Found TYPEDEFS_NEW_METADATA dictionary in config, assume at least some data is in new metadata format
INFO: Parsing suite definition files ...
INFO: Parsing suite definition file FV3/ccpp/suites/suite_FV3_GFS_v15p2.xml ...
INFO: Parsing suite definition file FV3/ccpp/suites/suite_FV3_GFS_v15p2_no_nsst.xml ...
CRITICAL: Suite definition file FV3/ccpp/suites/suite_FV3_GFS_v15p2_no_nsst.xml not found.
ERROR: Parsing suite definition file suite_FV3_GFS_v15p2_no_nsst.xml failed.
Traceback (most recent call last):
  File "./FV3/ccpp/framework/scripts/ccpp_prebuild.py", line 788, in <module>
    main()
  File "./FV3/ccpp/framework/scripts/ccpp_prebuild.py", line 701, in main
    raise Exception('Parsing suite definition files failed.')
Exception: Parsing suite definition files failed.
```

**Comment by ligiabernardet** [comment]
As the error messages indicates, Suite definition file FV3/ccpp/suites/suite_FV3_GFS_v15p2_no_nsst.xml not found

This is because this suite does not exist in the develop branch yet (only in the release/public-v1 branch). I believe at some point soon the release branch will be merged back to the develop branch.

Try, for example, --suites=suite_FV3_GFS_v15p2.xml

**Comment by edwardhartnett** [comment]
Awesome, thanks, that helped get it farther along. Now it fails here:

```
CMake Error at FV3/ccpp/physics/CMakeLists.txt:70 (include):
  include could not find load file:

    ./CCPP_TYPEDEFS.cmake



```

**Comment by ligiabernardet** [comment]
Glad I could help a bit. I hope others can help you the rest of the way.  Please note that you can also post questions on a user support forum set up specifically for issues related to the Weather Model (https://forums.ufscommunity.org/forum/ufs-weather-model).

**Comment by climbfuji** [comment]
Came across this by coincidence. This may again be a mixture of branches between the various repositories? The develop branch of ufs-weather-model only works with the branches listed in its .gitmodules file, and exactly with the hashes that this hash of ufs-weather-model has stored.

**Comment by edwardhartnett** [comment]
I am going to close this issue. It's not clear to me under what circumstances this is intended to build. I have fallen back to the 1.0 release for my current development work. It's the most recent release I can get to build cleanly.

I will hope for better luck moving forward as we improve the build and CI systems. Needless to say, it should be possible to check out the develop branch, run tests, and start working.
