### ISSUE TITLE
Minimum version requirement for ESMF

### ISSUE THREAD

**Issue by tsupinie** [ufs-community/ufs-weather-model#1162]
## Description
In the configure step, there is no version requirement for ESMF. However, the model requires the latest version of ESMF (v8.2.0). This causes an error when compiling with a lower version.

### To Reproduce:
I'm using Intel compilers on TACC Frontera, but it should be platform- and compiler-independent.

1. Attempt to compile with ESMF v8.1.0 or lower.
2. Notice the following compile error:
<img width="1680" alt="Screen Shot 2022-04-07 at 16 43 43" src="https://user-images.githubusercontent.com/885575/162324934-ad4e921f-499f-47be-b77c-abddd5f7c88d.png">

That happens because the `configFileName` argument is ESMF v8.2.0-only. 

## Fix
The fix is to add v8.2.0 as a minimum requirement for ESMF in the root CMakeLists.txt. I can submit a PR, or y'all can do it; it's literally a one-line fix.

**Comment by junwang-noaa** [comment]
@tsupinie we had some discussion on this issue. The plan is to use the minimum version number for all the libraries. But we'd like to clarify that ESMF beta snapshots (e.g. v8.3.0b09)  have been used in ufs-weather-model, and the  CMakeLists.txt can not interpret it correctly at this time. So setting ESMF minimum version number may not catch all the ESMF version issues.
