### ISSUE TITLE
Create a script to run regression tests on wcoss2 automatically

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#1166]
## Description
Right now, we cannot use auto_rt label to run regression tests on wcoss. A script will be developed to run regression tests on wcoss using a single line command.

## Solution
The script will be located at the following locations:
dell_p3: /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/rt_auto
cray:     /gpfs/hps3/emc/nems/noscrub/emc.nemspara/rt_auto

The command is
./rt_auto.sh [url of developer's repository] [name of developer's feature branch] [machine to run tests]

Example use run rt_auto.sh on wcoss_dell_p3:
cd your_working_dir
cp /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/rt_auto/rt_auto.sh .
nohup ./rt_auto.sh https://github.com/binli2337/ufs-weather-model update_cdeps wcoss_dell_p3 >output 2>&1 &

Example to use rt_auto.sh on wcoss_cray:
cd your_working_dir
cp /gpfs/hps3/emc/nems/noscrub/emc.nemspara/rt_auto/rt_auto.sh .
nohup ./rt_auto.sh https://github.com/binli2337/ufs-weather-model update_cdeps wcoss_cray >output 2>&1 &

**Comment by binli2337** [comment]
A new script "bl_and_rt_auto.sh" has been created. This script can be used to create a new baseline and then run the regression tests.

a) if new log from the tests is not saved to the feature branch, the command is
./bl_and_rt_auto.sh pr_url pr_branch_name rt_machine

b) if new log from the tests is saved to the developer's feature branch, the command is
./bl_and_rt_auto.sh pr_url pr_branch_name rt_machine push_log

**Comment by DusanJovic-NOAA** [comment]
What's the purpose of the 3rd command line argument (rt_machine)? The rt.sh does 'know' which machine it is running on. Why do we need to specify that again?

What will happen if I'm on dell but specify wcoss_cray for example?

**Comment by junwang-noaa** [comment]
@binli2337 Would you please address Dusan's comments? Thanks

**Comment by junwang-noaa** [comment]
@binli2337 can you provide some updates on this issue?

**Comment by binli2337** [comment]
The scripts have been tested and are working on WCOSS2.

**Comment by binli2337** [comment]
Location of the scripts: /lfs/h2/emc/nems/noscrub/emc.nems/auto_rt/.
