### ISSUE TITLE
Add a new suite definition file to FV3 (FV3_WoFS_v0) for SRW release

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1168]
## Description
Add a new suite definition file to FV3 (FV3_WoFS_v0) to use the NSSL cloud microphysics scheme with Noah LSM. For use use with the next SRW app release

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- https://github.com/ufs-community/ufs-weather-model/pull/1158

**Comment by MicroTed** [comment]
UPDATE: fd_nems.yaml file needed to be updated -- works now

@junwang-noaa 
I'm trying to do some tests with a subdomain of the 2019061518 "student" test, and I'm getting an odd error:

PET00 src/addon/NUOPC/src/NUOPC_Base.F90:2101 Invalid argument  - inst_tracer_diag_aod is not a StandardName in the NUOPC_FieldDictionary!

Any ideas? I see that inst_tracer_diag_aod is a new addition to atmos_model.F90, but the same ufs_model works fine on the regional_3km case.  (And also same error for regional_control -- strange)

**Comment by junwang-noaa** [comment]
Progress updates: 
- the suite file was committed to the SRW release branch. 
- the decomposition issue with blending turned on is resolved. @MicroTed submitted a [PR194](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/194) to dycore repo. 
- there are still issues with restart reproducibility, we are working on it.

**Comment by junwang-noaa** [comment]
The suite file was added to UFS SRW release release/public-v3. Will move the issue to Q4FY2022 RT development to resolve the restart issue.
