### ISSUE TITLE
Unify inline post interfaces for global and regional FV3

### ISSUE THREAD

**Issue by WenMeng-NOAA** [ufs-community/ufs-weather-model#1174]
## Description
At  FV3/io, global inline post and regional inline post uses two separate interfaces, post_gfs, post_regional. 

## Solution
These two interfaces can be unified. 

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by WenMeng-NOAA** [comment]
The changes will be made in both ufs-weather-model repository and fv3atm repository:

- fv3atm:
    1) Unified inline post interface post_fv3 
    2) Add bug fix for dx/dy computation
    3) Add reading pwat from FV3
    4) Clean up some legacy variable initialization.
    5) Read max/min 2m T from tmax_max2m for GFS, and from t02max/min for RRFS and HAFS.
    6) Read 3D cloud fraction from cld_amt for GFDL MP, and cldfra for other MPs.
    7) Add a new namelist model_inputs in itag for input modelname, e.g. GFS, FV3R.
    8) Update upp revision to c939eae

- ufs-weather-model:
    1) Update post_itag, post_itag_fv3lam and post_itag_hafs under tests/parm with modelname input
    2) Update all diag tables under tests/parm/diag_table to replace pwatclm with pwat

-

**Comment by WenMeng-NOAA** [comment]
Here are test results form UFS RT control and regional_control:
```
Compile 001 elapsed time 1114 seconds. -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v15_thompson_mynn,FV3_GFS_v15_thompson_mynn_RRTMGP,FV3_GFS_v17_p8,FV3_GFS_v15_thompson_mynn_lam3km -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release

baseline dir = /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/RT/NEMSfv3gfs/develop-20220408/control
working dir  = /gpfs/dell2/ptmp/Wen.Meng/FV3_RT/rt_42454/control
Checking test 001 control results ....
 Comparing sfcf000.nc ............ALT CHECK......NOT OK
 Comparing sfcf021.nc ............ALT CHECK......NOT OK
 Comparing sfcf024.nc ............ALT CHECK......NOT OK
 Comparing atmf000.nc .........OK
 Comparing atmf021.nc .........OK
 Comparing atmf024.nc .........OK
 Comparing GFSFLX.GrbF00 .........NOT OK
 Comparing GFSFLX.GrbF21 .........NOT OK
 Comparing GFSFLX.GrbF24 .........NOT OK
 Comparing GFSPRS.GrbF00 .........NOT OK
 Comparing GFSPRS.GrbF21 .........NOT OK
 Comparing GFSPRS.GrbF24 .........NOT OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
...
baseline dir = /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/RT/NEMSfv3gfs/develop-20220408/fv3_regional_control
working dir  = /gpfs/dell2/ptmp/Wen.Meng/FV3_RT/rt_42454/regional_control
Checking test 002 regional_control results ....
 Comparing dynf000.nc .........OK
 Comparing dynf024.nc .........OK
 Comparing phyf000.nc ............ALT CHECK......NOT OK
 Comparing phyf024.nc ............ALT CHECK......NOT OK
 Comparing PRSLEV.GrbF00 .........NOT OK
 Comparing PRSLEV.GrbF24 .........NOT OK
 Comparing NATLEV.GrbF00 .........NOT OK
 Comparing NATLEV.GrbF24 .........NOT OK

```

**Comment by WenMeng-NOAA** [comment]
The changed results above tests come from:

- sfcf*, phyf*: output variable name change from pwatclm to pwat
- UPP outputs in GRIB2 for GFS: output pwat from model calculation instead of UPP calculation
   891:51910349:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999814:rpn_rms=0.357892
- UPP outputs in GRIB2 for regional FV3 (RRFS, HAFS): a bug fix in ABSV, MCONV calculation in UPP; pwat update
   255:7249119:ABSV:200 mb:rpn_corr=0.992265:rpn_rms=8.01607e-06
   288:8296392:ABSV:250 mb:rpn_corr=0.99223:rpn_rms=8.99078e-06
   896:28635238:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999524:rpn_rms=0.598866

**Comment by junwang-noaa** [comment]
The issue was resolved and PR was merged. The issue will be closed.
