### ISSUE TITLE
high resolution CICE6 model scalability issue in UFS

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1177]
## Description
hae-cheol.kim@noaa.gov is running high resolution (1/12degree) NG-GODAS test and found some scalability issue with cice6 model. Below is the description from Hae-Cheol:

While running 1/12-th degree DATM-MOM6-CICE6 (with GEFS forcing), I bumped into a load balancing issue. Here is some information from ESMF_profile_summary and it looks like that the ice model does not scale at all, using 1240 tasks takes about the same time as using 480 tasks.  

[OCN] RunPhase1                                                   1240   480      18816.8680  18733.8906  1181    18921.8379  1274  
[ICE] RunPhase1                                                     1240   5760     12847.4015  7253.7183   1679    33491.1953  1420

vs:

 [OCN] RunPhase1                                                   1240   240      9620.5926   9615.5859   1108    9626.5898   563
 [ICE] RunPhase1                                                   480    2880     10219.5579  3330.6353   2101    16067.8545  1998

The location of the source on GAEA is /lustre/f2/dev/ncep/Hae-Cheol.Kim/ufs-weather-model_202203 and the run dir is
/lustre/f2/scratch/ncep/Hae-Cheol.Kim/FV3_RT/rt_48755/datm_cdeps_mx008_gefs_WORKING/

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. Compile the model code at /lustre/f2/dev/ncep/Hae-Cheol.Kim/ufs-weather-model_202203
2. run the test case datm_cdeps_mx008_gefs_WORKING

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

**Comment by binli2337** [comment]
The reason for the load balancing (scalability) issue has been found.

In the test using 1240 cores for CICE6, only 300 cores are actually used by CICE6 for forecasting.

Settings in ice_in are   
    nprocs            = 1240
    nx_global         = 4500
    ny_global         = 3297
    block_size_x      = 15
    block_size_y      = 3297
    max_blocks        = -1
    processor_shape   = 'slenderX1'

The above settings are equivalent to
    nprocs            = 300
    nx_global         = 4500
    ny_global         = 3297
    block_size_x      = 15
    block_size_y      = 3297
    max_blocks        = -1
    processor_shape   = 'slenderX1'

In nems.configure, even though the PET list bounds are between 1320 and 2559 for CICE6, only the first 300 cores (from core #1320 to core #1619) are used in the calculations. The following error messages are printed out from the other 940 cores reserved for CICE6:

20220418 150649.890 INFO             PET1620 (field_getfldptr): no local nodes or elements

20220418 150649.892 INFO             PET1621 (field_getfldptr): no local nodes or elements
...

20220418 150649.896 INFO             PET2559 (field_getfldptr): no local nodes or elements

**Comment by DeniseWorthen** [comment]
Is this a bug, or is it an error in how the test is being configured?

**Comment by junwang-noaa** [comment]
@hae-cheol.kim@noaa.gov @binli2337 Is this issue resolved?

**Comment by binli2337** [comment]
@Hae-CheolKim-NOAA Should we close this issue?

**Comment by Hae-CheolKim** [comment]
Yes, please. Thanks.
