### ISSUE TITLE
Allow More Flexibility in Grell-Freitas Convective Parameterization and Add Suite Definition Files used by GSL

### ISSUE THREAD

**Issue by hannahcbarnes** [ufs-community/ufs-weather-model#1188]
## Description
- We would like to be able to run the deep portion of the Grell-Freitas (GF) Convective Parameterization without a shallow convective parameterization. Right now, the code is hard-wired so that GF deep must be run with GF shallow. 
- GSL has a few Suite Definition Files that are not maintained in the repository. We would like to add these Suite Definition Files.

## Solution
- Resolving the issue in GF, only requires commenting out a few lines in cu_gf_driver.F90
- We have the additional Suite Definition Files ready to be submitted to the repository.

## Alternatives
- None

## Related to
- These changes have been committed to the GSL repository through the following pull requests
https://github.com/NOAA-GSL/ufs-weather-model/pull/120
https://github.com/NOAA-GSL/fv3atm/pull/127
https://github.com/NOAA-GSL/ccpp-physics/pull/127

**Comment by junwang-noaa** [comment]
@hannahcbarnes May I ask which project (RRFS, SRW, or MRW) is going to use this feature? Thanks

**Comment by junwang-noaa** [comment]
@hannahcbarnes PR#1195 was merged, can we close this issue?

**Comment by junwang-noaa** [comment]
The code is merged, close the issue.
