### ISSUE TITLE
Thompson microphysics sedimentation of hydrometers not correctly passed to aerosols

### ISSUE THREAD

**Issue by bbakernoaa** [ufs-community/ufs-weather-model#1191]
## Description
With the switch to the Thompson mp the sedimentation values of hydrometers is not calculated.  This causes a problem for the large scale wet removal of aerosols within the GOCART component creating an ever growing aerosol field in the S2S runs.  These variables were calculated in the GFDL microphysics but the capability was lost with the Thompson mp. 

please see: https://docs.google.com/presentation/d/1TAqtsgWWfswCE3AjHekv6u1SOp5O7Hr4/edit#slide=id.p1

**Comment by junwang-noaa** [comment]
@yangfanglin @lisa-bengtsson FYI.

**Comment by junwang-noaa** [comment]
The PR#1192 with fixed for this issue was merged this morning. the issue will be closed.
