### ISSUE TITLE
Compile time on hera is extremely long

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-weather-model#1194]
## Description
I am compiling the model via the compile.sh script on hera, and it take over 8 minutes to get past the configuration step and being the compilation.

## Solution
Can this be sped up?

## Alternatives
None

**Comment by junwang-noaa** [comment]
@pjpegion Did this happen to you before? The total time for compiling cpld case is taking about ~9mins.  Please see  
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/RegressionTests_hera.intel.log#L4

**Comment by pjpegion** [comment]
I first noticed it last week when I ran regression tests to compare the timing of RRTMG and RRTMGP. In that case, it took 1045 seconds to compile the atmosphere only model, and it is equally slow today.

**Comment by junwang-noaa** [comment]
@pjpegion I could not repeat the issue you reported. I compiled the atmonly test today, it took ~300s to finish the whole compile job.  /scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_151590/compile_001/compile_001_time.log

**Comment by pjpegion** [comment]
Interesting. I guess hera does not like me.
