### ISSUE TITLE
Update ICs for P8c surface fields 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1203]
## Description
The surface fields for p8c ICs were updated.  While likely sufficient for regression testing for the existing ICs, wanted to make everyone aware that there is a change in what we're running for the prototypes, so we should probably update these inputs when we get a chance.  

Essentially we need to do the following: 

for CDATE  in  2012010100  2012040100	2012070100  2012100100	2013010100  2013040100	2013070100  2013100100

cp  /scratch2/NCEPDEV/climate/climpara/S2S/IC/GEFS-NoahMP-aerosols-p8c/${CDATE}/gfs/C384/INPUT/sfc*.nc  /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/BM_IC-20220207/${CDATE}/gfs_p8c/C384_L127/INPUT/

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA as we discussed, would you please let us know the location of the wave ICs for the 8 cases? Thanks

**Comment by JessicaMeixner-NOAA** [comment]
The wave ICs can be found on hera, here: 
/scratch1/NCEPDEV/climate/role.ufscpara/IC/GEFSwave20220524/${CDATE}//wav/mx025/20150501.000000.restart.mx025 

Note you'll need to rename these files to restart.ww3 in the run directory.

**Comment by binli2337** [comment]
The FV3 ICs for P8c have been copied to  /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/BM_IC-20220207/YYYYMMDD00/p8c for the 8 cases. Please see issue #1250 .

**Comment by JessicaMeixner-NOAA** [comment]
So it looks like FV3BMIC needs to be updated to p8c so that we are actually using these ICs.

**Comment by binli2337** [comment]
@junwang-noaa @DeniseWorthen The wave ICs have been copied to /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/BM_IC-20220207/YYYYMMDD00/wav_p8c/mx025.
