### ISSUE TITLE
Grid(nb)%area(ix) field is corrupt 

### ISSUE THREAD

**Issue by lisa-bengtsson** [ufs-community/ufs-weather-model#1208]
## Description
When printing out the field Grid(nb)%area(ix), from ccpp/physics/physics (standard_name = cell_area in physics), I see that the field looks corrupt. I tested control_p8 and cpld_control_p8. Both tests have this issue. 

<img width="568" alt="area" src="https://user-images.githubusercontent.com/54411948/167284916-165e5629-3ee1-42c9-8d5e-9085cbb478ae.png">

I have not had much time to look into it, but I see that it gets initialized/set in GFS_init.F90, can something be wrong in this loop: ?

```
blksz = size(Grid(1)%xlon)

    nb = 1
    ix = 0
    do j = 1,size(xlon,2)
      do i = 1,size(xlon,1)
        ix=ix+1
        if (ix > blksz) then
          nb = nb + 1
          ix = 1
        endif
        Grid(nb)%xlon(ix)   = xlon(i,j)
        Grid(nb)%xlat(ix)   = xlat(i,j)
        Grid(nb)%xlat_d(ix) = xlat(i,j) * rad2deg
        Grid(nb)%xlon_d(ix) = xlon(i,j) * rad2deg
        Grid(nb)%sinlat(ix) = sin(Grid(nb)%xlat(ix))
        Grid(nb)%coslat(ix) = sqrt(1.0_kind_phys - Grid(nb)%sinlat(ix)*Grid(nb)%sinlat(ix))
        Grid(nb)%area(ix)   = area(i,j)
        Grid(nb)%dx(ix)     = sqrt(area(i,j))
      enddo
    enddo
```

I think it can cause some serious problems for e.g. physics scheme's using sqrt(garea) for scale-adaptive considerations, e.g. gravity wave drag, convection... @yangfanglin, @mdtoyNOAA  

### To Reproduce:
What compilers/machines are you seeing this with?

Hera, intel compiler, RT tests control_p8 and cpld_control_p8

**Comment by ChunxiZhang-NOAA** [comment]
@lisa-bengtsson Which variable is it in sfcf000.nc?

**Comment by ChunxiZhang-NOAA** [comment]
When I wrote out GFS_grid_type%area in sfcf000.nc, I got correct area size distribution.
<img width="953" alt="Screen Shot 2022-05-09 at 3 33 57 PM" src="https://user-images.githubusercontent.com/49283036/167484880-8893bc25-bf02-427b-9f4f-24672d5f444b.png">

**Comment by lisa-bengtsson** [comment]
Thank you very much Chunxi for taking a look, I wrote out "garea" (standard_name = cell_area) from the samfshalcnv.f by putting it in a diagnostic variable I use for printing out various fields from physics, all the other fields I print out look correct except this one. Do you know where in the model this grid-size field is written out? Is it e.g from the atmos_model.F90 before the call to physics, or from inside of CCPP?

**Comment by ChunxiZhang-NOAA** [comment]
We are looking at the same standard_name = cell_area. In GFS_typedefs.meta, it is assigned to a local name 'area'. I believe the grid-size field is written out from atmos_model.F90 and before the call to physics.

**Comment by ChunxiZhang-NOAA** [comment]
So "garea" could be either modified in physics incorrectly or handled by CCPP framework incorrectly.

**Comment by lisa-bengtsson** [comment]
If you have a chance, could you write standard_name = cell_area out from inside the physics in your test? I tried also the c384 cpld_control_p8 test and see the same thing... it's confusing. I'm currently on a 8 hour time-difference (in the UK) so may have to check in tomorrow.

**Comment by ChunxiZhang-NOAA** [comment]
I did another test and wrote standard_name = cell_area out inside samfshalcnv.f, and the grid sizes look correct too. I only test control_p8 though.

**Comment by lisa-bengtsson** [comment]
Ok thank you very much for testing Chunxi. I must have made some mistake on my end, I will check out the latest version of today and try again. I think I can close this issue for now.
