### ISSUE TITLE
Enable Intel 2022 and update test support on S4

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [ufs-community/ufs-weather-model#1223]
## Description
Support for S4 should be maintained so users of that system can continue to use the latest features of the UFS.  Currently, S4 support is lagging in two areas: regression testing and Intel 2022 support.

## Solution
1. Update the resources in `default_vars.sh` to reenable regression testing on S4, following #320.
2. Rebuild the hpc-stack libraries on S4 using the Intel 2022.1 compiler suite and update the `ufs_s4.intel` and `ufs_s4.intel_debug` to point to the 2022.1 libraries, following #1113.

**Comment by climbfuji** [comment]
Note: The new spack-stack build on S4 - ready for developers soon - uses the Intel 2022.01 compilers.

**Comment by junwang-noaa** [comment]
The code was merged. Close issue.
