### ISSUE TITLE
Inconsistency between a suite definition and the namelist in several regression tests.

### ISSUE THREAD

**Issue by tanyasmirnova** [ufs-community/ufs-weather-model#1225]
## Description
The FV3_GFS_v15_thompson_mynn physics suite uses the GFS surface layer scheme (sfc_diff.f). However, the namelist option with the use of this suite has do_mynnsfclay=.true., that means that MYNN surface layer scheme is supposed to be used.
A fix should be put either in the FV3_GFS_v15_thompson_mynn suite definition to use 
      <scheme>mynnsfc_wrapper</scheme>
or in the input.nml to switch from do_mynnsfclay=.true. to do_mynnsfclay=.false.

The regression tests affected:
regional_2threads/input.nml:       ccpp_suite = 'FV3_GFS_v15_thompson_mynn'
regional_control_2dwrtdecomp/input.nml:       ccpp_suite = 'FV3_GFS_v15_thompson_mynn'
regional_control/input.nml:       ccpp_suite = 'FV3_GFS_v15_thompson_mynn'
regional_debug/input.nml:       ccpp_suite = 'FV3_GFS_v15_thompson_mynn'
regional_hafs/input.nml:       ccpp_suite = 'FV3_GFS_v15_thompson_mynn'
regional_netcdf_parallel/input.nml:       ccpp_suite = 'FV3_GFS_v15_thompson_mynn'
regional_noquilt/input.nml:       ccpp_suite = 'FV3_GFS_v15_thompson_mynn'
regional_restart/input.nml:       ccpp_suite = 'FV3_GFS_v15_thompson_mynn'

The affected regression tests can pass, if thje logical flag - do_mynnsfclay-  is not used in any of physics IF statement.
In this case the GFS surface layer scheme is actually used. When the do_mynnsfclay flag is used, there could a problem, because sfc_diff.f does not provide all variables that sfc_diff.f provides. In this case the requested variable could be undefined.

Provide a clear and concise description of what the bug is.
Also give a description of what behavior you expected to happen.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

**Comment by DeniseWorthen** [comment]
@tanyasmirnova Do you have any updates on this issue?

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA Sam, did we fix this inconsistency in the gsl/develop branch?

**Comment by DeniseWorthen** [comment]
Can we get a status update on this issue?

**Comment by SamuelTrahanNOAA** [comment]
Those tests now use this suite:

```bash
export CCPP_SUITE=FV3_GFS_v15_thompson_mynn_lam3km
```

If you look in `suite_FV3_GFS_v15_thompson_mynn_lam3km.xml`, you will see it includes mynnsfc_wrapper:

```xml
      <scheme>mynnsfc_wrapper</scheme>
```

@tanyasmirnova - You opened this issue. Can you confirm the fix is acceptable? If so, can you close the issue?

**Comment by tanyasmirnova** [comment]
@DeniseWorthen @SamuelTrahanNOAA Yes, this issue is fixed now.

**Comment by tanyasmirnova** [comment]
The inconsistencies between suite definition and input.nml are fixed now.
