### ISSUE TITLE
Update to use fms/2022.01 on wcoss_cray

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#1229]
## Description
On other ufs-weather-model supported platforms, the FMS version used has been updated to fms/2022.01. However, on wcoss_cray, it is still fms/2021.04, e.g.,
https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_wcoss_cray#L61
https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_wcoss_cray_debug#L61

## Solution
Update to use fms/2022.01 on wcoss_cray.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- addressed by ufs-community/ufs-weather-model/pull/1227

**Comment by BinLiu-NOAA** [comment]
@junwang-noaa, is there a specific reason, the fms/2022.01 version was not updated for wcoss_cray? If not, and I can update it in PR #1227 if desired.

**Comment by junwang-noaa** [comment]
@BinLiu-NOAA Is the fms/2022.01 available on wcoss cray? If yes, please update in your PR#1227.

**Comment by BinLiu-NOAA** [comment]
@junwang-noaa, I believe so, fms/2022.01 is already there on wcoss_cray. I tested it from the HAFS side last Friday. And I will include this in PR #1227. Bin
