### ISSUE TITLE
Activate a v3-release version of the docs on readthedocs.org

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-weather-model#1236]
Currently, the only versions of the [WM documentation](https://ufs-weather-model.readthedocs.io/en/latest/) available on readthedocs.org are "latest," "ufs-v1.0.0," "ufs-v1.1.0," and "ufs-v2.0.0,"  even though there is a release/public-v3 branch. 

- For the SRW release (scheduled for next Friday, June 3, 2022), we need to provide links to an updated version of the WM docs. Ideally, we want to link to a static/tagged version. The easiest solution would likely be to activate a "ufs-v3.0.0" tag in the WM readthedocs.org account. 

- In most of the UFS docs, the wikis claim that "latest" points to head of develop, when in reality, it points to the latest release docs (in this case, likely v2.0.0, which is the latest release for which docs are available). Someone with access to the readthedocs account should verify whether "latest" indeed points to "develop" in the UFS WM readthedocs account (within a project, you can check under Admin --> Advanced Settings. Default Version and Default Branch should both be "develop."). 

@mark-a-potts @jkbk2004 @ligiabernardet

**Comment by jkbk2004** [comment]
@llpcarson @ligiabernardet can you add @gspetro-NOAA to the WM readthedoc site?

**Comment by ligiabernardet** [comment]
Yes but I need to know the ReadTheDocs userID for @gspetro-NOAA 
Meanwhile, I have already activated a hidden page for UFS WM v3 (see https://ufs-weather-model.readthedocs.io/en/release-public-v3/). I assuming there will be a tag called ufs-v3.0.0 created for the release (just like the previous releases)?

**Comment by gspetro-NOAA** [comment]
@ligiabernardet My RTD username is EPIC-AUS.

**Comment by gspetro-NOAA** [comment]
@ligiabernardet Thanks for activating the hidden page! At yesterday's SRW release meeting, we decided not to create tags (e.g., ufs-v3.0.0) for the SRW component docs. Instead, we'll use the latest docs for each component release branch. This way, if any updates are made to the component release branches subsequent to the SRW release, SRW users will be referred to documentation that reflects these updates.

**Comment by ligiabernardet** [comment]
OK.
I added EPIC-AUS as a maintainer to readthedocs at https://readthedocs.org/projects/ufs-weather-model/
