### ISSUE TITLE
Resolve issue and turn back on gdaswav test

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1237]
## Description
The gdas wave test was turned off after moving to the newest intel version because an issue with itags was discovered (see more info here: https://github.com/NOAA-EMC/WW3/issues/711).  A solution for this issue is needed and then this test needs to be turned back on. 

## Solution
Make sure all itag values in WW3 are <= 32k 

## Alternatives
Using different MPI environment variables might be possible short-term workarounds. 

## Related to
- https://github.com/NOAA-EMC/WW3/issues/711

**Comment by aliabdolali** [comment]
Associated issue on WW3: https://github.com/NOAA-EMC/WW3/issues/711

**Comment by arunchawla-NOAA** [comment]
@aliabdolali and @JessicaMeixner-NOAA was this resolved ?

**Comment by JessicaMeixner-NOAA** [comment]
@arunchawla-NOAA no this was never resolved.   There were some MTAG parameters that could get us past most cases and we have a good estimate of what to change to for GFSv16 if it became an issue with that, but long term fixes were never persued and short term (new MTAG numbers) would always seem to fail for one case or another and not work for everything.

**Comment by aliabdolali** [comment]
@arunchawla-NOAA if NCO wants to upgrade intel version to 2022 or newer in operation, we need to check MTAG on WCOSS2, otherwise, we can keep gdas test excluded (as gfsv17 unstr is on the way and it is single grid, no problem with MTAG). But we need to be ready if GFSv16 to use intel/2022 on WCOSS2 is going to happen, then we won't be under pressure.

**Comment by arunchawla-NOAA** [comment]
Any reason to keep this open if we are not pursuing a solution?

**Comment by JessicaMeixner-NOAA** [comment]
No, we have the details for GFSv16 in another issues if that ever becomes a need.
