### ISSUE TITLE
GFS V16 in-line post issue

### ISSUE THREAD

**Issue by WenMeng-NOAA** [ufs-community/ufs-weather-model#1244]
## Description
It was found GFSPRS datasets from GFS V16 in-line post with configurating different output frequencies and write groups have changed results.

### To Reproduce:
Kate Friedman did the following tests:
Test #1) If I run with the same output frequency as operations (hourly through 120 and 3hrly afterwards) = all output files match operations, including the master grb files from in-line post
Test #2) If I run the forecast with 3hrly outputs (not hourly through 120) = the atm/sfc/sflux files reproduce but the master.grb2 files start to differ with ops at f009 (up through f006 matches)
```
Kate.Friedman@clogin04:/lfs/h2/emc/ptmp/Kate.Friedman/comrot/devv16c3/gfs.20220531/00/atmos> cmp /lfs/h1/ops/prod/com/gfs/v16.2/gfs.20220531/00/atmos/gfs.t00z.master.grb2f009 gfs.t00z.master.grb2f009
/lfs/h1/ops/prod/com/gfs/v16.2/gfs.20220531/00/atmos/gfs.t00z.master.grb2f009 gfs.t00z.master.grb2f009 differ: byte 2475283324, line 12359829
```

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

**Comment by WenMeng-NOAA** [comment]
Hui-ya Chuang investigate the issue and found the difference was in field ceiling height.

**Comment by yangfanglin** [comment]
@WenMeng-NOAA To confirm, this fix will be applied to the operational model GFS.v16 on WCOSS2 but not on WCOSS1, is this correct ?     (@JamesAbeles-NOAA )

**Comment by WenMeng-NOAA** [comment]
@yangfanglin I would defer your question to @KateFriedman-NOAA and @junwang-noaa.

**Comment by junwang-noaa** [comment]
@KateFriedman-NOAA can correct me. After this fix is committed, I will create a new tag. My understanding is that it will be used on wcoss2 as we will not update the model on wcoss1.

**Comment by KateFriedman-NOAA** [comment]
Not worth updating the model on WCOSS1 since we're weeks away from go-live on WCOSS2, likely wouldn't be accepted anyway. @junwang-noaa If possible, please put the UPP fix into the v16.2 tag so it can at least be used for developers running that version via the global-workflow dev_v16 branch for the next few months and definitely get the UPP fix into the v16.3 tag. It'll at least go into WCOSS2 ops with the v16.3 update this fall...or sooner (via the updated v16.2 tag) if management gets permission from NCO to do a small update right after go-live. Need management to discuss that option. @yangfanglin @arunchawla-NOAA

**Comment by yangfanglin** [comment]
Kate and Jun, thank you for the clarification.

So this fix will not be included in the GFS on WCOSS2 which will go live as ops on June 28.

We should get this fix into the next update as soon as possible.  @arunchawla-NOAA @daryl.kleist@noaa.gov @jason.levit@noaa.gov, can we add this to GFS.v16.3 ?

**Comment by arunchawla-NOAA** [comment]
that should be possible
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone: 301-683-3740
Mobile: 240-564-5675
     Fax: 301-683-3703
------------------------------------------------------------

**Comment by junwang-noaa** [comment]
The code was merged. The issue will be closed.
