### ISSUE TITLE
build.sh error

### ISSUE THREAD

**Issue by JulieSchramm** [ufs-community/ufs-weather-model#125]
CMake Error at FV3/ccpp/physics/CMakeLists.txt:104 (include):
  include could not find load file:

    ./CCPP_TYPEDEFS.cmake

Fix:

Add line:

source ${BUILD_DIR}/FV3/ccpp/physics/CCPP_TYPEDEFS.sh

with other sourced CCPP*.sh files

**Comment by DusanJovic-NOAA** [comment]
The change that added CCPP_TYPEDEFS.sh was committed in PR #102 but we forgot to update build.sh. compile_cmake.sh was correctly updated.

**Comment by DusanJovic-NOAA** [comment]
@JulieSchramm Do you still see that error? Is this still an issue?

**Comment by junwang-noaa** [comment]
Since we haven't heard from Julie for 3 weeks, we will close the issue.  We can reopen it if there is still an issue.
