### ISSUE TITLE
P8c GOCART emission files

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1250]
## Description
The ufs-weather-model weekly test needs to be updated to run the cpld_bmark_p8 test with GOCART turned on. Besides the ICs update for atmosphere and wave, the GOCART emission files are also required to run the weekly test with the 8 cases (2012/2013, 010100, 040100, 070100, 100100). 

## Solution
Need the location of emission data for the 8 cases for 5 forecast days. 

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- PR will come to update the weekly test.

**Comment by junwang-noaa** [comment]
@bbakernoaa @JessicaMeixner-NOAA Would you please let us know the location of the P8c gocart emission data? Thanks.

**Comment by bbakernoaa** [comment]
@junwang-noaa This isn't a problem all emission data is on hera for these dates already and just need to be moved into the respective location for the RT.

**Comment by bbakernoaa** [comment]
@junwang-noaa All the emission data can be found here: /scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/NASA/ExtData for those dates.  If you need me to pull out exactly the files and put into a directory for you to copy let me know.

**Comment by binli2337** [comment]
@junwang-noaa I compared ICs between
 /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/BM_IC-20220207/2013040100/gfs_p8c/C384_L127/INPUT and 
/scratch1/NCEPDEV/climate/role.ufscpara/IC/GEFS-NoahMP-aerosols-p8c/2013040100/gfs/C384/INPUT.
The following 5 files are different:
sfc_data.tile1.nc
sfc_data.tile2.nc
sfc_data.tile3.nc
sfc_data.tile4.nc
sfc_data.tile5.nc

**Comment by junwang-noaa** [comment]
@binli2337 Would you please create a new directory under benchmark IC (let's call it p8c) and copy the ICs from /scratch1/NCEPDEV/climate/role.ufscpara/IC/GEFS-NoahMP-aerosols-p8c? In this way the benchmark RT tests will use the same ICs/fix files from the prototype runs.

**Comment by binli2337** [comment]
@junwang-noaa Under /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/BM_IC-20220207/2012010100, the current directory structure looks like the following:
cpc/
gfs_p7/
gfs_p8a/
gfs_p8c/
mom6_da/
wav_p7.2/
I will create a new directory called "p8c". After that the new directory structure will be:
cpc/
gfs_p7/
gfs_p8a/
gfs_p8c/
p8c/
mom6_da/
wav_p7.2/

**Comment by binli2337** [comment]
@junwang-noaa I can create a new directory "/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20220414/GOCART/p8c_2012_2013_5d" and copy the 5-day emission data (8 cases) to this directory.

**Comment by junwang-noaa** [comment]
@binli2337 Thanks

**Comment by DeniseWorthen** [comment]
@bbakernoaa Do you know the location of the emission data that the Prototypes are using? We should be able to use those in the RT 5-day test and not carry our own copy in the RT input data directories.

**Comment by bbakernoaa** [comment]
@DeniseWorthen 

You can find all the emissions on the various platforms here:

```bash 
        "WCOSS_DELL_P3")        AERO_INPUTS_DIR="/gpfs/dell2/emc/modeling/noscrub/Walter.Kolczynski/global-workflow/gocart_emissions" ;;
        "HERA")                         AERO_INPUTS_DIR="/scratch1/NCEPDEV/global/glopara/data/gocart_emissions";;
        "ORION")                        AERO_INPUTS_DIR="/work2/noaa/global/wkolczyn/noscrub/global-workflow/gocart_emissions";;
```

These are copies of research development that I have separately.

**Comment by DeniseWorthen** [comment]
@bbakernoaa Thanks. I attempted to point to the glopara location for the 5-d RT but I think the rc files in the current ``GOCART/p8c_2012_2013_5d`` directory in the RT input are organized differently. Do you know where I could located the correct rc files? I want to be able to just ``ln -s`` to the glopara directory for the 5-d test.

**Comment by junwang-noaa** [comment]
@bbakernoaa @lipan-NOAA Would you please let us know where are the aerosol rc files used in the prototype P8 runs? Thanks

**Comment by bbakernoaa** [comment]
@junwang-noaa I have a PR open to global-workflow now to update the rc files for the p8 runs 

The PR is here: https://github.com/NOAA-EMC/global-workflow/pull/888

The rc files that you are looking for can be found here: https://github.com/bbakernoaa/global-workflow/tree/feature/mapl_2-22-0/parm/chem

**Comment by bbakernoaa** [comment]
@DeniseWorthen can you explain a little more where this directory is...... I'm not sure where this exists

**Comment by DeniseWorthen** [comment]
@bbakernoaa The idea was that instead of the RT carrying a duplicate copy of the GOCART files required for doing the 5-day weekly tests, we could just point to the same files that the workflow was using. But when I tried that, it seemed the rc files were assuming a different directory structure for where the files were located. I think that is the basis of @junwang-noaa question about the location of the rc files that the prototype p8 runs are located.

**Comment by binli2337** [comment]
All GOCART input files used by RT have been copied to the input directory on Hera. Please note that the 5-day tests only run on Hera.
