### ISSUE TITLE
can't access data on ORION

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#1251]
## Description
Provide a clear and concise description of what the bug is.
Also give a description of what behavior you expected to happen.
I am running RT.sh on orion but got permission deny on some dataset

nf90_open: returned error code (13) opening ExtData/dust/FENGSHA_SOILGRIDS2019_GEFSv12_v1.2.nc [Permission denied]

can the owner do a chmod for dust dir ?

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

**Comment by jkbk2004** [comment]
@MinsukJi-NOAA same issue on my side when I run cpld_debug_p8. 
-rw-r-----  1 jminsuk  nems  247472553 May 12 14:16 FENGSHA_SOILGRIDS2019_GEFSv12_v1.2.nc
my run directory on orion is at: /work/noaa/epic-ps/jongkim/rt-mapl-12.2.3/stmp/jongkim/FV3_RT/rt_106813/cpld_debug_p8/

**Comment by MinsukJi-NOAA** [comment]
@jiandewang @jkbk2004 My apologies. I modified the permission on those files. Please try again and let me know.

**Comment by jiandewang** [comment]
@MinsukJi-NOAA thanks, I will close this issue.
