### ISSUE TITLE
Unrealistic surface/skin temperature and moisture values with latest model code

### ISSUE THREAD

**Issue by EricRogers-NOAA** [ufs-community/ufs-weather-model#1260]
@junwang-noaa On 6/7/2022 the LAMDA and LAMDAX parallels on WCOSS Dell started using the latest ufs-weather-model code (#4376018). Immediately upon starting the forecast this diagnostic print for potential skin temperature in module_sf_mynn.f90 was written out at millions of grid points:

THVSK_lnd(I)           1          10   361.996437289128
   345.488632091217        336.783800357902        339.217407226562
  7.862164942031374E-002

Mike Barlage noted that a surface skin temperature of 66C and a qsfc of 0.078 are quite high and unreasonable.  Ben Blake made  plots comparing a 36-hr forecast of skin temperature using our previous version of code (#a4c67ed committed on 3/24/2022) to a 00-hr forecast valid at the same time using the new code.  You can see the differences over land are quite drastic.

https://ftp.emc.ncep.noaa.gov/mmb/bblake/comparetsfc_namerica_f36.png (from old code)
https://ftp.emc.ncep.noaa.gov/mmb/bblake/comparetsfc_namerica_f00.png (from new code)

**Comment by SamuelTrahanNOAA** [comment]
@joeolson42 Will the typo PR https://github.com/NCAR/ccpp-physics/issues/941 fix this issue?

**Comment by SamuelTrahanNOAA** [comment]
This bug was probably caused by the typo on line 851 of module_sf_mynn which calculates the potential temperature:

```
 TH1D(I)=T1D(I)**(100000./P1D(I))**ROVCP !(Theta, K)
```

The first ** should be a *

```
 TH1D(I)=T1D(I)*(100000./P1D(I))**ROVCP !(Theta, K)
```

That is corrected in #941, though we won't be certain it will eliminate all of your qsat and skin temperature problems until you try the bugfix in your parallels.

**Comment by joeolson42** [comment]
Yes, this typo-bugfix will fix the problem. I ran a test and the result was very similar to the original version (now running in RRFS a & b).

**Comment by junwang-noaa** [comment]
@EricRogers-NOAA may I ask if the issue is resolved?

**Comment by EricRogers-NOAA** [comment]
It is resolved and it can be closed. Thanks.
