### ISSUE TITLE
Update release/public-v3 to use ccpp-v6 and the WoFS suite for use with SRW app release/public-v2

### ISSUE THREAD

**Issue by mark-a-potts** [ufs-community/ufs-weather-model#1261]
We need a release/public-v3 branch that can be used by the SRW for its release/public-v2.

The update of release/public-v3 of the fv3atm will bring in both the WoFS suite and version 6 of the CCPP.

- required to support SRW public release version 2

**Comment by mkavulich** [comment]
@mark-a-potts The top-level README.md also needs to be updated; currently it uses an unsupported CCPP suite (FV3_GFS_v15p2) as a build example.

**Comment by jkbk2004** [comment]
#1280 merged in
