### ISSUE TITLE
fix the density of the frozen precip types

### ISSUE THREAD

**Issue by HelinWei-NOAA** [ufs-community/ufs-weather-model#1268]
## Description

The snow density is used for all frozen precip types in the current operational GFS. With this assumption the density for sleet or freezing rain is too small and the snow depth is overestimated in this situation. This fix will give the different density to snow, graupel, and freezing rain in the Noah LSM driver.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- [ufs-weather-model PR 1267](https://github.com/ufs-community/ufs-weather-model/pull/1267)
- [fv3atm PR 546](https://github.com/NOAA-EMC/fv3atm/pull/546)
## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

**Comment by junwang-noaa** [comment]
The code is merged. The issue will be closed.
