### ISSUE TITLE
Updating the lheatstrg namelist variable for RT tests using NoahMP and set dt_inner=dt_atmos if sedi_semi=T for Thompson MP

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1274]
## Description
Physics group found that the lheatstrg namelist variable is set to .true. when NoahMP is used, this will double count the canopy heat storage effect which is taken care of in NOAH-MP. This variable needs to be set to .false in ufs-weather-model RT tests when NoahMP is used. Currently all the P8 tests (coupled and standalone) have lheatstrg=.true.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
- check out ufs-weather-model and run any coupled test.

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- PR is coming

**Comment by junwang-noaa** [comment]
@barlage @HelinWei-NOAA @yangfanglin @ChunxiZhang-NOAA  FYI.

**Comment by yangfanglin** [comment]
@DeniseWorthen @junwang-noaa @ChunxiZhang-NOAA Can this PR be combined with another existing PR ?   The changes are rather simple.  (@JessicaMeixner-NOAA ).

I have created a new branch https://github.com/yangfanglin/ufs-weather-model/tree/no_chsp out of the authoritative repo as of 5pm on 6/24/2022, in which I made the following changes to simplify the settings.  Now lheatstrg is set T or F depending on LSM value.

------------------
    in ./test/default_vars.sh set default  LHEATSTRG=.false. if LSM=2, and LHEATSTRG=.true. if LSM=1

    removed LHEATSTRG settings in all following control files to avoid local incorrect modifications
            modified:   default_vars.sh
            modified:   tests/atmaero_control_p8
            modified:   tests/control_2threads_p8
            modified:   tests/control_debug_p8
            modified:   tests/control_decomp_p8
            modified:   tests/control_p8
            modified:   tests/control_p8_lndp
            modified:   tests/control_p8_rrtmgp
            modified:   tests/control_restart_p8
            modified:   tests/control_thompson
            modified:   tests/control_thompson_debug
            modified:   tests/control_thompson_extdiag_debug
            modified:   tests/control_thompson_no_aero
            modified:   tests/control_thompson_no_aero_debug
            modified:   tests/control_thompson_progcld_thompson_debug
            modified:   tests/rrfs_conus13km_hrrr_warm
            modified:   tests/rrfs_conus13km_radar_tten_warm
            modified:   tests/rrfs_smoke_conus13km_hrrr_warm

**Comment by yangfanglin** [comment]
Executed "rt.sh -e -c -k -l rt.conf" on WCOSS.  104 out of total 105 RT tests passed.  The one failed is cpld_debug_p8, with the error message " Assertion failed in file ../../src/mpid/ch3/channels/nemesis/netmod/dapl/dapl_send_ud.c at line 2143: vc_reserve_area->RNDV_SEND_STATUS == RNDV_SEND_WAITING_FIN_REPLY".  Rerunning "rt.sh -c -k -n cpld_debug_p8" succeeded.

**Comment by ChunxiZhang-NOAA** [comment]
@yangfanglin I can add these changes into PR#1192.

**Comment by yangfanglin** [comment]
Add condition if sedi_semi=T then dt_inner=dt_atmos in
    
modified:   tests/cpld_bmark_p8
    modified:   tests/cpld_bmark_p8_35d
    modified:   tests/cpld_control_c192_p8
    modified:   tests/cpld_restart_bmark_p8
    modified:   tests/cpld_restart_c192_p8

RT tests for these cases on WCOSS are successful.  changes are committed to https://github.com/yangfanglin/ufs-weather-model/tree/no_chsp

 (@junwang-noaa @ChunxiZhang-NOAA @RuiyuSun @AnningCheng-NOAA @JessicaMeixner-NOAA )

**Comment by DeniseWorthen** [comment]
If the P8 configuration is ``sedi_semi=T``, then the ``dt_inner`` for any P8 test will need to be "hard-coded" to be the dt_atmos. The P8 configurations are static configurations as far as the RTs are concerned.

**Comment by yangfanglin** [comment]
@DeniseWorthen Please see the changes I made in https://github.com/yangfanglin/ufs-weather-model/tree/no_chsp.  dt_inner settings in the few p8 tests are now conditional dependent on sedi_semi

**Comment by JessicaMeixner-NOAA** [comment]
@yangfanglin should DT_INNER be changed fro p8 based standalone tests too?

**Comment by yangfanglin** [comment]
@JessicaMeixner-NOAA Yes.   I first tried to change default_vars.sh for all conditions/cases but found the settings are convoluted.  I will make another attempt to update default_vars.sh.

**Comment by DeniseWorthen** [comment]
@yangfanglin The setting should not be conditional since the P8 configuration assumes semi_sedi is True. Also, the same setting will need to be added to all the P8 restart tests.

**Comment by yangfanglin** [comment]
semi_sedi is true in default_vars.sh.  Then  dt_inner is set based on sedi_semi in, for instance,  tests/cpld_bmark_p8, as

export DT_INNER=${DT_INNER_c384}
if [[ $SEDI_SEMI = .true. ]]; then
 export DT_INNER=$DT_ATMOS
fi
