### ISSUE TITLE
EPIC request to delete the release/public-v3 & release-public-v3-SRW branches

### ISSUE THREAD

**Issue by daniel-hildebrandt** [ufs-community/ufs-weather-model#1276]
## Description
These were created on the original timeline for the proposed SRW release, however, it was later discussed to not include certain commits / features in the public-v3 branch. EPIC then wanted to create a new branch which was intended to be the new release branch, but unexpected issues arose during testing, not previously caught. 
EPIC will create a PR to pull from the current epic branch: 
https://github.com/NOAA-EPIC/ufs-weather-model-1
into a new branch that will be created for the SRW release based off commit b751b8d5e37d68324376161193d20bd28e8e116b. 
This new branch will allow a clean and easy to understand commit history while omitting key commits not scoped for this release. 

## Additional context
Summary:
- delete release/public-v3 branch
- delete release-public-v3-SRW branch
- create new branch "release/public-v3" based off b751b8d5e37d68324376161193d20bd28e8e116b

## Output

**Screenshots**

**output logs**

**Comment by jkbk2004** [comment]
#1280 merged in
