### ISSUE TITLE
write_dopost not writing out ice mask properly

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-weather-model#1283]
## Description
I am looking at the variable landsfc in the GFSFLX.GrbF<fhr> files, and I expect it to have values of 0 over open water, 1 over land, and 2 over ice. But what I see is only values of 2 near the ice-margin.  
  I re-ran the same case turning off write_dopost, and when  I get the netcdf output, the field looks like what I expect.  

### To Reproduce:
What compilers/machines are you seeing this with?
hera/intel
Give explicit steps to reproduce the behavior.
1. run the cpld_control_p8 regression test
2. modify model_configure to write out grib files and add the params_grib2_tbl_new  postxconfig-NT_FH00.txt  postxconfig-NT.txt files
3. then, oops, look at the bug
This plot show the land-sea-ice mask with netcdf output (top) and grib output (bottom)
![land](https://user-images.githubusercontent.com/38869668/174878168-5b324123-d6a1-42c3-8110-c6bbf7d49ee7.png)

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

**Comment by DusanJovic-NOAA** [comment]
landsfc variable (discipline=2, category=0, parameter=0) in grib files is land/sea mask. (sea=0, land=1), no other value should be specified. If I'm interpreting grib documentation correctly:

https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-2-0.shtml

those values of 2 near the ice/open water boundary are incorrect (should be 0), in my opinion.

**Comment by JessicaMeixner-NOAA** [comment]
@pjpegion this seems similar to a previous upp issue here: https://github.com/NOAA-EMC/UPP/issues/405

**Comment by DusanJovic-NOAA** [comment]
@pjpegion I repeated the same test as you did and found that in addition to adding `params_grib2_tbl_new`, `postxconfig-NT_FH00.txt` and `postxconfig-NT.txt` files to the run directory you also need file named `itag`, which defines, among other things, `modelname` which is used in UPP to properly set the vales of land/sea mask, as described in the above UPP issue.

If `itag` file is not present in the run directory mode will silently continue running and use incorrect (undefined) `modelname`. We must fix this in the model.

BTW, the filename `itag` is not very descriptive.

**Comment by pjpegion** [comment]
@DusanJovic-NOAA thanks. Adding the itag now create a land/sea mask that makes sense.  But since ice is not included in this mask, it does not make sense to me to have it in the output since it does not vary with time.

**Comment by DusanJovic-NOAA** [comment]
That's a different issue. As far as I understand, the land/sea mask variable LAND (as defined by the GRIB standard) is always static. There are other variables, like ICEC (Ice cover) (https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-10-2.shtml) that can be used to describe changing ice vs. non-ice points.

**Comment by pjpegion** [comment]
Indeed,  I'm going to close this issue since the itag resolved it.
