### ISSUE TITLE
Switch bmark_p8 test to a rectilinear 1/2deg grid

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#1297]
## Description
The 1/4 deg tripole grid is too slow for P8 to run w/in the 8-hour time frame; the corresponding regression test needs to be switched to the 1/2 deg rectilinear grid that will be used in the P8 runs.

## Solution

Update the RT scripts to use a mesh and wave domain different than the ocean and ice.

**Comment by pjpegion** [comment]
What components are moving from 1/4 to 1/2 degree?

**Comment by JessicaMeixner-NOAA** [comment]
Just the wave model component.  We had tried to increases the wave model's resolution to 1/4 degree, but now are moving back to the 1/2 deg for P8
