### ISSUE TITLE
Regression test development for Q4FY2022

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1310]
This EPIC includes UFS WM regression test development for all the applications.

**Comment by DeniseWorthen** [comment]
EPIC team does not have this in the PI6 list (task assignment list) but in future they should be picking these types of issues. 

This EPIC (RT framework etc) is a EPIC-team responsibility in the future. Test owners (application team or the feature developer) they need to work w/ EPIC. Test owners can be community, outside of EIB or even EMC.

**Comment by DeniseWorthen** [comment]
Potential impact of tracking gefsv13 and gfsv17 for global configuration. Sustainability of this is a question.

Dusan suggests some budgets that the RT tests fit inside of (core hours, all time etc). Each app gets a slice of the total pie. Each app team decides how to make use of their allocations. 

Jun reports that management is looking at the issue. Also issue of how the RTs split between EPIC and EIB.

**Comment by DeniseWorthen** [comment]
Lisa will submit new gfsv17 test and confirm that pass the ORTs at time of commit. But each ORT test type will not be added as new RT test for gfsv17. 

Jun reports that the issue of RT number and burden will be escalated to R2O steering committee.

**Comment by junwang-noaa** [comment]
We haven't heard from the UFS R2O steering committee. We will work with EPIC to create a separate issue.
