### ISSUE TITLE
aerosols breaks diagnose_cplFields for FV3

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#1314]
## Description
The setting of ``dbug_flag`` in nems.configure for the coupled model triggers the reporting of the min, max and sum of each connected import or export field for FV3. When the app is S2SWA, this produces an error in the PET logs connected to FV3.

### To Reproduce:
Run both ``cpld_control_p8`` (app=S2SWA) and ``cpld_control_noaero_p8`` (app=S2SW) but change the ``default_vars`` value of dbug_flag

index 28807b10..c9117d04 100755
--- a/tests/default_vars.sh
+++ b/tests/default_vars.sh
@@ -609,7 +609,7 @@ export coupling_interval_fast_sec=${DT_ATMOS}

 export RESTART_N=${FHMAX}
 export CPLMODE=nems_frac
-export cap_dbug_flag=0
+export cap_dbug_flag=6
 export use_coldstart=false
 export use_mommesh=true
 export RUNTYPE=startup

The log files for the cpld_control_noaero_p8 show no ERROR messages. 

For the cpld_control_p8, the PET logs show on import:

```
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:ice_fraction    0.000000      0.000000      0.000000
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:inst_ice_ir_dif_albedo    0.000000      0.000000      0.000000
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:inst_ice_ir_dir_albedo    0.000000      0.000000      0.000000
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:inst_ice_vis_dif_albedo    0.000000      0.000000      0.000000
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:inst_ice_vis_dir_albedo    0.000000      0.000000      0.000000
20220706 125643.987 ERROR            PET000 ESMF_LocalArrayGet.F90:3006 ESMF_LocalArrayGetData Arguments are incompatible  - farrayPtr rank does not match LocalArray rank
20220706 125643.987 ERROR            PET000 ESMF_ArrayGet.F90:2140 ESMF_ArrayGetFPtr Arguments are incompatible  - Internal subroutine call returned Error
20220706 125643.987 ERROR            PET000 ESMF_FieldGet.F90:2875 ESMF_FieldGetDataPtr Arguments are incompatible  - Internal subroutine call returned Error
20220706 125643.987 ERROR            PET000 module_cap_cpl.F90:227 Arguments are incompatible  - Passing error in return code
20220706 125643.988 INFO             PET000 UFS Aerosols: Advancing from 2021-03-22T06:00:00 to 2021-03-22T06:12:00
```

and on export:

```
20220706 125743.681 INFO             PET000 (FV3: state_diagnose) :ES:inst_temp_height_surface    284.7190      298.7269      112714.1
20220706 125743.681 INFO             PET000 (FV3: state_diagnose) :ES:inst_temp_levels    179.5572      298.2122     0.1222354E+08
20220706 125743.681 ERROR            PET000 ESMF_LocalArrayGet.F90:3006 ESMF_LocalArrayGetData Arguments are incompatible  - farrayPtr rank does not match LocalArray rank
20220706 125743.681 ERROR            PET000 ESMF_ArrayGet.F90:2140 ESMF_ArrayGetFPtr Arguments are incompatible  - Internal subroutine call returned Error
20220706 125743.681 ERROR            PET000 ESMF_FieldGet.F90:2875 ESMF_FieldGetDataPtr Arguments are incompatible  - Internal subroutine call returned Error
20220706 125743.681 ERROR            PET000 module_cap_cpl.F90:227 Arguments are incompatible  - Passing error in return code
```

**Comment by DeniseWorthen** [comment]
This appears to be caused by the dimcount=4 for aerosol fields. Additional code needs to be added to account for the possibility of dimcount=4 in the ptr retrieval.

**Comment by junwang-noaa** [comment]
@DeniseWorthen The aerosol tracer fields have 4 dimensions, are some code changes needed in GOART side or the NUOPC side?

**Comment by DeniseWorthen** [comment]
I think there just needs to be an option to have more than three dimension when retrieving a pointer inside of ``state_diagnose``. Right now, the code is written so that if dimcount is not 2, it is assumed to be 3. So we need to allow a dimcount of 2,3 or 4. We could also just exit the itemCount loop if dim > 3.

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen I've fixed this and I've tested this myself, seems to be OK. Since this won't change anything in UFSWM unless that debug setting is set, could you test my changes yourself: https://github.com/BrianCurtis-NOAA/ufs-weather-model/tree/bugfix/4d_state_diagnose

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Yes, this seems to be working correctly now. It will have no impact since it was a non-fatal error even when the debugging flag was turned on. It's an easy one to combine w/ another non-baseline change PR. Thanks!
