### ISSUE TITLE
Have CMake check capability for handling Fortran 2008 intrinsic FINDLOC

### ISSUE THREAD

**Issue by edwardhartnett** [ufs-community/ufs-weather-model#132]
See discussion in #114.

Seems that we need the GNU fortran compiler to handle some aspects of 2003 which it does not do before version 9.0.

So the CMake build needs to check the fortran compiler to make sure it can handle the Fortran 2003 that it needs to handle.

**Comment by climbfuji** [comment]
Thanks, tiny correction: Fortran 2008 standard, not 2003.

**Comment by edwardhartnett** [comment]
Sorry, 2008, not 2003. But what we will check for is the Fortran 2008 intrinsic called FINDLOC,

This does not just apply to GNU, right? Any fortran compiler has to be able to handle FINDLOC.

**Comment by climbfuji** [comment]
Correct, but essentially every compiler should comply to the Fortran 2008 standard.

**Comment by DusanJovic-NOAA** [comment]
We should add this check:

````
if (CMAKE_Fortran_COMPILER_ID MATCHES "GNU" AND CMAKE_Fortran_COMPILER_VERSION VERSION_LESS 9.0.0)        
  message(FATAL_ERROR "GNU Compiler >= 9 is required")
endif()
```

**Comment by edwardhartnett** [comment]
Instead of checking for the GNU fortran compiler version, lets check that the intrinsic is supported. That will work for all compilers, and will also trigger an error for other compilers that don't have this intrinsic we require.

I am putting together a PR now, using CMake function check_fortran_source_compiles.

**Comment by DusanJovic-NOAA** [comment]
It is much simpler to use this check instead of maintaining little test program that tests one particular intrinsic. And then keep adding different test programs. Once we establish the minimum version of both GNU and Intel we can just check for that specific version and that's it. We only support two compilers intel and gnu.

**Comment by edwardhartnett** [comment]
It is equally simple to make it work everywhere. There is no test program to maintain, it is all done in Cmake. What I have now is this:

```
check_fortran_source_compiles("integer i; i=FINDLOC ([2, 6, 4, 6], VALUE = 6)" f08findloc
                              SRC_EXT f90)

```

So as you see, no code to maintain. THe CMakeLists.txt does it all.

**Comment by edwardhartnett** [comment]
I have this ready, but I'm upgrading my gfortran and that is taking a while. When it's complete, and I've confirmed this works, I'll put up a PR.

**Comment by DusanJovic-NOAA** [comment]
> It is equally simple to make it work everywhere. There is no test program to maintain, it is all done in Cmake. What I have now is this:
> 
> ```
> check_fortran_source_compiles("integer i; i=FINDLOC ([2, 6, 4, 6], VALUE = 6)" f08findloc
>                               SRC_EXT f90)
> ```
> 
> So as you see, no code to maintain. THe CMakeLists.txt does it all.

The first argument is a test program. It is not in a separate file but it's a program that needs to be maintained.

If we need to test for some other intrinsic somebody will need to add another test, and maintain all those little programs. Also, there might be cases where we want to make sure a certain compiler version is used regardless of whether a test program compiles or not or if it executes or not. For example if there's a known bug or, for example, if we need a compiler version greater than some specific version in order to get a bit-reproducible result. 

Those kinds of requirements can not be tested by ``check_fortran_source_compiles``.

**Comment by edwardhartnett** [comment]
Yes, if someone wants another intrinsic which causes a problem, another test should be added.

This requirement is exactly what check_fortran_source_compiles is for, and it works fine.

If more things need to be checked (and they no doubt do), then we check them. This works for all versions of all fortran compilers. It is usual in build systems to try and solve the problem generally instead of only solving specific compilers.

**Comment by DusanJovic-NOAA** [comment]
It is much simpler to require minimum version of GNU and minimum version of Intel compiler. That's just two numbers and that's all. And like I said there are things that can not be checked by simple test program. 

After all cmake itself and all other packages (libraries) are using the concept of minimum required version. That's the whole idea of versioning. We do not write little test programs to check whether some function is available or not.

**Comment by edwardhartnett** [comment]
We do, in general, write test programs to test whether some function is present. That is very common, in fact, and usually necessary. For example, soon UFS will have to start checking whether netcdf supports szip. This cannot be done by version, because it can be built either way.

This is what netcdf-fortran and most other science packages do. The wisdom I would pass on to you from the netCDF experience is you should probably do things like other packages.

So there are two solutions proposed here, one which is general and works with all compilers, and one which is specific to gfortran. You may choose the one you like, I guess.

I will be happy to see this problem solved in either the general or compiler-specific way.

**Comment by DusanJovic-NOAA** [comment]
@climbfuji and @junwang-noaa What's your opinion on this? Should we add test programs or explicitly require minimum versions of GNU and Intel compilers?

**Comment by edwardhartnett** [comment]
Instead, you should be asking the question to CMake experts. How about we post it on stackoverflow and get opinions?

**Comment by DusanJovic-NOAA** [comment]
This will not be maintained by CMake experts or people on stackoverflow. It will be maintained by us.

**Comment by edwardhartnett** [comment]
It *will* be maintained by CMake experts. It will be maintained by us. ;-)

Don't worry, I'm not going away. ;-)

**Comment by climbfuji** [comment]
I agree with @DusanJovic-NOAA - it doesn't make sense to test for certain features. We'll end up testing for who-knows-how-many of those, and all of them need to be maintained. A complex piece of software pulling together so many different components can only be vetted for certain compilers and compiler versions, so @DusanJovic-NOAA's suggestion makes perfect sense.

**Comment by edwardhartnett** [comment]
Roger that. You will soon see however that we will be testing for many features, since that is what the build system should be doing.

However, I will he happy to see this problem solved in either the general or specif way. I will take down my PR.

**Comment by climbfuji** [comment]
> Roger that. You will soon see however that we will be testing for many features, since that is what the build system should be doing.
> 
> However, I will he happy to see this problem solved in either the general or specif way. I will take down my PR.

Thank you. There are also other reasons that cannot be covered with simple code feature tests in CMake. For example, for a specific version of the Intel 18 compiler (only one of them), a correct block of code led to a segfault. This was traced back to a bug in the compiler (together with the Intel developers), that could only be reproduced in the execution of the large program (a simple test case didn't do, and even that simple case involved about 50-100 lines of code). In this specific case, it was decided to rewrite the routine so that the bug didn't trigger and we could keep using that version of the Intel compiler. But in many cases we will want to exclude specific versions of compilers if we identify issues as the one described here.

**Comment by DusanJovic-NOAA** [comment]
> Roger that. You will soon see however that we will be testing for many features, since that is what the build system should be doing.

Well, I hope we don't end up doing that (writing tests to check whether a feature is available). Build systems **should not be doing that**, at least modern build systems. Build systems should only be used to define build options, targets and dependencies of those targets. Anything more than that only if absolutely necessary.

> 
> However, I will he happy to see this problem solved in either the general or specif way. I will take down my PR.

**Comment by edwardhartnett** [comment]
@DusanJovic-NOAA I know I must be misunderstanding you. What else is a build system for, except to run a bunch of tests on the system and determine the build settings? 

The problem of building scientific codes is well-solved outside of NOAA. 

Please keep in mind netCDF, which builds cleanly everywhere, both C and Fortran. The netCDF project has a fraction of the resources of UFS. (They don't even own an intel compiler to test on! Yet it never occurred to anyone that they would not build on intel.)

Let us emulate netCDF by embracing industry-standard best-practices. 

I will submit a PR tomorrow with the GNU-specific solution you have approved.
