### ISSUE TITLE
NG-GODAS development Q4FY2022

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1324]
This EPIC includes:

1) Update some CDEPS tests to use C-grid in CICE6 dynamics.
2) CDEPS code updates

**Comment by DeniseWorthen** [comment]
Needs to keep up-to-date w/ CDEPs in UWM. @binli2337 will still be code manager and do the updates when required. No current plan to bring in a 1/12 resolution test to UWM.

**Comment by DeniseWorthen** [comment]
Not clear what the role of EIB is for this EPIC.
