### ISSUE TITLE
Update modulefiles to Lua

### ISSUE THREAD

**Issue by aerorahul** [ufs-community/ufs-weather-model#1326]
## Description
The ufs-weather-model modulefiles need to be updated to Lua format.
The ufs-weather-model got a pass for transition to WCOSS2 for the GFS.

## Solution
Replace all modulefiles with Lua modules (For Orion, Hera and WCOSS systems) with the ability to pass versions of the dependencies from the environment.  See UPP for examples https://github.com/NOAA-EMC/UPP/tree/develop/modulefiles

## Alternatives
None

**Comment by BrianCurtis-NOAA** [comment]
Are there any issues with Gaea that you're aware of? I notice UPP doesn't have a modulefile for it.

**Comment by aerorahul** [comment]
> Are there any issues with Gaea that you're aware of? I notice UPP doesn't have a modulefile for it.

No idea.

**Comment by climbfuji** [comment]
I think gaea should stick with tcl env modules.

In spack-stack, we are going away from the hacky solution that I put in place for nceplibs/nceplibs-external and hpc-stack that requires running the `init_lmod.sh` script (which takes notes of all currently loaded modules, purges the environment, activates lua, loads them again - this works for many users, but not for all, since the order to reload is important). spack-stack will only generate tcl modules on gaea. Same currently for AWS ubuntu / aws ec2 instances.

**Comment by aerorahul** [comment]
Has there been an update to this ticket.
This is now a blocker in enabling workflow on WCOSS2.

**Comment by BrianCurtis-NOAA** [comment]
> Has there been an update to this ticket. This is now a blocker in enabling workflow on WCOSS2.

@aerorahul OK, I can get started on this.

**Comment by BrianCurtis-NOAA** [comment]
I get an interesting problem:
```
[ 99%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/io/module_wrt_grid_comp.F90.o
/scratch1/NCEPDEV/nems/Brian.Curtis/git/BrianCurtis-NOAA/ufs-weather-model/FV3/io/module_wrt_grid_comp.F90(136): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [CTLBLK_MOD]
      use ctlblk_mod, only: numx
----------^
/scratch1/NCEPDEV/nems/Brian.Curtis/git/BrianCurtis-NOAA/ufs-weather-model/FV3/io/module_wrt_grid_comp.F90(380): error #6404: This name does not have a type, and must have an explicit type.   [NUMX]
      numx = itasks
------^
/scratch1/NCEPDEV/nems/Brian.Curtis/git/BrianCurtis-NOAA/ufs-weather-model/FV3/io/module_wrt_grid_comp.F90(136): error #6580: Name in only-list does not exist or is not accessible.   [NUMX]
      use ctlblk_mod, only: numx
----------------------------^
compilation aborted for /scratch1/NCEPDEV/nems/Brian.Curtis/git/BrianCurtis-NOAA/ufs-weather-model/FV3/io/module_wrt_grid_comp.F90 (code 1)
```

This only happens with the .lua formatted modulefiles. I'm currently looking into it, but wanted to note here in case I can't get back to it until next week.

**Comment by BrianCurtis-NOAA** [comment]
my branch: https://github.com/BrianCurtis-NOAA/ufs-weather-model/tree/ufs_lua

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA Thanks for the help/fix!

**Comment by BrianCurtis-NOAA** [comment]
I've tested on acorn/wcoss2, hera. I have yet to test my changes Jet, Orion, Cheyenne. I will try getting a PR in tomorrow. https://github.com/BrianCurtis-NOAA/ufs-weather-model/tree/ufs_lua

**Comment by DeniseWorthen** [comment]
Can this issue be closed?

**Comment by BrianCurtis-NOAA** [comment]
> Can this issue be closed?

yes
