### ISSUE TITLE
regional FV3 slow on WCOSS2

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [ufs-community/ufs-weather-model#1329]
## Description
We are trying to set up RRFS on WCOSS2. However, regional FV3 warmstart is very slow on WCOSS2. The read I/O takes about 3000s to read in restart file.

### To Reproduce:
What compilers/machines are you seeing this with?
WCOSS2

Give explicit steps to reproduce the behavior.
1. cp /lfs/h2/emc/da/noscrub/Shun.Liu/test/canned_rrfs_warmstart to your directory
2.  modify line 89 in sub.sh to change your directory path
3. qsub sub.sh

Source code: 
https://github.com/NOAA-GSL/ufs-weather-model
branch: gsl/develop

**Comment by junwang-noaa** [comment]
@ShunLiu-NOAA I believe the slowness is resolved after using the model code with io slowness fix in PR#1294. Can we close this issue? Thanks

**Comment by ShunLiu-NOAA** [comment]
Jun,

You can close the issue. Thank you for your help.

Shun

**Comment by junwang-noaa** [comment]
PS. The initialization time is reduced to 50s with the latest code.

**Comment by ShunLiu-NOAA** [comment]
Thank you for this information. It is clear now that we need to update code
to take the advantage of I/O update.

Shun
