### ISSUE TITLE
RRFS Q4FY2022

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1331]
The EPIC includes issues related to RRFS in Q4FY2022

**Comment by DeniseWorthen** [comment]
* Ratko and Ben Blake are EMC contacts. 
* MPI decomp problems (RRFS, LAM) are all fixed.
* Restart problem in LAM is fixed, @RatkoVasic-NOAA will replace coarse resolution tests w/ small domain high resolution tests for UWM. Only script level changes will be needed.  All tests are with LAM configuration.
* RRFS-A is next candidate for opn, Will use same domain as LAM and eventually replace it. Next step will be to replace all regional tests from LAM to RRFS-A configuration.

**Comment by DeniseWorthen** [comment]
PR #1471 will conclude LAM update. Then work will begin on RRFS configuration which will eventually replace LAM.

**Comment by DeniseWorthen** [comment]
PR #1471 will conclude LAM update. Then work will begin on RRFS configuration which will eventually replace LAM.

**Comment by junwang-noaa** [comment]
I am closing this issue, will check RRFS team on reproducibility with RRFS configuration.
