### ISSUE TITLE
ocean SPPT can cause the ocean model to crash

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-weather-model#1332]
## Description
I am running with ensemble initial conditions, and I have one member that has large perturbations in it. These perturbations cause large physics tendencies, which are interacting with SPPT to produce a temperature in the ocean that is too cold, and the model fails when this blob of cold water reaches the surface.  

### To Reproduce:
I have a specific case with my own initial conditions, so it will not easy for someone to reproduce.

## Additional context
There is a check in the ocean model's SPPT that prevents salinity to go negative, and there needs to be a check to prevent water temperatures from getting too cold.

**Comment by DeniseWorthen** [comment]
@pjpegion I believe this was fixed in PR #1302 so I'm closing.
