### ISSUE TITLE
Orion Performance Issues

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1334]
## Description
When running the prototypes, we see huge variability in runtime performance on orion (not on hera). This has been seen with and without aerosols and has been an issue since at least December 2021 if not before.   The most recent runs were 35 day runs with p8c-ish like settings in which some runs took 1.4x as long as the faster runs which had similar runtimes to what is seen on hera.  The same variability in runtime is not seen on hera.  Issues were previously opened with the orion Helpdesk by @rmontuoro a long time ago, but no resolution or cause of issue was ever found. 

### To Reproduce:
Run the prototype runs for say 5 days multiple times on orion.  

## Additional context
Once the settings for P8 are finalized I can make a canned case or I can make them with dt=225 if someone is available to look at things now.  

## Output

**output logs**
/work2/noaa/marine/jmeixner/p8c/tp8c2013010100/COMROOT/tp8c2013010100/logs/2013010100/gfsfcst.log:   0: The total amount of wall time                        = 2249.260355
/work2/noaa/marine/jmeixner/p8c/tp8c2014070100/COMROOT/tp8c2014070100/logs/2014070100/gfsfcst.log:   0: The total amount of wall time                        = 16393.875572
/work2/noaa/marine/jmeixner/p8c/tp8c2015010100/COMROOT/tp8c2015010100/logs/2015010100/gfsfcst.log:   0: The total amount of wall time                        = 11416.527706

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA  A quick check, "we see huge variability in runtime performance on **hera**", Do you mean "Orion" or hera also has this issue?

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA A quick check, "we see huge variability in runtime performance on **hera**", Do you mean "Orion" or hera also has this issue?

@junwang-noaa yes, thank you! I have updated the text.

**Comment by zach1221** [comment]
Hi, @JessicaMeixner-NOAA . I know this is an older issue but I wanted to follow up with you on it. I ran a few different p8 tests, and it seemed like the performance between Orion and Hera was very similar, at least when referring to wall time. I ran 5 separate tests today of each on both HPCs and just took the average. If you were using a different case(s) to test, please let me know.
**Orion**	                              **Average 5x**
control_p8_intel	:              175.134s
cpld_control_p8_intel:	      335.311s
cpld_decomp_p8_intel	  :     342.005s
cpld_control_ciceC_p8_intel :	336.061s
cpld_control_c192_p8_intel	: 590.349s
	
**Hera**	
control_p8_intel	:               171.348s
cpld_control_p8_intel	:        344.858s
cpld_decomp_p8_intel:	         355.460s
cpld_control_ciceC_p8_intel :	348.532s
cpld_control_c192_p8_intel:	582.175s

**Comment by JessicaMeixner-NOAA** [comment]
@zach1221 indeed this is a long open issue.    I haven't run a large amount of runs in a while.  You're using fairly low resolution short tests and my tests were for coupled S2SW and S2SWA for C384 and C768 for a minimum of 7 days (I think this particular issue was for 35 day runs).  I know we were not the only group experiencing this issue either.  It's possible the issue has been resolved since opening this issue.  One question I have is that you report average time, how big of a variability do you get within the runs? We'd have runs literally double other run times.

**Comment by zach1221** [comment]
@JessicaMeixner-NOAA here's the individual run times.
![image](https://github.com/ufs-community/ufs-weather-model/assets/99902696/895b50a1-26ed-48f0-8af5-94fc076098ab)

**Comment by JessicaMeixner-NOAA** [comment]
So there's one run for control_p8_intel on orion that looks more than the others.  I don't know if this was ever seen at the regression test level.  I don't know if you have larger/longer tests to look at.  I wont have time to do a few tests from the g-w to see if we still have issues for probably at least a week or so.

**Comment by zach1221** [comment]
Ok, I think the 183.59 second run (~8 second difference from average) for control_p8 Intel on Orion is likely just machine variability that would be experienced across any of the platforms, when running enough tests. Can you walk me through how you're running coupled C384 for 7 to 35 days? Then I can test that on my end and see if it's still an issue.

**Comment by JessicaMeixner-NOAA** [comment]
I run the global-workflow https://github.com/noaa-emc/global-workflow

**Comment by zach1221** [comment]
Resolving ticket at this time.
