### ISSUE TITLE
Test name in tests/tests should be the same name that outputs in baseline directories

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#1337]
## Description
The test name in tests/tests should be the same names that appear in baseline directories on our supported machines.

baseline directories that do not match the name of their tests/tests name (I will add to this if needed):
fv3_regional_3km
fv3_regional_control
fv3_regional_debug
fv3_regional_netcdf_parallel
fv3_regional_noquilt

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I don't see any tests named fv3_regional_X anymore. Can we close this issue?

**Comment by BrianCurtis-NOAA** [comment]
Yes
