### ISSUE TITLE
ESMF still not working with clang compiler on macOS

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#1340]
## Description

When using Apple's or LLVM's clang/clang++ compilers on macOS, the ufs-weather-model immediately crashes at startup. I've reported this previously, it started around version 8 of ESMF. It didn't make it up high enough in the priority list (yet), but I believe this needs to be fixed, because software stacks like spack-stack are better supported with clang+gfortran on macOS than with gcc+gfortran (especially as we move towards software stacks that include more Python packages).

### To Reproduce:

Compile ufs-weather-model on macOS with clang+gfortran (choose hpc-stack or spack-stack, doesn't matter). Try to run the model, it immediately crashes. Unfortunately there is no good traceback information.

## Output

I will provide the little bit of info that is available later (@climbfuji todo)

**Comment by zach1221** [comment]
@climbfuji following up here as well. I know there has been some work done recently with ufs-weather-model on macOS, but I'm uncertain if this is still an issue.

**Comment by climbfuji** [comment]
We should try.

**Comment by climbfuji** [comment]
Closing this in favor of https://github.com/ufs-community/ufs-weather-model/issues/1698 (the problem persists, but more information is provided in #1698).
