### ISSUE TITLE
Updates for P8 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1350]
## Description
In response to the mini-P8c runs, we will make the following updates: 
* Revert calculation of T2m (@HelinWei-NOAA )
* Set do_gsl_drag_tofd=false as this resolved the stability issues similar to those reported in https://github.com/ufs-community/ufs-weather-model/issues/1277) 
* Updates to aerosol configuration (@bbakernoaa) 

## Solution
A PR with the above changes. 

## Alternatives
N/A 

## Related to

- (CCPP issue for T2m)

**Comment by HelinWei-NOAA** [comment]
@JessicaMeixner-NOAA You want me to commit the change to your ccpp-physics branch?

**Comment by JessicaMeixner-NOAA** [comment]
That or point me to your CCPP branch and I'll just point to your CCPP branch.  Or do you want it to all be from my branches?  I was hoping you might make the PR to CCPP as you will be able to provide a better description of the changes, but either way works for me.

**Comment by HelinWei-NOAA** [comment]
I prefer all from your branches. I have created [this branch](https://github.com/HelinWei-NOAA/ccpp-physics/tree/p8c_2mtq_revert) including our planned change.
