### ISSUE TITLE
Update documentation on readthedocs for ORTs to include information on what ORT's to run for specific types of tests.

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#1363]
The wiki has information on what we currently call ORT's (Operational Requirements Tests), previously called unit tests at https://github.com/ufs-community/ufs-weather-model/wiki/Running-unit-tests-using-utest .

If there's anything new about ORT's that the component devs need to know, it needs to be updated on that wiki. With all of the EPIC work and their current or upcoming methodologies, if there are any changes that needs to be updated/added it should be done as well.

A section for what ORT's need to be run for which tests should also be added. i.e. coupled, global, regional. Not all ORT's work for all types of tests (yet i think) and this needs to be documented.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I think the UWM user guide is where the most up-to-date information is kept. Perhaps we need to point to the UG on the [wiki](https://ufs-weather-model.readthedocs.io/en/latest/BuildingAndRunning.html#using-the-operational-requirement-test-script).

**Comment by BrianCurtis-NOAA** [comment]
> I think the UWM user guide is where the most up-to-date information is kept. Perhaps we need to point to the UG on the [wiki](https://ufs-weather-model.readthedocs.io/en/latest/BuildingAndRunning.html#using-the-operational-requirement-test-script).

Maybe instead of text on the wiki, we could provide a small wiki with links to the appropriate readthedocs section. That way we maintain the readthedocs and we won't need too many changes to the wiki itself.

Maybe we change this issue to address this change in readthedocs and another issue to address not maintaining two pieces of documentation?

**Comment by DeniseWorthen** [comment]
The UFS documentation is being re-worked right now by a member of the EPIC team. Having to maintain two locations for documentation inevitably leads to conflicting or non-current information. The first step is Gillian's PR #1354

**Comment by BrianCurtis-NOAA** [comment]
Agreed.

**Comment by BrianCurtis-NOAA** [comment]
In PR #1718 I have updated the scripts to skip cases that are not supported for the regression test being tested. It no longer fails and exits.

Ideally ORT should run on all tests, and that would be a good next step for ORT. So until then, unsupported tests are now skipped, so until ORT fully supports are cases I think this issue can be closed with #1718.
