### ISSUE TITLE
Regional FV3 with 3km (LAM configuration) is not reproducing results in restarted runs.

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [ufs-community/ufs-weather-model#1365]
## Description
Bitwise reproducibility is not working for restarted runs in regional case with LAM configuration. 

### To Reproduce:
All machines/compilers.
Run model for 24hrs. Write restart files every 3 hrs.
Run restart from 12hr restart file, until 24hrs.
Compare output files. They should be identical.

## Output

**Screenshots**

**output logs**

```

```

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA what is the status on this issue? We need the restart reproducibility for RRFSv1 implementation, please let me know if we need help from other groups. Thanks

**Comment by DeniseWorthen** [comment]
@RatkoVasic-NOAA Is this still an issue or can we close this?

**Comment by RatkoVasic-NOAA** [comment]
Yes, it's fixed. we can close the issue.
