### ISSUE TITLE
Update upp lib to 8.2.0 for GFS V16.3 Implementation

### ISSUE THREAD

**Issue by WenMeng-NOAA** [ufs-community/ufs-weather-model#1368]
## Description
To support GFS V16.3 implementation, upp lib upgrade is needed.

## Solution
Update upp to 8.2.0 for WCOSS2, Hera and Orion.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by junwang-noaa** [comment]
The code was merged to GFSv16 production branch.
