### ISSUE TITLE
crashes in testing develop branch with RRFS cases

### ISSUE THREAD

**Issue by hu5970** [ufs-community/ufs-weather-model#1370]
## Description
We are working on building RRFS cases (NA 3km grid and CONUS 3km grid) for testing the ufs-community/ufs-weather-model.  Right now, the RRFS ufs-weather-model is based on ufs-community/ufs-weather-model hash 5c2d1a9 (Tue May 17 12:28:01 2022)

We would like to run the head of the develop branch from the community/ufs-weather-model with RRFS cases but the current head (1f001a1)  crashed.  The further test shows that the hash 4376018 (Mon Jun 6 10:13:07 2022) is good but hash bfecf91b7 (Thu Jun 9 10:17:37 2022) crashes.

### To Reproduce:

Prepare code:
1)  git clone https://github.com/ufs-community/ufs-weather-model.gitcdufs-weather-model
2) git checkout bfecf91b70
3) git submodule update --init --recursive

Compile:
1) module purge
2) module use modulefiles
3) source modulefiles/ufs_hera.intel
4) ./build.sh

## Test

To check and run case on Hera:
CONUS 3km case location: /scratch1/BMC/wrfruc/mhu/test/fv3lam

The scripts to run case:   run_fv3lam.sh

**output logs**

The log for crashed case with hash bfecf91b7: 
/scratch1/BMC/wrfruc/mhu/test/fv3lam/2021053103_com_bfecf/slurm-34755604.out

The crash information shows as following:
fcst_advertise, cpl_grid_id=           1
application called MPI_Abort(comm=0x84000002, 1) - process 342
application called MPI_Abort(comm=0x84000002, 1) - process 78

The log for successful case with hash 4376018:
/scratch1/BMC/wrfruc/mhu/test/fv3lam/2021053103_com_43760/slurm-34763081.out

**Comment by BenjaminBlake-NOAA** [comment]
@hu5970  When running your tests, did you update your fd_nems.yaml file to the latest version?  
I looked in this directory on Hera: /scratch1/BMC/wrfruc/mhu/test/fv3lam/2021053103_com_bfecf 

Inside the PET.ESMF log files, I see messages like this one: "Invalid argument - mean_sensi_heat_flx_atm_into_ocn is not a StandardName in the NUOPC_FieldDictionary!"  I got similar messages about invalid arguments when updating to newer model code, and using the latest fd_nems.yaml file resolved my errors.  It should be in the ufs-weather-model/tests/parm directory.

**Comment by hu5970** [comment]
@BenjaminBlake-NOAA Thanks for pointing this out. I did not update fd_nems.yaml file in my case. After using the fd_nems.yaml from ufs-weather-model/tests/parm. The hash bfecf91b7 now can run through. I will test more recent hashes soon. Thanks.

**Comment by DeniseWorthen** [comment]
@hu5970 Please let us know if this issue is resolved by updating the fd_nems.yaml file. If so, please close the issue. Thanks.

**Comment by hu5970** [comment]
Yes, this issue was resolved by updating the fd_nems.yaml file. Thanks, Ming
