### ISSUE TITLE
Ongoing development for AQM component

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#1392]
This Epic relates to AQM development and testing in UWM

**Comment by DeniseWorthen** [comment]
Chunxi reports fixes are need to remove assumption of cice coupling when running aqm & chemistry coupled. Assign a value of fluxes over the land. 

Agreement between EPA and EMC was to not fork the EPA code. UMW will use EPA authoritative repo. 

Development of (app=AQM; the model is called CMAQ). Development of AQM app in UWM is not currently active. Need to get our code in UFS up-to-date with CMAQ latest. 

Implementation upcoming (early 2023)for air-quality component so couldn't update to latest.

**Comment by DeniseWorthen** [comment]
#1405 is required for code freeze (Oct 1). Fix for Issue #1404 will also be required. Both need to go to top of PR list when ready.

We need to know status of app w/ all oRTs. Restart might not be required if not currently used in opn (current v6), then restart will be required.

**Comment by BrianCurtis-NOAA** [comment]
Restarts are required for V7, so will need to pass them as well.

**Comment by BrianCurtis-NOAA** [comment]
Code freeze was moved to 12/1 from 10/1. Work towards that will ramp up in the coming days and weeks.

**Comment by DeniseWorthen** [comment]
Issues and PRs are being moved to official emc repo. Brian is AQM code manager. Decisions will be made about which of issues and Prs are required prior to science code freeze.

**Comment by junwang-noaa** [comment]
AQM is still working on code updates to finalize AQM v7 configuration.

**Comment by junwang-noaa** [comment]
The AQM development is now managed through github projects.
