### ISSUE TITLE
need to rename the organization that stochastic_physics sits under

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-weather-model#1396]
## Description
The stochastic physics repo sits under the noaa-psd organization, but we "psd" no longer exists, and we want to update the organization name to be NOAA-PSL.  
 When we rename the organization, there will need to be a PR issued to update the submodule pointer, but I am concerned that this will then break old versions, and tags of the ufs-weather-model.  
  Does anyone know if this will be an issued?    
@rsdunlapiv @dustinswales @bensonr @junwang-noaa @jkbk2004

**Comment by jswhit2** [comment]
typo above: will be changing the organization name to NOAA-PSL

The docs [here](https://docs.github.com/es/enterprise-cloud@latest/organizations/managing-organization-settings/renaming-an-organization) suggest that the old URLs that link to projects under the old org name should still work (until someone else claims the old name).  The top-level URL to the old organization (https://github.com/NOAA-PSD) won't work anymore though.

**Comment by pjpegion** [comment]
I edited my post to fix the typo.

**Comment by JessicaMeixner-NOAA** [comment]
@pjpegion The MOM6 repo moved from being under noaa-gfdl to mom-ocean, and that group might have some insight on the process and impacts even though in ufs-weather-model we pointed to a noaa-emc fork of MOM6.

**Comment by jiandewang** [comment]
@pjpegion Marshall Ward made MOM6 repo location switch and it had zero impact for downstream fork. I think it took him a while to figure out that seamless method. You may seek suggestions from him.

**Comment by pjpegion** [comment]
@jiandewang it looks like NOAA-GFDL still exists and is active, which would be different than in my case, but I will ask him.
