### ISSUE TITLE
Additional Updates to WM Documentation

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-weather-model#1397]
## Description
- Add a Configuration Parameters chapter that will include build configuration values (e.g., valid -DAPP and -DCCPP_SUITES values) and eventually other configuration values as needed.
- Remove duplication of directory diagrams in Code Overview chapter 
- Add/update CMAKE_FLAGS info in Build/Run chapter
- Expand/clarify RT info

## Solution
Update the documentation to include these changes.

## Alternatives
N/A

## Related to
N/A

**Comment by zach1221** [comment]
This issue was resolved with the merging of the UFS-WM documentation PR #1398
