### ISSUE TITLE
Corrupt albedo in restart files

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [ufs-community/ufs-weather-model#1419]
## Description
The land albedo records (albdirvis_lnd, albdirnir_lnd, albdifvis_lnd and albdifnir_lnd) in the restart files are corrupt.
Tiles 2 and 4 look ok. But tiles 1,3,5,6 are not ok.  For examples, see these files on Hera:
`/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220912/INTEL/cpld_bmark_p8/RESTART`

## Output

Here is a tile 1 example. Note parts of Africa look ok, but S. Amer is missing.

![ncview albdifnir_lnd](https://user-images.githubusercontent.com/52789452/190227676-d16edaa3-bacd-4e4d-8a14-90711b53e197.gif)

**Comment by LydiaStefanova-NOAA** [comment]
@GeorgeGayno-NOAA 

Could this be due to the lack of sunlight in these places (so albedo is perhaps considered meaningless at these times)?  If your restarts are for 06:00 GMT in September, the areas with non-valid land albedo are the areas of no sunlight at that time - see these two plots from (coupled) model output for 16 Sep 2012, 6z (top) and 18z (bottom): 

![6z](https://user-images.githubusercontent.com/48454097/190236803-62a01261-d145-4793-a1b9-4be1bef14a0f.jpg)


![18z](https://user-images.githubusercontent.com/48454097/190237004-147172a9-e0be-483c-9d83-b525994dbf2a.jpg)

**Comment by GeorgeGayno-NOAA** [comment]
That makes sense. Is there any easy way to interpolate the tiles to a regular lat/lon grid? That would verify your hunch.

**Comment by LydiaStefanova-NOAA** [comment]
Here is what albdirvis_lnd from your files looks like when plotted to lat/lon, so seems consistent with this hypothesis:  

<img width="739" alt="image" src="https://user-images.githubusercontent.com/48454097/190248092-6c8dc2c5-c205-4c9f-8665-200c35a66764.png">

**Comment by junwang-noaa** [comment]
@LydiaStefanova-NOAA @GeorgeGayno-NOAA It looks to me the atmosphere alone test (control_p8) does not have this feature, the ALBDIRVIS_LND is continuous in the restart files on all the tiles.

**Comment by GeorgeGayno-NOAA** [comment]
@junwang-noaa I am unclear what the different albedo records contain in coupled mode. I am not sure which one(s) global_cycle needs to update (would Moorthi know?)

alvsf/alvwf/alnsf/alnwf - water albedo at points with some open water?
albdirvis_ice/albdifvis_ice/albdirnir_ice/albdifnir_ice - ice albedo at points with some ice?
albdirvis_lnd/albdifvis_lnd/albdirnir_lnd/albdifnir_lnd - land albedo at points with some land?
alboldxy - is this an albedo?

Only the "lnd" fields are not defined at night.

**Comment by junwang-noaa** [comment]
@yangfanglin @SMoorthi-emc would you please help answer George's question? Thanks

**Comment by barlage** [comment]
These plots from Lydia are surprising to me. This is probably something we need to fix. In other applications of noahmp what we have done is just maintain the last calculated albedo (right before sunset) constant through the night, so that when the sun rises there is a valid albedo value; it seems here there is a missing value getting set.

**Comment by GeorgeGayno-NOAA** [comment]
> @LydiaStefanova-NOAA @GeorgeGayno-NOAA It looks to me the atmosphere alone test (control_p8) does not have this feature, the ALBDIRVIS_LND is continuous in the restart files on all the tiles.

@junwang-noaa I just checked your latest baseline control_p8 files (develop-20220919/INTEL/control_p8). You are right, the "lnd" albedos are continuous.

**Comment by HelinWei-NOAA** [comment]
@GeorgeGayno-NOAA develop-20220919 doesn't exist any more. Can you find another case to show me the problem? From my own RTs, I didn't find any problem. The calculated albedo by Noah MP strongly depends on the soil texture. It will show titled pattern (not continuous).

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA develop-20220919 doesn't exist any more. Can you find another case to show me the problem? From my own RTs, I didn't find any problem. The calculated albedo by Noah MP strongly depends on the soil texture. It will show titled pattern (not continuous).

See the files here: /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20221220/INTEL/cpld_bmark_p8/RESTART

**Comment by HelinWei-NOAA** [comment]
@GeorgeGayno-NOAA Thanks. The same pattern can also be found on those uncoupled p8 runs
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20221220/INTEL/control_p8/RESTART

**Comment by HelinWei-NOAA** [comment]
It looks like cpld_control_p8 has some different settings compared to cpld_bmark_p8 and control_p8. The albedo in the RESART files from cpld_control_p8 seems fine but not for the other two.

**Comment by HelinWei-NOAA** [comment]
@GeorgeGayno-NOAA Now I fully understand the issue you brought up. RT of cpld_bmark_p8 only ran up to 6 hours. During this period the sun never went up over the south america, so the albedo didn't get any value from NoahMP and the initial value of 0.2 is assigned over there. For RT of control_p8, it ran up to 1 day, so any land point has got a chance to get a valid albedo from NoahMP. FYI @barlage @junwang-noaa

**Comment by HelinWei-NOAA** [comment]
@barlage The results are the same after those four albedos in NoahMP are changed to inout from out.

**Comment by barlage** [comment]
@HelinWei-NOAA do you still see any strange "random" values for the component albedos from the land?

**Comment by HelinWei-NOAA** [comment]
@barlage I think my previous statement on "random" values was wrong because I interpreted the value of a single point improperly through ncview.

**Comment by barlage** [comment]
@GeorgeGayno-NOAA Can we close this issue? From tests by @HelinWei-NOAA, it seems that everything is working correctly. With noahmp, the albedo is initialized at a default value of 0.2, then after the land model is called the first time with solar radiation >0 a new land albedo is calculated and used at the following time step in the radiation scheme. After 24 hours, any land point that has had any solar radiation will have a non-0.2 albedo in the restart. At the end of the model day, the albedo is carried over to the following sunrise.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Can we close this issue? From tests by @HelinWei-NOAA, it seems that everything is working correctly. With noahmp, the albedo is initialized at a default value of 0.2, then after the land model is called the first time with solar radiation >0 a new land albedo is calculated and used at the following time step in the radiation scheme. After 24 hours, any land point that has had any solar radiation will have a non-0.2 albedo in the restart. At the end of the model day, the albedo is carried over to the following sunrise.

Yes, you may close this.

**Comment by barlage** [comment]
OK, I will close this. Since you opened it, I didn't want to overstep.

**Comment by barlage** [comment]
@GeorgeGayno-NOAA I think someone more powerful than I will have to close it.
