### ISSUE TITLE
write component fails when cubed_sphere_grid is used with post

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#1428]
## Description
The write component fails with segmentation fault for `control_p8` when `output_grid` is changed from `gaussian_grid` to `cubed_sphere_grid`. It seems that it is working if `write_dopost` is set to `.false.` in `model_configure`.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. checkout UFS weather model latest develop
2. edit `tests/control_p8` and change `OUTPUT_GRID` option from 'gaussian_grid' to 'cubed_sphere_grid'
3. then, check the error log

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
I collected this trace with DDT.

```
Process stopped in post_fv3::post_run_fv3 (post_fv3.F90:112) with signal SIGSEGV (Segmentation fault).
Reason/Origin: address not mapped to object (attempt to access invalid address)
```

**Comment by junwang-noaa** [comment]
@uturuncoglu Post processing does not have the capability to ingest native cubed sphere grid yet, so you can't run UPP with native grid output even offline. For the same reason, if you are using native cubed sphere grid, you need to turn inline post off.

**Comment by uturuncoglu** [comment]
@junwang-noaa okay. I did not know it. I think post is used by default now with `control_p8`. I have just synced my branch with the develop and had this issue. The previous version of code was based on UFS Jul 29 commit. Anyway, it might be useful if model rise a meaningful message or error in case of using `cubed_sphere_grid` with post.

**Comment by junwang-noaa** [comment]
@uturuncoglu This is fixed in fv3atm PR#622

**Comment by uturuncoglu** [comment]
@junwang-noaa Thanks for the update.

**Comment by junwang-noaa** [comment]
The PR was committed, close issue.
