### ISSUE TITLE
Update global fv3 regression test 

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#143]
## Description
After GFSv16 code changes are merged to ufs-weather-model develop branch, the ufs-weather-model global fv3 regression test will be cleaned, merged and updated. The old GFSv14 based tests will be removed,  GFSv16 test with 127 levels will be set up as control to facilitate future code development. 

## Solution
1. New initial conditions will be generated from GFSv16 analysis files for C96, C192 and C384. 
2. FV3 global control tests will be C96L127 GFSv16 test. The reproducibility tests will be updated based on the new control tests. Different resolution test C192 and C384 will be added to support GEFS and coupled model.
3.  All the RT test with GFS.v14 configuration (suite files FV3_GFS_2017*) will be removed. Feature tests using these configurations will be gradually move to GFS.v16 configuration (suite file FV3_GFS_v16*)

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. PR will be submitted when it is ready

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa Is this still relevant with the latest develop branch?

**Comment by junwang-noaa** [comment]
Yes.

**Comment by BrianCurtis-NOAA** [comment]
What do you think of copy/pasting the templates into these older issues to make sure they have everything?

**Comment by junwang-noaa** [comment]
Sure.
