### ISSUE TITLE
rt.sh $TASKS and $NODES are wrong, breaking rocoto workflow

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#1430]
## Description

The `$TASKS` and `$NODES` calculations in rt.sh are wrong; the new ones are in run_tests.sh. They should be moved to rt_utils.sh so they can be called in both locations.

### To Reproduce:
Run the cpld_bmark_esmfthreads_p8 test on hera using Rocoto

**Comment by zach1221** [comment]
Hi, @SamuelTrahanNOAA , wanted to follow up on this issue and check if it's still relevant? I doesn't look like cpld_bmark_esmfthreads_p8 is a case that exists anymore in rt.conf. However I'm able to successfully run cpld_2threads_p8  &  cpld_bmark_p8 cases on Hera using Rocoto.

**Comment by SamuelTrahanNOAA** [comment]
This was fixed long ago.
