### ISSUE TITLE
g2tmpl-1.10.2: backward compatibility issue on hafs cases

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#1441]
new version of g2tmpl-1.10.2 was installed on each RDHPCs.  The regression tests of the ufs-wm (hafs_regional_atm, hafs_global_multiple_4nests_atm, hafs_regional_specified_moving_1nest_atm) show the baselines are different between g2tmpl-1.10.0 and g2tmpl-1.10.2. Validation is needed from UPP and HAFS teams.

**Comment by BinLiu-NOAA** [comment]
@jkbk2004 Thanks for creating this issue! @LinZhu-NOAA will help to communicate this with @WenMeng-NOAA to check/confirm if the changing results are expected. Thanks!

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 Please provide me the locations of two regression tests, I can take a look.

**Comment by jkbk2004** [comment]
@WenMeng-NOAA can you take a look at RegressionTests_orion.intel.log: /work/noaa/epic-ps/jongkim/UFS-RT-tests/pr-dev/tests? I set some regression tests with g2tmpl-1.10.2.

**Comment by jkbk2004** [comment]
> @WenMeng-NOAA can you take a look at RegressionTests_orion.intel.log: /work/noaa/epic-ps/jongkim/UFS-RT-tests/pr-dev/tests? I set some regression tests with g2tmpl-1.10.2.

It's on Orion.

**Comment by jkbk2004** [comment]
g2tmpl update was merged with #1544
