### ISSUE TITLE
Update module dependencies to use spack-stack instead of hpc-stack

### ISSUE THREAD

**Issue by mark-a-potts** [ufs-community/ufs-weather-model#1448]
## Description
The hpc-stack approach to building the software stack required by the UFS-WM is being deprecated and the WM needs to be tested and validated with the new spack-based software stack.

## Solution
EPIC will install spack-based modules for all the packages required by the WM under their role accounts and begin the process of validating their use with the WM via regression test comparisons.

**Comment by benjamin-cash** [comment]
@mark-a-potts - This came up in another discussion that I think has gotten buried, so I wanted to include it here. To use spack-stack the version of [CMakeModules](https://github.com/NOAA-EMC/CMakeModules) that ufs-weather-model points to will need to be updated. Right now it is pointing to [cedeb2c](https://github.com/NOAA-EMC/CMakeModules/commit/cedeb2c64e55d3445ac4e4847ea7c4fa3220c3dd), which is a year out of date. The S2S application at least will fail to build using that version of CMakeModules.

**Comment by GeorgeVandenberghe-NOAA** [comment]
There has been a lot of progress on this problem but it hasn't been reported here.

**Comment by zach1221** [comment]
@mark-a-potts I want to let you know I've successfully tested your spack installations on the three NOAA Cloud platforms so far.

**Comment by zach1221** [comment]
@mark-a-potts looks like @ulmononian has created an additional issue for testing the new spack-stack UE on the tier 1 HPC resources. Are you Ok with me closing this as a duplicate and tracking the spack environmental testing from #1651 instead? 1651 can probably be closed when PR #1707 is merged.

**Comment by mark-a-potts** [comment]
Yes, that is fine with me.
