### ISSUE TITLE
New Winter Weather Diagnostics and Precip Ice Density

### ISSUE THREAD

**Issue by ericaligo-NOAA** [ufs-community/ufs-weather-model#1449]
## Description
The accumulated snow, graupel and freezing rain will be added to  history files. A new precipitation ice density will be used in NOAH and NOAH MP LSMs. This new precipitation ice density is currently used in the RUC LSM and the computation will be moved from the RUC LSM to GFS_MP_generic.F90. Users will have the ability to choose between the original formulations in NOAH and NOAH LSM and the new precipitation ice density through a namelist parameter.  Additionally, a bug fix to the hourly max fields will be applied. See below for related issue.

A case study illustrating the impacts of the new precipitation ice density and the new accumulated winter weather diagnostics is shown in the attachment.

## Related to
Hourly max bug fix: (https://github.com/NOAA-EMC/fv3atm/issues/437)
[New Precipitation Ice Density_Accumulated Surface Winter Diags Prelim Results.pdf](https://github.com/ufs-community/ufs-weather-model/files/9717914/New.Precipitation.Ice.Density_Accumulated.Surface.Winter.Diags.Prelim.Results.pdf)

**Comment by junwang-noaa** [comment]
@ericaligo-NOAA I think the code changes were committed in ufs-weather-model PR#1529. Can we close this issue? Thanks.

**Comment by ericaligo-NOAA** [comment]
Yes. Thanks!
