### ISSUE TITLE
production/GFS.v16 does not build on Jet and Hera

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [ufs-community/ufs-weather-model#145]
The production/GFS.v16 branch no longer builds on Jet and Hera because of system changes. The module settings for Jet and Hera need updating to reflect changes related to /contrib modules on those platforms. This impacts other client projects such as global-workflow, that won't function until this is fixed.

**Comment by edwardhartnett** [comment]
Is this related to the new versions of netCDF?

**Comment by christopherwharrop-noaa** [comment]
@edwardhartnett: No. I has nothing to do with that. 

It's caused by system changes in how `/contrib` modules are organized on Hera and Jet. The module commands used in the `production/GFS.v16` branch of this repository don't work anymore and need to be modified. See #146  which closes this issue.

**Comment by junwang-noaa** [comment]
No, it's not.
