### ISSUE TITLE
standalone tests do not launch w/ correct number of PEs

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#1466]
## Description

The calculation of ``tasks`` seems incorrect for the standalone RTs. 

### To Reproduce:
On Hera.intel, run the control_p8 RT. The job should run on 150 tasks:
```
nems.configure:
logKindFlag:          ESMF_LOGKIND_MULTI
 EARTH_component_list: ATM
 ATM_model:            fv3
 ATM_petlist_bounds:   0 149
 runSeq::
   ATM
 ::
```

The job launches on 160 tasks:

``srun --label -n 160 ./fv3.exe``

The PET logs 000-149 contain valid information. PET logs 150-159 show report only the reading of the config information.
```
(snip)
20221017 122740.426 INFO             PET150 Driver is in ModifyCplLists()
20221017 122740.426 INFO             PET150  Found            0  Connectors. Modifying CplList Attribute....
20221017 122740.431 INFO             PET150 Finalizing ESMF
```

**Comment by uturuncoglu** [comment]
@DeniseWorthen I just wonder if you check the number of io tasks? It could increase the number PR used in the test?

**Comment by DeniseWorthen** [comment]
The ``control_p8`` runs with 144 for FV3 and 6 wrt tasks, for a total of 150 (0-149).

**Comment by uturuncoglu** [comment]
Okay. That makes sense. There was a recent mods in the UFS side that moves that calculation from rt.sh to another script (I think?). Maybe it is related with it.

**Comment by DeniseWorthen** [comment]
Maybe---I remember something about that. I first noticed it when I built an atm-wav-cmeps test more than a month ago but I thought I had set something incorrectly (I was launching w/ 200 even though I only needed 180).

**Comment by DusanJovic-NOAA** [comment]
See this PR comment https://github.com/ufs-community/ufs-weather-model/pull/1305#discussion_r912130905

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Thanks. I see now that this is expected, so I will close the issue.
