### ISSUE TITLE
Rename nradar_reset

### ISSUE THREAD

**Issue by ericaligo-NOAA** [ufs-community/ufs-weather-model#1499]
The namelist parameter, nsradar_reset, in the gfs_phys_nml section should be renamed. The current name is misleading as it implies that something will be reset. No resetting is done.  The parameter nsradar_reset is the time in seconds for when the reflectivity is computed assuming water coated ice (full reflectivity). For hourly output and nsradar_reset = 3600s, the full reflectivity is computed only at the output time. For all other time steps the reflectivity is computed without using the assumption of water coated ice. Due to the large increase in resources required to run the full reflectivity at every time step, it was decided that the full reflectivity be computed only on output times. 

When the conditions to compute the full reflectivity are met, the logical melti in module_mp_thompson.F90  is set to true and the full reflectivity is computed. The proposal is to rename nsradar_reset to nsfullradar_diag.

## Related to
This change will be part of this issue: https://github.com/NOAA-EMC/UPP/issues/568

**Comment by ericaligo-NOAA** [comment]
@gthompsnWRF @RuiyuSun

**Comment by junwang-noaa** [comment]
@ericaligo-NOAA The code is merged, can you close the issue? Thanks
