### ISSUE TITLE
enable GOCART on wcoss2

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1506]
## Description
GDIT installed ESMF/MAPL on wcoss2, the GOCART tests are enabled.

## Solution
the ESMF/MAPL libraries need to be installed on wcoss2.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>

**Comment by DeniseWorthen** [comment]
@junwang-noaa I think we can close this?

**Comment by junwang-noaa** [comment]
The issue is resolved.
