### ISSUE TITLE
Add the CLM Lake Model and generate lake data on a regional grid.

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#1510]
## Description
The operational upgrade plan for RRFS is to run the CLM Lake Model. Hence, we must implement that in UFS.

## Solution
Add it to CCPP.

## Alternatives
Switch back to WRF? Get the Flake model to work, and produce good results?

## Related to
No related issues.

**Comment by junwang-noaa** [comment]
@MatthewPyle-NOAA FYI.

**Comment by MatthewPyle-NOAA** [comment]
@junwang-noaa I'm aware, but just asked Mike Barlage about the EMC work on it.

**Comment by SamuelTrahanNOAA** [comment]
The restart and threading issues are fixed, and these PRs are ready for review.

**Comment by SamuelTrahanNOAA** [comment]
Never mind. Restart doesn't work anymore. I'll have to walk back my list of changes until I find out why.

**Comment by SamuelTrahanNOAA** [comment]
False alarm: restart *does* still work. I had temporarily broken it while cleaning up the new regression tests.
