### ISSUE TITLE
Allow shared parallelio

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [ufs-community/ufs-weather-model#1512]
## Description
CMakeLists.txt hardcodes parallelio as a STATIC library. For flexibility and consistency with the way other libraries are used which allows either static or shared, can this be changed to allow for the shared version of PIO?

## Solution
Sufficiently recent versions of CMakeModules support shared PIO, at which point the PIO "STATIC" keyword in CMakeLists.txt can be removed.

**Comment by junwang-noaa** [comment]
George V. also had problem with the parallelio when building UFS on gaea C5. @DusanJovic-NOAA would you please take a look at this issue? Thanks

**Comment by climbfuji** [comment]
I would very much like the `STATIC` requirement to be removed from `CMakeLists.txt`. If the library has been built as static library, the ufs build should pick it up, i.e. no impact on the existing system.

**Comment by DusanJovic-NOAA** [comment]
I agree . Remove STATIC.

**Comment by junwang-noaa** [comment]
@AlexanderRichert-NOAA can you remove "STATIC" for parallelio in CMakeLists.txt and test it in ufs wm? We prefer to use "STATIC" for operational code, but let's see if this resolve the issue.

**Comment by AlexanderRichert-NOAA** [comment]
Yes-- it can be removed with a sufficiently recent copy of the CMakeModules submodule, which has a version of FindPIO.cmake that supports the shared library (and without needing to specify shared vs. static in CMakeLists.txt).

**Comment by GeorgeVandenberghe-NOAA** [comment]
Has this been done so I can build with shared PIO?

**Comment by AlexanderRichert-NOAA** [comment]
@GeorgeVandenberghe-NOAA Not yet. Once the CMakeModules submodule gets updated, then this change will be possible. If you want to make the change in your own installation, then just replace CMakeModules with the latest version, then remove the "STATIC" component from PIO in CMakeLists.txt.
