### ISSUE TITLE
Add unlimited to time dimension in gaussian_grid netcdf output

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/ufs-weather-model#1521]
## Description
gaussian_grid netcdf output files include "time" as a dimension but it is not defined as an unlimited dimension. @DeniseWorthen reports that this is not true when tiled netcdf output is used. It appears that this option was disabled for parallel netcdf output due to performance issues on Hera. Lack of a record dimension causes a number of follow on issues, particularly with the use of netcdf operators. 

## Solution
Allow for users to enable unlimited definition for netcdf output.  

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by DusanJovic-NOAA** [comment]
Do 'netcdf operators' require that each netcdf file has a record dimension?

**Comment by DeniseWorthen** [comment]
To concatenate a set of netcdf files into a timeseries using NCO, the time dimension needs to be a "record" dimension ie, be "unlimited". If the time dimension is not unlimited, you need to first pre-process the netcdf file using ``ncks --mk_rec_dim``.
