### ISSUE TITLE
Regional_control fails in Jenkins-ci pipeline

### ISSUE THREAD

**Issue by zach1221** [ufs-community/ufs-weather-model#1532]
## Description
When Jenkins-ci pipeline runs the ORT script using regional_control case with std, thr, and dcp tests it fails with generic "error code 1" message.

Build and compiles successfully, however failure occurs on the run_test.sh line.

### To Reproduce:
Error is seen on jenkins server utilizing Amazon EC2 instance.
1. Create PR from ufs-community/ufs-weather-model/develop branch
2. Add regional_control to jenkinsfile (as it has been removed)
3. Add jenkins-ci label to PR
4. Log into jenkins and run jenkins-ci pipeline (https://jenkins-epic.woc.noaa.gov/)
    

## Additional context
The issue may be caused by fms update to 2022.04, recent regional_control input data file change or resource issue in container and/or EC2 instance. 

## Output

<img width="451" alt="Jenkins-ci Error" src="https://user-images.githubusercontent.com/99902696/207169903-e5c7e9ff-2342-4cdf-9816-e92519f3bab3.PNG">

```
paste the code here (if a short section of log)
```

**Comment by jkbk2004** [comment]
fix was merged with #1599
