### ISSUE TITLE
Switch to use unified ugwp in HAFS regression tests

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#1550]
## Description
Switch to use the unified ugwp (instead of cires_ugwp) scheme in HAFS regression tests.

## Solution
Update the related HAFS regression tests to use the unified ugwp scheme.

## Alternatives
N/A.

## Related to
- ufs-community/ufs-weather-model/pull/1544

**Comment by DeniseWorthen** [comment]
@BinLiu-NOAA Are there any remaining issues with this or has it all been committed? Can you close the issue if it is resolved? Thanks.

**Comment by BinLiu-NOAA** [comment]
Thanks for the reminder, @DeniseWorthen! Closing it now.
