### ISSUE TITLE
Update to point latest WW3 dev/ufs-weather-model branch with HAFSv1 needed updates

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#1551]
## Description
Update to point latest WW3 dev/ufs-weather-model branch with HAFSv1 needed updates.

## Solution
@JessicaMeixner-NOAA is working on updating the corresponding WW3 branch, and we will update the submodule WW3 accordingly.

## Alternatives
N/A.

## Related to
- waiting on NOAA-EMC/WW3/pull/<>

**Comment by junwang-noaa** [comment]
@BinLiu-NOAA The wave branch was updated, can you close the issue? Thanks

**Comment by BinLiu-NOAA** [comment]
@junwang-noaa and @JessicaMeixner-NOAA, HAFSv1 is currently using the WW3's [production/hafs.v1 branch](https://github.com/NOAA-EMC/WW3/tree/production/hafs.v1). Once we make sure changes in this branch has gone back to WW3 dev/ufs-weather-model branch (updated for ufs-weather-model as well), we can close this issue. Thanks!
