### ISSUE TITLE
Running single test from non-default .conf file

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#1557]
## Description
Running single test from non-default .conf file does not work as expected, it always reads rt.conf instead of config file specified by -l flag. 

### To Reproduce:
Run single test from non-default configure file, for example:
```
./rt.sh -n regional_rrfs_a -l rt_weekly.conf
```

**Comment by junwang-noaa** [comment]
Code changes were committed. Close the issue.
