### ISSUE TITLE
"-xSSE4.2" FLAGS in connection with HYCOM build

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#1565]
1. Needs to confirm the flag fully go thru across hera/orion/cheyenne/jet: cmake/configure_gaea.intel.cmake
2. Compare the hafs regression test results with the flag on and off

**Comment by zach1221** [comment]
Hera, Cheyenne, Orion, and Jet all passed with and without the -xSSE4.2 flags. Ran the entire Hafs segment within the UFS-WM rt.conf suite. On Gaea the hafs cases passed with the flags, while some of the hafs cases with "ocn" failed without the flag on Gaea only. @jkbk2004 
Run times below:
cheyenne.intel with xSSE4.2 flag: 46min
cheyenne.intel without xSSE4.2 flag: 47min
hera.intel without xSSE4.2 flag: 32min
hera.intel with xSSE4.2 flag: 40min
orion.intel without xSSE4.2 flag: 34min
orion.intel with xSSE4.2 flag: 32min
jet.intel without xSSE4.2 flag: 01h:15m
jet.intel with xSSE4.2 flag: 48m

**Comment by zach1221** [comment]
[jet.intel with -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537874/jet.intel.with.-xSSE4.2.txt)
[orion.intel without -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537876/orion.intel.without.-xSSE4.2.txt)
[jet.intel with without -xSS
[hera.intel with -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537884/hera.intel.with.-xSSE4.2.txt)
E4.
[orion.intel with -xSSE4
[cheyenne.intel with -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537885/cheyenne.intel.with.-xSSE4.2.txt)
.2.txt](h
[cheyenne.intel without -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537882/cheyenne.intel.without.-xSSE4.2.txt)
ttps://github.com/ufs-community/ufs-weather-model/files/11537881/orion.intel.with.-xSSE4.2.txt)
2.
[hera.intel without -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537879/hera.intel.without.-xSSE4.2.txt)
txt](https://github.com/ufs-community/ufs-weather-model/files/11537878/jet.intel.with.without.-xSSE4.2.txt)

**Comment by zach1221** [comment]
[jet.intel with -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537887/jet.intel.with.-xSSE4.2.txt)

[orion.intel without -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537888/orion.intel.without.-xSSE4.2.txt)

[hera.intel without -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537891/hera.intel.without.-xSSE4.2.txt)

[orion.intel with -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537892/orion.intel.with.-xSSE4.2.txt)

[cheyenne.intel without -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537894/cheyenne.intel.without.-xSSE4.2.txt)

[hera.intel with -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537895/hera.intel.with.-xSSE4.2.txt)

[cheyenne.intel with -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537897/cheyenne.intel.with.-xSSE4.2.txt)

[jet.intel without -xSSE4.2.txt](https://github.com/ufs-community/ufs-weather-model/files/11537908/jet.intel.without.-xSSE4.2.txt)

**Comment by zach1221** [comment]
I'm going to go ahead and close this, since it doesn't look like results change depending on if the cmake flag is added to the machine's configure file versus if it is not.
