### ISSUE TITLE
Troubleshooting to compile with all CCPP suites

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#1568]
1. compile 012 in rt.conf used to perform the compile test of all ccpp suites. However, it causes random build issue across different accounts and platforms: https://github.com/ufs-community/ufs-weather-model/issues/1450
2. a fix might be with restricting the test to the suites only used in the regression test, as suggested in https://github.com/ufs-community/ufs-weather-model/issues/1450

**Comment by zach1221** [comment]
Related issues #1450 and PR #1544 are closed and merged, respectively. Closing this issue.
