### ISSUE TITLE
Test the FASTER compile option in UFS applications

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1572]
## Description
The FASTER compile option is added to UFS to speed up the HAFS runs. This compile option needs to be tested in all the UFS applications for reproducibility and run time saving. If that is confirmed, we will replace the RELEASE compile mode options with the FASTER compile options.

## Solution
Test the FASTER compile option in other applications including: ATM, S2SWA, NG-GODAS, ATML and ATMAQ

**Comment by MatthewPyle-NOAA** [comment]
Looking forward to this model speedup for RRFS.
