### ISSUE TITLE
For a "continue" run, WW3 should not start unless a restart is present

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#1590]
## Description

Currently WW3 can always start "cold", without a WW3 restart file present. This is not desirable w/in UWM since it could lead to unexpected results if a WW3 restart is expected but instead WW3 starts cold (e.g. the WW3 restart is not present for some reason). 

## Solution

In UWM, WW3 should fail if the ``runtype=continue`` and no WW3 restart file is present. This feature should be added to the mesh cap in order to not interfere w/ other use cases.

**Comment by DeniseWorthen** [comment]
Additional information has been added in Issue #1577. The conclusion there is that if we make use of the existing config variable to allow the user to set their own restart filename, then a code block which exercises an 'exists' conditional is active. That will prevent the WAV component from starting up if the restart file does not exist.

**Comment by junwang-noaa** [comment]
@DeniseWorthen Is the change included ww3 PR#1673?

**Comment by DeniseWorthen** [comment]
No, the capability is already present, we just need to turn it on by setting a configuration variable in nems.configure.
