### ISSUE TITLE
add information about setting resources for coupled configuration to the documentation

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#1607]
## Description

The UFS WM User Guide FAQ section contains only information about how to set ATM tasks (``How do I set the total number of tasks for my job?``). It should be updated to describe how to set for the coupled model and with ESMF-managed threading.

## Solution

The FAQ  should be updated to describe how to set resources for the coupled model with ESMF-managed threading.

**Comment by junwang-noaa** [comment]
The code was merged in PR#1597, the issue is closed.
