### ISSUE TITLE
Add diagnostic fields in FV3WAM history files

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1614]
## Description
FV3WAM group need to output some new variables for tidal diagnostics and daily mean u, v, t in model history files. This will be implemented through write grid component to maintain consistency with downstream jobs and workflow.

## Solution
1. add code changes to compute tide analysis. 
2. Add fields in the dycore field bundles 
3. Update the diag_table to output those fields.
4. Testing the code changes to ensure that the fields are output correctly.

**Comment by BrianCurtis-NOAA** [comment]
Working repo belongs to @SvetlanaKarol-NOAA : https://github.com/SvetlanaKarol-NOAA/ufs-weather-model/tree/fv3_wamphys

**Comment by BrianCurtis-NOAA** [comment]
Svetlana was successful. This will be closed.
