### ISSUE TITLE
Testing the new netcdf 4.9.2 compression features in ufs-weather-model

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1615]
## Description
New compression features are added in netcdf 4.9.0. UFS-weather-model will be updated to utilize the new features. 

## Solution
1) The new version of netcdf will be installed in the ufs weather model supported platforms 
2) The new compression feature with zstandard lib will be tested and used, replacing the current customized data quantization lossy compression algorithm used in FV3ATM IO.

**Comment by natalie-perlin** [comment]
@junwang-noaa - 
  There are hpc-stacks installations tested with netcdf-4.9.0 on some Tier1 platforms over the last few months, such as Cheyenne, Gaea, Hera, Jet. However, they may have different versions of other modules built for UFS WM and SRW, or would need to be rebuild with different compiler options before going through the Weather Model regression tests.  
  Is there a particular platform/ compiler that could be prepared first for full testing with the WM. Any other updates of the software versions are needed?..
  
  The netcdf-4.9.0 installations that were tested were based on hdf/1.12.1, netcdf version_c: 4.9.0, version_f: 4.6.0, version_cxx: 4.3.1 (as set up in a definition stack*.yaml file).

**Comment by junwang-noaa** [comment]
@natalie-perlin Thanks for the installation. It's good that we have the testing libraries installed on hera first, after we verify the correctness, we will ask you to install on other platforms for testing. At this time we need to have:

hdf5/1.14.0, netcdf 4.9.1 netcdf_fortran: 4.6.0. 

We also need to the libraries that depends on those libraries to be installed in order to use them in UFS, this includes: esmf 841b07 and MAPL 2.34.0. Please let me know if you have further questions. Thanks

**Comment by junwang-noaa** [comment]
HDF5 library needs to be built with plugin option and netcdf needs to be built with zstandard, as dynamic library.

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA and I discussed this task. Since Dusan has the code updates ready using ztsd compression as an option. We will create an new issue for code commit as it does not change current test results. We will leave this issue to handle library update. I will create another issue on adding RT tests with the zstd compression option turned on.
