### ISSUE TITLE
PR#1529 changes DISKNM to a directory with more restrictive permissions

### ISSUE THREAD

**Issue by JustinPerket** [ufs-community/ufs-weather-model#1620]
## Description

It seems the latest UFS PR (https://github.com/ufs-community/ufs-weather-model/pull/1529) locked me out of the new DISKNM directory on gaea

In rt.sh, It was changed from:
`DISKNM=/lustre/f2/pdata/ncep_shared/emc.nemspara/RT`
to:
`DISKNM=/lustre/f2/pdata/ncep/role.epic/RT`

https://github.com/ericaligo-NOAA/ufs-weather-model/blob/4083c199859c3fe82dec6317ed927f52d7ec13ba/tests/rt.sh#L193
### To Reproduce:

For example, running c48 coupled control RT results in this message in `log_gaea.intel/run_cpld_control_c48.log`:

```
+ cp '/lustre/f2/pdata/ncep/role.epic/RT/NEMSfv3gfs/input-data-20221101/FV3_fix/*.txt' .
 cp: cannot stat '/lustre/f2/pdata/ncep/role.epic/RT/NEMSfv3gfs/input-data-20221101/FV3_fix/*.txt': Permission denied
```

## Additional context
my groups are gfdl and gfdl_b. I see that /lustre/f2/pdata/ncep_shared/ has permissions `2775` , 
but /lustre/f2/pdata/ncep has permissions `2770`

I think there are others on Gaea not in the ncep group as well.

**Comment by jkbk2004** [comment]
@JustinPerket Thanks for reporting the issue. The location switch was introduced with jenkins and role account migration. I will double check to see if we can follow up on /lustre/f2/pdata/ncep_shared. BTW, we still maintain baseline and input files on /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs. I will keep you posted.

**Comment by JustinPerket** [comment]
Thanks Jong.

> BTW, we still maintain baseline and input files on /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs. I will keep you posted.

That's good to know. I wasn't sure.

**Comment by junwang-noaa** [comment]
Jong, the RT baseline data should go to ncep_shared.

**Comment by jkbk2004** [comment]
@junwang-noaa we have baselines at /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs. What about the idea to move up somewhere like  /lustre/f2/pdata/ncep_shared/RT/NEMSfv3gfs ? if we do that, epic jenkins account can access, I think.

**Comment by junwang-noaa** [comment]
@jkbk2004 Can role.epic write under /lustre/f2/pdata/ncep_shared? If yes, it's good to move the baseline out of emc.nemspara and to role.rpic under ncep_shared.

**Comment by jkbk2004** [comment]
Yes, role.rpic has write access under /lustre/f2/pdata/ncep_shared. We can follow up when all new epic hpc allocation hours are finalized. I will open a feature in next PI increment to check on gaea. I will close this issue.
