### ISSUE TITLE
Create HR1 Tag

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1626]
## Description

Preliminary testing of the proposed HR1 tag is at a stage where creating a tag for HR1 seems reasonable.  Can a tag be created from: https://github.com/ufs-community/ufs-weather-model/commit/c22aaadfb8dafb5687e2f3bf6416e8f11e3f9a1d

**Comment by DeniseWorthen** [comment]
A tag named [GFSv17.HR1](https://github.com/ufs-community/ufs-weather-model/tree/GFSv17.HR1) has been created.
