### ISSUE TITLE
add three parameters to input.nml for NSSL MP

### ISSUE THREAD

**Issue by Jili-Dong** [ufs-community/ufs-weather-model#1638]
To support RRFS multiphysics ensemble, three parameters in NSSL MP are being added to input.nml, including rain shape parameter (nssl_alphar), graupel-droplet collection efficiency (nssl_ehw0_in) and hail-droplet collection efficiency (nssl_ehlw0_in).

This change will not affect RT results.

Related to fv3atm PR:
https://github.com/NOAA-EMC/fv3atm/pull/632

**Comment by DeniseWorthen** [comment]
What is the status of this issue?

**Comment by JiliDong-NOAA** [comment]
> What is the status of this issue?

PR has been committed. Please close the issue.
