### ISSUE TITLE
Testing FMS 2023.01 in UFS WM

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1649]
## Description
When FMS 2023.01 release comes out and installed on UFS supported platforms, we need to test it in UFS WM before we try the new features on chunksize and compression options.

## Solution
Update FMS 2023.01 and test it in UFS WM.

**Comment by DusanJovic-NOAA** [comment]
FMS 2023.01 has been released:

https://github.com/NOAA-GFDL/FMS/releases/tag/2023.01

**Comment by DusanJovic-NOAA** [comment]
I compiled hpc-stack using fms 2023.01 on Hera and full regression test passed.

**Comment by jkbk2004** [comment]
@natalie-perlin Please, make sure the new version of FMS to be installed across RDHPCS.

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA FYI. Would you please install FMS 2023.01 on acorn? We need it to be installed on wcoss2 after testing.

**Comment by Hang-Lei-NOAA** [comment]
Okay, I will add it.

**Comment by natalie-perlin** [comment]
@jkbk2004 - will add the new fms to all the platforms today, and place a comment when done!

**Comment by jkbk2004** [comment]
> @jkbk2004 - will add the new fms to all the platforms today, and place a comment when done!

thanks!

**Comment by natalie-perlin** [comment]
FMS 2023.01 installed on Hera and Orion for the following hpc-stacks:
**Hera:**
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/intel-2022.1.2
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-10.2
**Orion:**
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2

**Comment by natalie-perlin** [comment]
FMS 2023.01 installed in standard EPIC hpc-stack locations:
**Cheyenne:**
/glade/work/epicufsrt/contrib/hpc-stack/intel2022.1
/glade/work/epicufsrt/contrib/hpc-stack/gnu10.1.0/
**Jet:**
/mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-2022.1.2
/mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274
**Gaea:**
/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0_noarch

**Comment by natalie-perlin** [comment]
fms/2023.01 has been added to the updated hpc-stacks based off netcdf/4.9.2 on Hera, Orion, Jet, Gaea:
**Jet:**
/mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-2022.1.2_ncdf492/
**Hera:**
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/intel-2022.1.2_ncdf492/
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2_ncdf492
**Orion:**
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2_ncdf492
**Gaea**
/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0_ncdf492
