### ISSUE TITLE
UFS Weather Model Regression Testing on Parallel Works Cloud Service Providers

### ISSUE THREAD

**Issue by zach1221** [ufs-community/ufs-weather-model#1650]
**Description**

The UFS Weather Model Regression Testing capability is currently structured to run on the tier 1 on premise HPCs (Orion, Hera, Jet, Gaea and Cheyenne). The Regression Testing scripts rt.sh, run_test.sh, compile.sh, and detect_machine.sh in the tests directory, as well as UFS module files in ufs-weather-model/modulefiles, and fv3 slurm job files and slurm compile files in tests/fv3_conf are not structured to run the regression test cases out of the rt.conf suite on Parallel Works cloud environments (AWS, GCP, Azure).  

**Solution**

Include Parallel Works cloud environment variables for (AWS, GCP, Azure) in the UFS WM Regression Testing related scripts and files mentioned above, so that the rt.sh script can run any case from the rt.conf suite on the these cloud environments.

**Comment by jkbk2004** [comment]
closed with #1667
