### ISSUE TITLE
Use nccmp to compare netcdf files in regression testing

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#1657]
## Description
Currently in regression testing we compare netcdf output files using unix `cmp` tool first, and if it returns error code (i.e. files are not bit-for-bit identical), we fall back to `comapre_ncfile.py` script. The issue with using this script, in addition to requiring non-standard python packages, and in addition to being slow, is that it does not compare global and field attributes, and other metadata. It just compares data values, which is not sufficient in all situations. For example we want to compare field's checksum attribute in fv3atm restart files.

## Solution
Use `nccmp` instead of `comapre_ncfile.py`. This will require that nccmp is available on all platforms we run regression test.

## Alternatives
Continue to use compare_ncfile.py

**Comment by ulmononian** [comment]
@DusanJovic-NOAA just a note: spack-stack unified-environment will contain `nccmp/1.9.0.1` out-of-the-box on all supported platforms.
