### ISSUE TITLE
clean up the run output error file

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1662]
## Description
Currently the model RT tests output two run files: err and out. The err file should only contain message when the model failed. All the run information goes to out file. However the err file now contains non-error message from physics and UPP. This needs to be fixed.
e.g., in the err file:

  0: Using non-aerosol-aware version of Thompson microphysics
  0:    calling table_ccnAct routine
  0:    creating qc collision eff tables
  0:    creating rain evap table
  0:    creating ice converting to snow table
  0:    creating rain collecting graupel table
  0:    creating freezing of water drops table
  0:   ... DONE microphysical lookup tables

144:  in readxml,bf readxml,size(post_avblflds%param)=           0
144:  xml_perl_data read Post flat file
144:  allocate paramset to :           2
144:  allocate param to :          47
...  

### To Reproduce:
Run a regression test e.g. control_p8. Check the err and out files in the run directory.

**Comment by junwang-noaa** [comment]
The code updates were committed in PR#1690, the issue is closed. A new issue will be created to clean up upp prints in ufs wm out file.

**Comment by junwang-noaa** [comment]
The prints from ccpp physics need to be moved to the out file too:

0: Using non-aerosol-aware version of Thompson microphysics
0: calling table_ccnAct routine
0: creating qc collision eff tables
0: creating rain evap table
0: creating ice converting to snow table
0: creating rain collecting graupel table
0: creating freezing of water drops table
0: ... DONE microphysical lookup tables

@Qingfu-Liu Would you please change all the:
```
write(0,*) ...
to
write(*,*) ...
```
in module_mp_thompson.F90 as the prints in those lines are not error messages. Thanks

**Comment by Qingfu-Liu** [comment]
@junwang-noaa 
OK. I will make the change

**Comment by Qingfu-Liu** [comment]
@Jun Wang - NOAA Federal ***@***.***> I just made the changes and
ran one test (suite FV3_GFS_v17_p8). I will commit the code once the test
finishes

**Comment by Qingfu-Liu** [comment]
I have committed the changes to PR#65. The only program changed is module_mp_thompson.F90 in this new commit
