### ISSUE TITLE
Sync with latest WW3 develop

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1668]
## Description
This is for a sync with the latest WW3 develop.  Recent updates include: 
* fix ust,ustdir,asf and add ussp when running with domain decomposition WW3 PR https://github.com/NOAA-EMC/WW3/pull/943
* fixes for logic statements and restart file corruption WW3 PR https://github.com/NOAA-EMC/WW3/pull/949 
* adds block explicit (and many other updates) WW3 PR https://github.com/NOAA-EMC/WW3/pull/888

## Solution
Will provide a PR to dev/ufs-waether-model branch of WW3 and a PR to ufs-weather-model --- anticipated by 3/23 

## Alternatives
None

## Related to
https://github.com/ufs-community/ufs-weather-model/issues/1556

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Since I am the one doing the actual work on the unstructured mesh for UFS, I would ask that you not merge the wise PR into the ufs-weather-model branch until I have a chance to test it using the unstructured mesh. I already have a draft pr to update the current dev/ufs-weather-model w/ the current fixes that were just merged [PR950](https://github.com/NOAA-EMC/WW3/pull/950) prior to wise.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I was actually doing this to help accelerate development for you, not to cause you problems, so I will certainly not do this at your request.  @MatthewMasarik-NOAA and I will take care of merging from WW3  develop to dev/ufs-weather-model as the WW3 code managers.  I'll back this out to just the two updates minus the WISE and wait utnil when you're ready for the WISE PR to be sync merged.  I did confirm that the WISE PR does not break the existing ufs-weather-model regression tests.  I'll wait for word from you about the unstructured grid development testing before syncing up develop again.

**Comment by DeniseWorthen** [comment]
I will let you know after I have tested the latest develop (including wise) for the unstructured case and let you know. It should only take a day. I want to make sure there are no unexpected surprises.
