### ISSUE TITLE
Remove requirement for esmf and mapl debug versions

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#1680]
## Description
The ufs-weather-model currently requires the software stack providers to create modules for esmf and mapl in debug mode that get used when the debug flag is enabled. This creates unnecessary burden on the software stack developers. For example, the first version of spack-stack (1.3.0) for the UFS will contain 4! versions of ESMF and 4! versions of MAPL:
```
esmf/8.3.0b09-debug
esmf/8.3.0b09            
esmf/8.4.1-debug   
esmf/8.4.1
mapl/2.22.0-debug-esmf-8.3.0b09-debug
mapl/2.22.0-esmf-8.3.0b09            
mapl/2.35.2-debug-esmf-8.4.1-debug   
mapl/2.35.2-esmf-8.4.1      
```
I don't think this is required. If the ESMF and MAPL developers want to debug problems with their software with ESMF or MAPL, they can (and often will) compile their own versions of ESMF and MAPL, with debug flags enabled, and use those.

Why "and often will"? Because when you are debugging a segmentation fault or something like that, you may start out with the official library, but then make changes based on a develop or bug fix version of ESMF and/or MAPL which you have to compile yourself anyway. What's more, the ESMF and MAPL developers are versed in using spack and have no problem building whatever version they need on whatever platform they need.

## Solution
Remove the requirement for ESMF and MAPL debug versions from the ufs-weather-model. And, while we are at, remove the DEBUG_LINKMPI logic as well (see #330 for more information).

The sooner this is done, the earlier the full transition to spack-stack can happen.

## Alternatives
The current status quo makes our life more complicated than it needs to be.

## Related to
#330

**Comment by climbfuji** [comment]
@arunchawla-NOAA @aerorahul @DusanJovic-NOAA @junwang-noaa FYI

**Comment by climbfuji** [comment]
I am volunteering to make this change if there is a chance for it to be accepted.

**Comment by DusanJovic-NOAA** [comment]
I support this change.

https://github.com/ufs-community/ufs-weather-model/issues/1651#issuecomment-1464013624

https://github.com/ufs-community/ufs-weather-model/issues/330#issuecomment-1132200869
