### ISSUE TITLE
Control output frequency for sub-hour output frequency (nsout)

### ISSUE THREAD

**Issue by hu5970** [ufs-community/ufs-weather-model#1686]
## Description

To control output frequency, we can use nfhmax_hf. Before nfhmax_hf, the output frequency is controlled by nfhout_hf and after  nfhmax_hf, the output frequency is controlled by nfhout. Those three varaibles defined as integer and unit is hour.

We can output 15 minute forecast by setting "nsout". But it will control the output frequency through the whole forecast period. 

The "nfhmax_hf" cannot control the output frequency as we needed. For example, we want to do 15 minute output before 18-h forecast and 1-h output from 18-60h forecast. A small code change is needed to apply "nfhmax_hf" with "nsout".

## Solution

The code to decide the output frequency is FV3/fv3_cap.F90    .   
Small code change is needed. Here is suggested code change in block  "if(nsout > 0) then" in FV3/fv3_cap.F90. :

```
      if(nsout > 0) then
!--- use nsout for output frequency nsout*dt_atmos
        nfh = 0
        nfh2 = 0
        if( nfhmax > nfhmax_hf ) then
          if( nfhmax > output_startfh ) nfh = nint((nfhmax_hf-output_startfh)/(nsout*dt_atmos/3600.))+1
          if( nfhout>0 ) nfh2 = nint((nfhmax-nfhmax_hf)/nfhout)
        else
          if( nfhmax > output_startfh ) nfh = nint((nfhmax-output_startfh)/(nsout*dt_atmos/3600.))+1
        endif
        if( nfh+nfh2 > 0) then
          allocate(output_fh(nfh+nfh2))
          if( output_startfh == 0) then
            output_fh(1) = dt_atmos/3600.
          else
            output_fh(1) = output_startfh
          endif
          do i=2,nfh
            output_fh(i) = (i-1)*nsout*dt_atmos/3600. + output_startfh
          enddo
          do i=1,nfh2
            output_fh(nfh+i) = nfhmax_hf + i*nfhout
          enddo
        endif

```

Should this small change go with some PR?

**Comment by junwang-noaa** [comment]
@hu5970 We are planning to remove the  legacy code of nfhmax_hf/nfhout/nsout as the model has the capability to output fields at flexible output time. In your case, I'd suggest of setting the output_fh from 0.25, 0.5, 0.75 1 1.25 ...(the way to 18) 19 20 21 ...60 in the model_configure, instead of using nsout/nfhmax etc.

**Comment by hu5970** [comment]
@junwang-noaa Thanks for suggestion. I will setup the sub-hour forecast through output_fh. 
Close this issue because the problem solved.
