### ISSUE TITLE
Can (quilt) initialization time be improved for large regional domains?

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [ufs-community/ufs-weather-model#1691]
## Description
 
In looking at model performance for the North America RRFS domain (3951 x 2701), we've noticed that there is a large timing difference at model start up depending on the size of the write component output grid, and particularly if the output grid extends beyond the integration domain area.  We need to use such an oversized output grid for the RRFS system to fully capture the integration domain.  

A summary of some timing tests made with variable output grid size [here
](https://docs.google.com/spreadsheets/d/1Bbb6Q7uVasKksn2mZMVT_1Y8Ww0QE5ai1qqmcuXIhsw/edit?usp=sharing) 

## Solution
 
Ideally this issue for large regional domains that include undefined points could be better understood and improved upon.   Naturally we'd like to minimize this setup time before the model integration commences.

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA I remember we have discussed this before, can we use a pre-calculated weights for forecast grid and history file output grid interpolation, instead of calculate them on the fly at the initialization step?

**Comment by DusanJovic-NOAA** [comment]
See this PR: https://github.com/NOAA-EMC/fv3atm/pull/585

You can try setting 'use_saved_routehandles:' in model_configure to .true. First time you run the model, it will save the routehandles to a file (named routehandle_fbXX) which you can then use in subsequent runs. Model will check if these files exist in the run directory and use them instead of recomputing interpolation weights.

**Comment by MatthewPyle-NOAA** [comment]
Thanks @DusanJovic-NOAA - will take a look at that functionality.

**Comment by MatthewPyle-NOAA** [comment]
I've confirmed with the latest code that this works as advertised.  

original run generating the routehandle_fb?? files:
in fv3cap init, time wrtcrt/regrdst   292.707430074000

rerun utilizing the routehandle_fb?? files
in fv3cap init, time wrtcrt/regrdst   2.04979804100003

Once the RRFS is pointing at the authoritative UFS weather model code, we can get this into our workflow.

**Comment by junwang-noaa** [comment]
@MatthewPyle-NOAA can we close this issue?
