### ISSUE TITLE
Jet time-out issue cases

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#1695]
## Description

- Continue to encounter Jet regression test time-out issue: regional_noquilt hafs_regional_datm_cdeps regional_wofs regional_atmaq regional_atmaq_faster
- Particular error message of hafs_regional_datm_cdeps is: error in zaiopf - can't open unit 13 (available on jet /lfs4/HFIP/h-nems/Jong.Kim/RT_RUNDIRS/Jong.Kim/FV3_RT/rt_52646/hafs_regional_datm_cdeps/out)
- Discussion is attached at #1692: temporarily turned of the cases on Jet.

## Solution

- Working or tuned configuration of these cases: either reduced forecast time or namelist option, etc.
- Or proper conclusion if related to Jet system issue

## Related to
- needed by #1692

**Comment by DavidHuber-NOAA** [comment]
It may be worth noting that these same tests timeout on S4, which has similar architecture to xjet.

**Comment by zach1221** [comment]
@jkbk2004 regional_atmaq regional_atmaq_faster are still failing. However, regional_noquilt, hafs_regional_datm_cdeps,  regional_wofs are now passing on Jet.

**Comment by DavidHuber-NOAA** [comment]
@jkbk2004 I'll give these a try on S4 as well.

**Comment by FernandoAndrade-NOAA** [comment]
Running with the current develop, `regional_noquilt` `hafs_regional_datm_cdeps` and `regional_wofs` pass,
while `regional_atmaq` and `regional_atmaq_faster` are still failing.

Test Directory: `/lfs4/HFIP/h-nems/Fernando.Andrade-maldonado/RT_RUNDIRS/Fernando.Andrade-maldonado/FV3_RT/rt_113246/`

regional_atmaq I'm seeing a 137 exit code in `out` and various SIGTERM 78 errors in `err`
```srun: error: x213: task 81: Killed
srun: launch/slurm: _step_signal: Terminating StepId=59439343.0
0: slurmstepd: error: *** STEP 59439343.0 ON x111 CANCELLED AT 2023-10-17T22:15:38 ***
108: forrtl: error (78): process killed (SIGTERM)
```
In regional_atmaq_faster, I'm seeing a memory error
```72: forrtl: severe (41): insufficient virtual memory```

**Comment by jkbk2004** [comment]
> Running with the current develop, `regional_noquilt` `hafs_regional_datm_cdeps` and `regional_wofs` pass, while `regional_atmaq` and `regional_atmaq_faster` are still failing.
> 
> Test Directory: `/lfs4/HFIP/h-nems/Fernando.Andrade-maldonado/RT_RUNDIRS/Fernando.Andrade-maldonado/FV3_RT/rt_113246/`
> 
> regional_atmaq I'm seeing a 137 exit code in `out` and various SIGTERM 78 errors in `err`
> 
> ```
> srun: launch/slurm: _step_signal: Terminating StepId=59439343.0
> 0: slurmstepd: error: *** STEP 59439343.0 ON x111 CANCELLED AT 2023-10-17T22:15:38 ***
> 108: forrtl: error (78): process killed (SIGTERM)
> ```
> 
> In regional_atmaq_faster, I'm seeing a memory error `72: forrtl: severe (41): insufficient virtual memory`

@FernandoAndrade-NOAA what about ulimit -s unlimited option in jet job card?

**Comment by FernandoAndrade-NOAA** [comment]
> > Running with the current develop, `regional_noquilt` `hafs_regional_datm_cdeps` and `regional_wofs` pass, while `regional_atmaq` and `regional_atmaq_faster` are still failing.
> > Test Directory: `/lfs4/HFIP/h-nems/Fernando.Andrade-maldonado/RT_RUNDIRS/Fernando.Andrade-maldonado/FV3_RT/rt_113246/`
> > regional_atmaq I'm seeing a 137 exit code in `out` and various SIGTERM 78 errors in `err`
> > ```
> > srun: launch/slurm: _step_signal: Terminating StepId=59439343.0
> > 0: slurmstepd: error: *** STEP 59439343.0 ON x111 CANCELLED AT 2023-10-17T22:15:38 ***
> > 108: forrtl: error (78): process killed (SIGTERM)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In regional_atmaq_faster, I'm seeing a memory error `72: forrtl: severe (41): insufficient virtual memory`
> 
> @FernandoAndrade-NOAA what about ulimit -s unlimited option in jet job card?

Adding that option has at least caused the same insufficient virtual memory error to show up in `regional_atmaq` err log as well now in addition to `regional_atmaq_faster`, but they are both still failing.

**Comment by BrianCurtis-NOAA** [comment]
@FernandoAndrade-NOAA can you try TPN=16 for those tests?

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA can you try TPN=16 for those tests?

Sure thing, it was also suggested to try ulimit -l unlimited, so I'll add that as well. I believe @zach1221 has previously tried a different TPN for jet. Zach do you remember if you had used 16 or 18?

**Comment by FernandoAndrade-NOAA** [comment]
Both are unfortunately still failing after those adjustments. I am seeing slightly different err messages:
`/lfs4/HFIP/h-nems/Fernando.Andrade-maldonado/RT_RUNDIRS/Fernando.Andrade-maldonado/FV3_RT/rt_13549/`
```
80: slurmstepd: error: Detected 1 oom-kill event(s) in StepId=60446146.0. Some of your processes may have been killed by the cgroup out-of-memory
 handler.
176: slurmstepd: error: Detected 1 oom-kill event(s) in StepId=60446146.0. Some of your processes may have been killed by the cgroup out-of-memory
 handler.
srun: error: x278: task 80: Out Of Memory
srun: launch/slurm: _step_signal: Terminating StepId=60446146.0
  0: slurmstepd: error: *** STEP 60446146.0 ON x172 CANCELLED AT 2023-11-01T16:47:00 ***
271: forrtl: error (78): process killed (SIGTERM)```

**Comment by zach1221** [comment]
> > @FernandoAndrade-NOAA can you try TPN=16 for those tests?
> 
> Sure thing, it was also suggested to try ulimit -l unlimited, so I'll add that as well. I believe @zach1221 has previously tried a different TPN for jet. Zach do you remember if you had used 16 or 18?

Hey, @FernandoAndrade-NOAA . Yes I attempted 18 in the past with no luck.

**Comment by zach1221** [comment]
@jkbk2004 I re-tested these on Rocky8 and they passed, specifically  regional_noquilt, hafs_regional_datm_cdeps, and regional_wofs. It doesn't look like regional_atmaq_faster is in rt.conf anymore and regional_atmaq has been hashed out, but I ran the atmaq compile suite successfully.

**Comment by zach1221** [comment]
@jkbk2004 per our conversation, closing this issue.
