### ISSUE TITLE
empty directories under FV3/upp

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#1703]
## Description
I am not sure this is a bug or not but following directories are empty when you checkout ufs-weather-model,

- FV3/upp/sorc/libIFI.fd
- FV3/upp/sorc/ncep_post.fd/post_gtg.fd

and `.gitmodules` under `upp/` directory points repositories that are not found.

### To Reproduce:
1. checkout model `git clone --recursive https://github.com/ufs-community/ufs-weather-model.git`
2. then check those directories

**Comment by junwang-noaa** [comment]
@uturuncoglu IFI and post_gtg code is private, only those who have permission can check out the code. It is expected to have empty directories for those who don't have access permission.
@SamuelTrahanNOAA FYI.

**Comment by SamuelTrahanNOAA** [comment]
Those are where the two UPP submodules reside, like the FV3 directory in ufs-weather-model. Few people can access those submodules because the source code is proprietary. For that reason, their automatic checkout is disabled.

**Comment by uturuncoglu** [comment]
@SamuelTrahanNOAA @junwang-noaa Okay. I did not know it. Now, makes sense. Thanks. I am closing this issue.
