### ISSUE TITLE
update FV3 to better handle data source for regional model LBC processing

### ISSUE THREAD

**Issue by Jili-Dong** [ufs-community/ufs-weather-model#1716]
Currently FV3 will read data source from global attribute "source" of gfs_data.nc to decide how LBC will be processed for regional model, e.g. RRFS. Sometimes there is no global attribute "source" in gfs_data.nc, particularly after regional cycled data assimilation, even though the data source is fv3gfs. This will cause FV3 to handle LBCs as they are from old GFS spectrum model. Furthermore, warm start runs don't need to read any variables from gfs_data.nc.

The solution is to add reading data source from LBC directly to decide how LBC will be processed. The PR also forces model to exit with error messages when no data source is found, which will avoid mistakenly take missing data source as data source being from legacy spectrum GFS spectrum.

Related to PR:

#1715

**Comment by jkbk2004** [comment]
closed with #1715
