### ISSUE TITLE
regional_atmaq_faster fails to run on both Acorn and WCOSS2 from PR #1731 

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#1742]
## Description

regional_atmaq_faster fails to run on both Acorn and WCOSS2 from PR #1731 

### To Reproduce:

Acorn: /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_192131 
WCOSS2 (Cactus): /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_57197

## Output

```
FATAL from PE   116: compute_qs: saturation vapor pressure table overflow, nbad=      1

Image              PC                Routine            Line        Source             
fv3.exe            0000000003D64156  Unknown               Unknown  Unknown
fv3.exe            0000000002A789BE  mpp_mod_mp_mpp_er          72  mpp_util_mpi.inc
fv3.exe            0000000002A7817A  mpp_mod_mp_mpp_er         149  mpp_util.inc
fv3.exe            0000000002948DEC  fms_mod_mp_fms_er         505  fms.F90
```

**Comment by junwang-noaa** [comment]
This looks to me a stability issue. @Qingfu-Liu

**Comment by Qingfu-Liu** [comment]
Did the same runs failed on the other machine (Hera, Cheyenne)? If not, why the runs only failed on Acorn and WCOSS2?

**Comment by BrianCurtis-NOAA** [comment]
They only failed on WCOSS2 and Acorn.

**Comment by BrianCurtis-NOAA** [comment]
I can reproduce the error with current UFSWM develop branch. It happens on time 1718 (completed would be 1800), so it's not too far from the end. @Qingfu-Liu This is not an AQM issue I don't believe. Do you know what might be causing this? (/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model) and (/lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_131626/regional_atmaq_faster_intel)

@junwang-noaa You mentioned a stability issue. Are there any changes we can make to help with the stability in the testing system, or is this a code change deeper into FV3?
