### ISSUE TITLE
baseline time stamp

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#1746]
## Description
I just re-ran my UFS WM PR after sync-ed to today's develop branch but my jobs failed in BL comparison.
Looking at https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt.sh#L471
it is marked as 0504 but today's finished PR (https://github.com/ufs-community/ufs-weather-model/pull/1731) had a new BL and I can see on HERA we have develop-20230509 directory.
Is there anything being missed in today's PR ?

**Comment by jkbk2004** [comment]
@jiandewang develop branch has BL_DATE=20230504. We started working on #1727. I am preparing for new BL_DATE=20230509.

**Comment by jiandewang** [comment]
@jkbk2004 I see, you have merged today's PR but haven't worked on BL changing yet.

**Comment by jkbk2004** [comment]
> @jkbk2004 I see, you have merged today's PR but haven't worked on BL changing yet.

Correct!
