### ISSUE TITLE
Inline post: move computation of diagnostic variables outside a do loop that loads arrays from a bundle

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#1748]
In inline post the computation of diagnostic variables here:

https://github.com/NOAA-EMC/fv3atm/blob/160b422dc1d294623cc8ebfabfbe7d28d7c65c62/io/post_fv3.F90#L4353

from line 4353 to 4413 (and several other loops) should me moved outside of the field loop (after file_loop_all loop) . Those additional fields should be computed when all the fields from the fields bundle have been assigned values, otherwise these fields will be computed when each field is assigned values.

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA FYI.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA @junwang-noaa Good catching. We will work on that in the upcoming PR. Thanks!
