### ISSUE TITLE
Update PR template to notify library changes

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [ufs-community/ufs-weather-model#1757]
I'm filing this issue on behalf of the spack-stack folks. As part of the PR template for ufs-weather-model, we would like to include some sort of documentation and preferably a checklist item that ensures that any changes in libraries used-- adding, removing, or upgrading the version of any dependency-- is reported to the spack-stack team as a GitHub issue as soon as the PR is submitted. That way, we can be sure to keep up with the discussion and make sure we have enough lead time to make modifications in Spack and spack-stack.

cc @climbfuji

**Comment by climbfuji** [comment]
Thanks, @AlexanderRichert-NOAA !

**Comment by BrianCurtis-NOAA** [comment]
It most definitely needs to be a part of the whole process. Because libraries take a long time to get into WCOSS2, and in my opinion should be mandatory before acceptance into UFSWM, I think something along the lines of:
```
### Library Updates/Changes
<!-- Library updates take time. If this PR needs updates to libraries, please make sure to accomplish the following tasks -->
- [ ] Not Needed
- [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
- [ ] Add issue link from JCSDA/spack-stack following this item
<!-- for example: "- JCSDA/spack-stack/issue/1757" -->
```
Which will produce:
### Library Updates/Changes

- [ ] Not Needed
- [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
- [ ] Add issue link from JCSDA/spack-stack following this item

**Comment by AlexanderRichert-NOAA** [comment]
Yes that looks good to me, especially requiring a link to the spack-stack issue.

**Comment by climbfuji** [comment]
@BrianCurtis-NOAA --> no @AlexanderRichert-NOAA If you would like to create a PR for this, please? I will be on leave for a few weeks, won't be able to approve. Thanks for your help!

**Comment by climbfuji** [comment]
Any progress on this?

**Comment by BrianCurtis-NOAA** [comment]
> Any progress on this?

Its been on my to-do, just need to make the time to add it to a PR and have been a little busy.

**Comment by jkbk2004** [comment]
We will update on next PR.

**Comment by climbfuji** [comment]
> We will update on next PR.

Thanks, that's great to hear!

**Comment by jkbk2004** [comment]
PR template was updated thru #1776
