### ISSUE TITLE
missing baseline on wcoss2

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#1760]
## Description
at this moment ufs-weather-model BL is 20230515, see
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt.sh#L471
but 20230515 directory doesn't exist on wcoss2 
/lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA Would you please look into this?

**Comment by BrianCurtis-NOAA** [comment]
@jiandewang I'm getting the baselines moved over there now. I'll close this once it's completed. Thanks for letting us know.

**Comment by BrianCurtis-NOAA** [comment]
Files synced into develop-20230515. Closing
