### ISSUE TITLE
UFS-WM RT cases failing on Cheyenne now passing for Derecho

### ISSUE THREAD

**Issue by zach1221** [ufs-community/ufs-weather-model#1762]
**Description**

The following cases fail on Cheyenne, using intel compilers, hafs_regional_1nest_atm_qr, hafs_global_1nest_atm_qr, hafs_global_multiple_4nests_atm_qr, and hafs_regional_storm_following_1nest_atm_qr . 

**To Reproduce:**

1. Clone UFS-WM ufs-community:develop on Cheyenne.
2. cd ufs-weather-model
3. run: ./rt.sh -c -n hafs_regional_1nest_atm_qr

**Additional context**

Failures only happen on Cheyenne and seem to be related to mpt/2.25 and hdf5. Note that these four cases in question have been turned off on cheyenne in rt.conf.

Related to updates from PR #1722 

**Output**

**Screenshots**
![image](https://github.com/ufs-community/ufs-weather-model/assets/99902696/2b48d8df-58f7-4a37-b0ff-e2cb9a7ac8a8)

**Comment by ulmononian** [comment]
@zach1221 thanks for reporting this. i had issues with `hafs_regional_storm_following_1nest_atm_ocn_debug` on hercules, but probably entirely unrelated. are these turned off in the `rt_conf` in ufs-wm develop?

**Comment by zach1221** [comment]
Hey, @ulmononian . Currently the hafs qr tests, there are four, are turned off on Cheyenne. However they run successfully on the other HPCs (hera.intel, jet, orion and gaea.

**Comment by zach1221** [comment]
I can confirm these hafs tests mentioned above will now run on Cheyenne. I re-enabled the above tests on the HPC, and there were no failures.

**Comment by DeniseWorthen** [comment]
Multiple hafs _qr tests are still turned off on cheyenne. If you've tested and they now work, a PR will need to be made to turn those tests back on. Then you can close the issue.

https://github.com/ufs-community/ufs-weather-model/blob/251ec56df56d987fe3a2ba900d9a22b95e2058de/tests/rt.conf#L218-L226

**Comment by zach1221** [comment]
> Multiple hafs _qr tests are still turned off on cheyenne. If you've tested and they now work, a PR will need to be made to turn those tests back on. Then you can close the issue.
> 
> https://github.com/ufs-community/ufs-weather-model/blob/251ec56df56d987fe3a2ba900d9a22b95e2058de/tests/rt.conf#L218-L226

Since we're transitioning away from Cheyenne to Derecho I think this ticket can be closed. However, I did run the Hafs cases against the ufs-wm repo used in the Derecho PR here [#1836](https://github.com/ufs-community/ufs-weather-model/pull/1836), and they passed. log: /glade/work/zshrader/RegressionTests_derecho.log

**Comment by DeniseWorthen** [comment]
@zach1221 It looks like you created the baseline, but did you run against it and confirm it was B4B? It would be good to verify that too. Assuming that is OK, then the person making the Derecho PR needs to turn these tests on. Once they are in the Derecho PR, I agree we can close this issue.

**Comment by zach1221** [comment]
@DeniseWorthen ok, I will run the matching as well. When you say turn the tests on, do you mean put the "+ derecho" in the column next to the test?

**Comment by DeniseWorthen** [comment]
Yes, we need to replace cheyenne w/ derecho for those tests. I think we should be doing that in the Derecho PR for all Cheyenne occurrences (in general, removing Cheyenne where it occurs).

**Comment by zach1221** [comment]
Closing, as cases aren't in rt.conf any longer.
