### ISSUE TITLE
Document WM Land Configurations

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-weather-model#1763]
## Description
It would be useful for users to have information on different WM configurations. Since there are a multitude of possible configurations, EPIC is starting to document configurations related to application releases. The Land DA System is the most recent release, and therefore, we hope to update the WM documentation to include WM configurations that use the land component. 

## Solution
Add information on land component configurations listed in rt.conf.

## Alternatives
We are open to suggestions on what configuration information should be included. 

## Related to
N/A

**Comment by zach1221** [comment]
Merging of UFS-WM #1761 should satisfy this issue ticket. Placing this is closed status.
