### ISSUE TITLE
Modulefile update for Gaea following C3,C4 partition upgrades

### ISSUE THREAD

**Issue by natalie-perlin** [ufs-community/ufs-weather-model#1772]
A modulefile for Gaea needs to be updated following the C3, C4 partitions upgrades. An updated software stack (hpc-stack) has been built with the new intel modules and mpich. UFS-WM regression tests successfully pass successfully with the new software stack, and a [PR-1758 for the UFS-Weather Mode](https://github.com/ufs-community/ufs-weather-model/pull/1758) has been opened.
(https://github.com/ufs-community/ufs-weather-model/pull/1758)

A software stack uses modules `intel-classic-2022.0.2 `and `mpich-cray/7.7.20`; the path the following:
`/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-classic-2022.0.2/modulefiles/stack`

**Comment by junwang-noaa** [comment]
@natalie-perlin Just want to follow up on gaea module files. In issue #1621, you provide to us new library module files under:

Gaea: /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0_ncdf492

Do you plan to update the intel compiler to intel-classic-2022.0.2 for those modules? Thanks

**Comment by natalie-perlin** [comment]
@junwang-noaa - yes, thanks for reminding, planning to update the intel-classic-2022.0.2 asap to have a netcdf/4.9.2 version, and will tag here.

**Comment by natalie-perlin** [comment]
@junwang-noaa - 
The stack on `Gaea `has been updated to have hdf5/1.14.0, netcdf/4.9.2, pio/2.5.10, esmf/8.4.2, and mapl/2.35.2:
`/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-classic-2022.0.2_ncdf492`

This is the part needed for the ufs_gaea.intel.lua modulefile:
```
prepend_path("MODULEPATH","/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-classic-2022.0.2_ncdf492/modulefiles/stack")
load(pathJoin("hpc", os.getenv("hpc_ver") or "1.2.0"))

load(pathJoin("intel-classic", os.getenv("intel_ver") or "2022.0.2"))
load_any(pathJoin("cray-mpich", os.getenv("cray_mpich_ver") or "7.7.20"),"cray-mpich")
load(pathJoin("hpc-intel-classic", os.getenv("hpc_intel_classic_ver") or "2022.0.2"))
load(pathJoin("hpc-cray-mpich", os.getenv("hpc_cray_mpich_ver") or "7.7.20"))
load(pathJoin("libpng", os.getenv("libpng_ver") or "1.6.37"))
```
Attached are full ufs_gaea.intel.lua, ufs_common.lua, and RegressionTests_gaea.log for the control_p8_intel (a  quick check ).
[ufs_common.lua.txt](https://github.com/ufs-community/ufs-weather-model/files/11707108/ufs_common.lua.txt)
[ufs_gaea.intel.lua.txt](https://github.com/ufs-community/ufs-weather-model/files/11707112/ufs_gaea.intel.lua.txt)
[RegressionTests_gaea.log.txt](https://github.com/ufs-community/ufs-weather-model/files/11707114/RegressionTests_gaea.log.txt)

**Comment by natalie-perlin** [comment]
@junwang-noaa - 
Is there a partucular test that could be run to test a WM develop branch with the current GOCART, to test functionality with the new software stack?

**Comment by DeniseWorthen** [comment]
@natalie-perlin Jun is out this week, so I will answer. You can try either the  ``atmaero_control_p8`` or the``cpld_control_p8`` . Both include aerosols, one is atmosphere only and one is the fully coupled case.
