### ISSUE TITLE
Update repo_check.sh 

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#1778]
## Description

1. Need to update repo check script to make sure all of pr subcomponents up to date (see the case in PR #1743)
2. Need a feature to capture PR owner's latest commit (see the case in PR #1731)

## Solution

1. repo_check.sh currently covers fv3 mom6 cice ww3 stoch gocart cmeps cdeps hycom cmake
2. add a functionality to check ccpp and cubed sphere subcomponents as well

**Comment by zach1221** [comment]
@jkbk2004 I think this is ready to close. Feel free to re-open if you disagree.
