### ISSUE TITLE
nccmp log is many gigabytes long due to `-f` option to `nccmp`

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#1781]
## Description

On some platforms, rt.sh uses nccmp to compare files, and it uses the `-f` option, which tells nccmp to report all differences in all fields. This can be uselessly long if the entire grid is different. The fix is to use the `-c` option, which limits the number of differences printed per variable.

The fix is to add `-q -S`. This disables printing of data and metadata differences, but enables a table of statistics comparing the data.

### To Reproduce:
Run a failing regression test and look at the _nccmp.log files. If you're lucky, that is. Often it'll take so long to generate the log that the job will hit its wallclock limit.

### Additional Context

I am testing a fix now, and I will put it in #1769

**Comment by zach1221** [comment]
As UFS-WM PR 1769 has been merged, am I good to close this issue @SamuelTrahanNOAA ?

**Comment by SamuelTrahanNOAA** [comment]
Yes. Sorry, I forgot to put `fixes ` before the PR number to close it automatically.
