### ISSUE TITLE
The ORT dbg test runtime exceeds for cpld_control_p8 on hera

### ISSUE THREAD

**Issue by sadeghitabas** [ufs-community/ufs-weather-model#1785]
## Description

The ORT dbg test runtime exceeds the time limit for cpld_control_p8 application on hera.  Please see below working directory for more information:
/scratch1/NCEPDEV/stmp2/Sadegh.Tabas/FV3_OPNREQ_TEST/opnReqTest_10253/cpld_control_p8_intel_dbg_base

### To Reproduce:

./opnReqTest -a nems -n cpld_control_p8 -c dbg

## Output

```
slurmstepd: error: *** STEP 45654430.0 ON h16c14 CANCELLED AT 2023-06-05T17:18:17 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 45654430 ON h16c14 CANCELLED AT 2023-06-05T17:18:17 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
```

**Comment by BrianCurtis-NOAA** [comment]
Please let me know if an increased wallclock fixes this issue.

**Comment by BrianCurtis-NOAA** [comment]
I looked at the logs and it seems the WLCLK is not getting exported to the run env as I noticed the err file shows it only tried for 30 minutes. I've edited the opnReqTest script to export it and i'm testing now to see if that fixes this issue.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I thought the wall clock should have only been extended for the hera.gnu case? The ORT is not using gnu, is it?

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen 
https://github.com/ufs-community/ufs-weather-model/blob/5d47ea8b820596930e5d82a486b8bf97c4c283bc/tests/opnReqTest#L207-L220

Seems all dbg cases are supposed to be WLCLK=60

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA It's been a long time since I looked at how the ORTs are run. Are they using fewer resources than when we run the normal RTs? Why do they require such long wall clocks?

**Comment by DeniseWorthen** [comment]
Can this be closed?

**Comment by sadeghitabas** [comment]
> I looked at the logs and it seems the WLCLK is not getting exported to the run env as I noticed the err file shows it only tried for 30 minutes. I've edited the opnReqTest script to export it and i'm testing now to see if that fixes this issue.

@BrianCurtis-NOAA I was wondering if this issue got fixed? Thanks

**Comment by BrianCurtis-NOAA** [comment]
I know I tried to fix it. We haven't had any issues with ORT, correct? Hey @zach1221 are we running the cpld_control_p8? If so, we can close this issue.

**Comment by zach1221** [comment]
> I know I tried to fix it. We haven't had any issues with ORT, correct? Hey @zach1221 are we running the cpld_control_p8? If so, we can close this issue.

We're running ORTs against cpld_control_nowave_noaero_p8 with gnu on hera. I can test cpld_control_p8 specifically to see if it has issues.

**Comment by zach1221** [comment]
> cpld_control_p8

cpld_control_p8 passes ORTs bit, debug and standard on hera using gnu compilers. No timeouts.

**Comment by DeniseWorthen** [comment]
Can we close this then?

**Comment by sadeghitabas** [comment]
> Can we close this then?

Yes, I think we can close it now. Thanks
