### ISSUE TITLE
Add compilation lines without updating every `COMPILE` in the rt.conf

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#1796]
## Description

Presently, if you want to add a new `COMPILE` line to rt.conf, you have to increment the numbers of every COMPILE line after that.

## Solution
Use a name instead of a number:

```bash
COMPILE | p8_s2swa_dyn32 | intel | -DAPP=S2SWA -D32BIT=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | | fv3 |
RUN | cpld_control_p8_mixedmode                         |                            | baseline |
...

COMPILE | p8_s2swa | intel | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | | fv3 |
RUN | cpld_control_p8                                   |                            | baseline |
...

COMPILE | p8_s2swa | gnu | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | + hera cheyenne | fv3 |
RUN | cpld_control_p8                                   | + hera cheyenne            | baseline |
...

COMPILE | p8_s2s | gnu | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | + hera cheyenne | fv3 |
RUN | cpld_control_nowave_noaero_p8                     | + hera cheyenne            | baseline |
```

The COMPILE_NR is the second column, then an _, and then the third column:

- `COMPILE | p8_s2swa | intel` => `p8_s2swa_intel`
- `COMPILE | p8_s2swa | gnu` => `p8_s2swa_gnu`

You can detect duplicated compile lines using gnu bash dictionaries, which requires bash 4.

This is implemented in #1797

## Alternatives
1. Remove the number entirely.
2. Step by 10 instead of 1. This way, nine compilations can be inserted between two of them before renumbering the file.

## Related to
Nothing.

**Comment by BrianCurtis-NOAA** [comment]
I wanted to write a script that would auto-adjust the rt.conf compile numbers for just this situation, but haven't had time.  Something that reads it line by line and when it sees "COMPILE" add +1 and update that line if not equal.

**Comment by SamuelTrahanNOAA** [comment]
> I wanted to write a script that would auto-adjust the rt.conf compile numbers for just this situation, but haven't had time. Something that reads it line by line and when it sees "COMPILE" add +1 and update that line if not equal.

It would be easy to simply ignore the compile numbers and use the COMPILE line counter instead. However, adding a general string would be best. I don't know if the various workflows can handle that.

**Comment by BrianCurtis-NOAA** [comment]
Also we could re-write the failures of tests such that a missing compile would write out an error of "MISSING COMPILE" and we could get rid of compile numbers again.

My main issue with no compile number was when it failed a compile it would say "compile_016 failed" and I would have to count the compile lines, skipping any lines that didn't run on the specific machine, and sometimes i'd count wrong because i'd miss a compile. So I can say the new compile number has saved me some good time with testing.

I'd be fine with a special string, maybe we can find a standard to the naming of it, but it's easy to grep for that special string in my example annoyance above.

**Comment by SamuelTrahanNOAA** [comment]
I'm testing this:

```bash
COMPILE | p8_s2swa_dyn32 | intel | -DAPP=S2SWA -D32BIT=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | | fv3 |
RUN | cpld_control_p8_mixedmode                         |                            | baseline |
...

COMPILE | p8_s2swa | intel | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | | fv3 |
RUN | cpld_control_p8                                   |                            | baseline |
...

COMPILE | p8_s2swa | gnu | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | + hera cheyenne | fv3 |
RUN | cpld_control_p8                                   | + hera cheyenne            | baseline |
...

COMPILE | p8_s2s | gnu | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | + hera cheyenne | fv3 |
RUN | cpld_control_nowave_noaero_p8                     | + hera cheyenne            | baseline |
```

The COMPILE_NR is the second column, then an _, and then the third column:

- `COMPILE | p8_s2swa | intel` => `p8_s2swa_intel`
- `COMPILE | p8_s2swa | gnu` => `p8_s2swa_gnu`

It detects duplicated compile lines using gnu bash dictionaries, which requires bash 4.

**Comment by SamuelTrahanNOAA** [comment]
Okay, it works. I've updated my PR #1797 to use names instead of numbers.
