### ISSUE TITLE
Build the HAFS-MOM6 application

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#1798]
## Description
A new HAFS-MOM6 system has been set up. This PR will build the HAFS-MOM6 application. New regression tests using this application will be added in future pull requests.

## Related to
CMEPS PR: https://github.com/NOAA-EMC/CMEPS/pull/90
CDEPS PR: https://github.com/NOAA-EMC/CDEPS/pull/57

**Comment by DeniseWorthen** [comment]
Closing. Feature was committed in #2028
