### ISSUE TITLE
Typo when setting DO_MYJPBL to true in certain RTs

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-weather-model#1814]
## Description
Some of the regression tests list `DO_MYJPBL=.true` (no period after `.true`). It seems like this might not successfully set DO_MYJPBL to true. Thus far, this typo appears in: 

- rrfs_conus13km_hrrr_warm
- rrfs_conus13km_hrrr_warm_restart_mismatch
- rrfs_smoke_conus13km_hrrr_warm_debug
- rrfs_smoke_conus13km_hrrr_warm_debug_2threads
- rrfs_smoke_conus13km_radar_tten_warm

It may also appear in other tests, although these are the ones where I noticed it. 

### To Reproduce:
Look at the code! ;) 
I am unclear on what the actual effect of this typo is on results, so someone else may want to run these tests and see if DO_MYJPBL is actually getting set to true or if the default `.false.` value remains because `.true` is invalid. 

## Additional context
This may need to be fixed in other RTs; someone will need to verify. 

## Output
N/A

**Comment by DeniseWorthen** [comment]
There does not appear to be any test remaining which relies on the ``DO_MYJPBL`` variable. The only only nml file I could find with that variable present is the ``regional_atmaq.nml.IN`` and it is hard-wired false ``do_myjpbl = .false.``.

@SamuelTrahanNOAA I believe you were the last person to update/remove these old conus13km tests. Can we remove the ``DO_MYJPBL`` variable?

**Comment by SamuelTrahanNOAA** [comment]
The typo is still present in `default_vars.sh` `export_hrrr()`

```bash
export DO_MYJPBL=.true
```

but the variable is not used anywhere.

I've added a fix to this draft PR:

- https://github.com/ufs-community/ufs-weather-model/pull/2064

It should cease to be a draft soon. I was waiting for the original author of module_diag_hailcast.F90 to respond, and now they have.

**Comment by DeniseWorthen** [comment]
Great, thanks Sam.
