### ISSUE TITLE
Document WM RRFS Configurations

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-weather-model#1820]
## Description
It would be useful for users to have information on different WM configurations. Since there are a multitude of possible configurations, EPIC is starting to document configurations related to application releases. With the SRW v3.0.0/RRFS capabilities release forthcoming, we hope to update the WM documentation to include WM configurations that test RRFS configurations.

## Solution
Add information on RRFS configurations listed in rt.conf.

## Alternatives
We are open to suggestions on what configuration information should be included.

## Related to
N/A

**Comment by zach1221** [comment]
Closing PR. #1870 has since been merged with documentation updates.
