### ISSUE TITLE
re-enable c48-5deg warmstart test

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#1822]
## Description

The C48-5deg warmstart test was disabled in PR #1812. It needs to be re-enabled.

## Solution

Once PR #1777 and #1807 are merged, a new set of warm start ICs should be created and added to the input-data directory. This will allow the test to be re-enabled.

**Comment by DeniseWorthen** [comment]
@NickSzapiro-NOAA Are you able to work on this now? I want to include the required files in the input-data update I will be making for the Bu angle fix. 

We need new ICs (really warmstart) files at ``2021032306``. You can see the required files in the existing input-data directories for CICE,MOM6,CMEPS and FV3_input_data48/INPUT_L127_mx500.

These are generated by running the ``cpld_control_c48`` at the current develop. Once you have them generated, I will populate the new input-data directory I have you can confirm that the warmstart test runs. We'll then have to verify the restart-from-warmstart test also passes.

**Comment by NickSzapiro-NOAA** [comment]
@DeniseWorthen restarts from cpld_control_c48 are available on hera at /scratch1/NCEPDEV/nems/Nick.Szapiro/tasks/warmStart_c48-5deg/IC
Please let me know if you'd like me to rename/arrange

**Comment by DeniseWorthen** [comment]
@NickSzapiro-NOAA Thanks. I've repopulated the input-data directory here ``/scratch1/NCEPDEV/stmp4/Denise.Worthen/input-data_20240501``

Now can you re-enable the two c48 cpld tests (warmstart and restart) and create a warm start baseline after pointing to this location for the input and verify both the warm and restart tests pass?

**Comment by NickSzapiro-NOAA** [comment]
cpld*c48 tests now pass on hera. See /scratch1/NCEPDEV/nems/Nick.Szapiro/tasks/warmStart_c48-5deg/ufs-weather-model/tests

**Comment by junwang-noaa** [comment]
@NickSzapiro-NOAA are you going to create a UFS WM PR to include the tests in RT?

**Comment by NickSzapiro-NOAA** [comment]
@junwang-noaa I think @DeniseWorthen already did in https://github.com/ufs-community/ufs-weather-model/pull/2235

**Comment by DeniseWorthen** [comment]
Yes, because re-enabling the test requires new input data, I added it to the PR which will fix input grid data for CICE.
