### ISSUE TITLE
UWM gnu compiling failed when multiple compiling jobs are launched

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#1828]
## Description

I am testing MOM6 updating in UWM but got compiling failed for all gnu jobs (intel are fine). So I just checked out latest UWM develop branch (as of Jul 8th) and repeated what I did, but found out the same issue.
If I just compile one gun job, it works fine. What I did is compile all gnu S2S and NG-GODAS in one shot, then problem happened with following error:
_mod has detected the following error: Cannot load module "mpich/3.3.2"
because these module(s) are loaded:
   impi_
_While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    mpich/3.3.2      /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2/modulefiles/compiler/gnu/9.2/mpich/3.3.2.lua_

  See example on HERA at /scratch1/NCEPDEV/stmp2/Jiande.Wang/FV3_RT/rt_22254

### To Reproduce:

- check out latest UWM
- edit rt.conf, remove all except gnu S2S, S2SW, S2SWA and NG-GODAS (46-51)
- run rt.sh under ecflow
- see err file in compiling directory

**Comment by jkbk2004** [comment]
@jiandewang can you try with latest develop? We replace the compiling numeric sequence with actual app name.

**Comment by jkbk2004** [comment]
@jiandewang I am throwing several gnu jobs on hera: /scratch2/NCEPDEV/marine/Jong.Kim/UFS-RT/dev-gnu/tests/rt.conf. Looks like running. let me try your /scratch1/NCEPDEV/climate/Jiande.Wang/working/TEST-HEAR-gnu/ufs-weather-model/tests/rt.conf-JW. @BrianCurtis-NOAA might be parsing issue with non-baseline cases.

**Comment by natalie-perlin** [comment]
@jiandewang - 
  Not able to reproduce the error you report. 
 Is it possible that you have intel and impi modules loaded when submitting the rt.sh job?
 Could you make sure the intel and impi are unloaded before submitting the job?
 
 The current test directory set up to investigate the issue:
 /scratch1/NCEPDEV/stmp2/Natalie.Perlin/UFS-WM/ufs-wm-test/tests
 the rt.conf-gnu copied from /scratch1/NCEPDEV/climate/Jiande.Wang/working/TEST-HEAR-gnu/ufs-weather-model/tests.
 
 The working directory with the compile jobs:
 /scratch1/NCEPDEV/stmp2/Natalie.Perlin/FV3_RT/rt_70300 
 all compiled, and running at the moment

**Comment by jiandewang** [comment]
@natalie-perlin apparently you try works normal, don't know the root cause at this moment, could be script issue. @HelinWei-NOAA just reported tha he got the same problem as mine.
I did modul purge before although it is not really necessary as rt.sh will do that

**Comment by natalie-perlin** [comment]
@jiandewang 
Is the RT_COMPILER variable set in the shell from which the job is submitted by any chance? (It may need _not_ to be set, so the compiler is set dynamically depending on the input file)

**Comment by jiandewang** [comment]
@natalie-perlin no this variable doesn't need to be set as intel and gun jobs were combined in a recent UWM PR and that worked for a while until this weekend I got this problem when I was testing my branch

**Comment by jkbk2004** [comment]
@jiandewang I was able to run your rt.conf-JW at /scratch2/NCEPDEV/marine/Jong.Kim/UFS-RT/dev-gnu/tests/logs/RegressionTests_hera.log. What about module purge? If you use different shell on hera.

**Comment by jiandewang** [comment]
@jkbk2004 what's your default shell ? mine is tcsh. Let me try bash

**Comment by natalie-perlin** [comment]
@jiandewang -
Regression testing with the rt.conf-gnu as shown below ran to completion (similar to @jkbk2004 reported), at /scratch1/NCEPDEV/stmp2/Natalie.Perlin/UFS-WM/ufs-wm-test/tests/logs/RegressionTests_hera.log

rt.conf-gnu:
```
### S2S tests ###
COMPILE | 46 | gnu | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | + hera cheyenne | fv3 |
RUN | cpld_control_p8                                   | + hera cheyenne            | baseline |

COMPILE | 47 | gnu | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | + hera cheyenne | fv3 |
RUN | cpld_control_nowave_noaero_p8                     | + hera cheyenne            | baseline |

COMPILE | 48 | gnu | -DAPP=S2SWA -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | + hera cheyenne | fv3 |
RUN | cpld_debug_p8                                     | + hera cheyenne            | baseline |

# Unstructured WW3
COMPILE | 49 | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 -DPDLIB=ON | + hera cheyenne | fv3 |
RUN | cpld_control_pdlib_p8                             | + hera cheyenne            | baseline |

COMPILE | 50 | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 -DPDLIB=ON -DDEBUG=ON | + hera cheyenne | fv3 |
RUN | cpld_debug_pdlib_p8                               | + hera cheyenne            | baseline |

### CDEPS Data Atmosphere test ###
COMPILE | 51 | gnu | -DAPP=NG-GODAS | + hera cheyenne | fv3 |
RUN | datm_cdeps_control_cfsr                           | + hera cheyenne            | baseline |
```

**Comment by jiandewang** [comment]
@natalie-perlin what's your default shell ? also did you do any pre-setup such as define RT_COMPILER ? thanks for the updating

**Comment by jkbk2004** [comment]
@jiandewang I am using bash on hera. You may try "module purge".

**Comment by jiandewang** [comment]
@jkbk2004 I assume your default shell is bash. For me it is tcsh. I recall we had similar problem on GAEA, but rt.sh works fine on HEAR regardless of your shell for a long time and this is why I rely on HERA for most of my testing. But now switching to bash still got the same error for me on HERA. Very strangely why all intel jobs work fine for me on HERA. I also don't understand why gnu works fine if not using ecflow

**Comment by jkbk2004** [comment]
@jiandewang what about "source /apps/lmod/lmod/init/bash && module purge" ? Do you need to stay with tcsh ?

**Comment by jiandewang** [comment]
@jkbk2004 so far I have not successed. Let me try what you suggested here. I want to say that this issue is something new, it only happened in the past several days. I have been using HERA for all my previous test without problem.

**Comment by jiandewang** [comment]
@jkbk2004 just tried your suggestion, still got the same error
one error I have in log is
_++ MACHINE_ID=hera
++ case $(echo $PW_CSP) in
./detect_machine.sh: line 108: PW_CSP: unbound variable_

not sure this is related or it's harmless

**Comment by jkbk2004** [comment]
Sounds like it might be worth to set dummy PW_CSP  name like export PW_CSP=nono. Clearly, some env variables are screwed up on your side.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I found this same issue earlier, posted to the uwm slack channel. I do not think it is related

[2:50 PM](https://noaa-emc.slack.com/archives/G01D4LV13M0/p1686768617306519)
I was looking at the output from a compile and noticed this
detect_machine.sh: line 108: PW_CSP: unbound variable

EDIT: This did not copy well from Slack. I posted this on June 14. There is no reason why Sam's PR would have created this issue.

**Comment by HelinWei-NOAA** [comment]
@SamuelTrahanNOAA may offer some help.

**Comment by SamuelTrahanNOAA** [comment]
In tests/detect_machine.sh, try changing this:

```bash
case $(echo $PW_CSP) in
```

to this:

```bash
case "${PW_CSP:-nono}" in
```

**Comment by HelinWei-NOAA** [comment]
@SamuelTrahanNOAA Thanks for your quick response. All gnu RTs still failed to compile with the error:
Lmod has detected the following error: Cannot load module "hpc-gnu/9.2"
because these module(s) are loaded:
   hpc-intel

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    hpc-gnu/9.2      /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2/modulefiles/core/hpc-gnu/9.2.lua
    ufs_hera.gnu     /scratch1/NCEPDEV/global/Helin.Wei/save/git/sync/hr2_land1/ufs-weather-model/modulefiles/ufs_hera.gnu.lua

So probably the environmental setting on my account is not fully right.

**Comment by SamuelTrahanNOAA** [comment]
Make sure you don't load any modules in your rc files. That can break build systems and workflow systems.

**Comment by HelinWei-NOAA** [comment]
BINGO. It is working after I removed all those module loads in my rc files. Thanks @SamuelTrahanNOAA @jiandewang 
> Make sure you don't load any modules in your rc files. That can break build systems and workflow systems.

**Comment by jiandewang** [comment]
@HelinWei-NOAA do you have to switch to bash ?

**Comment by HelinWei-NOAA** [comment]
@jiandewang I did switch to bash but I am not sure if it is necessary.

**Comment by SamuelTrahanNOAA** [comment]
The regression test system is supposed to clean out your environment via "module purge" before doing anything. Also, it isn't supposed to use "set -u" before sourcing the detect_machine.sh. Why would these problems happen only to you, but nobody else?

**Comment by jiandewang** [comment]
I swear I didn't touch my .rc file at least in the past year. I suspect something is being changed (library ?) in the past month and that is having negative effect (module purge is unable to clean up what it is suppose to do) to users whose default shell is tcsh. This is why @HelinWei-NOAA had the same issue yesterday. I have been using HERA for all my test in the past several years and had no any trouble until now.
Last night I tried to remove all module load in my .rc file and that worked for my run, no need to switch to bash.
Couple of puzzles:
(1) why it only attack gnu jobs ?
(2) why it works if I launch gnu job sequentially ?
(3) why it doesn't attack bash users ?

**Comment by jiandewang** [comment]
we had a similar situation on GAEA about half year ago. Before that time if your default shell is tcsh, what you need to do is 
module purge followed by switching to bash, that will work. But at the time when library had updating, this approach is no longer working. You have to have default shell to be bash.

**Comment by natalie-perlin** [comment]
@jiandewang - 
  To answer your questions (IMHO, suggesting possible reasons):
  1) You likely have intel or impi modules loaded in your .rc file, that are not unloaded before you attempt loading gnu or/and mpich that raise conflicts.
  2) When your job launched sequentially, module purge when you do in your current shell unloads intel and impi. When you submit several gnu compile jobs, a new user shell is launched at some point that reads your default .rc , and thus causes the same conflict.
  3) It is likely that bash users have something like` #!/usr/env bash ` that inherits environment from the previous shell instead of sourcing the default user shell

**Comment by SamuelTrahanNOAA** [comment]
I don't trust the rc files, so I always start a clean environment when I run rt.sh on Hera.

nohup /usr/bin/env - PATH=/bin:/usr/bin HOME=$HOME USER=$USER TERM=$TERM ACCNR=zrtrr /bin/bash --login --norc -c './rt.sh -r' > rt.log 2>&1 &

You can replace the `-r` with `-e` or whatever other options you want.

Explaining bit-by-bit:

1. `nohup ... > rt.log 2>&1 &` - this eliminates stdout, stdin, and stderr so bash won't connect to a terminal at all.
2. `/usr/bin/env -` - The `-` in this means env will wipe the environment, only retaining variables you explicitly give it.
3. `PATH=/bin:/usr/bin` - Minimal possible $PATH in UNIX.
4. `HOME=$HOME USER=$USER` - The other two mandatory UNIX variables.
5. `TERM=$TERM` - In case something needs to query the terminal type.
6. `/bin/bash` - explicitly start the system version of the bash shell to run this command
7. `--login --norc` - read the profile file but not the bashrc
9. `-c './rt.sh -r'` - bash should run the command "rt.sh -r"

**Comment by SamuelTrahanNOAA** [comment]
> It is likely that bash users have something like#!/usr/env bash that inherits environment from the previous shell instead of sourcing the default user shell

The rt.sh is a bash script. Specifically, bash 4.2 or newer. If you try to execute it with sh or tcsh, you'll get many syntax errors. It must use bash, not the user's default shell.

**Comment by natalie-perlin** [comment]
@jiandewang - 
Note that Gaea has some updates as to non-bash shells for UFS/EPIC needs. Please feel free test if possible and let us know if any issues are still found!

**Comment by jiandewang** [comment]
> @jiandewang - To answer your questions (IMHO, suggesting possible reasons):
> 
> 1. You likely have intel or impi modules loaded in your .rc file, that are not unloaded before you attempt loading gnu or/and mpich that raise conflicts.  -- @natalie-perlin you are right, I do have them in my .rc file
> 2. When your job launched sequentially, module purge when you do in your current shell unloads intel and impi. When you submit several gnu compile jobs, a new user shell is launched at some point that reads your default .rc , and thus causes the same conflict.  -- @natalie-perlin yes I can see clearly from log it complains on module conflict, but why intel jobs are all fine ?
> 3. It is likely that bash users have something like`#!/usr/env bash` that inherits environment from the previous shell instead of sourcing the default user shell

**Comment by jiandewang** [comment]
> @jiandewang - Note that Gaea has some updates as to non-bash shells for UFS/EPIC needs. Please feel free test if possible and let us know if any issues are still found!

@natalie-perlin I tried last night on GAEA but no luck. Couple of days ago I was being asked by another user whose shell is tcsh by default, he had the same issue. I understand it might be hard for you to do test as your fefault is bash.

**Comment by jiandewang** [comment]
> I don't trust the rc files, so I always start a clean environment when I run rt.sh on Hera.
> 
> nohup /usr/bin/env - PATH=/bin:/usr/bin HOME=$HOME USER=$USER TERM=$TERM ACCNR=zrtrr /bin/bash --login --norc -c './rt.sh -r' > rt.log 2>&1 &
> 
> You can replace the `-r` with `-e` or whatever other options you want.
> 
> Explaining bit-by-bit:
> 
> 1. `nohup ... > rt.log 2>&1 &` - this eliminates stdout, stdin, and stderr so bash won't connect to a terminal at all.
> 2. `/usr/bin/env -` - The `-` in this means env will wipe the environment, only retaining variables you explicitly give it.
> 3. `PATH=/bin:/usr/bin` - Minimal possible $PATH in UNIX.
> 4. `HOME=$HOME USER=$USER` - The other two mandatory UNIX variables.
> 5. `TERM=$TERM` - In case something needs to query the terminal type.
> 6. `/bin/bash` - explicitly start the system version of the bash shell to run this command
> 7. `--login --norc` - read the profile file but not the bashrc
> 8. `-c './rt.sh -r'` - bash should run the command "rt.sh -r"

@SamuelTrahanNOAA thanks for your detailed explanation

**Comment by DusanJovic-NOAA** [comment]
> @jkbk2004 I found this same issue earlier, posted to the uwm slack channel. I do not think it is related
> 
> [2:50 PM](https://noaa-emc.slack.com/archives/G01D4LV13M0/p1686768617306519) I was looking at the output from a compile and noticed this detect_machine.sh: line 108: PW_CSP: unbound variable
> 
> EDIT: This did not copy well from Slack. I posted this on June 14. There is no reason why Sam's PR would have created this issue.

There are few more unbound variables, for example, if you run:
```
$ ./rt.sh -n control_p8 intel > rt.log 2>&1
```
then look in rt.log:

```
++ eval 'echo ${3}'
+++ echo intel
+ OPTIND=4
++ eval 'echo ${4}'
./rt.sh: line 165: 4: unbound variable                                                       
+ [[ '' =~ ^-.* ]]
++ eval 'echo ${4}'
./rt.sh: line 165: 4: unbound variable
+ '[' -z ']'
+ [[ 2 != 2 ]]
+ SINGLE_NAME=control_p8
```

**Comment by SamuelTrahanNOAA** [comment]
Looking through the code, I see a few errors:

1. The module-setup.sh is using `set -eu`. The scripts that use module-setup will source it, so that `set -eu` propagates to the caller.
2. The module-setup.sh has `set -eu` turned on while sourcing system scripts, like /etc/profile and the lmod init script. There may be uninitialized variables or non-zero return values in those scripts that are normal and expected.
3. `Line 165: 4: unbound variable` comes from rt.sh's getopt loop checking if the next argument is an option argument when handling `-n`. It uses a truly bizarre method to do it: spawn a subshell looking for `$4`. It would be simpler to check the argument list length in `$#`. This error message is harmless, but it would get good to clean up this code.
4. In detect_machine.sh, the cloud stuff at the bottom assumes $MACHINE_ID has been set, when it may not have been. This will cause an error due to the `set -u`.
5. Likewise, it assumes $PW_CSP is set. Generally, that is not set.
6. `case $( echo $PW_CSP ) in` - Echoing this serves no purpose. Use `case "${PW_CSP:-empty}" in`

Apart from item 3, those are genuine errors that should be fixed. I doubt wel'll solve the hera or gaea problems this way, but maybe we'll get lucky on that front.

**Comment by DusanJovic-NOAA** [comment]
Regarding 4)

Code at the bottom of detect_machine.sh, the cloud stuff looks like:

```
case $(echo $PW_CSP) in

  aws) MACHINE_ID=aws ;; ### parallelworks aws
  google)  MACHINE_ID=gcp ;; ### parallelworks gcp
  azure)  MACHINE_ID=azure ;; ### parallelworks azure

esac
[[ ${MACHINE_ID} =~ "aws" || ${MACHINE_ID} =~ "gcp" || ${MACHINE_ID} =~ "azure" ]] && MACHINE_ID=noaacloud
```
If $PW_CSP is either aws or gcp or azure set MACHINE_ID to aws or gcp or azure, then immediately if MACHINE_ID is aws or gcp or azure set it to noaacloud. 

I do not understand why. Can MACHINE_ID be set directly to noaacloud?

**Comment by SamuelTrahanNOAA** [comment]
> If $PW_CSP is either aws or gcp or azure set MACHINE_ID to aws or gcp or azure, then immediately if MACHINE_ID is aws or gcp or azure set it to noaacloud.
> I do not understand why. Can MACHINE_ID be set directly to noaacloud?

I only see this being useful in one situation. If the MACHINE_ID was already set to one of those values before detect-machine.sh, then the `[[...]] && MACHINE_ID=noaacloud` would change it to noaacloud. Is someone relying on that? I don't know.

**Comment by DusanJovic-NOAA** [comment]
Regarding 1) and 2)

Both module-setup.sh and rt.sh (script that sources module-setup.sh), set `set -eu`

> > If $PW_CSP is either aws or gcp or azure set MACHINE_ID to aws or gcp or azure, then immediately if MACHINE_ID is aws or gcp or azure set it to noaacloud.
> > I do not understand why. Can MACHINE_ID be set directly to noaacloud?
> 
> I only see this being useful in one situation. If the MACHINE_ID was already set to one of those values before detect-machine.sh, then the `[[...]] && MACHINE_ID=noaacloud` would change it to noaacloud. Is someone relying on that? I don't know.

I did not write this code so I do not know for sure what the intentions are, but it looks to me that if PW_CSP is one of those three strings (aws, ....) then MACHINE_ID should be set to naoacloud regardless of the value it already has, if it has any value.

In any case setting MACHINE_ID to aws then immediately resetting it to noaacloud does not make sense to me.

The code for detecting 'cloud' machines should follow the same logic as with any other machine, except instead of looking at $hostname we look at $PW_CSP.

**Comment by natalie-perlin** [comment]
@jiandewang - 
Re: Gaea - could you elaborate on what steps do you take, and where the issue is? I've set up tcsh default on Gaea specifically to replicate such issues and to find solutions for non-bashers.

**Comment by jiandewang** [comment]
@natalie-perlin 
 I just made a fresh clone and tried. 
1. login to GAEA, default shell is tcsh
2. git clone https://github.com/ufs-community/ufs-weather-model
3. git submodule update --init --recursive
4. cd test
5. cp rt.conf rt.conf-JW
6. delete most of the jobs, only kept two for testing (see /lustre/f2/dev/ncep/Jiande.Wang/working/UWM-test-tcsh/ufs-weather-model/test/rt.conf-JW)
7. nohup ./rt.sh -e -a nggps_emc -l rt.conf-JW>output

job died right away with error:
_/etc/profile: line 78: PS1: unbound variable
++++ echo 'rt.sh finished'_

my 2nd try is switching to bash
1. login to GAEA
2. module purge
3. bash
4. repeat the tcsh step above
now I got error:
_Lmod has detected the following error: The load_any function failed because it
could not find any of the following modules : cmake/3.20.1 cmake_
see /lustre/f2/scratch/ncep/Jiande.Wang/FV3_RT/rt_3294/compile_s2swa_32bit_intel

**Comment by SamuelTrahanNOAA** [comment]
>  /etc/profile: line 78: PS1: unbound variable

This is caused by the "set -eu" in module-setup.sh

**Comment by natalie-perlin** [comment]
@jiandewang -
  Please note that you can **not** simply do "module purge" on Gaea. To get a clean environment and free from customized shell configuration, please run a script that purges the modules, initializes Lmod module environment, and loades the default modules, as following:
 `  source /lustre/f2/dev/role.epic/contrib/Lmod_init.sh`
   for tcsh usrs:
`   source /lustre/f2/dev/role.epic/contrib/Lmod_init.csh`

**Comment by natalie-perlin** [comment]
If you wish to switch to bash, do so before running Lmod_init.sh script:
```
bash
source /lustre/f2/dev/role.epic/contrib/Lmod_init.sh
```
![Gaea_bash_init](https://github.com/ufs-community/ufs-weather-model/assets/68030316/8d6ec93f-f344-47e0-864b-77a25ca0ffd0)
![Gaea_tcsh_init](https://github.com/ufs-community/ufs-weather-model/assets/68030316/d8b2cc15-2d7f-4389-b680-70aefec6b635)

**Comment by jiandewang** [comment]
@natalie-perlin I have asked SA to switch my default shell to bash, so we can close this.
