### ISSUE TITLE
Remove ip dependency?

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [ufs-community/ufs-weather-model#1830]
I am unable to find any usage of the ip library in UFS. Can the ip module be removed from ufs_common.lua?

**Comment by WenMeng-NOAA** [comment]
The ip module is used by UPP which is configured as a sub module of FV3 for in-line post.

**Comment by AlexanderRichert-NOAA** [comment]
I couldn't find it actually getting used anywhere in UPP, but I can take that up separately. Do you know offhand if anyone builds UFS with BUILD_WITH_GTG=ON? I don't know where/when that gets used in general.

**Comment by WenMeng-NOAA** [comment]
That's right. The ip module is used by gtg code which is in the NCAR private repository. The option "BUILD_WITH_GTG" is turned on for generating operational aviation products (wafs) and only authorized persons can check out that code.

**Comment by AlexanderRichert-NOAA** [comment]
Okay, thanks for the clarification.
