### ISSUE TITLE
Need to add repo check under FV3ATM to check CCPP, UPP, Stochastic Physics, and atm cubed sphere submodules

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#1839]

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA Do you think a modified repo check script would be accepted by fv3atm for their GitHub actions?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Do you think a modified repo check script would be accepted by fv3atm for their GitHub actions?

Which repo check script?

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA On FV3 side, we can try to add https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/ci/repo_check.sh. This script is linked to gitaction. We can follow up on EPIC side. Let me know.

**Comment by DusanJovic-NOAA** [comment]
Okay. I'm confused why this issue is open in ufs-weather-model if you want to add a script to the fv3atm repository.

**Comment by BrianCurtis-NOAA** [comment]
> Okay. I'm confused why this issue is open in ufs-weather-model if you want to add a script to the fv3atm repository.

I agree. I was one step ahead of you in finding out if that's something they'd want in fv3atm or not.

**Comment by DeniseWorthen** [comment]
Can we close this in UWM repo if the feature is (possibly) being added to FV3?
