### ISSUE TITLE
KPP option for MOM6 in UFS HAFS

### ISSUE THREAD

**Issue by hyunsookkim-NOAA** [ufs-community/ufs-weather-model#1840]
Running errors with KPP mixing in place of the default ePBL mixing in the ocean model MOM6 in UFS-weather-model.  The errors seem related to writing ocean state variables (see below for example). As test, the reported variable is commented out in "diag_table.tmp" and errors occur next variable.

_NOTE from PE     0: Tracer cld_amt_left not in input file
FATAL from PE     0: NetCDF: HDF error: netcdf_write_data_4d: file:ocn_2020_08_25_03.nc variable: uo
FATAL from PE     0: NetCDF: HDF error: netcdf_write_data_4d: file:ocn_2020_08_25_03.nc variable: uo
Image              PC                Routine            Line        Source
hafs_forecast.x    0000000005188747  Unknown               Unknown  Unknown
hafs_forecast.x    0000000004D518D9  mpp_mod_mp_mpp_er          72  mpp_util_mpi.inc
hafs_forecast.x    0000000004C28E51  fms_io_utils_mod_         190  fms_io_utils.F90
hafs_forecast.x    0000000004C79822  netcdf_io_mod_mp_         368  netcdf_io.F90
hafs_forecast.x    0000000004CA3723  netcdf_io_mod_mp_         393  netcdf_write_data.inc
hafs_forecast.x    0000000004C4AC4D  fms_netcdf_domain         923  domain_write.inc
hafs_forecast.x    00000000050F99A4  diag_output_mod_m         841  diag_output.F90
hafs_forecast.x    0000000004B8786A  diag_util_mod_mp_        2218  diag_util.F90
hafs_forecast.x    0000000004B6E956  diag_manager_mod_        3414  diag_manager.F90
hafs_forecast.x    0000000004B567EB  diag_manager_mod_        1850  diag_manager.F90
hafs_forecast.x    000000000411AEE6  mom_diag_manager_         348  MOM_diag_manager_infra.F90
hafs_forecast.x    0000000003B713C2  mom_diag_mediator        1784  MOM_diag_mediator.F90
hafs_forecast.x    0000000003B6EDF9  mom_diag_mediator        1595  MOM_diag_mediator.F90_

**Comment by DeniseWorthen** [comment]
@jiandewang Have you looked into this issue?

**Comment by hyunsookkim-NOAA** [comment]
@DeniseWorthen @jiandewang @binli2337 It requires different diag-table for KPP. Ask Bin Li for the template.

**Comment by DeniseWorthen** [comment]
@hyunsookkim-NOAA So do you want to implement this in UWM for some test case?

**Comment by DeniseWorthen** [comment]
If you have what you need (the corrected diag_table) and have no plan to create an optional test using this alternate diag_table, can we close this issue?

**Comment by hyunsookkim-NOAA** [comment]
@DeniseWorthen It will be useful to have it for both the global and regional applicatoin.  As for HAFS, it has been tested and will be implemented for the version 2.  But, as for the global, I defer Jiande.

**Comment by DeniseWorthen** [comment]
Thanks @hyunsookkim-NOAA ! 

@jiandewang Will this be used as an option in the global configurations?

**Comment by jiandewang** [comment]
> Thanks @hyunsookkim-NOAA !
> 
> @jiandewang Will this be used as an option in the global configurations?

no there is no plan for this in global S2S
