### ISSUE TITLE
baseline directory does not exist on Cheyenne

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#1843]
## Description
The following baseline directory does not exist `/glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20230720` on Cheyenne. 

### To Reproduce:
What compilers/machines are you seeing this with? Cheyenne / INTEL
Give explicit steps to reproduce the behavior.
1. git clone --recursive https://github.com/ufs-community/ufs-weather-model.git
2. cd ufs-weather-model/tests
3. ./rt.sh -k -n cpld_control_p8 intel
4. check logs/log_cheyenne/rt_001_cpld_control_p8_intel.log 

## Additional context
N/A

## Output
```
baseline dir = /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20230720/cpld_control_p8_intel
working dir  = /glade/scratch/turuncu/FV3_RT/rt_53753/cpld_control_p8_intel
Checking test 001 cpld_control_p8_intel results ....
 Comparing sfcf021.tile1.nc ............MISSING baseline
 Comparing sfcf021.tile2.nc ............MISSING baseline
 Comparing sfcf021.tile3.nc ............MISSING baseline
 Comparing sfcf021.tile4.nc ............MISSING baseline
```

**Comment by DeniseWorthen** [comment]
Hi @uturuncoglu. We had an issue with running tests on Cheyenne for a while. I'm not sure when the next baselines will be created on Cheyenne, but maybe today or tomorrow.

**Comment by uturuncoglu** [comment]
@DeniseWorthen Thanks. It is good to know. I am trying to run full regression test in there to finalize testing of my upcoming component land PR. So, it would be nice to have the baseline. I could test it on Orion too if it will take time.

**Comment by DeniseWorthen** [comment]
@uturuncoglu Thanks. I also want to be sure you are aware of #1807 for the signs of export fields. This PR will ensure that all fields exported to CMEPS have a consistent positive-down definition. I'm not sure whether you will rely on these fv3atm export fields or not.

**Comment by uturuncoglu** [comment]
@DeniseWorthen Thanks for heads up. I did not do anything special about the signs at least for the component land. Once this is in, I could test it in my case.

**Comment by DeniseWorthen** [comment]
I'm going to close this issue since Cheyenne is w/in 10days of EOL.
