### ISSUE TITLE
Adding /contrib-epic path in spack stack module files provided for PW-AWS

### ISSUE THREAD

**Issue by sadeghitabas** [ufs-community/ufs-weather-model#1855]
## Description

We cannot load spack-stack modules maintained by epic team in PW-AWS as the paths for modules would be different for projects other than EPIC.  The epic `/contrib` directory is shared as `/contrib-epic` for other projects. Please add the path `/contrib-epic` as well in the spack-stack modulefiles so it would be usable in projects other than EPIC.

**Comment by zach1221** [comment]
Thanks for reporting this, Sadegh. 
Copying @natalie-perlin here as well, so AUS is aware.

**Comment by zach1221** [comment]
@SadeghTabas-NOAA my understanding is this has been resolved on AWS, correct? Also, I have updated the input-data on AWS, and am almost finished updating the baselines as well.

**Comment by sadeghitabas** [comment]
> @SadeghTabas-NOAA my understanding is this has been resolved on AWS, correct? Also, I have updated the input-data on AWS, and am almost finished updating the baselines as well.

I've this issue on GCP, AWS was working fine. I dont have access to aws anymore, I need the epic-contrib directory on GCP for spackstack. Thanks

**Comment by zach1221** [comment]
> > @SadeghTabas-NOAA my understanding is this has been resolved on AWS, correct? Also, I have updated the input-data on AWS, and am almost finished updating the baselines as well.
> 
> I've this issue on GCP, AWS was working fine. I dont have access to aws anymore, I need the epic-contrib directory on GCP for spackstack. Thanks

Ok, I'll close this issue then since there is already a ticket open for GCP with [2088](https://github.com/ufs-community/ufs-weather-model/issues/2088)

**Comment by natalie-perlin** [comment]
@zach1221 , @SadeghTabas-NOAA - 
Please note that the spack-stack/1.5.1 has been installed and/or corrected on all NOAA Cloud platforms, except the path needs to be adjusted. Currently it is listed in ufs_noaacloud.intel.lua as /contrib/EPIC/spack-stack/spack-stack-1.5.0/, but it needs to be 
/contrib/spack-stack/spack-stack-1.5.1/ , i.e. the full corrected line needs to be changed to 
`prepend_path("MODULEPATH", "/contrib/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core")`
for AWS, GCP and Azure. 
@jkbk2004 will help to include this change into one of the subsequent PRs

**Comment by zach1221** [comment]
@natalie-perlin I entered the new spack path. Should I be updating the module versions of any of the below? Lmod could not locate them on AWS.
"fms/2023.02.01" "gftl-shared/1.6.1" "mapl/2.40.3-esmf-8.5.0" "esmf/8.5.0"
