### ISSUE TITLE
create coupled IAU RT test case 

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1856]
## Description
The GFSv17 will run with IAU in the coupled configuration. A test case need to set up with IAU turned on for both atmosphere and ocean to ensure that IAU and all the component outputs are working properly.

## Solution
1) Create C384 ICs for the coupled case with IAU increments for atmosphere and ocean (dummy ocean increments, see https://github.com/NOAA-EMC/global-workflow/issues/1776).
2) Create test case with IAU turned on for fv3atm and mom6. 

## Related to
- global workflow issue https://github.com/NOAA-EMC/global-workflow/issues/1776

**Comment by junwang-noaa** [comment]
@guillaumevernieres do you have a 1 degree ocn increment file? Thanks

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres do you have a 1 degree ocn increment file? Thanks

@junwang-noaa , I don't but we could prepare one if you remind me next week.

**Comment by junwang-noaa** [comment]
FMS updates are required to have averaged fields starting from different forecast time.

**Comment by junwang-noaa** [comment]
CICE requires some code updates.

**Comment by junwang-noaa** [comment]
@guillaumevernieres would you please create an 1 degree ocn IAU increment file? Thanks

**Comment by pjpegion** [comment]
@junwang-noaa you can download one from our AWS bucket:

https://noaa-ufs-gefsv13replay-pds.s3.amazonaws.com/index.html#1deg/
click on a year and month, and the 12z cycles have a mom6_increment.nc file.

**Comment by junwang-noaa** [comment]
@pjpegion Thanks for the info. May I ask if you have 1/4 degree pgb files from gefsv13 replay?

**Comment by guillaumevernieres** [comment]
> @junwang-noaa you can download one from our AWS bucket:
> 
> https://noaa-ufs-gefsv13replay-pds.s3.amazonaws.com/index.html#1deg/ click on a year and month, and the 12z cycles have a mom6_increment.nc file.

thanks @pjpegion

**Comment by pjpegion** [comment]
yes, they are in the 06z directories (e.g. https://noaa-ufs-gefsv13replay-pds.s3.amazonaws.com/index.html#1997/04/1997040106/)

**Comment by junwang-noaa** [comment]
@pjpegion Thanks for the information. Is that correct that 

1) the 1/4 degree pgb files only available for 06z, not other cycles?
2) There is no 6 hourly precipitation available in all the cycles? I only see GFSPRS.GrbF00 and GFSPRS.GrbF03 from all the runs.
