### ISSUE TITLE
Need to re-establish UFS-WM baselines on Cheyenne

### ISSUE THREAD

**Issue by zach1221** [ufs-community/ufs-weather-model#1866]
## Description

Currently the Baselines on Cheyenne are not entirely up to date with UFS-Community:Develop. Mostly due to the below qr tests failing to match against baselines. 
![image](https://github.com/ufs-community/ufs-weather-model/assets/99902696/f314f906-2d51-4bfd-8d78-bce5dc402992)

### To Reproduce:

1. log into Cheyenne
2. Run ./rt.sh -a <account> -c -e -l rt.conf to create baselines
3. Run  ./rt.sh -a <account> -e -l rt.conf to match against baselines

## Additional context

Seems to have started after PR#1812, and could be associated with issue #1832.

**Comment by zach1221** [comment]
PR# [1853](https://github.com/ufs-community/ufs-weather-model/pull/1853) may resolve this issue and allow us to re-establish baselines completely on Cheyenne.

**Comment by DeniseWorthen** [comment]
I'm going to close since Cheyenne is w/in 10days of EOL.
