### ISSUE TITLE
Enable lossy compression for regional grids

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [ufs-community/ufs-weather-model#1868]
## Description

Regional domains still cannot run with lossy compression, which surprised Jun Wang (who asked me to open this issue about it).  There still is a check within module_wrt_grid_comp.F90 that terminates regional domains with nbits .ne. 0.  

`20230815 204334.539 ERROR            PET3847 wrt_run: lossy compression is not supported for regional grids
`

## Solution

Ideally would like to take advantage of the full range of compression options if possible for the RRFS application.  We've seen decent compression with the lossless option, but given the high I/O load within the system, the more compression we can achieve, the better.

## Alternatives

We will live with the existing functionality if it is our only option.

## Related to

Suspect it will be related to an fv3atm issue eventually....

**Comment by DeniseWorthen** [comment]
Can this issue be closed after merging #1929?

**Comment by MatthewPyle-NOAA** [comment]
Yes, have confirmed that can use lossy compression with regional grids now, so will close.
