### ISSUE TITLE
Coupler restarts appear to take a very long time to write

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1873]
## Description
In preparation for HR2, scout runs have been conducted using ufs-weather-model hash [4d05445](https://github.com/ufs-community/ufs-weather-model/commit/4d05445e88d0481de8190615679888b063bac7ad).   The runs are taking significantly longer than anticipated and one potential cause seems to be that the coupler restart files seem to be taking a long time to write: 

**Atm (one file of many):** 
-rw-r--r-- 1 Jessica.Meixner climate 646917167 Aug 16 21:37 20191203.120000.sfc_data.tile1.nc
-rw-r--r-- 1 Jessica.Meixner climate 646917167 Aug 16 23:13 20191204.000000.sfc_data.tile1.nc
-rw-r--r-- 1 Jessica.Meixner climate 646917167 Aug 17 00:47 20191204.120000.sfc_data.tile1.nc
lrwxrwxrwx 1 Jessica.Meixner climate       137 Aug 17 08:24 20191205.000000.sfc_data.tile1.nc 

**Ocn**: 
-rw-r--r-- 1 Jessica.Meixner climate 3732530120 Aug 16 21:34 20191203.120000.MOM.res.nc
-rw-r--r-- 1 Jessica.Meixner climate 3769865536 Aug 16 21:34 20191203.120000.MOM.res_1.nc
-rw-r--r-- 1 Jessica.Meixner climate 3794748728 Aug 16 21:35 20191203.120000.MOM.res_2.nc
-rw-r--r-- 1 Jessica.Meixner climate  970483196 Aug 16 21:35 20191203.120000.MOM.res_3.nc
-rw-r--r-- 1 Jessica.Meixner climate 3732530120 Aug 16 23:10 20191204.000000.MOM.res.nc
-rw-r--r-- 1 Jessica.Meixner climate 3769865536 Aug 16 23:10 20191204.000000.MOM.res_1.nc
-rw-r--r-- 1 Jessica.Meixner climate 3794748728 Aug 16 23:11 20191204.000000.MOM.res_2.nc
-rw-r--r-- 1 Jessica.Meixner climate  970483196 Aug 16 23:11 20191204.000000.MOM.res_3.nc
-rw-r--r-- 1 Jessica.Meixner climate 3732530120 Aug 17 00:44 20191204.120000.MOM.res.nc
-rw-r--r-- 1 Jessica.Meixner climate 3769865536 Aug 17 00:45 20191204.120000.MOM.res_1.nc
-rw-r--r-- 1 Jessica.Meixner climate 3794748728 Aug 17 00:45 20191204.120000.MOM.res_2.nc
-rw-r--r-- 1 Jessica.Meixner climate  970483196 Aug 17 00:45 20191204.120000.MOM.res_3.nc
-rw-r--r-- 1 Jessica.Meixner climate 3732530120 Aug 17 02:19 20191205.000000.MOM.res.nc
-rw-r--r-- 1 Jessica.Meixner climate 3769865536 Aug 17 02:19 20191205.000000.MOM.res_1.nc
-rw-r--r-- 1 Jessica.Meixner climate 3794748728 Aug 17 02:19 20191205.000000.MOM.res_2.nc
-rw-r--r-- 1 Jessica.Meixner climate  970483196 Aug 17 02:19 20191205.000000.MOM.res_3.nc

**Ice**: 

-rw-r--r-- 1 Jessica.Meixner climate 1978216948 Aug 16 21:34 20191203.120000.cice_model.res.nc
-rw-r--r-- 1 Jessica.Meixner climate 1978216948 Aug 16 23:10 20191204.000000.cice_model.res.nc
-rw-r--r-- 1 Jessica.Meixner climate 1978216948 Aug 17 00:44 20191204.120000.cice_model.res.nc
-rw-r--r-- 1 Jessica.Meixner climate 1978216948 Aug 17 02:19 20191205.000000.cice_model.res.nc

**Wave (note in rundir not com):** 
-rw-r--r-- 1 Jessica.Meixner climate 6989666400 Aug 16 21:25 20191203.000000.restart.ww3
-rw-r--r-- 1 Jessica.Meixner climate 6989666400 Aug 16 21:35 20191203.120000.restart.ww3
-rw-r--r-- 1 Jessica.Meixner climate 6989666400 Aug 16 23:10 20191204.000000.restart.ww3
-rw-r--r-- 1 Jessica.Meixner climate 6989666400 Aug 17 00:45 20191204.120000.restart.ww3
-rw-r--r-- 1 Jessica.Meixner climate 6989666400 Aug 17 02:19 20191205.000000.restart.ww3

**Cpl**: 
-rw-r--r-- 1 Jessica.Meixner climate 3134707996 Aug 16 23:01 ufs.cpld.cpl.r.2019-12-03-43200.nc
-rw-r--r-- 1 Jessica.Meixner climate 3134707996 Aug 17 00:36 ufs.cpld.cpl.r.2019-12-04-00000.nc
-rw-r--r-- 1 Jessica.Meixner climate 3134707996 Aug 17 02:10 ufs.cpld.cpl.r.2019-12-04-43200.nc
-rw-r--r-- 1 Jessica.Meixner climate 2736564908 Aug 17 03:19 ufs.cpld.cpl.r.2019-12-05-00000.nc

The time stamps on the coupler file appear to be significantly delayed compared to the other restart files. 

This could be a bad assumption, but I'm curious if others have seen this or suspect other issues.  I've seen this on both hera and orion.   The coupler history files are 3.0GB and the runs die due to clock time. 
 

### To Reproduce:
These runs were from the global-workflow branch: https://github.com/jessicameixner-noaa/global-workflow/tree/HR2updates 
C768 case for S2SW for IC date 2019120300

## Additional context
 This is not the latest develop of ufs-weather-model, but is the hash of the ufs-weather-model currently in the develop of the global-workflow. 

## Output
**Run log file**: /scratch1/NCEPDEV/climate/Jessica.Meixner/HR2/scoutrunhr2/COMROOT/scoutrunhr2/logs/2019120300/gfsfcst.log.0
**Run directory**: /scratch1/NCEPDEV/climate/Jessica.Meixner/HR2/scoutrunhr2/RUNDIRS/scoutrunhr2/fcst.264492
**COMDIR**: /scratch1/NCEPDEV/climate/Jessica.Meixner/HR2/scoutrunhr2/COMROOT/scoutrunhr2/gfs.20191203/00

**Output of gfsv17 rt test** (that should theoretically match except for resolution, there are differences that have been noted, but nothing that I think would be the cause of this issue): /scratch1/NCEPDEV/stmp2/Jessica.Meixner/FV3_RT/ufs-20230724_rt_201723/cpld_control_gfsv17_intel

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA There was a change at hash [https://github.com/ufs-community/ufs-weather-model/commit/251ec56df56d987fe3a2ba900d9a22b95e2058de](https://github.com/ufs-community/ufs-weather-model/commit/251ec56df56d987fe3a2ba900d9a22b95e2058de) to add a configuration variable to the mediator attributes:

https://github.com/ufs-community/ufs-weather-model/blob/bb525bb7812f56a4cf1cef35fa6e7853440626dc/tests/parm/nems.configure.cpld.IN#L127

This was required in because the default PIO settings in  CMEPS were changed. To return to what had been the previous default setting, set ``pio_rearranger = box``

I did see a big impact on runtime when I was first testing the PR prior to reverting to the previous default.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen Thank you so much for pointing this out!! I will rerun a test with this added input and report back.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen  Thank you again - this worked and the restart writing times seem normal (and not 40+ min).  I'll make sure this gets updated in the workflow.

**Comment by DeniseWorthen** [comment]
Can we close this? I happened to see it looking for something else.
