### ISSUE TITLE
Update to ESMF 8.5.0?

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#1875]
## Description
Same as for https://github.com/ufs-community/ufs-weather-model/issues/1874, should the next spack-stack release 1.5.0 (release date planned Sep 8 +/-) use esmf 8.5.0 as default, or keep the current 8.4.2? And if 8.5.0, which version of mapl?

## Solution
Install correct esmf and mapl version for ufs-weather-model in spack-stack-1.5.0.

## Alternatives
n/a

## Related to
n/a

**Comment by climbfuji** [comment]
Note. Just learned that mapl@2.40 requires esmf@8.5.0 or newer

**Comment by junwang-noaa** [comment]
@climbfuji  I actually created an issue #1854 on testing ESMF 850 in ufs weather model, would you like to look at the discussion there? Thanks

**Comment by climbfuji** [comment]
This is a duplicate of https://github.com/ufs-community/ufs-weather-model/issues/1854
