### ISSUE TITLE
running rrfs_conus13km_hrrr_warm case longer?

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#1878]
## Description
I am trying to run `rrfs_conus13km_hrrr_warm` test for more than 3-hours but getting netcdf error. The reason might be the input file that has no data more than 3-hours. Is there any way to have an input file (probably for LBC) for longer simulation like 1-day etc? If you give me more information to generate new one that would be also helpful. Since I am developing new capability in FV3 side, it would be nice for me to test the case with longer simulation.

### To Reproduce:
What compilers/machines are you seeing this with? Cheyenne / Intel
Give explicit steps to reproduce the behavior.
1. checkout `ufs-weather-model`
2. run `rrfs_conus13km_hrrr_warm` by modifying `nhours_fcst` from 3 to 24.

## Additional context
N/A

## Output
**Screenshots**
N/A

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

Standard out has following error:
```
23:  check netcdf status=           2
23:
23:FATAL from PE    23:  NetCDF error No such file or directory
23:
```
and part of the trace:
```
59:Image              PC                Routine            Line        Source
59:fv3.exe            00000000042144A7  Unknown               Unknown  Unknown
59:fv3.exe            0000000002AF41B9  mpp_mod_mp_mpp_er          72  mpp_util_mpi.inc
59:fv3.exe            0000000001FBBD75  fv_regional_mod_m        3412  fv_regional_bc.F90
59:fv3.exe            0000000001F8ABFB  fv_regional_mod_m        1734  fv_regional_bc.F90
59:fv3.exe            0000000001FB0AE7  fv_regional_mod_m        1592  fv_regional_bc.F90
59:fv3.exe            0000000001DF2D1A  atmosphere_mod_mp         673  atmosphere.F90
59:fv3.exe            0000000001C75068  atmos_model_mod_m         854  atmos_model.F90
59:fv3.exe            0000000001B26787  module_fcst_grid_        1348  module_fcst_grid_comp.F90
```
Standard out has following,
```
0:
0:FATAL from PE     0:  NetCDF error No such file or directory
0:
```

**Comment by uturuncoglu** [comment]
I clone ufs-utils to create new initial condition for 2023-07-05 but I could not find any detailed information to use that tool. The SRW doc only mention about the tool without how to use it to create initial + boundary conditions. https://ufs-srweather-app.readthedocs.io/en/release-public-v2/

**Comment by RatkoVasic-NOAA** [comment]
Ufuk, for quick references, I usually use Chan-Hoo's guide. I think in his guide, section 6 you can get answers how to create new BCs: https://drive.google.com/file/d/1zyCvHmuL_LWx0Yto6B1GXF04m-n6Kbs2/view

**Comment by uturuncoglu** [comment]
@RatkoVasic-NOAA Thanks. I'll check it. It seem it has lots of information that I need. Is there any way to know which data set is used to create ICBC for `rrfs_conus13km_hrrr_warm`. So, I could create a new data set in a constant way with this configuration. Thanks again. Best

**Comment by uturuncoglu** [comment]
@RatkoVasic-NOAA BTW, i am not sure which ufs util is referred in this document but I don't have those scriptsin my case. For example, the document mentioning about `exregional_make_ics.sh` script but I have only `exemcsfc_global_sfc_prep.sh` under scripts directory. Any idea?

**Comment by uturuncoglu** [comment]
@RatkoVasic-NOAA Sorry, I think I found it under https://github.com/ufs-community/ufs-srweather-app. Thanks again for your help.

**Comment by uturuncoglu** [comment]
The workflow fails since it could not find necessary files. There is a script under SRW app use directory like retrieve_data.py but I am not sure how this can be used. Running like `./retrieve_data.py --file_set fcst --data_stores aws --output_path test --ics_or_lbcs LBCS --cycle_date 2023070600 --config config.yaml --data_type netcdf` not working. Also there is no any information in the script about valid values of `--data_type`. I tried to download the data manually but I could not find one for 2023-07-06 00:00:00 since https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/v16.3/ stores only last 10 days. Is there any other archive that I could download the data? Or maybe there is another way in the workflow that I don't know.

**Comment by uturuncoglu** [comment]
Okay I it seems that data is available in AWS but the issue is that the web access restricted from compute nodes on Cheyenne and the data download fails. So, it seems that rater than running rococo to submit data retrieval jobs to job scheduler, it is better to run `./run_get_ics.sh` and `./run_get_lbcs.sh` manually.

**Comment by uturuncoglu** [comment]
@RatkoVasic-NOAA Thanks for all your help. I could able to run SRW for desired dates using its workflow. Cheyenne is not working since it tries to download data files but compute nodes do not allow to access internet. Orion is fine and submits data retrieval jobs to specific ddn nodes that could access to AWS to get the data. Anyway, thanks again. I am closing this ticket.
