### ISSUE TITLE
Update module files to SCOTCH v7.0.4 on RDHPCS

### ISSUE THREAD

**Issue by MatthewMasarik-NOAA** [ufs-community/ufs-weather-model#1885]
## Description
Module files for RDHPCS machines should be updated to newest SCOTCH version, v7.0.4.

## Solution
Modify SCOTCH version in module files for RDHPCS machines from v7.0.3 to v7.0.4.

## Alternatives
The SCOTCH version could be kept 'as is' at v7.0.3.  This would mean bugfixes for scalability and compiling with openmpi would _not_ be available.

## Related to
- depends on jcsda/spack-stack/issues/748

**Comment by natalie-perlin** [comment]
Installing SCOTCH v7.0.4 is planned as a part of spack-stack/1.5.0, 
@climbfuji could likely confirm.

**Comment by climbfuji** [comment]
Yes, confirmed.

**Comment by MatthewMasarik-NOAA** [comment]
@natalie-perlin @climbfuji  Great!  Thank you for that update.

**Comment by MatthewMasarik-NOAA** [comment]
Closing as completed by #1920.

**Comment by MatthewMasarik-NOAA** [comment]
Closed.
