### ISSUE TITLE
Create HR2 Tag

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1886]
## Description
Updates to the workflow have been finalized and merged ( https://github.com/NOAA-EMC/global-workflow/commit/63270daf00ddb6c9b3cb546bcb2e4532d181def7).  Several scout runs have been conducted and analyzed by @LydiaStefanova-NOAA  to give us confidence in making this tag. 

We're ready to create an HR2 tag for the ufs-weather-model commit:  https://github.com/ufs-community/ufs-weather-model/commit/4d05445e88d0481de8190615679888b063bac7ad

## Solution
Tag for HR2

## Alternatives
Do not tag and reference the hash from the commit. 

## Related to
n/a

**Comment by DeniseWorthen** [comment]
I've created tag [GFSv17.HR2](https://github.com/ufs-community/ufs-weather-model/tree/GFSv17.HR2). Please let me know if there are any issues.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @DeniseWorthen!
