### ISSUE TITLE
Updates to C3 and SAS cumulus convection schemes

### ISSUE THREAD

**Issue by lisa-bengtsson** [ufs-community/ufs-weather-model#1899]
## Description
Bring out tuning parameters betadcu and betascu from prognostic closure routines as optimal settings depend on physics suite and application. Some bug-fixes in C3 for when progsigma=T.

**Comment by natalie-perlin** [comment]
@jkbk2004 - 
Code improvement requested, assigning to a Code Management team

**Comment by DeniseWorthen** [comment]
Closed by #1941
