### ISSUE TITLE
Consistent field names between CMEPS, MOM6 and CICE6

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#1905]
## Description

Currently there is a mix of field names being used in MOM6 and CICE6, meaning some field names are specified CESM-style (F = flux, S = state) and some using descriptions (mean_xxx_flux).  This was the result of unifying both the MOM6 and CICE6 caps at the same time that UFS was transitioning from the NEMS mediator to the CMEPS mediator. The CMEPS mediator in UFS uses only CESM-style field names.

It is clearer from a user perspective and for developing documentation if the naming convention is consistent. It also avoids the ambiguity around what "mean" means (spatial, temporal, both?). The "averaging" context can be provided in the description entry in the field dictionary if required.

## Solution

Coupling field names in the MOM6 and CIE6 caps need to be changed to the CESM-style (S=state, F=flux) field names. 
Note that for WW3, the only non CESM style field name will be resolved in NOAA-EMC/WW3/pull/1034

## Related to

- #1800

**Comment by natalie-perlin** [comment]
@jkbk2004 - 
Code modification required to address this suggested enhancement, assigning to a Code Management team

**Comment by junwang-noaa** [comment]
@natalie-perlin may I ask why this is assigned to code management team?

**Comment by jkbk2004** [comment]
@natalie-perlin Please, don't assign randomly.
