### ISSUE TITLE
Update stochastic physics to create a EP5 tag

### ISSUE THREAD

**Issue by bingfu-NOAA** [ufs-community/ufs-weather-model#1908]

**Comment by bingfu-NOAA** [comment]
A stochastic physics PR will be submitted to update stochastic physics in order to create a EP5 tag.

**Comment by pjpegion** [comment]
@bingfu-NOAA This is not correct.  We need to merge in the stochastic physics PR, then the ufs-weather-model will point to the top of the noaa-psl stochastic physics.

**Comment by pjpegion** [comment]
There is a [PR](https://github.com/NOAA-PSL/stochastic_physics/pull/68)for the stochastic physics to add additional tapering of SPPT perturbations in the lower layer of the model. This update will not affect the regression test baselines.
