### ISSUE TITLE
Control_wam_debug problems on Hercules

### ISSUE THREAD

**Issue by zach1221** [ufs-community/ufs-weather-model#1909]
## Description

Regression test case control_wam_debug may need code change for running on Hercules and should be disabled on the platform for the time being. 

### To Reproduce:

1. log into Hercules and cd to workspace
2. git clone -b feature/add_hercules https://github.com/ulmononian/ufs-weather-model
3. cd ufs-weather-model
4. git submodule update --init --recursive
5. cd test/
6. ./rt.sh -a nems -c -n control_wam_debug intel

## Additional context

Code changes possibly needed to the below.
atmos_cubed_sphere/model/nh_utils.F90

#ifdef MOIST_CAPPA
       dz2(i,km) = -dm2(i,km)*rgas*pt2(i,km)*exp((cp2(i,km)-1.)*log(max(p_fac*pm2(i,km),p1(i)+pm2(i,km))))
#else

**Comment by ulmononian** [comment]
just to note that this test does work w/ intel, e.g.: `/work2/noaa/stmp/cbook/stmp/cbook/FV3_RT/REGRESSION_TEST/control_wam_debug_intel`.

**Comment by DeniseWorthen** [comment]
@zach1221 I'm not sure why #PR1910 is connected to this. Is this issue still open?

**Comment by zach1221** [comment]
> @zach1221 I'm not sure why #PR1910 is connected to this. Is this issue still open?

@DeniseWorthen no I'll close. Thank you.
