### ISSUE TITLE
A bug was found with the MERRA2 coupled Thompson microphysics

### ISSUE THREAD

**Issue by AnningCheng-NOAA** [ufs-community/ufs-weather-model#1914]
## Output

![prs_liq_h2](https://github.com/ufs-community/ufs-weather-model/assets/48297505/740a12b6-6cf0-41cb-9c8f-346b76b715bc)

![prs_liq_96](https://github.com/ufs-community/ufs-weather-model/assets/48297505/06205356-91c5-462f-9f38-9e058d5d6d68)
![track_vmax_bias](https://github.com/ufs-community/ufs-weather-model/assets/48297505/68dcb81b-73f6-4d6c-96b9-dac130928382)

**Comment by DeniseWorthen** [comment]
@AnningCheng-NOAA Is this actually a bug in FV3 and/or CCPP?

**Comment by AnningCheng-NOAA** [comment]
No. It is a bug when setting mraeroso=.True. in coupling aerosol with Thompson microphysics.  I am Preparing PRs for this issue.

**Comment by DeniseWorthen** [comment]
I see, thanks.
