### ISSUE TITLE
Unavailable datasets in NOMADS needed to run GEFS

### ISSUE THREAD

**Issue by detached-head** [ufs-community/ufs-weather-model#1919]
I'm trying to run [GEFS](https://github.com/NOAA-EMC/GEFS) - which I understand is based on the UFS system. The link_gefs.sh script requests the following datasets:

/scratch2/NCEPDEV/ensemble/noscrub/common/FIX/gefs/fix_nco_gefsv12.3

Which isn't available on the FTP server and is therefore a blocker for running GEFS. I've also raised the issue here:
- https://github.com/NOAA-EMC/GEFS/issues/129

Would it be possible to upload this dataset to the FTP server?

Thanks in advance 😄

**Comment by jkbk2004** [comment]
@detached-head Since it's pretty much GEFS data link issue. Can you create a git issue to https://github.com/NOAA-EMC/GEFS ? So GEFS code managers can follow on.

**Comment by jkbk2004** [comment]
@detached-head Oh! you created one in GEFS repo already.

**Comment by jkbk2004** [comment]
@detached-head I see a contact email richard.wobus@noaa.gov in GEFS repo. Do you think it might be worth to send an email to a GEFS code manager ?

**Comment by detached-head** [comment]
@jkbk2004 thanks for your help. I realise that I've been conflating NOMADS and FTP. I've updated the issue here, and will email Richard, thanks for sending that contact.

**Comment by jkbk2004** [comment]
I think xianwu.xue@noaa.gov is another main code manager on GEFS repo. I sent an email to him about the issue. I will keep you posted once he reply.

**Comment by jkbk2004** [comment]
Xianwu left EMC and confirms to contact
```
Bing Fu - NOAA Federal <Bing.Fu@noaa.gov>,
Eric Sinsky - NOAA Affiliate <eric.sinsky@noaa.gov>
```
