### ISSUE TITLE
control_p8_gnu test fails on Hera

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#1939]
`control_p8_gnu` test fails on Hera.

Can somebody try to reproduce:

```
./rt.sh -n control_p8 gnu
```

**Comment by BrianCurtis-NOAA** [comment]
I get the error on compile:
```
CMake Error at CMakeLists.txt:165 (find_package):
  By not providing "Findbacio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "bacio", but
  CMake did not find one.

  Could not find a package configuration file provided by "bacio" (requested
  version 2.4.0) with any of the following names:

    bacioConfig.cmake
    bacio-config.cmake

  Add the installation prefix of "bacio" to CMAKE_PREFIX_PATH or set
  "bacio_DIR" to a directory containing one of the above files.  If "bacio"
  provides a separate development package or SDK, be sure it has been
  installed.
```
@jkbk2004 is there a problem with bacio on the gnu stack?

**Comment by grantfirl** [comment]
I also just got a failure for the control_p8_gnu test. It compiled fine and seemed to run OK, but failed in comparing results. This test should definitely not have failed with the changes that I was testing (in the CCPP framework), and it was the only test that failed. Is there a bad baseline?

**Comment by zach1221** [comment]
I'll take a look.

**Comment by DusanJovic-NOAA** [comment]
Looks like control_p8_gnu baseline has been updated yesterday:
```
drwxr-sr-x 3 Zachary.Shrader stmp   4096 Oct  4 16:39 cpld_control_pdlib_p8_gnu
drwxr-sr-x 3 Zachary.Shrader stmp   4096 Oct  4 16:40 cpld_control_pdlib_p8_intel
drwxr-sr-x 2 Zachary.Shrader stmp   4096 Oct 11 18:31 cpld_control_gfsv17_iau_intel
drwxr-sr-x 3 Zachary.Shrader stmp   4096 Oct 12 17:25 control_p8_gnu
```

**Comment by zach1221** [comment]
I'll attempting to recreate control_p8_gnu baselines now. I'm also testing the other baselines to ensure there aren't issues anywhere else.

**Comment by zach1221** [comment]
Ok, the compare results for control_p8_gnu passes for me now. Can you please try again @DusanJovic-NOAA ?

**Comment by DusanJovic-NOAA** [comment]
control_p8_gnu test passed successfully. Thank you.

**Comment by grantfirl** [comment]
Thanks @zach1221

**Comment by zach1221** [comment]
> Thanks @zach1221

Of course!
