### ISSUE TITLE
Updating MOM_input_template_500 with wave coupling configurations

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1957]
## Description
In PR#1916, the MOM_input_template_500 is not updated to the one used in the global workflow because the one in GW changes results due to the change for EPBL_LANGMUIR_SCHEME variable when "USE_WAVE" is set to false. Wave group will confirm how to set this variable with "USE_WAVE" setting. A follow up PR will be made to make MOM_input_template_500 consistent in the model and GW.

**Comment by JessicaMeixner-NOAA** [comment]
I heard back from GFDL today and setting EPBL_LANGMUIR_SCHEME=ADDITIVE, is consistent with the OM4 settings, so I think the best thing to do will be to add this setting to the C48 coupled test with the 5 deg ocean.  I have a branch that has this update along with updates to make the MOM templates consistent with updates for DA being added in https://github.com/NOAA-EMC/global-workflow/pull/1944 as requested by @aerorahul. I'm currently running a full set of regression tests with both sets of changes which can be found here: https://github.com/JessicaMeixner-NOAA/ufs-weather-model/tree/feature/mom6sync Once regression tests finish I can make a PR. Baselines for the C48 test will change because of the change in EPBL_LANGMUIR_SCHEME and the updates from https://github.com/NOAA-EMC/global-workflow/pull/1944

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Thanks for checking with GFDL. I want to confirm that the "EPBL_LANGMUIR_SCHEME" is an independent variable to USA_WAVES. In other words, either USE_WAVES is .true. or .false., we should use EPBL_LANGMUIR_SCHEME="ADDITIVE", is that correct?

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa yes, it is independent.  From Brandon: 
The Langmuir number is set by Qing Li's theory waves formula when there is no wave model.

**Comment by JessicaMeixner-NOAA** [comment]
The regression tests ran overnight and had a few unexpected failures since I had not  added the new MOM settings in the datm tests section in default vars.  I'll get that updated this morning and re-run tests.    PR should be submitted late today or Monday.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Thanks for updating the template.

@aerorahul FYI.  With this MOM input template update, G-W can use the model templates. The difference is that model uses the variables for the IAU configurations.  
```
< ODA_TEMPINC_VAR = @[ODA_TEMPINC_VAR]    ! default = "ptemp_inc"
<                                         ! The name of the potential temperature inc. variable in
<                                         ! ODA_INCUPD_FILE.
< ODA_SALTINC_VAR = @[ODA_SALTINC_VAR]    ! default = "sal_inc"
<                                         ! The name of the salinity inc. variable in
<                                         ! ODA_INCUPD_FILE.
< ODA_THK_VAR = @[ODA_THK_VAR]            ! default = "h"
<                                         ! The name of the int. depth inc. variable in
<                                         ! ODA_INCUPD_FILE.
< ODA_INCUPD_UV = @[ODA_INCUPD_UV]        !
< ODA_UINC_VAR = @[ODA_UINC_VAR]          ! default = "u_inc"
<                                         ! The name of the zonal vel. inc. variable in
<                                         ! ODA_INCUPD_UV_FILE.
< ODA_VINC_VAR = @[ODA_VINC_VAR]          ! default = "v_inc"
<                                         ! The name of the meridional vel. inc. variable in
<                                         ! ODA_INCUPD_UV_FILE.
---
> ODA_TEMPINC_VAR = "Temp"        ! default = "ptemp_inc"
>                                 ! The name of the potential temperature inc. variable in
>                                          ! ODA_INCUPD_FILE.
> ODA_SALTINC_VAR = "Salt"        ! default = "sal_inc"
>                                 ! The name of the salinity inc. variable in
>                                 ! ODA_INCUPD_FILE.
> ODA_THK_VAR = "h"               ! default = "h"
>                                 ! The name of the int. depth inc. variable in
>                                 ! ODA_INCUPD_FILE.
> ODA_INCUPD_UV = true            !
> ODA_UINC_VAR = "u"              ! default = "u_inc"
>                                 ! The name of the zonal vel. inc. variable in
>                                 ! ODA_INCUPD_UV_FILE.
> ODA_VINC_VAR = "v"              ! default = "v_inc"
>                                 ! The name of the meridional vel. inc. variable in
>                                 ! ODA_INCUPD_UV_FILE.
```

**Comment by aerorahul** [comment]
Thanks for the work @JessicaMeixner-NOAA.
Thank you for the confirmation @junwang-noaa 
I will have a companion global-workflow issue using these templates for the next sprint.
