### ISSUE TITLE
cpld_control_p8 and cpld_debug_p8 fail on Hercules with GNU compilers

### ISSUE THREAD

**Issue by zach1221** [ufs-community/ufs-weather-model#1963]
## Description

These two cases seem to fail towards the very end of run_test 

### To Reproduce:

Clone ufs-community:dev and run either case mentioned above. Both baseline creation and matching fails.

## Additional context

In my testing making the following edit in ufs-weather-model/tests/tests/cpld_control_p8 setting TPN = 18 allows both tests to pass.

if [[ $MACHINE_ID = hercules ]]; then
  TPN=18
fi

**Comment by climbfuji** [comment]
I've spent quite some time today looking into Hercules and the various options to build a GNU-MPI stack that works. The short answer is that it is a long story ... I found one bug in WW3 I believe using a particular combination of gcc@11.3.1 and mvapich2@2.3.7:
```
  0:            PM25 ->       pm25  [ug/m3]
  0:             SO2 ->        so2  [ppm]
  0:             SO4 ->        so4  [ug/kg]
  0:              SS ->      seas1  [ug/kg]
  0: --------------------------------------
  0: UFS Aerosols: Model initialized
144:   aft fcst run output time=         720 FBcount=           3 na=           1
196: At line 557 of file /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/WW3/model/src/w3timemd.F90
196: Fortran runtime error: Index '51' of dimension 1 of array 'ndpm' above upper bound of 12
196:
196: Error termination. Backtrace:
193: At line 557 of file /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/WW3/model/src/w3timemd.F90
193: Fortran runtime error: Index '52' of dimension 1 of array 'ndpm' above upper bound of 12
193:
```
I haven't looked into it in detail, but this is where my `cpld_debug_p8` test currently fails.

**Comment by climbfuji** [comment]
@jkbk2004 FYI - ran into an out of bounds error in WW3 when running `cpld_debug_p8` on Hercules with GNU+MVAPICH2.

**Comment by climbfuji** [comment]
I got it to run in release mode where it ignores/doesn't see this out of bound error.

**Comment by climbfuji** [comment]
here is the trace log for one of the failing tasks in debug mode:
```
184: At line 557 of file /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/WW3/model/src/w3timemd.F90
184: Fortran runtime error: Index '52' of dimension 1 of array 'ndpm' above upper bound of 12
184:
184: Error termination. Backtrace:
184: #0  0x1508b20f3860 in ???
184: #1  0x1508b20f43b9 in ???
184: #2  0x1508b20f4a2d in ???
184: #3  0x14798cc in mymd21
184: 	at /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/WW3/model/src/w3timemd.F90:557
184: #4  0x1479a10 in __w3timemd_MOD_dsec21
184: 	at /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/WW3/model/src/w3timemd.F90:415
184: #5  0x14c5ccf in __w3wavemd_MOD_w3wave
184: 	at /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/WW3/model/src/w3wavemd.F90:2435
184: #6  0x11e7796 in modeladvance
184: 	at /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/WW3/model/src/wav_comp_nuopc.F90:1126
184: #7  0xa25a83 in ???
184: #8  0xa25d94 in ???
184: #9  0xa274a1 in ???
184: #10  0x4265b6 in ???
184: #11  0x266e093 in ???
184: #12  0x98d31e in ???
184: #13  0x98d692 in ???
184: #14  0xa67f2c in ???
184: #15  0xa6acaa in ???
184: #16  0xa5ec0d in ???
184: #17  0x98bf17 in ???
184: #18  0xb61f15 in ???
184: #19  0x76a71c in ???
184: #20  0x925a66 in ???
184: #21  0xa25a83 in ???
184: #22  0xa25d94 in ???
184: #23  0xa274a1 in ???
184: #24  0x4265b6 in ???
184: #25  0x91b4c6 in ???
184: #26  0x98d31e in ???
184: #27  0x98d692 in ???
184: #28  0xa6ab67 in ???
184: #29  0xa5ec0d in ???
184: #30  0x98bf17 in ???
184: #31  0xb61f15 in ???
184: #32  0x76a71c in ???
184: #33  0x41f07f in ufs
184: 	at /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/driver/UFS.F90:394
184: #34  0x41f7eb in main
184: 	at /work2/noaa/jcsda/dheinzel/ufs-wm-spst150/driver/UFS.F90:35
```

**Comment by JessicaMeixner-NOAA** [comment]
@climbfuji - thanks for pointing out this WW3 issue.  @MatthewMasarik-NOAA and I will look into this and see if we can't get a fix for this.  Here's a WW3 issue for this: https://github.com/NOAA-EMC/WW3/issues/1109

**Comment by MatthewMasarik-NOAA** [comment]
Thank you @climbfuji.  Looking into this now

**Comment by climbfuji** [comment]
Thank you both! I just pushed an update to my ufs-weather-model PR that uses mvapich2 with GNU on Hercules, in case you can't reproduce the issue elsewhere.

**Comment by JessicaMeixner-NOAA** [comment]
@climbfuji and @zach1221 I'm trying to run on hercules because I suspect I wont be able to replicate this error elsewhere.  I am using https://github.com/climbfuji/ufs-weather-model/tree/feature/spack_stack_150 and am just trying to run a subset of tests, but I can't even get the intel versions of the tests to compile.... is there something special I should be doing on hercules, admittedly this is my first time working on hercules and I believe there are issues in develop so I don't know if that's a good sanity point check? 

ufs clone: /work2/noaa/marine/jmeixner/hercules/ufs-01 (tests/rt.bug.conf subset of tests)
rt output: /work2/noaa/stmp/jmeixner/stmp/jmeixner/FV3_RT/rt_1886735

**Comment by zach1221** [comment]
> @climbfuji and @zach1221 I'm trying to run on hercules because I suspect I wont be able to replicate this error elsewhere. I am using https://github.com/climbfuji/ufs-weather-model/tree/feature/spack_stack_150 and am just trying to run a subset of tests, but I can't even get the intel versions of the tests to compile.... is there something special I should be doing on hercules, admittedly this is my first time working on hercules and I believe there are issues in develop so I don't know if that's a good sanity point check?
> 
> ufs clone: /work2/noaa/marine/jmeixner/hercules/ufs-01 (tests/rt.bug.conf subset of tests) rt output: /work2/noaa/stmp/jmeixner/stmp/jmeixner/FV3_RT/rt_1886735

@JessicaMeixner-NOAA are you receiving an error of some kind you can share? Once you've modified rt.conf to run only a subset of tests, the command I use is ./rt.sh -a nems -c -e -l rt.conf . 

Edit: I see you gave the path to the logs, I'll take a look.

**Comment by JessicaMeixner-NOAA** [comment]
/work2/noaa/stmp/jmeixner/stmp/jmeixner/FV3_RT/rt_1886735/compile_s2s_intel/err :

```
CMake Error at CICE-interface/CMakeLists.txt:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "CICE-interface/CMakeLists.txt".

```

**Comment by climbfuji** [comment]
Stupid mistake in my last commit …

**Comment by climbfuji** [comment]
I also need to change the mpirun command for gnu … in a meeting now will push both shortly

**Comment by JessicaMeixner-NOAA** [comment]
Just wanted to update here.  @MatthewMasarik-NOAA  and I have been able to reproduce the issue and have started putting in a multitude of debug print statements in attempts to figure out exactly what is going on here.  No answers yet, but we have spent time and will continue to debug.  We'll post more when we have something.

**Comment by climbfuji** [comment]
> Just wanted to update here. @MatthewMasarik-NOAA and I have been able to reproduce the issue and have started putting in a multitude of debug print statements in attempts to figure out exactly what is going on here. No answers yet, but we have spent time and will continue to debug. We'll post more when we have something.

Thanks for looking into this, @JessicaMeixner-NOAA

**Comment by JessicaMeixner-NOAA** [comment]
Short story:  We are trying to access an uninitialized variable of which the hercules + gnu + debug compiler initialized as a different value than what intel, gnu, or intel+debug have for any other machine which somehow caused an issue where as the odd values on all the other machines have not done.  Long story has been posted in the WW3 issue here: https://github.com/NOAA-EMC/WW3/issues/1109#issuecomment-1779412258 for those who are interested.   I have a proposed fix for this, but cannot fully test until hercules is back from maintenance as we do not see the crash  on any other machine (and that also goes for the various machines others in the WW3 community use).    Hopefully we should be able to confirm this solves the issue tomorrow.  In the meantime I'll be doing some WW3 standalone testing and testing on hera along with some ufs-weather-model testing on hera to confrim no answers change with this fix as expected.

**Comment by climbfuji** [comment]
Great detective work @JessicaMeixner-NOAA, thanks very much. We can include the bug fix once tested in this PR I suppose?

**Comment by JessicaMeixner-NOAA** [comment]
@climbfuji that works for me I'll point you the branch & PRs  as soon as I've finished testing on hercules - so probably some time tomorrow afternoon

**Comment by JessicaMeixner-NOAA** [comment]
All tests on hera went well yesterday, testing on Hercules just started. Will report back in an hour or two with updates.

**Comment by JessicaMeixner-NOAA** [comment]
@climbfuji @zach1221 - My branch that I'm testing from is here: https://github.com/JessicaMeixner-NOAA/ufs-weather-model/tree/feature/spack_stack_150 its the same as Dom's but points to the WW3 branch: https://github.com/JessicaMeixner-NOAA/WW3/tree/bug/devufs/flout7uninit 

Yesterday, I created a baseline on hera and then updated WW3 and I could match that baseline without answer changes.  I'm now testing on hercules as that's really where we need to test this as it was the only machine that showed this problem.  However, today when I'm running on hercules I'm getting errors or hangs and I don't think it's related to WW3.  I haven't tried to replicate the failures seen on Tuesday which might be a good next step given maitence.  Right now my jobs just appear to be hanging: 

/work2/noaa/marine/jmeixner/hercules/stmp/jmeixner/FV3_RT/rt_3281844/cpld_control_p8_gnu/out
at 
`  0: UFS Aerosols: Advancing from 2021-03-22T06:00:00 to 2021-03-22T06:12:00
`for both gnu jobs (debug and control).  

In err: 
```
 80: 	[WARNING] Shared memory window cannot be created, for better performance, please consider increasing the value of MV2_SHMEM_COLL_NUM_COMM (current value 32)
 80: 
 20: pe=00020 FAIL at line=00037    NetCDF4_get_var.H                        <Unable to get variable: SO2_elev from file: ExtData/CEDS/v2019/2021/CEDS.2019.emis.20210323.nc>
 20: pe=00020 FAIL at line=00705    ServerThread.F90                         <status=1>
 20: pe=00020 FAIL at line=00469    ServerThread.F90                         <status=1>
 20: pe=00020 FAIL at line=01096    ServerThread.F90                         <status=1>
 20: pe=00020 FAIL at line=00088    MessageVisitor.F90                       <status=1>
 20: pe=00020 FAIL at line=00113    AbstractMessage.F90                      <status=1>
 20: pe=00020 FAIL at line=00107    SimpleSocket.F90                         <status=1>
 20: pe=00020 FAIL at line=00407    ClientThread.F90                         <status=1>
```

which is different than the first time I ran this where I just got: 
/work2/noaa/marine/jmeixner/hercules/stmp/jmeixner/FV3_RT/rt_3234878/cpld_control_p8_gnu/err
```
 80: [hercules-07-09:mpi_rank_80][MPIDI_CH3I_Win_allocate_shm]
 80:    [WARNING] Shared memory window cannot be created, for better performance, please consider increasing the value of MV2_SHMEM_COLL_NUM_COMM (current value 32)
 80:
  0: [hercules-07-08:mpi_rank_0][MPIDI_CH3I_Win_allocate_shm]
  0:    [WARNING] Shared memory window cannot be created, for better performance, please consider increasing the value of MV2_SHMEM_COLL_NUM_COMM (current value 32)
  0:
111: Fatal error in MPI_Win_allocate:
111: Other MPI error, error stack:
111: MPI_Win_allocate(164).................: MPI_Win_allocate(size=0, disp_unit=4, MPI_INFO_NULL, comm=0xc40000f8, base=0x7ffc3f676020, win=0x7ffc3f676070) failed
111: MPID_Win_allocate(129)................:
111: MPIDI_CH3U_Win_allocate(238)..........:
111: MPIDI_CH3I_Win_allocate_shm(895)......:
111: MPIU_SHMW_Hnd_deserialize(324)........:
111: MPIU_SHMW_Seg_open(865)...............:
111: MPIU_SHMW_Seg_create_attach_templ(635): open failed - No such file or directory
111:
```

The second time I also ran the two intel tests as a sanity check and they both ran through.   Not really sure what the best next step is and am hoping others can chime in with ideas.

**Comment by climbfuji** [comment]
I think I fixed that by adjusting MV2_SHMEM_COLL_NUM_COMM. I’m in an all-day meeting today but will pick this up tonight. Please push the WW3 submodule pointer update to my branch so that folks can start creating new baselines?

**Comment by JessicaMeixner-NOAA** [comment]
Made a PR here: https://github.com/climbfuji/ufs-weather-model/pull/16

**Comment by zach1221** [comment]
Closing as ufs-wm PR#1920 has been merged, and demonstrated both cpld_control_p8_gnu and cpld_debug_p8_gnu pass on Hercules now.
