### ISSUE TITLE
Enable taking into account sea surface current in atmosphere-ocean coupling

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#1975]
## Description

Currently, sea surface current (SSC) is not considered in ufs-weather-model atmosphere-ocean coupling. We would like to take into account the SSC impact on air-sea momentum and enthalpy flux calculations by using the SSC-relative winds.

## Solution

Passing SSC from ocean model component (e.g., MOM6) through CMEPS into FV3ATM, and within FV3ATM (and ccpp-physics) taking into consideration SSC when calculating air-sea momentum and enthalpy fluxes. Currently some HAFS developers (e.g., @binli2337) is working to enable this capability for the UFS HAFS application.

## Alternatives

Do not consider SSC impacts on atmosphere-ocean coupling.

## Related to

- fixed by ufs-community/ufs-weather-model/pull/2104
- fixed by NOAA-EMC/fv3atm/pull/755
- fixed by NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/311
- fixed by ufs-community/ccpp-physics/pull/155
- fixed by NOAA-EMC/CMEPS/pull/107

**Comment by yangfanglin** [comment]
@BinLiu-NOAA @binli2337  Bin and Bin, can you share some science background information (ppts or publications) on this project ?   Is this relate to the sea spray effect ( @JongilHan66 ) which has been included in the CCPP ?

**Comment by junwang-noaa** [comment]
@BinLiu-NOAA I am curious, should the air-sea fluxes be computed in mediator where the SSC is available? @DeniseWorthen FYI.

**Comment by BinLiu-NOAA** [comment]
@yangfanglin and @junwang-noaa, when calculating/estimating the air-sea fluxes (including momentum and heat fluxes), theoretically, one should use the sea surface current (SSC) relative wind. For example, wind stress = rho x Cd x (wind - SSC) x (wind - SSC). Similarly for air-sea heat and moisture fluxes calculations, one should also use SSC-relative wind. 

Typically, it is assumed that SSCs are relative small compared to atmospheric wind, thus ignoring SSCs when estimating air-sea fluxes. This in general should not be a big issue. However, considering strong current regions (e.g., Gulf Stream region or current under tropical cyclone forcing), SSCs could reach 1-2 m/s or even stronger. Then it sometimes could be a non-negligible portion compared to the atmospheric winds. Besides, there are situations SSCs are in different directions from the wind, which could also affect the air-sea flux estimation/calculation. 

Hope this helps for the context. Plus, I do recall there are literatures/researches taking in account SSC in atmosphere-ocean coupling already. Thanks!

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA I am curious, should the air-sea fluxes be computed in mediator where the SSC is available? @DeniseWorthen FYI.

@junwang-noaa, it depends. Typically air-sea fluxes calculations are much more frequent (saying every dt_atmos time step) in the atmosphere (physics) side. If we only calculate the fluxes in the CMEPS side, then it will be every dt_cpl time step, which is typically much larger than dt_atmos.

**Comment by DeniseWorthen** [comment]
The SSC can be sent through CMEPS to the ATM. But regardless of whether the fluxes are computed in CMEPS or the ATM, you will have constant ocean currents during the fast coupling loop until the next time OCN runs and updates. I think for HAFS, where everything runs in the fast loop, this is not an issue. 

Also, a correction. The aoflux calculation occurs in the fast loop, so those fluxes are calculated at the dt_atmos. They are accumulated and averaged before sending to OCN.

On an unrelated subject, I did notice the other day that the ATM timestep is 180s in the HAFS RTs, but the fast coupling is 360s. So the ATM takes two full time-steps before exporting. Is that correct?

**Comment by BinLiu-NOAA** [comment]
> On an unrelated subject, I did notice the other day that the ATM timestep is 180s in the HAFS RTs, but the fast coupling is 360s. So the ATM takes two full time-steps before exporting. Is that correct?

@DeniseWorthen, the HAFS RTs use coarse resolution configurations probably. In operational HAFS (both HFSA and HFSB configurations), dt_atmos is 90s, while coupling time step (dt_cpl) is 360s currently. Of course, this might be changed/updated in future HAFS upgrades.
