### ISSUE TITLE
New regression tests for v2 surface coldstart files

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [ufs-community/ufs-weather-model#1977]
## Description
To support fractional grids, a new coldstart surface file format has been created. 

## Solution
Three new regression tests are proposed. One based on the `control_p8` test, one based on the `control_c48` test, and one based on `cpld_control_p8`. The coldstart files for the new tests will be based on the same test case (i.e., same input data to chgres) as the current tests. 

## Related to
The new coldstart file format requires an update to an FV3 io routine. See:
- NOAA-EMC/fv3atm#670
- NOAA-EMC/fv3atm#698

**Comment by junwang-noaa** [comment]
@GeorgeGayno-NOAA Please list the locations of a coupled test atm ICs, we can work with Barry to generate ICs with aerosols.
