### ISSUE TITLE
cpld_bmark_p8 failure due to time limit on Gaea

### ISSUE THREAD

**Issue by FernandoAndrade-NOAA** [ufs-community/ufs-weather-model#1978]
## Description

The cpld_bmark_p8_intel test timed out and failed during baseline creation runs with rt.sh on gaea15 (C4) while testing for #1924

### To Reproduce:

1. run rt.sh with -c : `./rt.sh -a <account> -c -e -l rt.conf` or `./rt.sh -a <account> -c -e -n cpld_bmark_p8 intel` for single test run
2. verify failure within RegressionTests_gaea.log and err files shown below

## Additional context

* Setting `WLCLK_cpl_bmrk` in the Gaea section within default_vars.sh resolved the issue during rt.sh -c runs. Setting to 45 should resolve the errors.

## Output

1. Within RegressionTests_gaea.log:
```
    193   0: The total amount of wall time                        = 344.457294
    194   0: The maximum resident set size (KB)                   = 1603760
    195
    196 Test 002 cpld_control_p8_intel PASS
    197
    198 Test 003 cpld_bmark_p8_intel FAIL
    199
    200 Test 003 cpld_bmark_p8_intel FAIL
```

2. Within cpld_bmark_p8_intel/err:
```
    356 slurmstepd: error: *** JOB 269426590 ON nid02099 CANCELLED AT 2023-11-02T23:39:36 DUE TO TIME LIMIT ***
    357  528: Stack trace terminated abnormally.
    358  219: forrtl: error (78): process killed (SIGTERM)
    359  219:
    360  219: Stack trace terminated abnormally.
    361  273: *** longjmp causes uninitialized stack frame ***: terminated
    362  367: forrtl: error (78): process killed (SIGTERM)
```

**Comment by zach1221** [comment]
Hey, @FernandoAndrade-NOAA . I'm going to close this issue, as we've merged in code changes for Gaea C5, in ufs-wm PR [1784](https://github.com/ufs-community/ufs-weather-model/pull/1784/), and cpld_bmark_p8_intel passed without issue.
