### ISSUE TITLE
Update CICE6 to 6.5.0 release

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1986]
## Description
CICE 6.5.0 release is out. It will be updated in the UFS -weather-model.

**Comment by DeniseWorthen** [comment]
@junwang-noaa We generally just keep up-to-date with the top of Consortium main. Do you mean instead that we want to use only release tags for CICE6 in UWM, so that we would stay at 6.5.0 until the next tagged release?

**Comment by junwang-noaa** [comment]
Sorry. I mean we want to move to the top of main branch with CICE 6.5.0 updates.
