### ISSUE TITLE
Repository should have a README.md

### ISSUE THREAD

**Issue by underwoo** [ufs-community/ufs-weather-model#2]
To help users understand and navigate to the documentation in the wiki, it would be a good idea to have a `README.md` file.  This file should briefly describe the project and have a link that points to the wiki for more documentation.  The [MOM6](https://github.com/NOAA-GFDL/MOM6) readme file is a great example.

**Comment by junwang-noaa** [comment]
README.md is added to the repository in pull request #9, close the issue.
