### ISSUE TITLE
[production/AQM.v7]  model compilation with debug mode

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-weather-model#2002]
All executable codes must be compiled and tested with debug mode.  The debug flag must have -g but at least needs to have -check all and -ftrapuv.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Can we close this issue?

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen Yes, Thanks.
