### ISSUE TITLE
ecflow error

### ISSUE THREAD

**Issue by ericaligo-NOAA** [ufs-community/ufs-weather-model#2003]
I'm getting an ecflow error on hera. I don't believe this is a disk issue. I ran rt.sh -c -e -a fv3-cam. Will I be able to run the next step:  ./rt.sh -m -e -a fv3-cam or should we get this error message straightened out first?
+ rm -rf /scratch1/NCEPDEV/stmp2/Eric.Aligo/FV3_RT/rt_168919
+ [[ false == true ]]
+ [[ false == true ]]
+ [[ '' != '' ]]
+ date
++ printf '%02dh:%02dm:%02ds\n' 1 32 37
+ elapsed_time=01h:32m:37s
+ echo 'Elapsed time: 01h:32m:37s. Have a nice day!'
+ echo 'Elapsed time: 01h:32m:37s. Have a nice day!'
Elapsed time: 01h:32m:37s. Have a nice day!
+ echo 'rt.sh finished'
rt.sh finished
+ cleanup
++ awk '{print $2}'
+ [[ 168919 == 168919 ]]
+ rm -rf /scratch1/NCEPDEV/fv3-cam/Eric.Aligo/noscrub/ufs_refconv/tests/lock
+ [[ true == true ]]
+ ecflow_stop
+ [[ true == true ]]
+ set +e
++ ecflow_client --get
++ grep '^suite'
+ SUITES=
+ echo SUITES=
SUITES=
+ '[' -z '' ']'
+ ecflow_client --halt=yes
+ ecflow_client --check_pt
Error: request( --check_pt ) failed!  Server reply: Could not save check point file. file system full or permissio            ns ?

+ ecflow_client --terminate=yes
+ trap 0
+ exit

**Comment by zach1221** [comment]
Hi, @ericaligo-NOAA . There are disk space issues on Hera currently, making it difficult to run tests. Can you try perhaps running a test through the rt.conf suite? ./rt.sh -a nems -e -l rt.conf
