### ISSUE TITLE
Permission error on gaea for RT baseline

### ISSUE THREAD

**Issue by JustinPerket** [ufs-community/ufs-weather-model#2031]
## Description
Since there's now Gaea c5 support (thanks a bunch!), I'm trying out a simple datm_cdeps_land test, but I am getting a permission error for the basline:

rt.sh exists with:

      Baseline directory does not exist:
      + echo '   /lustre/f2/pdata/ncep/role.epic/C5/RT/NEMSfv3gfs/develop-20231207'
         /lustre/f2/pdata/ncep/role.epic/C5/RT/NEMSfv3gfs/develop-20231207
      + exit 1
      + echo 'rt.sh finished'
      rt.sh finished

I do not have permission for that:

`ls /lustre/f2/pdata/ncep/role.epic/C5/RT/NEMSfv3gfs/develop-20231207` returns:

`ls: cannot access '/lustre/f2/pdata/ncep/role.epic/C5/RT/NEMSfv3gfs/develop-20231207': Permission denied`

It's been a while trying to use Gaea because of the c5 issue. I see that RTs are no longer also placed in `/lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/` What should I do?

Thanks,
Justin

**Comment by DeniseWorthen** [comment]
@JustinPerket On C5, baselines are in ``/lustre/f2/pdata/ncep/role.epic/C5/RT/NEMSfv3gfs/`` but you can't run because you have no permission, correct?

**Comment by DeniseWorthen** [comment]
@jkbk2004 We are storing baselines for C5 in ncep, not ncep_shared (there are baselines in ncep_shared that are 10 months old, develop-202302XX). But using ncep means folks like Justin can't use them:

```
[Gaea] /lustre/f2/pdata: ls -lrt
total 146
drwxrwsr-x  3 root esrl 33280 Nov  6  2019 esrl
drwxrwsr-x 23 root ncep 41472 Feb 24  2023 ncep_shared
drwxrws--- 35 root ncep 41472 Mar 16  2023 ncep
drwxrwxr-x 23 root gfdl 33280 Aug 31 13:24 gfdl
```

**Comment by jkbk2004** [comment]
It involves with role.epic setup. We can resolve the permission issue when we migrate F2 to F5 file system. They will mount F5 on Jan 08, 2024.

**Comment by JustinPerket** [comment]
@DeniseWorthen 


> @jkbk2004 We are storing baselines for C5 in ncep, not ncep_shared (there are baselines in ncep_shared that are 10 months old, develop-202302XX). But using ncep means folks like Justin can't use them:

Yes, exactly that.  I'm not part of the ncep group, which wasn't a problem for the ncep_shared folder permissions (2775), but is for the ncep one (2770)

**Comment by jkbk2004** [comment]
@JustinPerket I may try to set temporary baseline cases and input files at /lustre/f2/pdata/ncep_shared/role.epic/RT/NEMSfv3gfs. Would that be ok for you?

**Comment by JustinPerket** [comment]
Thanks @jkbk2004 , I believe so. The  `INPUTDATA_ROOT*` dirs are also set to be under `/lustre/f2/pdata/ncep/role.epic/C5/RT/NEMSfv3gfs/` in `rt.sh`:

      INPUTDATA_ROOT=${INPUTDATA_ROOT:-$DISKNM/NEMSfv3gfs/input-data-20221101}
      INPUTDATA_ROOT_WW3=${INPUTDATA_ROOT}/WW3_input_data_20220624
      INPUTDATA_ROOT_BMIC=${INPUTDATA_ROOT_BMIC:-$DISKNM/NEMSfv3gfs/BM_IC-20220207}
      
But these do seem to be mirrored in ncep_shared, so I can work around that.

**Comment by jkbk2004** [comment]
@JustinPerket I backed up develop-202312* baselines at /lustre/f2/pdata/ncep_shared/role.epic/RT/NEMSfv3gfs. Can you check?

**Comment by JustinPerket** [comment]
Thanks @jkbk2004 , sorry for the delay over the holidays. Yes, that did work when I changed to `DISKNM=/lustre/f2/pdata/ncep/role.epic/C5/RT` for the gaea-c5 machine. (however, since then, the newest develop's baseline date is 20231221, which wasn't there then, but for my purposes I can also switch to a slightly older baseline)
