### ISSUE TITLE
Testing ESMF 8.6.0 in ufs weather model

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#2036]
## Description
ESMF 8.6.0 is released, it needs to be tested in ufs-weather-model.

**Comment by junwang-noaa** [comment]
Test ESMF 8.6.0 on acorn in spack-stack 1.6.0. All tests passed with no results change.
Hang installed it in hpc-stack, will test it when the module file is ready.

**Comment by junwang-noaa** [comment]
From Hang:

 the spack-stack 1.6.0 has been installed on acorn under
/lfs/h1/emc/nceplibs/noscrub/spack-stack/ This should work fine with ufs
default modulefiles for spack-stack. For the running with hpc-stack
installations, please use following modulefile.

 A exactly same library settings to the UFS repo was made on acorn for
further testing:
/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles/ufs_acorn.intel.lua
/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles/ufs_common.lua


 We are still missing some latest versions of libraries on cactus and
Dogwoods to match spack-stack. I will test a wcoss2 version based on
current libraries on Cactus. And push missing versions there soon.

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA I cannot use the provided modulefiles to test 8.6.0 using the hpc-stack. There is an issue with the script finding bacio or netcdf in some cases. I've tried permutations of it with no success either. Please provide a working modulefile for the hpc-stack setup to test ESMF 8.6.0.

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Let me know what
problems you have in your test. I previously successfully built the UFS
with these
/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles/ufs_acorn.intel.lua
/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles/ufs_common.lua

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA @junwang-noaa  Currently, if I use that modulesfiles on the top of develop branch, in my case I just tried building the control_c48 case and it fails at finding NetCDF. Is there a CMakeModules I'm supposed to update to as well?

**Comment by junwang-noaa** [comment]
I don't think so. @Hang-Lei-NOAA would you please check the ESMF/8.6.0 module path?

**Comment by Hang-Lei-NOAA** [comment]
@Jun Wang - NOAA Federal ***@***.***> The ESMF/8.6.0 is on
***@***.***:/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles>
ls
/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9/esmf/8.6.0.lua
/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9/esmf/8.6.0.lua
***@***.***:/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles>
module load esmf/8.6.0

The following have been reloaded with a version change:
  1) esmf/8.5.0 => esmf/8.6.0

***@***.***:/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles>
module show esmf/8.6.0
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9/esmf/8.6.0.lua:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
help([[]])
conflict("esmf")
prepend_path("PATH","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/bin")
prepend_path("LD_LIBRARY_PATH","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/lib")
prepend_path("DYLD_LIBRARY_PATH","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/lib")
prepend_path("LIBRARY_PATH","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/lib")
prepend_path("MANPATH","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/share/man")
prepend_path("CPATH","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/include")
setenv("ESMF_ROOT","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0")
setenv("ESMF_DIR","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0")
setenv("ESMF_PATH","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0")
setenv("ESMF_BIN","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/bin")
setenv("ESMF_INC","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/include")
setenv("ESMF_INCLUDES","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/include")
setenv("ESMF_LIB","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/lib")
setenv("ESMF_LIBRARIES","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/lib")
setenv("ESMF_VERSION","8.6.0")
setenv("ESMF_MOD","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/mod")
setenv("ESMFMKFILE","/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/lib/
esmf.mk")
whatis("Name: esmf")
whatis("Version: 8.6.0")
whatis("Category: library")
whatis("Description: ESMF library")

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA my issue is with netcdf. CMake is not finding NetCDF.

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Please send your
modulefiles to me. Thanks

**Comment by BrianCurtis-NOAA** [comment]
It is the same ones you linked to me:
```
/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles/ufs_acorn.intel.lua
/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles/ufs_common.lua
```
I've only modified the ESMF & MAPL version to 8.6.0

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA what's the error message?

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa @Hang-Lei-NOAA 
```
CMAKE_FLAGS="-DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8" ./build.sh 
-- The C compiler identification is Intel 19.1.3.20200925
-- The CXX compiler identification is Intel 19.1.3.20200925
-- The Fortran compiler identification is Intel 19.1.3.20200925
-- Cray Programming Environment 2.7.13 C
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/cray/pe/craype/2.7.13/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.7.13 CXX
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/cray/pe/craype/2.7.13/bin/CC - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Cray Programming Environment 2.7.13 Fortran
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/cray/pe/craype/2.7.13/bin/ftn - skipped
-- Checking whether /opt/cray/pe/craype/2.7.13/bin/ftn supports Fortran 90
-- Checking whether /opt/cray/pe/craype/2.7.13/bin/ftn supports Fortran 90 - yes

Configuring UFS app in S2S mode

FMS .............. ON
FV3 .............. ON
AQM .............. OFF
GOCART ........... OFF
MOM6 ............. ON
HYCOM ............ OFF
CICE6 ............ ON
WW3 .............. OFF
STOCH_PHYS ....... ON
CDEPS ............ OFF
CMEPS ............ ON
NOAHMP ........... OFF

Setting configuration for acorn

32BIT ............ OFF
CCPP_32BIT ....... OFF
AVX2 ............. OFF
SIMDMULTIARCH .... OFF
DEBUG ............ OFF
INLINE_POST ...... ON
MULTI_GASES ...... OFF
MOVING_NEST ...... OFF
REGIONAL_MOM6..... OFF
OPENMP ........... ON
PARALLEL_NETCDF .. ON
JEDI_DRIVER ...... OFF
CMEPS_AOFLUX ..... OFF
CDEPS_INLINE ..... OFF

-- Found MPI_C: /opt/cray/pe/craype/2.7.13/bin/cc (found version "3.1") 
-- Found MPI_CXX: /opt/cray/pe/craype/2.7.13/bin/CC (found version "3.1") 
-- Found MPI_Fortran: /opt/cray/pe/craype/2.7.13/bin/ftn (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found OpenMP_C: -qopenmp (found version "5.0") 
-- Found OpenMP_CXX: -qopenmp (found version "5.0") 
-- Found OpenMP_Fortran: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
CMake Error at CMakeModules/Modules/FindNetCDF.cmake:246 (message):
  Unable to properly find NetCDF.  Found static libraries at:
  /lfs/h1/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/esmf860/NetCDF_C_LIBRARY-NOTFOUND
  but could not run nc-config:
Call Stack (most recent call first):
  CMakeLists.txt:147 (find_package)


CMake Error at CMakeModules/Modules/FindNetCDF.cmake:246 (message):
  Unable to properly find NetCDF.  Found static libraries at:
  /lfs/h1/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/esmf860/NetCDF_Fortran_LIBRARY-NOTFOUND
  but could not run nc-config:
Call Stack (most recent call first):
  CMakeLists.txt:147 (find_package)


CMake Error at /apps/spack/cmake/3.20.2/intel/19.1.3.304/a43g47cjru4jlyziud2y2zc7k6jnbsn2/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find NetCDF (missing: NetCDF_INCLUDE_DIRS NetCDF_LIBRARIES C
  Fortran) (Required is at least version "4.7.4")
Call Stack (most recent call first):
  /apps/spack/cmake/3.20.2/intel/19.1.3.304/a43g47cjru4jlyziud2y2zc7k6jnbsn2/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/Modules/FindNetCDF.cmake:312 (find_package_handle_standard_args)
  CMakeLists.txt:147 (find_package)


-- Configuring incomplete, errors occurred!
See also "/lfs/h1/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/esmf860/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Sorry, it is my
fault. Please reload them. I just used the system netcdf-A build esmf/8.5.0.
I have modified the loadings with new fms/2023.04. ESMF/8.6.0 and mapl. Now
try:

/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles/ufs_acorn.intel.lua
/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles/ufs_common.lua

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA would you be able to use https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_wcoss2.intel.lua for your ufs_acorn.intel.lua (this skips the need for ufs_common.lua which wcoss2 will never use.

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Here I provide you a
version that named wcoss2, but actually works on acorn. When all modules
available on wcoss2 cactus and dogwoods, I will update one. We also have
old ones working on wcoss2 loading old library versions.

Only works on acorn:
***@***.***:/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles>
module use module use
/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles
***@***.***:/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles>
module load ufs_wcoss2.intel
***@***.***:/lfs/h1/emc/eib/noscrub/Hang.Lei/ufs-weather-model/modulefiles>
module list

Currently Loaded Modules:
  1) PrgEnv-intel/8.1.0   4) cmake/3.20.2    7) libpng/1.6.37  10)
netcdf/4.9.2  13) crtm/2.4.0     16) ip/4.3.0      19) gftl-shared/1.6.1
 22) esmf/8.6.0
  2) intel/19.1.3.304     5) jasper/2.0.32   8) szip/2.1.1     11)
fms/2023.04   14) g2/3.4.5       17) sp/2.3.3      20) pio/2.5.10
23) mapl/2.40.3-esmf-8.6.0
  3) craype/2.7.13        6) zlib/1.2.13     9) hdf5/1.14.0    12)
bacio/2.4.1   15) g2tmpl/1.10.2  18) w3emc/2.10.0  21) scotch/7.0.4
24) ufs_wcoss2.intel

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA using your ufs_acorn.intel.lua and ufs_common.lua i get the following error in CMake:
```
CMAKE_FLAGS="-DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8" ./build.sh 
-- The C compiler identification is Intel 19.1.3.20200925
-- The CXX compiler identification is Intel 19.1.3.20200925
-- The Fortran compiler identification is Intel 19.1.3.20200925
-- Cray Programming Environment 2.7.13 C
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/cray/pe/craype/2.7.13/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.7.13 CXX
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/cray/pe/craype/2.7.13/bin/CC - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Cray Programming Environment 2.7.13 Fortran
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/cray/pe/craype/2.7.13/bin/ftn - skipped
-- Checking whether /opt/cray/pe/craype/2.7.13/bin/ftn supports Fortran 90
-- Checking whether /opt/cray/pe/craype/2.7.13/bin/ftn supports Fortran 90 - yes

Configuring UFS app in S2S mode

FMS .............. ON
FV3 .............. ON
AQM .............. OFF
GOCART ........... OFF
MOM6 ............. ON
HYCOM ............ OFF
CICE6 ............ ON
WW3 .............. OFF
STOCH_PHYS ....... ON
CDEPS ............ OFF
CMEPS ............ ON
NOAHMP ........... OFF

Setting configuration for acorn

32BIT ............ OFF
CCPP_32BIT ....... OFF
AVX2 ............. OFF
SIMDMULTIARCH .... OFF
DEBUG ............ OFF
INLINE_POST ...... ON
MULTI_GASES ...... OFF
MOVING_NEST ...... OFF
REGIONAL_MOM6..... OFF
OPENMP ........... ON
PARALLEL_NETCDF .. ON
JEDI_DRIVER ...... OFF
CMEPS_AOFLUX ..... OFF
CDEPS_INLINE ..... OFF

-- Found MPI_C: /opt/cray/pe/craype/2.7.13/bin/cc (found version "3.1") 
-- Found MPI_CXX: /opt/cray/pe/craype/2.7.13/bin/CC (found version "3.1") 
-- Found MPI_Fortran: /opt/cray/pe/craype/2.7.13/bin/ftn (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found OpenMP_C: -qopenmp (found version "5.0") 
-- Found OpenMP_CXX: -qopenmp (found version "5.0") 
-- Found OpenMP_Fortran: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Found NetCDF: /apps/prod/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/intel-19.1.3.304/cray-mpich-8.1.12/netcdf/4.9.2/include (found suitable version "4.9.2", minimum required is "4.7.4") found components: C Fortran 
-- FindNetCDF defines targets:
--   - NetCDF_VERSION [4.9.2]
--   - NetCDF_PARALLEL [TRUE]
--   - NetCDF_C_CONFIG_EXECUTABLE [/apps/prod/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/intel-19.1.3.304/cray-mpich-8.1.12/netcdf/4.9.2/bin/nc-config]
--   - NetCDF::NetCDF_C [SHARED] [Root: /apps/prod/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/intel-19.1.3.304/cray-mpich-8.1.12/netcdf/4.9.2] Lib: /apps/prod/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/intel-19.1.3.304/cray-mpich-8.1.12/netcdf/4.9.2/lib/libnetcdf.so 
--   - NetCDF_Fortran_CONFIG_EXECUTABLE [/apps/prod/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/intel-19.1.3.304/cray-mpich-8.1.12/netcdf/4.9.2/bin/nf-config]
--   - NetCDF::NetCDF_Fortran [SHARED] [Root: /apps/prod/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/intel-19.1.3.304/cray-mpich-8.1.12/netcdf/4.9.2] Lib: /apps/prod/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/intel-19.1.3.304/cray-mpich-8.1.12/netcdf/4.9.2/lib/libnetcdff.so 
-- Found ESMF: /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/esmf/8.6.0/lib/libesmf.a (found suitable version "8.6.0", minimum required is "8.3.0") 
-- Found MPI: TRUE (found version "3.1") found components: Fortran 
-- Found OpenMP_Fortran: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0") found components: Fortran 
-- Found MPI: TRUE (found version "3.1")  
-- Found FMS: "/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/fms/2023.04" (Version: "2023.4.0")
-- FMS targets:
--   - FMS::fms_r4 [Lib: /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/fms/2023.04/lib/libfms_r4.a]
--   - FMS::fms_r8 [Lib: /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/fms/2023.04/lib/libfms_r8.a]
-- Found PIO: /apps/prod/intel-19.1.3.304/cray-mpich-8.1.9/pio/2.5.10 (found suitable version "2.5.10", minimum required is "2.5.3") found components: C Fortran 
-- FindPIO:
--   - PIO_PREFIX [/apps/prod/intel-19.1.3.304/cray-mpich-8.1.9/pio/2.5.10]
--   - PIO_VERSION: [2.5.10]
--   - PIO Components Found: C;Fortran
-- Found bacio: /apps/ops/prod/libs/intel/19.1.3.304/bacio/2.4.1/lib/libbacio_4.a (found version "2.4.0")
-- Found OpenMP_Fortran: -qopenmp (found version "5.0") 
-- Found sp: /apps/ops/prod/libs/intel/19.1.3.304/sp/2.3.3/lib/libsp_4.a (found version "2.3.3")
CMake Error at CMakeLists.txt:171 (find_package):
  By not providing "Findw3emc.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "w3emc", but
  CMake did not find one.

  Could not find a package configuration file provided by "w3emc" (requested
  version 2.9.2) with any of the following names:

    w3emcConfig.cmake
    w3emc-config.cmake

  Add the installation prefix of "w3emc" to CMAKE_PREFIX_PATH or set
  "w3emc_DIR" to a directory containing one of the above files.  If "w3emc"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/lfs/h1/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/esmf860/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Please try it again.
It should be fine now. I was reorganizing the library and cleaning the
unnecessary libraries to remove dependency last night and this morning,
which may affect your test.

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA 
```
CMake Error at /apps/spack/cmake/3.20.2/intel/19.1.3.304/a43g47cjru4jlyziud2y2zc7k6jnbsn2/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findbufr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "bufr", but
  CMake did not find one.

  Could not find a package configuration file provided by "bufr" with any of
  the following names:

    bufrConfig.cmake
    bufr-config.cmake

  Add the installation prefix of "bufr" to CMAKE_PREFIX_PATH or set
  "bufr_DIR" to a directory containing one of the above files.  If "bufr"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/w3emc/2.10.0/lib64/cmake/w3emc/w3emc-config.cmake:46 (find_dependency)
  CMakeLists.txt:171 (find_package)


-- Configuring incomplete, errors occurred!
See also "/lfs/h1/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/esmf860/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Bufr was not
supposed to be loaded. If you need to load it for your run, please add the
line to ufs_common.lua
{["bufr"]              = "11.7.0"},
If other version is required, please change the version number.

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***>  I checked out the
latest develop branch. The compile is successful. You can directly start
from:
/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/works/ufscompression/develop/tests/compilelibs0305.log

Directly load from
/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/works/ufscompression/develop/modulefiles/

**Comment by BrianCurtis-NOAA** [comment]
Something is wrong with that hdf5:
```
/var/run/palsd/61fdedd2-98c0-485f-addd-4e5a51d5bcdf/files/fv3.exe: error while loading shared libraries: libhdf5_hl.so.310: cannot open shared object file: No such file or directory
/var/run/palsd/61fdedd2-98c0-485f-addd-4e5a51d5bcdf/files/fv3.exe: error while loading shared libraries: libhdf5_hl.so.310: cannot open shared object file: No such file or directory
/var/run/palsd/61fdedd2-98c0-485f-addd-4e5a51d5bcdf/files/fv3.exe: error while loading shared libraries: libhdf5_hl.so.310: cannot open shared object file: No such file or directory
```

**Comment by Hang-Lei-NOAA** [comment]
***@***.***:/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/works/ufscompression/develop>
ll
/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/hdf5/1.14.0/lib/libhdf5_hl.so.310
lrwxrwxrwx 1 hang.lei nceplibs 21 Oct  2 14:31
/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.9/hdf5/1.14.0/lib/libhdf5_hl.so.310
-> libhdf5_hl.so.310.0.0

@Brian Curtis - NOAA Affiliate ***@***.***> The
libhdf5_hl.so.310* there
since OCt 21. *
It could be some loading issue of acorn.
See my run directory with latest checkout
at /lfs/h2/emc/ptmp/hang.lei/FV3_RT/rt_18183

I will do a test run by
(2) replace the hdf5 and netcdf in the ufs_common.lua by hdf5-A and
netcdf-A. Then rerun the case.

The system installed hdf5-A and netcdf-A have been tested many times. The
hdf5 in hpc-stack was adding extra functions for doing zstd compression
test. But my test shows no difference between two groups.

I will let you know the result of tonight's tests.

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> I feel it is like an
acorn system issue. I run many times, some like the beginning one succeed
over the walltime.  /lfs/h2/emc/ptmp/hang.lei/FV3_RT/rt_18183

After module purge, all my cases failed. Even the basic "mv" command failed.

But everytime, I build with aerosol model, succeed. ( ./compile.sh acorn
"-DAPP=ATMAERO -DCCPP_SUITES=FV3_GFS_v17_p8 -D32BIT=ON" 001
>compilelibs0306.log)

@Jun.Wang I am going to rebuild all the code, and start the personal test
of UFS on cactus tomorrow and will let you know the result. That will give
a sure answer to us.

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> @Jun Wang - NOAA
Federal ***@***.***> The UFS on cactus is more consistent. Please
check my run on /lfs/h2/emc/ptmp/hang.lei/FV3_RT/rt_145944
You can start by copy the modulefiles
from /lfs/h2/emc/eib/noscrub/hang.lei/ufsdevelop/modulefiles/ufs_wcoss2.intel.lua
baseline may need to be regenerated using esmf/8.6.0 series.

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA on WCOSS2 I get issues with netcdff finding the appropriate so. 

```
./fv3.exe: error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory
```

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Please show me your
working directory.

**Comment by Hang-Lei-NOAA** [comment]
The library is there, since last Jul:
ls -l
/apps/prod/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/intel-19.1.3.304/cray-mpich-8.1.12/netcdf/4.9.2/lib
total 7248
-rwxr-xr-x 1 hpc-adm hpc-adm    1912 Jul 17  2023 libh5bzip2.la
-rwxr-xr-x 1 hpc-adm hpc-adm   97456 Jul 17  2023 libh5bzip2.so
-rw-r--r-- 1 hpc-adm hpc-adm 2316308 Jul 17  2023 libnetcdf.a
-rw-r--r-- 1 hpc-adm hpc-adm  857668 Jul 17  2023 libnetcdf_c++4.a
-rwxr-xr-x 1 hpc-adm hpc-adm    1943 Jul 17  2023 libnetcdf_c++4.la
lrwxrwxrwx 1 hpc-adm hpc-adm      23 Jul 17  2023 libnetcdf_c++4.so ->
libnetcdf_c++4.so.1.1.0
lrwxrwxrwx 1 hpc-adm hpc-adm      23 Jul 17  2023 libnetcdf_c++4.so.1 ->
libnetcdf_c++4.so.1.1.0
-rwxr-xr-x 1 hpc-adm hpc-adm  475664 Jul 17  2023 libnetcdf_c++4.so.1.1.0
-rw-r--r-- 1 hpc-adm hpc-adm 1042008 Jul 17  2023 libnetcdff.a
-rwxr-xr-x 1 hpc-adm hpc-adm    1917 Jul 17  2023 libnetcdff.la
-rw-r--r-- 1 hpc-adm hpc-adm    2372 Jul 17  2023 libnetcdff.settings
lrwxrwxrwx 1 hpc-adm hpc-adm      19 Jul 17  2023 libnetcdff.so ->
libnetcdff.so.7.1.0
lrwxrwxrwx 1 hpc-adm hpc-adm      19 Jul 17  2023 libnetcdff.so.7 ->
libnetcdff.so.7.1.0
-rwxr-xr-x 1 hpc-adm hpc-adm  837840 Jul 17  2023 libnetcdff.so.7.1.0
-rwxr-xr-x 1 hpc-adm hpc-adm    1631 Jul 17  2023 libnetcdf.la
-rw-r--r-- 1 hpc-adm hpc-adm    2030 Jul 17  2023 libnetcdf.settings
lrwxrwxrwx 1 hpc-adm hpc-adm      19 Jul 17  2023 libnetcdf.so ->
libnetcdf.so.19.2.2
lrwxrwxrwx 1 hpc-adm hpc-adm      19 Jul 17  2023 libnetcdf.so.19 ->
libnetcdf.so.19.2.2
-rwxr-xr-x 1 hpc-adm hpc-adm 1751776 Jul 17  2023 libnetcdf.so.19.2.2
drwxr-xr-x 2 hpc-adm hpc-adm    4096 Jul 17  2023 pkgconfig

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA
run_dir: /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_171470/regional_atmaq_debug_intel

my setup is: /lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Just rechecked,
Please load the modulefile again.
/lfs/h2/emc/eib/noscrub/hang.lei/ufsdevelop/modulefiles/ufs_wcoss2.intel.lua
This build of libraries are based on hdf5-A; NETCDF-A and PIO-A.
Please correct and try it again.

**Comment by Hang-Lei-NOAA** [comment]
WCOSS2 Ticket number 2024031510000019

Assigned to Bongi

Pushed on April/4

**Comment by Hang-Lei-NOAA** [comment]
Associated mapl/2.40.3-esmf-8.6.0 version updates is with Ticket number 2024031510000028
Assigned to Bongi
Pushed on April/4

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA Do you hear anything from Bongi? Are the libraries available on wcoss2 now?

**Comment by Hang-Lei-NOAA** [comment]
@junwang-noaa after we tested on acron, it was Tuesday. GDIT then need to ask NCO to start the RFC ticket. At least it will take a week to get it on wcoss2. Please just wait. I will inform Brian once it is ready for confirm testing.

**Comment by Hang-Lei-NOAA** [comment]
Lib-C series are available on cactus for quick fully testing. @junwang-noaa

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA just to confirm that you will test the ESMF 8.6.0 in your test with other library update (pio netcdf), right?

**Comment by BrianCurtis-NOAA** [comment]
Yes
