### ISSUE TITLE
Testing fms 2023.04 in ufs weather model

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#2037]
## Description
FMS 2023.04 was released last week, it contains the diag_table bug fix in FMS 2023.02.01 and fixes related to the gnu compiler in FMS 2023.03. It needs to be tested in ufs weather model.

**Comment by junwang-noaa** [comment]
Test fms 2023.04 on acorn from spack-stack. Will test it under current HPC-stack that is used in cactus/dogwood.

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa I used module spider after loading the Acorn modulefile to search for fms/2023.04 and it doesn't seem to be there, yet?

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa should I be using spack-stack 1.6 for this?

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA I tested the spack-stack 1.6 when Hang installed on acorn. It worked. We want to test HPC-stack for wcoss2. @Hanglei-noaa May I ask if you have fms/2023.04 installed in acorn in HPC-stack? Thanks

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA Is FMS/2023.04 available in the HPC-stack acorn ?

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> yes, it is there:
/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9/fms/2023.04.lua

**Comment by Hang-Lei-NOAA** [comment]
Task transferred from NCO to GDIT

Ticket number 2024040310000021 

Assigned to Bongi
