### ISSUE TITLE
Update ATMAQ tests to v16

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#2046]
## Description
Current ATMAQ tests use physics suite FV3_GFS_v15p2, while the operational model is using v16. It's important to have tests using the v16 package as they transition back to a development setup from ops implementation

## Solution
Bring in updated inputs and namelists from current ops branch back into develop branch tests

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA Is this still in the plan for future AQM development?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA Is this still in the plan for future AQM development?

@junwang-noaa Yes, I think so. I will know more once AQM development ramps up again. I had work started on WCOSS2 with updates inputs, but i had some trouble recognizing which input.nml variable the model did not like.

**Comment by BrianCurtis-NOAA** [comment]
I think this work will be cancelled as the AQM-Workflow repo comes together. We will use that to generate a new suite of AQM tests updated to either v16 or v17
