### ISSUE TITLE
Fix build system so that CMAKE_<COMPILER>_FLAGS set at top level will be used by subcomponents

### ISSUE THREAD

**Issue by mark-a-potts** [ufs-community/ufs-weather-model#2050]
## Description

CMEPS, CDEPS,  CICE, and MOM6 do not inherit CMAKE_<COMPILER>_FLAGS from the top level build and there is no way to specify new flags like "-fPIC" when linking to other applications like JEDI>

## Solution
Change CMakeLists.txt files to inherit flags from top level

## Alternatives
The "-fPIC" flag could be added to each CMakeLists.txt file directly, but that would not allow for any flexibility

**Comment by DeniseWorthen** [comment]
Please fill out the requested information for this issue.
