### ISSUE TITLE
Nice to have: option to run compile jobs of regression test suite only

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#2063]
## Description
It would be really nice to have an option to run only the `COMPILE` jobs of the regression test suite and skip the actual tests. That's useful for developers of the CCPP framework, for example, when making changes to `ccpp_prebuild.py`.

## Solution
Add option to `rt.sh` that skips running the tests and only executes the `COMPILE` jobs in `rt.conf` (or whatever `rt*.conf` is selected via `-l`).

## Alternatives
Don't implement.

## Related to
n/a

**Comment by DusanJovic-NOAA** [comment]
Is something like this not satisfactory:

```
grep "^COMPILE" rt.conf > rt_compile.conf
./rt.sh -l rt_compile.conf
```

**Comment by climbfuji** [comment]
> Is something like this not satisfactory:
> 
> ```
> grep "^COMPILE" rt.conf > rt_compile.conf
> ./rt.sh -l rt_compile.conf
> ```

Yes that works, too. I had already coded it up - I'll ask you to take a look later when I open a PR (that I need anyway for submodule ptr updates) and if you think it is overkill I'll revert it.
