### ISSUE TITLE
Allow use of `ice_in.IN` in global applications

### ISSUE THREAD

**Issue by aerorahul** [ufs-community/ufs-weather-model#2068]
## Description
There are a few inconsistencies in `ice_in.IN` that is preventing the use of it in the global application.

## Solution
Eliminate the inconsistencies

## Alternatives
Short of managing a second copy, there are none.

## Related to
Follow-up to #2010

**Comment by junwang-noaa** [comment]
@aerorahul Would you please list the inconsistencies? We will make changes accordingly.

**Comment by aerorahul** [comment]
> @aerorahul Would you please list the inconsistencies? We will make changes accordingly.

Sure.  They are in the PR: https://github.com/ufs-community/ufs-weather-model/pull/2069/files
