### ISSUE TITLE
gnv1_nested failed in cmp on wcoss2

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#2078]
## Description
While I am testing MOM6 code updating which shall has no any impact on non-S2S jobs, I found "gnv1_nested" failed in final cmp step on wcoss2 when I ran the whole rt.sh.  No issue is found on HERA. I repeated twice on wcoss2 and had the same issue.

### To Reproduce:
checkout latest UWM (I did it on Jan 6th, hash # is 407c6fda)
run gnv1_nested job on wcoss2

## Output
Checking test 141 gnv1_nested_intel results ....
 Comparing atmf006.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.nc ............ALT CHECK......NOT OK
 Comparing atm.nest02.f006.nc ............ALT CHECK......NOT OK
 Comparing sfc.nest02.f006.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.coupler.res .........OK
 Comparing RESTART/20200825.180000.fv_core.res.nc .........OK
 Comparing RESTART/20200825.180000.fv_core.res.nest02.nc .........OK
 Comparing RESTART/20200825.180000.fv_core.res.nest02.tile7.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_core.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_core.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_core.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_core.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_core.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_core.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_srf_wnd.res.nest02.tile7.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_srf_wnd.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_srf_wnd.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_srf_wnd.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_srf_wnd.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_srf_wnd.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_srf_wnd.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_tracer.res.nest02.tile7.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_tracer.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_tracer.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_tracer.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_tracer.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_tracer.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.fv_tracer.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.phy_data.nest02.tile7.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.phy_data.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.phy_data.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.phy_data.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.phy_data.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.phy_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.phy_data.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.sfc_data.nest02.tile7.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.sfc_data.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.sfc_data.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.sfc_data.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.sfc_data.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.sfc_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20200825.180000.sfc_data.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_BC_ne.res.nest02.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_BC_sw.res.nest02.nc ............ALT CHECK......NOT OK

**Comment by BrianCurtis-NOAA** [comment]
I think there was a bad baseline. I tested against dev branch as well and got the same result. I re-did the baseline and it's all OK now. Thanks for letting us know. Closing.
