### ISSUE TITLE
rt.sh failed with COMPILE_NR: unbound variable

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#2081]
## Description

I just checkout latest UFSWM (hash # 1cab8b7f) but got COMPILE_NR: unbound variable. I tried on HERA and GAEA and got the samething.

### To Reproduce:

checkout latest UFSWM and run rt.sh

**Comment by BrianCurtis-NOAA** [comment]
@jiandewang can you please let us know the exact command you used to run rt.sh (i.e. ./rt.sh -e )

**Comment by jiandewang** [comment]
> @jiandewang can you please let us know the exact command you used to run rt.sh (i.e. ./rt.sh -e )

./rt.sh -a marine-cpu -k -l rt.conf-JW>output&
here rt.conf-JW is based on rt.conf but I deleted most of the jobs and only kept one I need.

# Aerosol, no Wave
RUN | cpld_s2sa_p8                                      | - noaacloud                           | baseline |

COMPILE | s2sw | intel | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 |                                 | fv3 |
RUN | cpld_control_nowave_noaero_p8                     | - noaacloud                           | baseline |

**Comment by BrianCurtis-NOAA** [comment]
Hera rt.sh was successful with `./rt.sh -e -n control_p8 intel`, i'll try the cpld_control_nowave_noaero_p8 to see if I can reproduce.

**Comment by DeniseWorthen** [comment]
It might be more informative to test on Gaea, since the last PR removed C4. @jiandewang you got the error on hera for sure?

**Comment by jiandewang** [comment]
> It might be more informative to test on Gaea, since the last PR removed C4. @jiandewang you got the error on hera for sure?

yes I tried on GAEA and HERA

I just tried this and got the same error
commit 407c6fdac4fd992f054b003bbadafa35ebc802d6 (HEAD)
Author: Dustin Swales <dustin.swales@noaa.gov>
Date:   Thu Jan 4 07:43:44 2024 -0700

**Comment by jiandewang** [comment]
I am having another meeting now, will try arouind 3pm

**Comment by BrianCurtis-NOAA** [comment]
> > @jiandewang can you please let us know the exact command you used to run rt.sh (i.e. ./rt.sh -e )
> 
> ./rt.sh -a marine-cpu -k -l rt.conf-JW>output& here rt.conf-JW is based on rt.conf but I deleted most of the jobs and only kept one I need.
> # Aerosol, no Wave
> 
> RUN | cpld_s2sa_p8 | - noaacloud | baseline |
> 
> COMPILE | s2sw | intel | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | | fv3 | RUN | cpld_control_nowave_noaero_p8 | - noaacloud | baseline |

If that's your rt.conf then it's missing a compile line for that run line on top

**Comment by jiandewang** [comment]
@BrianCurtis-NOAA thanks for your time. Sorry it's my bad for the false alarm. I had a typo in my modified rt.sh
