### ISSUE TITLE
RT "passes" even when multiple tests fail due to Disk quota error

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2087]
## Description

I attempted to run a full RT on Hera for a PR. I got a successful log file but happened to notice the last test in the log, which should be ``datm_cdeps_control_cfsr_gnu`` test was not the last test in the log. The final test was 

```
Test 213 control_wam_debug_gnu PASS
``` 

I then looked at the run_ files in ``logs/log_hera`` and found 52 tests which failed due to disk quota. The RT run directory was deleted and no ``fail`` files were present in the tests directory. 

See /scratch1/NCEPDEV/nems/Denise.Worthen/WORK/ufs_dw/tests

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen can you try for the same issue using https://github.com/ufs-community/ufs-weather-model/pull/2061 ? It's a good test to see what my changes are doing.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA This failure will not repeat if folks have cleaned up the project space in the time between when I got the failure and now. We need a way to "fake" a full quota. I assume we share the same project space, so your own testing should also trigger it. 

I also think we need a fix sooner rather than later, because I know of no way to guard against this other than manually grepping for quota in the run_ files.

**Comment by jkbk2004** [comment]
@RatkoVasic-NOAA @natalie-perlin @ulmononian file count quota issues should be addressed with cleaning up spack stack old versions: /scratch1/NCEPDEV/nems/role.epic/

**Comment by DeniseWorthen** [comment]
When I say "we need a fix", I mean we need to ensure that the rt scripts can catch silent failures due to quota issues. This is critical.

**Comment by jkbk2004** [comment]
> When I say "we need a fix", I mean we need to ensure that the rt scripts can catch silent failures due to quota issues. This is critical.

@DeniseWorthen do you mean to include resource management option in RT system?

**Comment by jkbk2004** [comment]
resource monitoring is available at https://noaa-epic-dashboard.s3.amazonaws.com/index.html. We can add more option in the dashboard as well.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I mean that we cannot have silent failures---meaning that the RT scripts report successful RTs when in fact 50+ tests failed to run. "Fixing" it by cleaning up quotas is not getting to the fundamental issue, which is that the RT system is not catching failures caused by quota.

**Comment by ulmononian** [comment]
> @RatkoVasic-NOAA @natalie-perlin @ulmononian file count quota issues should be addressed with cleaning up spack stack old versions: /scratch1/NCEPDEV/nems/role.epic/

cleaned up some space here

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen with #2061 merged, i think if a test fails from disk quota the RT log should show it, even if it currently comes up as "Failed to Compare" if it makes it to the comparison section. I think we can close this, but wanted your OK first.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I started an RT yesterday expecting a few tests would not compare. The RT said it passed, so I checked my logs. We are still failing to capture disk quota failures:

```
baseline dir = /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240315/cpld_bmark_p8_intel
working dir  = /scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_2688309/cpld_bmark_p8_intel
Checking test cpld_bmark_p8_intel results ....
rt_utils.sh: line 287: printf: write error: Disk quota exceeded
 Comparing sfcf006.nc .....rt_utils.sh: line 305: printf: write error: Disk quota exceeded
USING NCCMP..rt_utils.sh: line 335: echo: write error: Disk quota exceeded
....OK
```
I think what is actually failing on is the writing the ``_nccmp.log`` file? Because I can see the case ran to completion. 

Then, since the control case "ran to completion" the dependent (restart case starts). That case also fails to compare because of quota. This happens to multiple tests, and the end result is that the overall RT reports success.

There is no associated log content for the tests which failed due to quota:
```
[Hera: hfe08] /scratch1/NCEPDEV/nems/Denise.Worthen/WORK/ufs_dw/tests/logs/log_hera: wc -l rt_*log
    50 rt_control_c384gdas_intel.log
    18 rt_control_c384_intel.log
    46 rt_control_c48_intel.log
     0 rt_control_c48.v2.sfc_intel.log
     0 rt_control_csawmgt_gnu.log
    34 rt_control_CubedSphereGrid_intel.log
    22 rt_control_CubedSphereGrid_parallel_intel.log
     0 rt_control_flake_intel.log
    24 rt_control_iovr4_intel.log
     0 rt_control_iovr5_intel.log
    18 rt_control_latlon_intel.log
     0 rt_control_lndp_intel.log
    54 rt_control_noqr_p8_intel.log
    54 rt_control_p8_intel.log
    26 rt_control_p8_lndp_intel.log
     0 rt_control_p8_mynn_intel.log
    54 rt_control_p8_rrtmgp_intel.log
    54 rt_control_p8.v2.sfc_intel.log
    18 rt_control_ras_intel.log
    46 rt_control_restart_noqr_p8_intel.log
    46 rt_control_restart_p8_intel.log
     0 rt_control_stochy_intel.log
    14 rt_control_wam_intel.log
    18 rt_control_wrtGauss_netcdf_parallel_intel.log
    23 rt_conus13km_control_intel.log
    12 rt_conus13km_restart_mismatch_intel.log
    60 rt_cpld_2threads_p8_intel.log
     0 rt_cpld_bmark_p8_intel.log
    60 rt_cpld_control_c192_p8_intel.log
    57 rt_cpld_control_c48_intel.log
    72 rt_cpld_control_ciceC_p8_intel.log
    71 rt_cpld_control_gfsv17_intel.log
    69 rt_cpld_control_noaero_p8_agrid_intel.log
    71 rt_cpld_control_noaero_p8_intel.log
    69 rt_cpld_control_nowave_noaero_p8_intel.log
    72 rt_cpld_control_p8_faster_intel.log
    72 rt_cpld_control_p8_intel.log
    72 rt_cpld_control_p8_mixedmode_intel.log
    72 rt_cpld_control_p8.v2.sfc_intel.log
    71 rt_cpld_control_pdlib_p8_intel.log
    72 rt_cpld_control_qr_p8_intel.log
    59 rt_cpld_debug_gfsv17_intel.log
    59 rt_cpld_debug_noaero_p8_intel.log
    60 rt_cpld_debug_p8_intel.log
    59 rt_cpld_debug_pdlib_p8_intel.log
    60 rt_cpld_decomp_p8_intel.log
    71 rt_cpld_mpi_gfsv17_intel.log
    60 rt_cpld_mpi_p8_intel.log
     0 rt_cpld_restart_bmark_p8_intel.log
    60 rt_cpld_restart_qr_p8_intel.log
    58 rt_cpld_s2sa_p8_intel.log
    13 rt_datm_cdeps_bulk_cfsr_intel.log
    13 rt_datm_cdeps_bulk_gefs_intel.log
     0 rt_hafs_regional_datm_cdeps_intel.log
    54 rt_hrrr_control_2threads_intel.log
     0 rt_hrrr_control_decomp_intel.log
    54 rt_merra2_thompson_intel.log
     0 rt_rap_sfcdiff_decomp_intel.log
     0 rt_regional_2dwrtdecomp_intel.log
    18 rt_regional_2threads_intel.log
    18 rt_regional_control_intel.log
     0 rt_rrfs_v1nssl_intel.log
     0 rt_rrfs_v1nssl_nohailnoccn_intel.log
```

**Comment by BrianCurtis-NOAA** [comment]
Line 245/317 in rt.sh uses grep for the word 'quota'.

So something I'm doing on those lines isn't working as I expected.

Can you look at those lines and see if that grep works for that file. Maybe the file is wrong?

**Comment by DeniseWorthen** [comment]
Check which file? The ``rt_cpld_bmark_p8_intel.log`` is empty. Here is the start of the ``run`` log 

```
Slurm unknown status -. Check sacct ...
57820934                COMPLETED rt_2688309_cpld_bma+
57820934.ba+            COMPLETED                batch
57820934.ex+            COMPLETED               extern
57820934.0              COMPLETED              fv3.exe
304 min. Job is ,  status: - jobid 57820934
+ [[ false = false ]]
+ check_results
+ '[' -o xtrace ']'
+ set_x='set -x'
+ set +x
rt_utils.sh: line 273: echo: write error: Disk quota exceeded
rt_utils.sh: line 274: echo: write error: Disk quota exceeded
rt_utils.sh: line 275: echo: write error: Disk quota exceeded
rt_utils.sh: line 276: echo: write error: Disk quota exceeded

baseline dir = /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240315/cpld_bmark_p8_intel
working dir  = /scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_2688309/cpld_bmark_p8_intel
Checking test cpld_bmark_p8_intel results ....
rt_utils.sh: line 287: printf: write error: Disk quota exceeded
 Comparing sfcf006.nc .....rt_utils.sh: line 305: printf: write error: Disk quota exceeded
USING NCCMP..rt_utils.sh: line 335: echo: write error: Disk quota exceeded
....OK
```

**Comment by RatkoVasic-NOAA** [comment]
FYI I just deleted two old spack-stack directories, about 1M files. That should give us some time before we switch 100% to Rocky, when I'll be able to remove several millions of files (built on CentOS).
EDIT: I removed 1.4.0 version as well (0.7M files). Total 3 installations (1.3.0, 1.3.1, and 1.4.0) removed. Hopefully nobody is using those old spack-stacks.
