### ISSUE TITLE
PW-GCP spack-stack libraries

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#2088]
## Description

User report a trouble to mount the /contrib-epic directory on PW-GCP to use spack-stack libraries.
```
ALLNODES
/contrib/pw/mount-epic-contrib.sh
if [[ $HOSTNAME == mgmt* ]]; then
  # head node only instructions
fi"
```
AWS works fine

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA @natalie-perlin can you please take a look at this issue on GCP?

**Comment by ulmononian** [comment]
@jkbk2004 can the user who reported this please give this another go? curious if this is still an ongoing problem.

**Comment by zach1221** [comment]
> @jkbk2004 can the user who reported this please give this another go? curious if this is still an ongoing problem.

@SadeghTabas-NOAA are you able to re-test?
