### ISSUE TITLE
Spack stack 1.6.0 upgrade

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#2091]
## Description

Release: https://github.com/JCSDA/spack-stack/releases/tag/spack-stack-1.6.0
* Update spack submodule from branch release/1.6.0 to tag spack-stack-1.6.0
* Update documentation for acorn
* Update documentation for spack-stack-1.6.0 for Hera, Jet, Gaea C5
* Library update:
  * fms-2023.04
  *  esmf-8.6.0
 * Issues to be resolved and revisited:
   * fms_io issue on mom6 side: https://github.com/ufs-community/ufs-weather-model/issues/2070
   * Update on PW-Clouds: https://github.com/ufs-community/ufs-weather-model/issues/2088
   
RDHPCS/PW-Clouds/Container Install and Test Status:
- [x] Hera intel/gnu: 
- [x] Hercules intel/gnu: 
- [x] Orion intel: 
- [x] Gaea-C5 intel: 
- [x] Jet intel: 
- [x] Derecho intel:
- [x] PW-Clouds: AWS, GCP, AZURE
- [ ] Docker container

WCOSS2 Install Tracker:
- [x] esmf/8.6.0 (Library Name: )
- [x] mapl/2.40.3-esmf-8.6.0 (Library Name: )
- [x] fms/2023.04 (Library Name: )

**Comment by BrianCurtis-NOAA** [comment]
This should also track the status of the install on WCOSS2 for all new libraries/ library changes: esmf/8.6.0 mapl/2.40.3-esmf-8.6.0 fms/2023.04 @Hang-Lei-NOAA

**Comment by junwang-noaa** [comment]
@jkbk2004 would you please add a table for the platforms to track installation and testing results? Thanks

**Comment by jkbk2004** [comment]
- Platform maintainers list: https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html, https://github.com/JCSDA/spack-stack/issues/924
- Project chapter: https://github.com/JCSDA/spack-stack/blob/develop/project_charter.md

**Comment by jkbk2004** [comment]
@zach1221 As Gaea is back on-line, can you test /ncrc/proj/epic/spack-stack/spack-stack-1.6.0?

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @Hang-Lei-NOAA test looks good on RDHPCS side: pretty much ready.

**Comment by ulmononian** [comment]
@jkbk2004 a new container is available on dockerhub w/ an ubtunu22.04 base, intel compiler/mpi, and spack-stack/1.5.1 (ufs-wm-env): https://hub.docker.com/r/noaaepic/ubuntu22.04-intel-ufs-wm/tags. this container can be updated to include spack-stack/1.6.0 when this is needed for the ufs-wm.

**Comment by zach1221** [comment]
Spack-stack 1.6.0 is integrated into weather model repo. Closing this issue.
