### ISSUE TITLE
LICENSE.md needs to be updated

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#2110]
## Description
Currently, the [LICENSE.md](https://github.com/ufs-community/ufs-weather-model/blob/develop/LICENSE.md) file does not cover all the latest ufs-weather-model subcomponents (e.g., MOM6, HYCOM, WW3, CMEPS, CDEPS, etc.). Meanwhile, there might be outdated submodules over there as well (NEMS, FMS?).

## Solution
Properly update the license related information and links related to ufs-weather-model subcomponents/submodules.

## Alternatives

N/A

## Related to
 - fixed by ufs-community/ufs-weather-model/pull/<pr_number>

**Comment by jkbk2004** [comment]
@gspetro-NOAA I think it will be ok just to update component list. But can we double check with RTX and EPT for the license page information?

**Comment by zach1221** [comment]
Per https://github.com/ufs-community/ufs-weather-model/pull/2142 closing this issue.
