### ISSUE TITLE
Namelist updates for the cloud water detrainment rates (c1_deep & c1_shal) of the SAS convection scheme

### ISSUE THREAD

**Issue by JunghoonShin-NOAA** [ufs-community/ufs-weather-model#2112]
## Description
 In the SAS scheme, the cloud water detrainment rates (c1_deep & c1_shal) are hardwired in the source code GFS_typedefs.F90. 
HAFS team wants to decrease (or tune) these cloud water detrainment rates (c1_deep & c1_shal) of the SAS convection scheme, because 1. the atmosphere seems to be too humid for Hurricane Lee (2023 13L) case, and 2. reducing these two parameters produced better HAFS forecast for the Western Pacific tropical cyclones.

## Solution
HAFS team wants to make these two parameters (c1_deep & c1_shal) as a namelist option so that HAFS model can use the different cloud water detrainment rates for Western Pacific basin.

## Alternatives
 Not applicable

## Related to
 Not applicable

**Comment by BinLiu-NOAA** [comment]
It looks c1_deep and c1_shal are already namelist controlled options:

https://github.com/NOAA-EMC/fv3atm/blob/6c2b775e96545edfe62c3972bbced4af8a2d9f0a/ccpp/data/GFS_typedefs.F90#L4009
https://github.com/NOAA-EMC/fv3atm/blob/6c2b775e96545edfe62c3972bbced4af8a2d9f0a/ccpp/data/GFS_typedefs.F90#L4013

@JunghoonShin-NOAA please help to check, test, confirm from HAFS team side. If it works properly, we can then close this issue. Thanks!

**Comment by JunghoonShin-NOAA** [comment]
Through the technical test, HAFS team has confirmed that the cloud water detrainment rates (c1_deep & c1_shal) of the SAS convection scheme are already in the namelist option. 
It means that we don’t need to make any changes in the UFS model side. 
So, I close this pull request. 
Thank you.

**Comment by JunghoonShin-NOAA** [comment]
Through the technical test, HAFS team has confirmed that the cloud water detrainment rates (c1_deep & c1_shal) of the SAS convection scheme are already in the namelist option. And it worked properly.
It means that we don’t need to make any changes in the UFS model side. 
So, I close this pull request. 
Thank you.
