### ISSUE TITLE
baseline data permission issues on Orion

### ISSUE THREAD

**Issue by JustinPerket** [ufs-community/ufs-weather-model#2120]
## Description

Current and recent develop branches reference baseline data that are inaccessible outside of some groups. This causes RT to fail. For the current develop head, I get this message when running rt.sh:

    + RTPWD=/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240124
    + [[ false == false ]]
    + [[ ! -d /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240124 ]]
    ++ ls -1 /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240124/
    ++ wc -l
    ls: cannot open directory /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240124/: Permission denied

## Additional context

`/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240126/` is in the group `epic` and has permissions 2750, so is not readable by others like me not part of the group

Also, ` /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240124/` and `/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240111`  are in group `stmp` and also have permissions (2)750

**Comment by zach1221** [comment]
Hi, @JustinPerket . Can you please try accessing or running tests against the baselines in  /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240124/ and /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240111 ?

I'll have 20240126 fixed shortly.

**Comment by JustinPerket** [comment]
Thanks @zach1221.  /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240124/ and /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240111 now are readable to me.

**Comment by DeniseWorthen** [comment]
@JustinPerket Can we close this now? Thanks.

**Comment by zach1221** [comment]
@JustinPerket can you please check /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240126/ again for me?

**Comment by JustinPerket** [comment]
Yes, thank you. Sorry, I was waiting until /work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240126/ was readable yet, and it wasn't when I had to leave yesterday. Thanks for the fast response!
