### ISSUE TITLE
Reduce number of compile jobs submitted at once by the rt.sh on Hera

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#2122]
Hera system administrators asked us to reduce the number of compile jobs submitted at once. If ecflow is used number of compile jobs is currently set to 10:

https://github.com/ufs-community/ufs-weather-model/blob/932a532516e8b9fd7aa13cc137f777cbcc8e8709/tests/rt.sh#L691-L693

and if Rocoto is used it is 20:

https://github.com/ufs-community/ufs-weather-model/blob/932a532516e8b9fd7aa13cc137f777cbcc8e8709/tests/rt.sh#L682-L682

They recommend that we reduce Rocoto number to 10, for now.

**Comment by BrianCurtis-NOAA** [comment]
I've been running on Hera a ton for the past couple of weeks. I've been using only ecflow. Should I reduce from 10 at all?

**Comment by DusanJovic-NOAA** [comment]
For now, let's reduce only Rocoto to 10, and see what happens.

**Comment by zach1221** [comment]
> For now, let's reduce only Rocoto to 10, and see what happens.

We tested reducing rocoto to 10 and committed the change in WM PR# 2213.
