### ISSUE TITLE
ufs_noaacloud modulefile should be upgraded to spack-stack-1.5.1

### ISSUE THREAD

**Issue by ulmononian** [ufs-community/ufs-weather-model#2131]
## Description
ufs_noaacloud_intel.lua needs to be updated to `spack-stack-1.5.1` to be consistent with other machine modulefiles. 

## Solution
change the path to `/contrib/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core`

fyi @natalie-perlin @RatkoVasic-NOAA @zach1221 @kbooker79 @jkbk2004

**Comment by zach1221** [comment]
@ulmononian I'm going to close this as spack-stack/1.5.1 has been installed on the cloud environments. I've tested it successfully on AWS and GCP. Azure there are some known issues with the cluster preventing RTs from running. I'm currently working with parallel works admin to resolve.

**Comment by ulmononian** [comment]
@zach1221 https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_noaacloud.intel.lua is still using 1.5.0. shouldn't it go to 1.5.1 to be consistent with the rest of the wm?

**Comment by zach1221** [comment]
> @zach1221 https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_noaacloud.intel.lua is still using 1.5.0. shouldn't it go to 1.5.1 to be consistent with the rest of the wm?

Yes, you're correct. I thought we had added this code change to the modulefile already. My mistake
