### ISSUE TITLE
Derecho Workflow Issues

### ISSUE THREAD

**Issue by zach1221** [ufs-community/ufs-weather-model#2132]
## Description

Ecflow and Rocoto Failing to run tests on Derecho

Rocoto:  rocoto_workflow.xml :: Submission of compile_s2swa_32bit_intel failed!  FATAL ERROR: task `compile_s2swa_32bit_intel` cannot be submitted due to missing <nodesize> information

Ecflow: ecflow_client --halt=yes
rt_utils.sh: line 683: ecflow_client: command not found

### To Reproduce:

Clone ufs-weather-model repo. 
cd ufs-weather-model/tests/
./rt.sh -a nral0032 -e -l rt.conf and  ./rt.sh -a nral0032  -l rt.conf -r 

 ## Additional context

miniconda install on derecho is now owned by root glade/p/ral

**Comment by zach1221** [comment]
@natalie-perlin are you able to help us look into these workflow issues on Derecho?

**Comment by zach1221** [comment]
Ecflow works on derecho now obviously. @natalie-perlin do you know if there is any plan to install rocoto as well? I know normally there is a rocoto module installed by HPC admins but it seems they've chosen not to that with Derecho.

**Comment by MichaelLueken** [comment]
Rocoto is available on Derecho - `/glade/work/epicufsrt/contrib/derecho/rocoto/modulefiles`.
