### ISSUE TITLE
Jet OS migration to Rocky8: tjet:xjet

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#2136]
## Description

OS migration is planned after the maintenance on 02/20. Regression test should be confirmed.

## Solution

Possibly Spack Stack re-installation with new OS

**Comment by zach1221** [comment]
@RatkoVasic-NOAA are you able to check if ecflow/rocoto workflow should be setup differently on rocky8, in addition to spack-stack?
Testing with ufs-weather-model develop branch, using a worflow, the jobs aren't making it to the queue, so just want to ensure you're aware.
ecflow: ecflow_client: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

rocoto: Cycle 197001010000, Task compile_s2swa_32bit_intel, jobid=139348, in state DEAD (FAILED), ran for 3.0 seconds

Sequential run without workflow, fails during compile of the physics suite: cmake: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
/lfs4/HFIP/h-nems/Zachary.Shrader/RT_RUNDIRS/Zachary.Shrader/FV3_RT/rt_1074176/

**Comment by RatkoVasic-NOAA** [comment]
@zach1221 I didn't run whole rt.sh, just small test to check if it is working on Hera/Rocky8:
`/scratch2/NCEPDEV/fv3-cam/Ratko.Vasic/Rocky8/ufs-weather-model/tests/1.conf`
I used rocoto to run it. It passed that test (`./rt.sh -k -l 1.conf -a epic -r`)
It was on Feb 16th. Maybe something changed in the meantime!?

**Comment by zach1221** [comment]
> @zach1221 I didn't run whole rt.sh, just small test to check if it is working on Hera/Rocky8: `/scratch2/NCEPDEV/fv3-cam/Ratko.Vasic/Rocky8/ufs-weather-model/tests/1.conf` I used rocoto to run it. It passed that test (`./rt.sh -k -l 1.conf -a epic -r`) It was on Feb 16th. Maybe something changed in the meantime!?

I'm on fe5 node, do you remember which you used? Just curious.

**Comment by zach1221** [comment]
> > @zach1221 I didn't run whole rt.sh, just small test to check if it is working on Hera/Rocky8: `/scratch2/NCEPDEV/fv3-cam/Ratko.Vasic/Rocky8/ufs-weather-model/tests/1.conf` I used rocoto to run it. It passed that test (`./rt.sh -k -l 1.conf -a epic -r`) It was on Feb 16th. Maybe something changed in the meantime!?
> 
> I'm on fe5 node, do you remember which you used? Just curious.
Edit: I'm on Jet also. Hera may be working. I have not tested rocky8 there yet, just Jet.

**Comment by RatkoVasic-NOAA** [comment]
Oh, sorry, I thought you talked about Hera. This is Jet. No, I haven't tested yet. I'm currently installing spack-stack(s) on Jet.

**Comment by jkbk2004** [comment]
@RatkoVasic-NOAA @zach1221 Jet system admin's update: the version ecflow/5.11.4 has been installed on Jet. The current ecflow server is on fe8. We need to test. @BrianCurtis-NOAA Thanks for catching the ecflow issue with system admin!

**Comment by jkbk2004** [comment]
@RatkoVasic-NOAA We need to install Spack stack versions on Rocky8 node on jet.
```
CentOS-7 login:     fe[1-4]
CentOS-7 clusters: kJet, vJet, sJet, and uJet
```

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 here is the progress:
https://github.com/JCSDA/spack-stack/issues/1010

**Comment by zach1221** [comment]
> @jkbk2004 here is the progress: [JCSDA/spack-stack#1010](https://github.com/JCSDA/spack-stack/issues/1010)

@RatkoVasic-NOAA are the checked boxes in JCSDA/spack-stack#1010 completed installs? I ran a test trying to use spack-stack-1.5.1/envs/unified-env on fe5 using ufs-community:develop repo, and received the same error mentioned above. Maybe I need to change something in jet modulefile?

**Comment by RatkoVasic-NOAA** [comment]
@zach1221 I just finished installation of the spack-stack on Jet/Rocky8
1.5.0, 1.5.1 and 1.6.0 versions (with gsi addons)
I'm going to try to compile SRW and WM  using this installation.

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 @zach1221 , spack stacks are installed on Jet/Rocky OS. I tested 1.5.0 and 1.5.1 versions.

UFS-WM: `/mnt/lfs4/HFIP/hfv3gfs/Ratko.Vasic/brisi/ufs-weather-model/tests` (1.conf) I compiled and ran two tests (one global, one regional) using (`./rt.sh -k -l 1.conf -a epic`). Tests passed! You can go ahead and test other tests from rt.conf I used current development branch. In order to run from Rocky login node, I just had to update spack-stack path in `modulefiles/ufs_jet.intel.lua` and dprefix in `tests/rt.sh`

BTW, also SRW: /mnt/lfs4/HFIP/hfv3gfs/Ratko.Vasic/brisi/ufs-srweather-app it compiled OK. Still have to run tests.

**Comment by zach1221** [comment]
Hi, @RatkoVasic-NOAA I'm retesting now, just running the tests sequentially. Do you expect ecflow to be available on rocky8 soon or is that still a work in progress?

**Comment by RatkoVasic-NOAA** [comment]
@zach1221 we have ecflow on jet/Rocky:
`ecflow/5.11.4 (D)`

So rt.sh can be changed to:
```
  module load ecflow/5.11.4
  ECFLOW_START=/apps/ecflow/5.11.4/bin/ecflow_start.sh
```

**Comment by zach1221** [comment]
> @zach1221 we have ecflow on jet/Rocky: `ecflow/5.11.4 (D)`
> 
> So rt.sh can be changed to:
> 
> ```
>   module load ecflow/5.11.4
>   ECFLOW_START=/apps/ecflow/5.11.4/bin/ecflow_start.sh
> ```

Ok great. I tested 1.5.1 and 1.6.0 with a few tests each and they passed. Rocoto also seems to be working so far.

**Comment by zach1221** [comment]
@RatkoVasic-NOAA have you been able to run ecflow, yet on Rocky? I'm getting segmentation fault from rt_utils.sh: line 614  (core dumped) ${PATHRT}/abort_dep_tasks.py . I adjusted rt.sh and ran on both fe5 & fe8 .

**Comment by RatkoVasic-NOAA** [comment]
I haven't. I will try.

**Comment by RatkoVasic-NOAA** [comment]
@zach1221 I tested ufs-wm with rocoto and ecflow:
1) rocoto is working, but there is an issue with slurm. If we have job that brakes through wallclock limit, it hangs as state "COMPLETING", and rocoto never finishes it's job. I opened ticket with Jet admins.
2) for me ecflow also is not working, but in my case it is just hanging (no core dump)

**Comment by zach1221** [comment]
> @zach1221 I tested ufs-wm with rocoto and ecflow:
> 
> 1. rocoto is working, but there is an issue with slurm. If we have job that brakes through wallclock limit, it hangs as state "COMPLETING", and rocoto never finishes it's job. I opened ticket with Jet admins.
> 2. for me ecflow also is not working, but in my case it is just hanging (no core dump)

Ok, noted. I can open a ticket regarding the ecflow issue, unless you have done so already?

**Comment by RatkoVasic-NOAA** [comment]
> 
> Ok, noted. I can open a ticket regarding the ecflow issue, unless you have done so already?

I didn't, please go ahead.

**Comment by RatkoVasic-NOAA** [comment]
@zach1221 @jkbk2004 I think I found solution for ecflow. It is hard to test it, we are currently over disk quota, or something is wrong with FS: `cat: write error: Disk quota exceeded`
I'll open PR with changes for Jet/Rocky.

**Comment by jkbk2004** [comment]
> @zach1221 @jkbk2004 I think I found solution for ecflow. It is hard to test it, we are currently over disk quota, or something is wrong with FS: `cat: write error: Disk quota exceeded` I'll open PR with changes for Jet/Rocky.

@RatkoVasic-NOAA I cleaned up a bit /mnt/lfs4/HFIP/hfv3gfs. Can you try ?

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 yes. It is compiling now. Bit slow, but working for now.

**Comment by zach1221** [comment]
@jkbk2004 I tested the rocky8 changes in PR 2017, and the tests compiled and ran successfully on Rocky8 using ecflow.

**Comment by zach1221** [comment]
Hi, @RatkoVasic-NOAA WM PR 2164 has been merged with the Jet rcoky8 changes, so closing this issue. Please let me know if you have any questions.
