### ISSUE TITLE
Hera OS migration to Rocky 8

### ISSUE THREAD

**Issue by FernandoAndrade-NOAA** [ufs-community/ufs-weather-model#2143]
## Description

Hera, like Jet is transitioning its OS to Rocky 8. Successful regression tests should be confirmed. Rocky 8 is currently available on the hfe[09-12] nodes. hfe12 is available for ecflow testing.

The following schedule was given within the transition announcement:
```
2/6: four front-ends available to all users (hfe09-hfe12)
2/8: 130 nodes available to all users
3/5: 1/3 of Hera (and 50% FGE), all of Niagara
3/19: 2/3 of Hera
4/2: remainder of Hera (remainder of FGE)
```
## Solution

Verify successful regression tests on Hera.

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA has installed new stacks for the hera/jet rocky8 upgrade and tests have been successful

**Comment by jkbk2004** [comment]
@RatkoVasic-NOAA Rocky8 version on hera is this one /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8, right? @hu5970 FYI

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA Rocky8 version on hera is this one /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8, right? @hu5970 FYI

Yes.

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 @zach1221 @ulmononian 
I was preparing PR for Hera/Rocly8, and tests compiled with GNU compiler failed. Problem was with new slurm. When replaced srun with mpirun in job card, it was working. We are currently checking with admins why is GNU not working with srun command.

**Comment by RatkoVasic-NOAA** [comment]
GNU issue is solved. On Hera/Rocky GNU compiler is `gnu/9.2.0b` and Open MPI is `openmpi/4.1.6_gnu9.2.0`
Now both GNU and Intel are working. Intel have bit identical results, and GNU have new results due to different Open MPI version.

**Comment by BrianCurtis-NOAA** [comment]
@RatkoVasic-NOAA is it going to be possible to update to a much newer version of GNU? 9.2 is very old.

**Comment by RatkoVasic-NOAA** [comment]
Yes, on Hera there is new GNU compiler, `gnu/13.2.0`. We can open new issue for that. For this issue/PR we are just moving from CentOS to Rocky.

**Comment by BrianCurtis-NOAA** [comment]
> Yes, on Hera there is new GNU compiler, `gnu/13.2.0`. We can open new issue for that. For this issue/PR we are just moving from CentOS to Rocky.

That would be great, thanks Ratko!

**Comment by zach1221** [comment]
Closing as, 2194 has been merged.
