### ISSUE TITLE
Request for prototype/hr3 tag 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#2144]
## Description
We are going to be using hash https://github.com/ufs-community/ufs-weather-model/tree/a837cfcb0c79803e13a1375a362d3d0b14b62320 for HR3 prototype runs.  It would be great to have a tag prototype/hr3 from this hash. 

## Solution
A tag prototype/hr3 of hash a837cfcb0c79803e13a1375a362d3d0b14b62320 

## Alternatives
We'll only reference a hash 

## Related to
https://github.com/NOAA-EMC/global-workflow/issues/2331

**Comment by DeniseWorthen** [comment]
A tag has been created https://github.com/ufs-community/ufs-weather-model/releases/tag/prototype%2Fhr3

**Comment by JessicaMeixner-NOAA** [comment]
Thank you @DeniseWorthen !
