### ISSUE TITLE
tests which fail to run are not reported correctly

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2150]
## Description

In testing for a CICE PR, I ran a subset of tests. They failed to run because the accompanying change to ice_in was not present (the model aborted). In this case, the log file showed these as 'fail to compare' rather than 'fail to run'

```
* TEST cpld_control_c48_intel: FAIL TO COMPARE
-- LOG: /scratch1/NCEPDEV/nems/Denise.Worthen/WORK/ufs-weather-model/tests/logs/log_hera/rt_cpld_control_c48_intel.log
```

which shows all the comparison files were missing. But the run directory shows that the model aborted
```
+ srun --label -n 20 ./fv3.exe
16: Abort(128) on node 16 (rank 16 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 128) - process 16
17: Abort(128) on node 17 (rank 17 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 128) - process 17
18: Abort(128) on node 18 (rank 18 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 128) - process 18
19: Abort(128) on node 19 (rank 19 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 128) - process 19
 0: slurmstepd: error: *** STEP 56100882.0 ON h18c55 CANCELLED AT 2024-02-23T19:59:11 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: h18c55: tasks 0-19: Killed
srun: Terminating StepId=56100882.0
```

### To Reproduce:

Check out the develop branch and point to this branch of CICE https://github.com/DeniseWorthen/CICE/tree/feature/pio_options

Run the cpld_control_c48 test.

**Comment by zach1221** [comment]
Hi, @DeniseWorthen . I tested for this issue again but could not recreate it. The log output stated the case failed to compare, as the RESTART files were missing.
+ echo '* TEST cpld_control_c48_intel: FAILED: UNABLE TO RUN COMPARISON'
LOG: /work/noaa/nems/zshrader/hercules/ufs-weather-model/tests/logs/log_hercules/run_cpld_control_c48_intel.log'`

And the err log in the experiment directory stated 
+ srun --label -n 20 ./fv3.exe
12: FATAL from PE     0: Permission denied: netcdf_file_open:./RESTART/20210322.180000.MOM.res.nc` 

Do you think this could have been resolved with 2225?
