### ISSUE TITLE
Regression test is failing on Hercules due to file permission issue

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#2152]
When I run regression test on Hercules some tests are failing with the following error:

```
++ cp -r '/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20221101/FV3_input_data48/INPUT_L127_v2_sfc/*' ./INPUT/.
cp: cannot stat '/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20221101/FV3_input_data48/INPUT_L127_v2_sfc/*': Permission denied
+ '[' 1 -eq 0 ']'
+ write_fail_test
+ echo 'control_c48.v2.sfc_intel failed in run_test'
+ exit 1
```

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA Sym link was missing some files there. can you try one more time?

**Comment by zach1221** [comment]
Hi, @DusanJovic-NOAA . Following up here, were you able to re-run those tests on hercules?

**Comment by DusanJovic-NOAA** [comment]
The issue with file permission seems to be fixed. I ran one test that failed a few days ago and it passed today. I'll run a full regression test now just to confirm that everything works as expected.

**Comment by DusanJovic-NOAA** [comment]
Regression test passed successfully.
