### ISSUE TITLE
Need new modules for ufs build on hera rocky nodes, jet rocky nodes, and orion rocky nodes

### ISSUE THREAD

**Issue by GeorgeVandenberghe-NOAA** [ufs-community/ufs-weather-model#2167]

**Comment by GeorgeVandenberghe-NOAA** [comment]
The hera, jet, and orion HPC clusters are transitioning to the Rocky  O.S. from CenTOS.    Most dependencies will have to be rebuilt.   ufs-weather-model depends on spack-stack for its dependencies and the path to spack-stack has changed on nodes running Rocky because they share space with the CenTOS nodes and the packages are incompatible.   The hera , jet, and orion ufs-weather-model build will need path changes in ./modulefiles/  On Jet the change should be FROM prepend_path("MODULEPATH", "/mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core")   to prepend_path("MODULEPATH", "/mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8/install/modulefiles/Core"). 

 On hera,  the module should use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8/install/modulefiles/Core

Other earlier forks of the model on jet and hera should select from one of these paths, depending on spack-stack level needed
HERA
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.0/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.0/envs/unified-env-rocky8
 /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8

On JET the paths are
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.0/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.0/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8


Orion paths have not yet been specified.

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA @jkbk2004 fyi

@GeorgeVandenberghe-NOAA stack updates for the orion os upgrade are forthcoming

**Comment by hu5970** [comment]
The whole Hera will be Rocky 8 and the current model failed during compile:

```
_physics_cap.F90.o CMakeFiles/ccpp_physics.dir/ccpp_FV3_global_nest_v1_radiation_cap.F90.o CMakeFiles/ccpp_physics.dir/ccpp_FV3_global_nest_v1_stochastics_cap.F90.o CMakeFiles/ccpp_physics.dir/ccpp_FV3_global_nest_v1_time_vary_cap.F90.o
/usr/bin/ar: Relink `/apps/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `sinf'
Error running link command: Segmentation fault
make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:2842: FV3/ccpp/physics/libccpp_physics.a] Error 1
make[2]: *** Deleting file 'FV3/ccpp/physics/libccpp_physics.a'
make[2]: Leaving directory '/scratch1/BMC/wrfruc/mhu/rrfs/v0.8.4/rrfs-workflow/temp/ufs-weather-model/tests/build_fv3_32bit'
make[1]: *** [CMakeFiles/Makefile2:622: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/all] Error 2
```

Is there a brach or PR to fix the compiling with Rocky 8?

Thanks, 
Ming

**Comment by jkbk2004** [comment]
@hu5970 I am following up hera rocky8 update at https://github.com/ufs-community/ufs-weather-model/issues/2143

**Comment by GeorgeVandenberghe-NOAA** [comment]
There are generally (GSI may be an exception) no modules in the various repositories to support Rocky8 nodes.   The issue description defines the problem and what needs to be done but a code manager will have to actually do this.   Meanwhile, pending that resolution, the issue description describes what to do manually  for most repositories, not just ufs-weather-model until  repository modules are in place.

**Comment by SamuelTrahanNOAA** [comment]
The compile_s2swa_32bit_pdlib_debug_intel in the regression tests on Rocky Hera are segfaulting in the compiler:

```
/bin/ar: Relink `/apps/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `sinf'
Error running link command: Segmentation fault
make[2]: *** [FV3/ccpp/framework/src/CMakeFiles/ccpp_framework.dir/build.make:97: FV3/ccpp/framework/src/libccpp_framework.a] Error 1
make[2]: *** Deleting file 'FV3/ccpp/framework/src/libccpp_framework.a'
make[1]: *** [CMakeFiles/Makefile2:886: FV3/ccpp/framework/src/CMakeFiles/ccpp_framework.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
warning #15396: Vector specification for function 'shr_const_mod_mp_shr_const_isspval_' is ignored with specified optimization options.
/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/nested-workflow/sorc/commit-me/CDEPS-interface/CDEPS/share/shr_const_mod.F90(89): (col. 30) warning #13401: vector function was emulated
/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/nested-workflow/sorc/commit-me/CDEPS-interface/CDEPS/share/shr_const_mod.F90(89): (col. 30) warning #13401: vector function was emulated
warning #15396: Vector specification for function 'ufs_const_mod_mp_shr_const_isspval_' is ignored with specified optimization options.
/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/nested-workflow/sorc/commit-me/CMEPS-interface/CMEPS/ufs/ufs_const_mod.F90(84): (col. 30) warning #13401: vector function was emulated
/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/nested-workflow/sorc/commit-me/CMEPS-interface/CMEPS/ufs/ufs_const_mod.F90(84): (col. 30) warning #13401: vector function was emulated
/bin/ar: Relink `/apps/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `sinf'
Error running link command: Segmentation fault
make[2]: *** [GOCART/Process_Library/CMakeFiles/Process_Library.dir/build.make:112: GOCART/Process_Library/libProcess_Library.a] Error 1
make[2]: *** Deleting file 'GOCART/Process_Library/libProcess_Library.a'
make[1]: *** [CMakeFiles/Makefile2:1502: GOCART/Process_Library/CMakeFiles/Process_Library.dir/all] Error 2
/bin/ar: Relink `/apps/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `sinf'
Error running link command: Segmentation fault
```

**Comment by RatkoVasic-NOAA** [comment]
@SamuelTrahanNOAA are you running on Hera? Today they moved default login node to Rocky OS. If you want to use current ufs-weather-model, you have to ssh to hfe01-hfe04 (CentOS).
If you want to use Rocky login node, you can use code from [this](https://github.com/ufs-community/ufs-weather-model/pull/2194) PR before it goes in develop branch.
I just ran regression test with s2swa_32bit_pdlib_debug only (5.conf in /scratch2/NCEPDEV/fv3-cam/Ratko.Vasic/2143/ufs-weather-model/tests). It compiled OK and is running model now.

**Comment by SamuelTrahanNOAA** [comment]
Thank you, @RatkoVasic-NOAA, your PR appears to be what I need. I'm testing a pair of bug fixes for the nesting on Rocky 8 on Hera. My regression tests were on hfe10 and failed with the message I sent. Now that I have your PR, I'll test my bug fixes on top of it.
