### ISSUE TITLE
Branch/tag cleanup

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#218]
## Description

Time to clean up some branches and tags.

Do we still need the "documentation branch"?

**Comment by climbfuji** [comment]
I think we can also delete tags
```
ufs-v1.0.0.beta01 
ufs-v1.0.0.beta01doc
```

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA do you agree that we can delete the "documentation" branch as well as tags
```
ufs-v1.0.0.beta01 
ufs-v1.0.0.beta01doc
```
? Please let me know and I'll try to delete them.

**Comment by junwang-noaa** [comment]
Yes, I think we can delete them

**Comment by climbfuji** [comment]
I deleted tags
```
ufs-v1.0.0.beta01 
ufs-v1.0.0.beta01doc
```
and branch `documentation`.
