### ISSUE TITLE
rt.sh crashes with 'Permission denied' error while creating run directory on Gaea

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#2198]
## Description

When I run regression test on Gaea rt.sh crashes with 'Permission denied' error while creating run directory. Script tried to create directory under /gpfs/f5/epic/scratch, and I do not have permission to write to that directory.

### To Reproduce:

1. Run rt.sh on Gaea from a user account which is not member of the epic project.

## Output

```
+ PARTITION=c5
+ STMP=/gpfs/f5/epic/scratch
+ PTMP=/gpfs/f5/epic/scratch
+ SCHEDULER=slurm
+ mkdir -p /gpfs/f5/epic/scratch/Dusan.Jovic
mkdir: cannot create directory ‘/gpfs/f5/epic/scratch/Dusan.Jovic’: Permission denied
++ echo 'rt.sh error on line 897'
rt.sh error on line 897
++ cleanup

```

**Comment by FernandoAndrade-NOAA** [comment]
Hi @DusanJovic-NOAA, users outside of the epic group on Gaea will need to update the paths referring to /gpfs/f5/epic/ in order to run WM RTs. A permissions update to the directories unfortunately likely wouldn't work as I've noticed something on Gaea's back-end has regularly been resetting directories to their more restricted defaults after the C5/F5 transition.

**Comment by jkbk2004** [comment]
might need to add one more global variable to set a f5 scratch project specific path name: default epic.

**Comment by DusanJovic-NOAA** [comment]
Maybe something like this:

```diff
diff --git a/tests/rt.sh b/tests/rt.sh
index fd6464c6..823bca5a 100755
--- a/tests/rt.sh
+++ b/tests/rt.sh
@@ -674,8 +674,9 @@ elif [[ $MACHINE_ID = gaea ]]; then
   QUEUE=normal
   COMPILE_QUEUE=normal
   PARTITION=c5
-  STMP=/gpfs/f5/epic/scratch
-  PTMP=/gpfs/f5/epic/scratch
+  dprefix=${dprefix:-/gpfs/f5/$ACCNR/scratch/$USER}
+  STMP=${STMP:-$dprefix/RT_BASELINE}
+  PTMP=${PTMP:-$dprefix/RT_RUNDIRS}
 
   SCHEDULER=slurm

```
Similar to how it's done on Jet.

**Comment by JustinPerket** [comment]
> Maybe something like this:
> 
> ```diff
> diff --git a/tests/rt.sh b/tests/rt.sh
> index fd6464c6..823bca5a 100755
> --- a/tests/rt.sh
> +++ b/tests/rt.sh
> @@ -674,8 +674,9 @@ elif [[ $MACHINE_ID = gaea ]]; then
>    QUEUE=normal
>    COMPILE_QUEUE=normal
>    PARTITION=c5
> -  STMP=/gpfs/f5/epic/scratch
> -  PTMP=/gpfs/f5/epic/scratch
> +  dprefix=${dprefix:-/gpfs/f5/$ACCNR/scratch/$USER}
> +  STMP=${STMP:-$dprefix/RT_BASELINE}
> +  PTMP=${PTMP:-$dprefix/RT_RUNDIRS}
>  
>    SCHEDULER=slurm
> ```
> 
> Similar to how it's done on Jet.

I do something very similar.  but I define `STMP` and `PTMP` in my environment. I would be happy to see a fix like this so I won't have to keep editing rt.sh as well.
