### ISSUE TITLE
extremely verbose write statement in FV3

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#2209]
## Description
This write statement produces many megabytes of output for some configurations. It is enough to have a significant impact on the runtime:

```f90
write(0,*) ' history_type_store_data3D kinds ', kind_phys, kind(work), lbound(work), ubound(work), size(work)
```

### To Reproduce:
Run FV3 with the write component. Witness the write statement

**Comment by DusanJovic-NOAA** [comment]
I already removed it in this PR:

https://github.com/NOAA-EMC/fv3atm/pull/803/files#diff-fbce29fff88e35fff84fde16c5b1f1a366a0940468defddf41b28a940cb9833d

**Comment by SamuelTrahanNOAA** [comment]
That PR is still a draft.

Our fix is identical (delete the line) so it doesn't matter which one is merged first.

**Comment by SamuelTrahanNOAA** [comment]
This was actually fixed in an earlier pull request, not 2201. Probably the pull request Dusan points to, two messages ago (https://github.com/NOAA-EMC/fv3atm/pull/803/) but I can't be certain.
