### ISSUE TITLE
baseline doesn't exist on wcoss2

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#2210]
## Description

I just cloned latest UWM but unable to launch rt.sh on wcossw with error
+ [[ ! -d /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20240315 ]]
+ echo 'Baseline directory does not exist:'

### To Reproduce:
checkout latest's UWM and run rt.sh

**Comment by jiandewang** [comment]
jiande.wang@dlogin09:/lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs> ls -l
total 148
drwxr-sr-x  11 emc.nems nems  4096 Jun  9  2022 BM_IC-20220207
drwxrwsr-x 113 emc.nems emc  12288 Nov  6 19:42 develop-20231106
drwxrwsr-x 115 emc.nems emc  12288 Nov 15 14:31 develop-20231108
lrwxrwxrwx   1 emc.nems nems    16 Nov 15 14:32 develop-20231109 -> develop-20231108
drwxr-sr-x 115 emc.nems emc  12288 Nov 16 19:15 develop-20231115
drwxr-sr-x 115 emc.nems emc  12288 Nov 17 19:01 develop-20231117
drwxr-sr-x 115 emc.nems emc  12288 Nov 17 19:01 develop-20231122
drwxr-sr-x 115 emc.nems nems 12288 Nov 30 20:50 develop-20231130
drwxr-sr-x 116 emc.nems nems 12288 Jan 10 19:09 develop-20240111
drwxr-sr-x 120 emc.nems emc  12288 Feb  7 14:24 develop-20240126
drwxr-sr-x 120 emc.nems emc  12288 Feb  7 14:24 develop-20240208
drwxr-sr-x 120 emc.nems nems 12288 Feb 13 13:34 develop-20240212
drwxr-sr-x 120 emc.nems nems 12288 Feb 13 20:55 develop-20240213
drwxr-sr-x  43 emc.nems nems  4096 Oct 26  2022 input-data-20220414
drwxr-sr-x  39 emc.nems nems  4096 Apr 24  2023 input-data-20221101

**Comment by jiandewang** [comment]
@jkbk2004 can you sync baseline dir from prod to dev so that I can run test ?

**Comment by jkbk2004** [comment]
@jiandewang I don't have access to wcoss2. @BrianCurtis-NOAA may follow up.

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 has been really slow syncing, but it was started last night. Might be done by now.

**Comment by jiandewang** [comment]
@BrianCurtis-NOAA thanks. Close this issue.
