### ISSUE TITLE
Can next set of PRs include a ccpp-framework update (CI updates only)

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#2216]
## Description

This was merged without being tested in the UFS, and the submodule pointer needs to be updated: https://github.com/NCAR/ccpp-framework/pull/551#event-12272308346

## Solution

It only affects the CI scripts in ccpp-framework, but still it would be nice to include this update in one of the next PRs.

## Alternatives

Wait until the next ccpp-framework PR is tested in the UFS WM

## Related to

n/a

**Comment by DusanJovic-NOAA** [comment]
I updated ccpp/framework submodule (to 0f416a2 commit) in my branch for #2218 (remove nowarn) and submitted regression test on Hercules. So far ~20 tests passed. I expect all tests will pass, I do not see any issues with updated ccpp/framework.
