### ISSUE TITLE
add regression tests for coupled model at c96 (1deg) and c192 (1/2deg)

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#222]
**Description**
Non-benchmark regression tests should use c96+1deg ocean/ice. 

**Solution**
Create a set of tests which replicate the current c96+1/4 deg ocean/ice tests. 

**Alternatives**

**Additional context**

**Comment by DeniseWorthen** [comment]
@junwang-noaa Do we have a target run-time in mind for the RTs in the unified repo? The current 1d BM test run between 14 (no wave) to 24 (wave) minutes. Will this be an acceptable time or should we decrease to 12h?  

The control cases (c96, c192) now run for 1 day; the restart test is done using a 12h c96 test. The c96 control runs in about 2minutes.

**Comment by junwang-noaa** [comment]
Generally it's good to have the individual test finished within 30minutes.
So I think the current 1d BM tests are OK so far. We may need to reduce to
12h when the fv3 vertical levels are increased to 127.
