### ISSUE TITLE
Add DATM component to s2s

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#224]
**Description**
The data atmosphere component (DATM) will be added to the s2s repository.

**Solution**
1. The DATM will be added to s2s.
2. Files used by CMake will be added to DATM repository.
3. The DATM-MOM6-CICE6-CMEPS model will be built using CMake.
4. A separate test directory (test_datm) will be created.
5. The parm directory will be moved to test_datm.
6. New baseline results will be created on Hera and Orion.

**Comment by junwang-noaa** [comment]
Bin, we will not make any updates in s2s repo after the current PRs are merged. After Rahul's [PR #217](https://github.com/ufs-community/ufs-weather-model/pull/217) is committed to ufs-weather (panned for tomorrow), it will be able to support s2s/DATM development on ufs-weather. So all the future s2s development will go to ufs-weather (we may rename the repo). So please add DATM in ufs-weather, not s2s.

**Comment by binli2337** [comment]
This issues is replaced by Issue #255.
