### ISSUE TITLE
Optimize compute resources for C96, C192, C384 regression tests

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#226]
**Description**
Optimize the number of PETs to efficiently run C96, C192, C384 regression tests described in Issue ufs-community/ufs-weather-model#222 

**Solution**
Trial-and-error tests will be run on Orion to come up with efficient use of compute resources

**Comment by MinsukJi-NOAA** [comment]
ATM+OCN+ICE benchmark can be found [here](https://docs.google.com/spreadsheets/d/1cdi81HqhXMaYawFb6ErqbPA2_fPZHY8EL79GK--Rm6s/edit#gid=0).
C384 with 1/4 deg OCN/ICE is done.
C192 and C96 to be added.

**Comment by MinsukJi-NOAA** [comment]
Summary of C384 with 1/4 deg OCN/ICE on Orion
![C384](https://user-images.githubusercontent.com/57227195/96908084-284a9f00-146a-11eb-9779-f260ad1db471.png)

**Comment by arunchawla-NOAA** [comment]
@MinsukJi-NOAA can this ticket be closed?

**Comment by MinsukJi-NOAA** [comment]
@arunchawla-NOAA I was thinking of revising this for the latest regression test cases, and updating the run configuration. I guess we could close this for now, and reopen it in the future.
