### ISSUE TITLE
module-setup.sh does not recognize Frontera

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/ufs-weather-model#2266]

**Comment by gspetro-NOAA** [comment]
@benjamin-cash Is this still a problem? I see that `module-setup.sh` currently has a stanza for Frontera, so in theory, it should work, but sometimes theory != practice.

**Comment by benjamin-cash** [comment]
Hi @gspetro-NOAA - this has been sort of overtaken by events so I think we can close it. Thanks for checking in!
