### ISSUE TITLE
Compile ufs_weather_model on Gaea-C5

### ISSUE THREAD

**Issue by DavidBurrows-NCO** [ufs-community/ufs-weather-model#2268]
## Description
ufs_weather_model is failing to build on Gaea-C5

## Solution
Update modulefiles/ufs_gaea.intel.lua to compile ufs_weather_model on Gaea-C5

## Alternatives
NA

## Related to
- required to support NOAA-EMC/global-workflow/issues/2535

**Comment by DusanJovic-NOAA** [comment]
@DavidBurrows-NCO Which build errors do you see on Gaea?

**Comment by DavidBurrows-NCO** [comment]
@DusanJovic-NOAA 
```
cd ufsm
module use modulefiles
module load ufs_gaea.intel
export CMAKE_FLAGS="-DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16"
./build.sh
```
```

UFS MODEL DIR: /gpfs/f5/epic/scratch/David.Burrows/ufs_fails_to_build_on_gaea/ufsm
cmake: /opt/cray/pe/gcc/10.3.0/snos/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by cmake)
```

This occurs because cmake is not loaded.

**Comment by DusanJovic-NOAA** [comment]
I see. It was loaded in the old ufs_gaea.intel.lua

https://github.com/ufs-community/ufs-weather-model/blob/f42e347b1cad15b4b2470fecb17cb19bb2d19459/modulefiles/ufs_gaea.intel.lua

**Comment by DavidBurrows-NCO** [comment]
@DusanJovic-NOAA hmm. Maybe I'm confused. If I look at the develop branch then cmake is not loaded: [develop branch](https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_gaea.intel.lua)

**Comment by DusanJovic-NOAA** [comment]
It is not loaded now, but in the 'original' version of ufs_gaea.intel.lua (before c5 support was added) it was. The initial version of  ufs_gaea-c5.intel.lua did not have it. Here https://github.com/ufs-community/ufs-weather-model/blob/f42e347b1cad15b4b2470fecb17cb19bb2d19459/modulefiles/ufs_gaea.intel.lua

**Comment by DusanJovic-NOAA** [comment]
Then maybe this line is not needed anymore:

https://github.com/ufs-community/ufs-weather-model/blob/85d73f2091904fcb434162702182d20c1974aebd/tests/rt.sh#L724

This was added as a quick fix for cmake issue, while in fact the problem was that cmake was not actually loaded from spack-stack installation.
