### ISSUE TITLE
upgrade MERRA2 climatology from 2003-2014 mean to 2014-2024 mean

### ISSUE THREAD

**Issue by AnningCheng-NOAA** [ufs-community/ufs-weather-model#2272]
## Description

UFS uses MERRA2 climatology from 2003 to 2014 mean. The dataset is out of date and needed upgrade

## Solution

45 years of MERRA2 dataset from 1980 to 2024 are downloaded and processed. Four sets of climatology 80s (1980 to 1993 mean), 90s (1994-2003 mean), 20s (2003-2014 mean) and 21s (2014-2024 mean) are compared for 2020 summer using C768L127 UFS p8. It turns out 2014 to 2024 mean give the best AC score  (Attached figure) and vsdb tests are also more reasonable.  Two figures on aerosol variation for past 45 years have been attached.  The sulfate has the most regional variation, so might have the most influence on the results. 

![ts_merra2_5](https://github.com/ufs-community/ufs-weather-model/assets/4829750
![ts_merra2_su](https://github.com/ufs-community/ufs-weather-model/assets/48297505/b4f15d1e-cfe5-44eb-a3e8-f42c9ebee2c0)
5/1e771024-4f1e-417a-8778-7176bf980913)
![merra2_AC](https://github.com/ufs-community/ufs-weather-model/assets/48297505/ec769a4b-6db9-4f00-8bbe-dbbf45bb5735)

## Related to

- https://github.com/ufs-community/ufs-weather-model/pull/2273

**Comment by DeniseWorthen** [comment]
@AnningCheng-NOAA I've edited what you provided to move your text outside of the <-- and --> sections. Please use the "preview" button in the future so you can be sure you the information you are providing is visible. Thanks.

**Comment by AnningCheng-NOAA** [comment]
@DeniseWorthen Thankyou! will do

**Comment by DeniseWorthen** [comment]
I forgot to "save" my changes ;-). It should look correct now.

**Comment by NickSzapiro-NOAA** [comment]
Merged in #2273
