### ISSUE TITLE
add waves into debug tests

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#229]
When running the debug test, we don't have a way right now to pass WW3 debug flags.  This needs to be updated and we need to make sure WW3 can successfully run with debug flags turned on as well.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Is the any progress on this issue?

**Comment by JessicaMeixner-NOAA** [comment]
Not really.  We still need to have the build updated for WW3 to accept the DEBUG flags from the top level to get turned on.  It does look likely that the one-way coupling test would work.  Haven't had a chance to check the S2S in a while, but I think that still crashes.   Right now I'm working on the MPI issues for waves among other things.  So this would be after that.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA  I tested whether it was possible to build S2SW in debug mode (knowing that Waves itself would not be compiled in debug mode). The model fails with a 'divide by zero'. It is pointing to ``w3initmd.F90:627``. This may or may not be the actual failure? I have no idea where in the source code tree this routine might be.

**Comment by JessicaMeixner-NOAA** [comment]
The model fails in build mode? 

This is the issue of not actually building WW3 in debug, we don't get the stack trace.   We need to manually add traceback in the WW3 build for this.  

It was my understanding that this task is waiting for the WW3 build update to accept the DEBUG flags, which would come in with updating WW3 to cmake.  Is that not true anymore?

**Comment by DeniseWorthen** [comment]
No, the S2SW builds with DEBUG=Y but when run, it fails with the error I pointed to. The model fails with (in err): 

``196: forrtl: error (73): floating divide by zero``

If I do a back trace on the core file, I get the error in the w3initmd.F90 as the first failure.

/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_201936/cpld_control_wave

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I ran a quick test with traceback.  The line that said divide by zero didn't make sense as the value should not be zero.  I ran a test w/it printed out. Sure enough... not zero and we got an error somewhere else.  Needless to say, not likely going to be a quick fix.

**Comment by JessicaMeixner-NOAA** [comment]
I have added a debug test that has waves and am actively debugging this.  Currently, I have hard-coded an update in WW3 which will have WW3 compile with debug flags.  So far I've found about 4 different spots where WW3 divides by zero or takes a log of zero.   My test can be seen in the branch here: https://github.com/JessicaMeixner-NOAA/ufs-weather-model/tree/feature/addwavetests/tests

**Comment by JessicaMeixner-NOAA** [comment]
With WW3 hard coded to have debug flags in the compile, and some sort of temporary fixes to get around https://github.com/NOAA-EMC/WW3/issues/497, https://github.com/NOAA-EMC/WW3/issues/487 and one other error of a log(0) the debug test will run. However, with these same fixes if we do not compile the wave model in debug mode, we still get errors in places where there are not errors (because if you print the value of the 'divide by zero' errors, those values are not actually zero).  Working on fixes for the known WW3 issues now and continuing to work on trying to get this to work without WW3 being compiled with debug flags so it can go into the test before we have the proper CMAKE build to pass the information down to compile with debug in WW3.

**Comment by JessicaMeixner-NOAA** [comment]
A fix for NOAA-EMC/WW3#487 has been merged to the WW3 develop branch.  A fix for the divide by zero issue in WW3 NOAA-EMC/WW3#497 was found which had no impact to non-debug standalone WW3 regression tests, but we are going to explore adding one more additional improvement to this fix before merging it to WW3, which should help be a better future-proof.  These two fixes allow WW3 to run w/the hard coding the WW3 build to use debug flags.  We'll try again without this hard-coding to see if WW3 will pass the debug test, however we do not anticipate that this will work.

**Comment by MatthewMasarik-NOAA** [comment]
From testing last week we concluded that we aren't able to add WW3 into debug mode prior to the CMAKE build system.  The determining factor was we could not consistently pass RTs when we alternated debug mode (ON/OFF) for runs successively or concurrently, though each of the runs were consistently successful when run as a one-off in a fresh repository.  For those interested in doing one-off debug runs, it is easy to hard-code WW3 to be in debug mode and use the compile options of your choice.  I'll show the edit required to do this below, though first I'll give the exact compile option strings we tested with and whether or not they were successful.
<br/>

1.   __WW3 debug options__:  compiles/runs successfully.

```bash
optc="$optc -O0 -debug all -warn all -check all -check noarg_temp_created -fp-stack-check -heap-arrays -traceback -fpe0"
```

2.  __UFS debug options (without `-init=snan,arrays`)__:  compiles/runs successfully.

```bash
optc="$optc -O0 -check -check noarg_temp_created -check nopointer -warn -warn noerrors -fp-stack-check -fstack-protector-all -fpe0 -debug -ftrapuv"
```
3. __UFS debug options + `-init=snan,arrays`__:  compiles successfully/run fails.

```bash
optc="$optc -O0 -check -check noarg_temp_created -check nopointer -warn -warn noerrors -fp-stack-check -fstack-protector-all -fpe0 -debug -ftrapuv -init=snan,arrays"
```
<br/>

The run failure in 3. above occurs in during initialization in the WW3 ESMF cap, `wmesmfmd.F90`.  The run terminates due to a '`forrtl: error (65): floating invalid`' (e.g., NaN value, divide-by-zero, etc.).  An issue has been submitted for this, [NOAA-EMC/WW3#552](https://github.com/NOAA-EMC/WW3/issues/552).
<br/>

### Hard-code debug mode in WW3
_Instructions for Intel compiler_:  Edits only need to be made in [WW3/model/bin/cmplr.env#L163-L181](https://github.com/NOAA-EMC/WW3/blob/develop/model/bin/cmplr.env#L163-L181), where the `if`-blocks for both 'debugging options' and 'optimized options' should be commented out and replaced with the option string you like.  For example, using 2. above:
```bash
#  # optimized options
#  if [ -z "$(echo $cmplr | grep debug)" ] ; then
#    optc="$optc -O3"
#    optl="$optl -O3"
#  fi

  # profiling option
  if [ ! -z "$(echo $cmplr | grep prof)" ] ; then
    optc="$optc -p"
    optl="$optl -p"
  fi

### UFS Opts
optc="$optc -O0 -check -check noarg_temp_created -check nopointer -warn -warn noerrors -fp-stack-check -fstack-protector-all -fpe0 -debug -ftrapuv"

#  # debugging options
#  if [ ! -z "$(echo $cmplr | grep debug)" ] ; then
#    optc="$optc -O0 -debug all -warn all -check all -check noarg_temp_created -fp-stack-check -heap-arrays -traceback -fpe0"
#    optl="$optl -O0 -traceback"
#  fi
```

**Comment by MatthewMasarik-NOAA** [comment]
One correction to the code above, the `optl` for 'debugging options' needs to be retained.
```bash
#  # optimized options
#  if [ -z "$(echo $cmplr | grep debug)" ] ; then
#    optc="$optc -O3"
#    optl="$optl -O3"
#  fi

  # profiling option
  if [ ! -z "$(echo $cmplr | grep prof)" ] ; then
    optc="$optc -p"
    optl="$optl -p"
  fi

#  # debugging options
#  if [ ! -z "$(echo $cmplr | grep debug)" ] ; then
#    optc="$optc -O0 -debug all -warn all -check all -check noarg_temp_created -fp-stack-check -heap-arrays -traceback -fpe0"

### UFS Opts
  optc="$optc -O0 -check -check noarg_temp_created -check nopointer -warn -warn noerrors -fp-stack-check -fstack-protector-all -fpe0 -debug -ftrapuv"
  optl="$optl -O0 -traceback"
#  fi
```

**Comment by arunchawla-NOAA** [comment]
@MatthewMasarik-NOAA @JessicaMeixner-NOAA @junwang-noaa is this still an issue with cmake build for ww3? if yes then we need to add the dependency of the cake build for ww3 under ufs ?

**Comment by JessicaMeixner-NOAA** [comment]
This is dependent on CMAKE and hopefully can be resolved soon.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA @JessicaMeixner-NOAA Can we get an update for debug when using the existing (wmesmf) cap?

**Comment by JessicaMeixner-NOAA** [comment]
For ATMW the wmesmf will pass debug.  For S2SW, this work was paused as we were focusing on using the mesh based cap for p8.  Depending on long term cap plans this work will be revisited as necessary for wmesmf & S2S.
