### ISSUE TITLE
Regression tests that are not looking for specific output files can fail silently

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#23]
Some of the DEBUG regression tests do not check for the presence of output files generated by the model, the idea being that the code should just run and complete without an error. However, even if the code crashes rt.sh still thinks that the model ran ok (see issue https://github.com/ufs-community/ufs-weather-model/issues/24 for an example).

**Comment by climbfuji** [comment]
This issue is avoided for the ufs_public_release branches only in https://github.com/ufs-community/ufs-weather-model/pull/25 by explicitly checking for output files from the DEBUG tests.

**Comment by junwang-noaa** [comment]
Dom,

Do you still want to work on this issue, or if we can close it?

**Comment by climbfuji** [comment]
I think this needs to be fixed for the develop branch - all debug tests should look for specific output files.

**Comment by junwang-noaa** [comment]
I see, will add output files for debug tests in  the next develop branch
commit.

**Comment by climbfuji** [comment]
@junwang-noaa do you know if this has been fixed, i.e. are all DEBUG tests looking for output files nowadays? I know that all the DEBUG tests I put in do.

**Comment by junwang-noaa** [comment]
Sorry, not yet. We still need to add output files
for fv3_ccpp_control_debug and fv3_ccpp_stretched_nest_debug.

**Comment by climbfuji** [comment]
Closed via https://github.com/ufs-community/ufs-weather-model/commit/248b609b7a3ba8e0ef05085218a0e3c0cd2b739c
