### ISSUE TITLE
Derecho not using SS 1.6

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2314]
https://github.com/ufs-community/ufs-weather-model/blob/a183a521516110cc9bcb86d853bd9b0dccef5bc7/modulefiles/ufs_derecho.intel.lua#L12

**Comment by jkbk2004** [comment]
@RatkoVasic-NOAA we clearly missed derecho at https://github.com/ufs-community/ufs-weather-model/pull/2093/files. Can you come with hot fix? Strange thing is test ran somehow.

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004  @DeniseWorthen I'll check it soon.

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 it is done. PR #2316 
Reason it worked is that Derecho is not using `ufs_common`, it is using spack-stack's `ufs-weather-model-env` environment.

**Comment by DeniseWorthen** [comment]
This issue should have been closed with merge of PR #2283
