### ISSUE TITLE
 cpld_debug_gfsv17_intel failure on Derecho in the PR 2324

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#2338]
## Description

The cpld_debug_gfsv17_intel case passes when running on the develop branch. But it crashes from https://github.com/ufs-community/ufs-weather-model/pull/2324 with error message:
```
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
libpthread-2.31.s  000014C29057C8C0  Unknown               Unknown  Unknown
fv3.exe            0000000012250BF8  med_mp_datainitia        2147  med.F90
```

**Comment by DeniseWorthen** [comment]
It also fails at develop ([a3d4733](https://github.com/ufs-community/ufs-weather-model/commit/a3d4733443950809b4dc1070c6f52c18d89ce045)) if the configuration variable ``write_restart_at_endofrun=.false.`` is present.
