### ISSUE TITLE
Update Wiki Page: "Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents"

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#234]
Update/Review Changes to Wiki Page: "Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents"

I have created a temporary location for my Wiki page update in my own repository [HERE](/BrianCurtis-NOAA/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents)

https://github.com/BrianCurtis-NOAA/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents

Please discuss here any changes, inaccuracies or improvements and I will make them ASAP.

NOTE: I expect information to still be outdated or inaccurate for items I was unsure of.

The section at the bottom titled "Specifics for NOAA Staff" will contain special instructions for NOAA staff to reference that pertain to our tier1/tier2 systems. i.e. Rocoto or ECFlow

**Comment by junwang-noaa** [comment]
Brian, Please update the "HERE" link, it does not work.

**Comment by BrianCurtis-NOAA** [comment]
Both the "HERE" link and the hard link work for me. Is there a reason why you wouldn't be able to see that wiki page from my repo?

**Comment by junwang-noaa** [comment]
It gave me invalid link error. Now it is working.

**Comment by BrianCurtis-NOAA** [comment]
Moved over: https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents
