### ISSUE TITLE
Issue running both Intel and GNU regression tests using ecflow on the same machine (node)

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#235]
## Description

Under special circumstances, the regression tests fail for the GNU or Intel compiler in the compilation.

### To Reproduce:

- regression testing using ecflow for compiler A is kicked off on a node and then terminated using ctrl+c
- this allows the ecflow server survive, and it remembers the modules for compiler A
- on the same node (different shell or changing `RT_COMPILER` or logging out and back in), kick off the regression tests using ecflow for compiler B
- the compile jobs will fail with module load conflicts

## Output

Example:
```
...
+ [[ hera.gnu == cheyenne.* ]]
+ [[ hera.gnu == wcoss_dell_p3 ]]
+ BUILD_JOBS=8
+ hostname
+ set +x
Lmod has detected the following error: Cannot load module "hpc-gnu/9.2.0"
because these module(s) are loaded:
   hpc-intel

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    hpc-gnu/9.2.0    /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/v1.0.0-beta1/modulefiles/core/hpc-gnu/9.2.0.lua
    fv3              /scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-hafs-feature-hwrf-physics-20200922-update-from-authoritative-repositories/gnu/modulefiles/hera.gnu/fv3
```

**Comment by climbfuji** [comment]
@DusanJovic-NOAA can you look at this when you get a chance, please? Since you implemented the ecflow-based regression testing and the reuse of an existing ecflow server, you know this system best.

**Comment by junwang-noaa** [comment]
Dusan is on leave, so let me assign the issue to him so that he can work on
it when he is back.

Jun

**Comment by DusanJovic-NOAA** [comment]
@climbfuji I can not reproduce the bug. I ran `rt.sh -e` on Hera and after few minutes killed it using ctrl-c. It stopped ecflow server:

```
+ echo 'ecflow tasks remaining: 93'
ecflow tasks remaining: 93
+ /scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/develop/ufs-weather-model/tests/abort_dep_tasks.py
+ [[ 93 -ne 0 ]]
+ wait 15570
+ sleep 10
^C++ echo 'rt.sh interrupted'
rt.sh interrupted
++ rt_trap
++ [[ false == true ]]
++ [[ true == true ]]
++ ecflow_kill
++ [[ true == true ]]
++ set +e
++ ecflow_client --suspend /regtest_1640
++ ecflow_client --kill /regtest_1640
++ sleep 20
++ ecflow_client --delete=force yes /regtest_1640
++ cleanup
++ [[ true == true ]]
++ ecflow_stop
++ [[ true == true ]]
++ set +e
+++ ecflow_client --get
+++ grep '^suite'
++ SUITES=
++ echo SUITES=
SUITES=
++ '[' -z '' ']'
++ ecflow_client --halt=yes
++ ecflow_client --check_pt
++ ecflow_client --terminate=yes
++ rm -rf /scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/develop/ufs-weather-model/tests/lock
++ trap 0
++ exit
```

**Comment by climbfuji** [comment]
> @climbfuji I can not reproduce the bug. I ran `rt.sh -e` on Hera and after few minutes killed it using ctrl-c. It stopped ecflow server:
> 
> ```
> + echo 'ecflow tasks remaining: 93'
> ecflow tasks remaining: 93
> + /scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/develop/ufs-weather-model/tests/abort_dep_tasks.py
> + [[ 93 -ne 0 ]]
> + wait 15570
> + sleep 10
> ^C++ echo 'rt.sh interrupted'
> rt.sh interrupted
> ++ rt_trap
> ++ [[ false == true ]]
> ++ [[ true == true ]]
> ++ ecflow_kill
> ++ [[ true == true ]]
> ++ set +e
> ++ ecflow_client --suspend /regtest_1640
> ++ ecflow_client --kill /regtest_1640
> ++ sleep 20
> ++ ecflow_client --delete=force yes /regtest_1640
> ++ cleanup
> ++ [[ true == true ]]
> ++ ecflow_stop
> ++ [[ true == true ]]
> ++ set +e
> +++ ecflow_client --get
> +++ grep '^suite'
> ++ SUITES=
> ++ echo SUITES=
> SUITES=
> ++ '[' -z '' ']'
> ++ ecflow_client --halt=yes
> ++ ecflow_client --check_pt
> ++ ecflow_client --terminate=yes
> ++ rm -rf /scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/develop/ufs-weather-model/tests/lock
> ++ trap 0
> ++ exit
> ```

Hmm weird. But that's only part of the problem. The real problem is that a running ecflow server has information about the compiler that is used in the tests (because the module gets loaded when the server is started). Is that really needed? The scripts do create the `.env` files for the jobs that do contain all the information, and the `job_card` files also contain explicit `module load fv` calls for the correct modules. Shouldn't the ecflow server be agnostic to the particulars (i.e. compiler) of the `rt.sh` call?

You can reproduce the problem differently. Start an ecflow regression test on a hera node, then log into that node again in a different shell and set RT_COMPILER to true, start another round of regression tests - it will fail (but it shouldn't in my opinion).

**Comment by junwang-noaa** [comment]
Similar thing happened to me after I ran ecflow for RT. So I run full RT
using :"rt.sh -fe" on hera for intel compiler. Then I was trying to set
RT_COMPILER to run gnu make test. But I got empty line:

[Jun.Wang@hfe12 tests]$ setenv RT_COMPILER gnu
[Jun.Wang@hfe12 tests]$ echo $RT_COMPILER
[Jun.Wang@hfe12 tests]$

Then I opened a new hera window, I got:

[Jun.Wang@hfe06 ~]$ setenv RT_COMPILER gnu
[Jun.Wang@hfe06 ~]$ echo $RT_COMPILER
gnu

**Comment by DusanJovic-NOAA** [comment]
@climbfuji Try:

```
$ git diff rt.sh
diff --git a/tests/rt.sh b/tests/rt.sh
index 8d27e1e..8aa2723 100755
--- a/tests/rt.sh
+++ b/tests/rt.sh
@@ -192,11 +192,6 @@ elif [[ $MACHINE_ID = gaea.* ]]; then
 
 elif [[ $MACHINE_ID = hera.* ]]; then
 
-  source $PATHTR/NEMS/src/conf/module-setup.sh.inc
-
-  module use $PATHTR/modulefiles/${MACHINE_ID}
-  module load fv3
-
   module load rocoto
   ROCOTORUN=$(which rocotorun)
   ROCOTOSTAT=$(which rocotostat)
```

**Comment by climbfuji** [comment]
Closed via https://github.com/ufs-community/ufs-weather-model/commit/248b609b7a3ba8e0ef05085218a0e3c0cd2b739c
