### ISSUE TITLE
Allow use of downscaled MOM6 and CICE6 warmstart files for SFS test

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2351]
## Description

The downscaled ICs produced by UFS-UTILS/ocnice_prep [utility](https://ufs-community.github.io/UFS_UTILS/ocnice_prep/index.html)  are being tested for SFS. The desire is for the current SFS test (``cpld_control_sfs``) to use those warmstart files. This requires either the addition of a new 1-deg MOM6 input template or the modification of the existing template to include new configurable export variables. 

A copy of the required 1-deg MOM_input file currently resides at /scratch1/NCEPDEV/stmp4/Denise.Worthen/MOM_input_for_Neil.  

Ideally the warmstart ICs for ocean and ice will be used in concert w/ updated ATM ICs.

**Comment by DeniseWorthen** [comment]
Reading ``MOM_state_initialization.F90`` shows that it will be possible to use the same MOM_input for either Z-level initialization or warm-start initialization 

```
  if (from_Z_file) then
    ! Initialize thickness and T/S from z-coordinate data in a file.
    if (.NOT.use_temperature) call MOM_error(FATAL,"MOM_initialize_state : "//&
       "use_temperature must be true if INIT_LAYERS_FROM_Z_FILE is true")

    call MOM_temp_salt_initialize_from_Z(h, tv, depth_tot, G, GV, US, PF, &
                                         just_read=just_read, frac_shelf_h=frac_shelf_h)
    convert = .false.
  else
    ! Initialize thickness, h.
    call get_param(PF, mdl, "THICKNESS_CONFIG", h_config, &
  ....
```

The above referenced MOM_input will work, as long as ``VELOCITY_CONFIG = "zero"`` is used along with ``INIT_LAYERS_FROM_Z_FILE = True`` when not using the warm-starts. 

For warm-starts, the Z_file parameter will be false, and we will need to provide the file name and variable names for the eta, T,S,U and V fields.

**Comment by NeilBarton-NOAA** [comment]
@DeniseWorthen ICs are on hera at
/scratch2/NCEPDEV/stmp3/Neil.Barton/ICs/REPLAY_ICs/CI/2023012300
Note, this is using a structured wave grid.

**Comment by DeniseWorthen** [comment]
@NeilBarton-NOAA Thanks. Currently the ``cpld_control_sfs`` test uses the date of 2021-03-22-06, so that is the warm start date I staged. Right now, it is the only test that will use the new files. 

I know there is a project underway to update all the tests but I'm not sure if the RT date will change. This PR will add the needed MOM input templates to UWM at least. As long as we keep the files date and resolution stamped, we can add new ones to the RT system to match the new ATM ICs.

**Comment by NeilBarton-NOAA** [comment]
@DeniseWorthen see the edits MOM input template at
https://github.com/NeilBarton-NOAA/global-workflow/blob/SFS_baseline/RUN/MOM_input_coldstart_100.IN

This adds the options for stochastics, which is needed for SFS

**Comment by DeniseWorthen** [comment]
Great. Thanks. I'll add those and update the PR.

**Comment by DeniseWorthen** [comment]
@NeilBarton-NOAA I've checked the input template in this PR against the vs the one ln your link. They appear to contain all the same namelist values. There is a slight ordering difference. Please let me know the missing settings.

**Comment by NeilBarton-NOAA** [comment]
@DeniseWorthen Looks good. Thanks
