### ISSUE TITLE
cpld_control-p8 / cpld_debug_p8 failing with gnu on Hercules

### ISSUE THREAD

**Issue by zach1221** [ufs-community/ufs-weather-model#2353]
## Description

Following Hercules maintenance the last week of June, cpld_control-p8 / cpld_debug_p8 regression test cases have begun failing with gnu compilers. Problem only occurs with gnu compilers, the same tests pass with intel on Hercules. 

Issue appears to be caused by spack-stack mvapich2 installation on Hercules, following the maintenance last week. Mvapich2 Hercules installation may have been overwritten, and needs to be re-installed. 

### To Reproduce:

1. clone ufs-wm repo
2. cd tests/ 
3.  Edit rt.conf to include only cpld_control-p8_gnu & cpld_debug_p8_gnu cases
4. ./rt.sh -a epic -l rt.conf

## Additional context

The below is pulled from err log:
Unable to get variable: mtpo from file: ExtData/MEGAN_OFFLINE_BVOC/v2019-10/2021/MEGAN.OFFLINE.BIOVOC.2021.emis.20210323.nc
Unable to get variable: biomass from file: ExtData/QFED/2021/03/qfed2.emis_oc.006.20210322.nc4

In this example, the RT complains it cannot find biomass or mtpo from the input-data file, but they exist.

**Comment by DeniseWorthen** [comment]
@zach1221 How is this different than Issue #2350 ?

**Comment by zach1221** [comment]
> @zach1221 How is this different than Issue #2350 ?

@DeniseWorthen Oh, I did not realize it had been reported already, that's good. I can remove mine.

**Comment by zach1221** [comment]
Duplicate. Closing
