### ISSUE TITLE
Install FMS 2024.01 and test with UFSWM

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#2358]
## Description

FMS 2024.01 contains features/fixes we need with the UFSWM.
We'd like to see it installed on (if not already)
- [ ] Acorn
- [ ] WCOSS2 (Dogwood/Cactus)
- [x] Spack Stack 1.6 (RDHPCS)
Tier 1 machines:
- [x] Hera (Intel): /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Hera (GNU): /scratch2/NCEPDEV/stmp1/role.epic/spack-stack/spack-stack-1.6.0_gnu13/envs/fms-2024.01/install/modulefiles/Core
- [x] Gaea-C5 (Intel): /ncrc/proj/epic/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Gaea-C6 (Intel): /ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Jet (Intel): /contrib/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Orion (Intel): /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Hercules (GNU & Intel): /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.02/install/modulefiles/Core
- [x] Derecho (GNU & Intel): /glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] AWS (Intel): /contrib/spack-stack-rocky8/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Azure (Intel): /contrib/spack-stack-rocky8/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [ ] GCP (Intel) - out of resources

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA is this installed on Acorn?

**Comment by Hang-Lei-NOAA** [comment]
Yes, it is on acorn
/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/
19.1.3.304/cray-mpich/8.1.9

And it is on wcoss2 under para.

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 FMS2024.01 install sets an incorrect FMS_ROOT env var:
```
brian.curtis@clogin01:/lfs/h2/emc/nems/noscrub/brian.curtis/git/ufs-community/ufs-weather-model/tests> module show fms
--------------------------------------------------------------------------------------------------------------------------------
   /apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9/fms/2024.01.lua:
--------------------------------------------------------------------------------------------------------------------------------
help([[]])
conflict("fms")
setenv("FMS_ROOT","/apps/ops/prod/libs/intel/19.1.3.304/cray-mpich/8.1.9/fms/2024.01")
setenv("FMS_VERSION","2024.01")
whatis("Name: fms")
whatis("Version: 2024.01")
whatis("Category: library")
whatis("Description: GFDL FMS library")

brian.curtis@clogin01:/lfs/h2/emc/nems/noscrub/brian.curtis/git/ufs-community/ufs-weather-model/tests> printenv | grep FMS
FMS_VERSION=2024.01
FMS_ROOT=/apps/ops/prod/libs/intel/19.1.3.304/cray-mpich/8.1.9/fms/2024.01
brian.curtis@clogin01:/lfs/h2/emc/nems/noscrub/brian.curtis/git/ufs-community/ufs-weather-model/tests> ls $FMS_ROOT
ls: cannot access '/apps/ops/prod/libs/intel/19.1.3.304/cray-mpich/8.1.9/fms/2024.01': No such file or directory
brian.curtis@clogin01:/lfs/h2/emc/nems/noscrub/brian.curtis/git/ufs-community/ufs-weather-model/tests> ls /apps/ops/prod/libs/intel/
19.1.3.304/cray-mpich/8.1.9/fms/202
2022.04/    2023.02.01/
```

**Comment by Hang-Lei-NOAA** [comment]
After Rahul pointed out, I have informed the NCO about this. They will make
changes.

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA @rickgrubin-tomorrow FYI

**Comment by RatkoVasic-NOAA** [comment]
@BrianCurtis-NOAA can you please open new issue at spack-stack github so we can start process there. Thanks.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA can you please open new issue at spack-stack github so we can start process there. Thanks.

@RatkoVasic-NOAA done: https://github.com/JCSDA/spack-stack/issues/1215

**Comment by RatkoVasic-NOAA** [comment]
Installed on Hercules. [Here is description](https://github.com/JCSDA/spack-stack/issues/1215#issuecomment-2292758444)

**Comment by BrianCurtis-NOAA** [comment]
it's on WCOSS2 para, but I ran with it and it doesn't seem to link with ESMF quite right and fails all compiles (check include paths for ESMF)

**Comment by Hang-Lei-NOAA** [comment]
This may ask @Matthew Pyle - NOAA Federal ***@***.***> for help.
Matt has previously tested it with RRFS.

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA would you please list the library change and the linking error message?

**Comment by BrianCurtis-NOAA** [comment]
Comment out line 29 in modulefiles/ufs_wcoss2.intel.lua (the fms line with -- before it)
Add the following to line 50 in modulefiles/ufs_wcoss2.intel.lua
```
prepend_path("MODULEPATH","/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9/")
load("fms/2024.01")
```

error:
```
+ OMP_NUM_THREADS=1
+ make -j 8 VERBOSE=1
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/GOCART/ESMF/Shared/Chem_AeroGeneric.F90(18): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [ESMF]
   use ESMF
-------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90(11): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [ESMF]
  use ESMF        , only : ESMF_Finalize, ESMF_END_ABORT, ESMF_LOGMSG_ERROR, ESMF_LogWrite
------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90(11): error #6580: Name in only-list does not exist or is not accessible.   [ESMF_FINALIZE]
  use ESMF        , only : ESMF_Finalize, ESMF_END_ABORT, ESMF_LOGMSG_ERROR, ESMF_LogWrite
---------------------------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90(11): error #6580: Name in only-list does not exist or is not accessible.   [ESMF_END_ABORT]
  use ESMF        , only : ESMF_Finalize, ESMF_END_ABORT, ESMF_LOGMSG_ERROR, ESMF_LogWrite
------------------------------------------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90(11): error #6580: Name in only-list does not exist or is not accessible.   [ESMF_LOGMSG_ERROR]
  use ESMF        , only : ESMF_Finalize, ESMF_END_ABORT, ESMF_LOGMSG_ERROR, ESMF_LogWrite
----------------------------------------------------------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90(11): error #6580: Name in only-list does not exist or is not accessible.   [ESMF_LOGWRITE]
  use ESMF        , only : ESMF_Finalize, ESMF_END_ABORT, ESMF_LOGMSG_ERROR, ESMF_LogWrite
-----------------------------------------------------------------------------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90(64): error #6404: This name does not have a type, and must have an explicit type.   [ESMF_LOGMSG_ERROR]
    call ESMF_LogWrite(local_string, ESMF_LOGMSG_ERROR)
-------------------------------------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90(65): error #6632: Keyword arguments are invalid without an explicit interface.   [ENDFLAG]
    call ESMF_Finalize(endflag=ESMF_END_ABORT)
-----------------------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90(65): error #6404: This name does not have a type, and must have an explicit type.   [ESMF_END_ABORT]
    call ESMF_Finalize(endflag=ESMF_END_ABORT)
-------------------------------^
compilation aborted for /lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CDEPS-interface/CDEPS/share/shr_abort_mod.F90 (code 1)
make[2]: *** [CDEPS-interface/CMakeFiles/share.dir/build.make:88: CDEPS-interface/CMakeFiles/share.dir/CDEPS/share/shr_abort_mod.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1734: CDEPS-interface/CMakeFiles/share.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/lfs/h2/emc/nems/noscrub/brian.curtis/git/BrianCurtis-NOAA/ufs-weather-model/develop/CMEPS-interface/CMEPS/ufs/perf_mod.F90(3): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [ESMF]
  use ESMF
------^
```

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA  the prepend module path does not have ESMF library.  Would you please provide a module file so that both the esmf-C and fms can be loaded?

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA @jkbk2004 Can EPIC test the fms 2024.01 in ufs-weather-model on Hercules?

**Comment by RatkoVasic-NOAA** [comment]
@junwang-noaa yes. Those tests were done.
I also tested fms@2024.02:
Here are new baselines: /work2/noaa/stmp/rvasic/stmp/rvasic/FV3_RT/REGRESSION_TEST
And here are log files /work/noaa/epic/rvasic/test-FMS/ufs-weather-model/tests/logs/log_hercules
Since we are going to install fms@2024.02 in coming spack-stack 1.8.0 release.

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA thanks for installing the FMS library and testing it in UFS wm.

**Comment by Hang-Lei-NOAA** [comment]
@Jun Wang - NOAA Federal ***@***.***> and @Brian Curtis - NOAA
Affiliate ***@***.***> just run a case on cactus, using almost
the same modulefile.lua it succeed. develop branch
/lfs/h2/emc/eib/noscrub/hang.lei/ufsdevelop/tests
 ./rt.sh -a GFS-DEV -n "cpld_control_p8 intel"
/lfs/h2/emc/ptmp/hang.lei/FV3_RT/rt_140532

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA Your modulefile in /lfs/h2/emc/eib/noscrub/hang.lei/ufsdevelop/tests/modulefiles/ufs_wcoss2.intel.lua still produces the build failure i've previously listed in: https://github.com/ufs-community/ufs-weather-model/issues/2358#issuecomment-2311011969

**Comment by Hang-Lei-NOAA** [comment]
@Brian what case did you run ? Please let me know

**Comment by BrianCurtis-NOAA** [comment]
cpld_control_p8

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> Why my test of it
succeed? I am using ufs develop branch. Just download the other day. But it
seems that the run directory was not kept.

 Comparing RESTART/iced.2021-03-23-21600.nc .....USING NCCMP......OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc .....USING
NCCMP......OK
 Comparing 20210323.060000.out_pnt.ww3 .....USING CMP......OK
 Comparing 20210323.060000.out_grd.ww3 .....USING CMP......OK

The total amount of wall time                        = 355.123194
The maximum resident set size (KB)                   = 3122628

Test cpld_control_p8_intel PASS

**Comment by BrianCurtis-NOAA** [comment]
Can you try that test again? Then send me the modulefile you used?

**Comment by Hang-Lei-NOAA** [comment]
Hi, Brian, I try it twice, I will try it one more time. The modulefile is
the one that I pointed out in previous reply. NO change.
Please check in:
Linking /lfs/h2/emc/ptmp/hang.lei/FV3_RT/rt_221868 to
/lfs/h2/emc/eib/noscrub/hang.lei/ufsdevelop/tests/run_dir
Run regression test in: /lfs/h2/emc/ptmp/hang.lei/FV3_RT/rt_221868

**Comment by BrianCurtis-NOAA** [comment]
OK, I will re-clone and try. I could just have a stale clone. I'll let you know if I encounter anything bad.

**Comment by BrianCurtis-NOAA** [comment]
> OK, I will re-clone and try. I could just have a stale clone. I'll let you know if I encounter anything bad.

All went well this time around. My clone became stale at some point prior.

**Comment by Hang-Lei-NOAA** [comment]
@BrianCurtis-NOAA The NCO has created extra modulefile to include fms/2024.01 into the system default. You no longer need to add extra paths.

**Comment by zach1221** [comment]
> @junwang-noaa yes. Those tests were done. I also tested fms@2024.02: Here are new baselines: /work2/noaa/stmp/rvasic/stmp/rvasic/FV3_RT/REGRESSION_TEST And here are log files /work/noaa/epic/rvasic/test-FMS/ufs-weather-model/tests/logs/log_hercules Since we are going to install fms@2024.02 in coming spack-stack 1.8.0 release.

@RatkoVasic-NOAA As you know, I'm working to test 2024.02 using spack-stack/1.8.0 installation on Hera, at (/contrib/spack-stack/spack-stack-1.8.0/envs/ue-intel-2021.5.0/install/modulefiles/Core). However, I cannot find the 1.6.0 installation with fms/2024.01 anywhere on machines hera,jet,gaea,hercules,orion,derecho. Can you tell me where these installations are?

**Comment by RatkoVasic-NOAA** [comment]
@zach1221 we were asked to install fms@2024.01 for testing only on one machine:
hercules: /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core/

**Comment by zach1221** [comment]
> @zach1221 we were asked to install fms@2024.01 for testing only on one machine: hercules: /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core/

Ok I will test it on Hercules, using that path. Is it possible to add this fms/2024.01 installation to those other machines?

**Comment by RatkoVasic-NOAA** [comment]
Yes. I'm currently busy with 1.8.0, but I will try to do that in the meantime.

**Comment by zach1221** [comment]
@FernandoAndrade-NOAA @jkbk2004 the 2024.01 installation on Hercules at  (/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core/) is working fine. RTs are passing. The rest of the machines are planned to be setup after 1.8.0 install is done.

**Comment by DeniseWorthen** [comment]
@zach1221 Have you tested on Hercules with turning the various cpld/gnu tests back on? ``cpld_control_p8``  ``cpld_debug_p8``?

**Comment by zach1221** [comment]
> @zach1221 Have you tested on Hercules with turning the various cpld/gnu tests back on? `cpld_control_p8` `cpld_debug_p8`?

Looks like they both still fail on hercules, during fatal call to CCPP physics_init step, "An error occurred in ccpp_physics_init
143: Invalid suite FV3_GFS_v17_coupled_p8_ugwpv1".  Should the export lines export_ugwpv1 and export CCPP_SUITE=FV3_GFS_v17_coupled_p8_ugwpv1 be removed from the tests/tests files?

**Comment by DeniseWorthen** [comment]
I think the problem is the compile. Did you change the SDF in the compile lines for GNU? 

https://github.com/ufs-community/ufs-weather-model/blob/706219146401bec7a29e7384eb1a642392ca47fe/tests/rt.conf#L413-L420

**Comment by zach1221** [comment]
> I think the problem is the compile. Did you change the SDF in the compile lines for GNU?
> 
> https://github.com/ufs-community/ufs-weather-model/blob/706219146401bec7a29e7384eb1a642392ca47fe/tests/rt.conf#L413-L420

@DeniseWorthen I did not change anything there. I guess they should be changed to -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 ?

**Comment by DeniseWorthen** [comment]
@zach1221 Yes. It should be compiled the same way as the intel version of the test. Since these tests are not run anywhere right now, I think Dan missed updating the compile lines in his last update 

https://github.com/ufs-community/ufs-weather-model/blob/706219146401bec7a29e7384eb1a642392ca47fe/tests/rt.conf#L40-L42

**Comment by RatkoVasic-NOAA** [comment]
@zach1221 I installed fms@2024.01 addons on more machines:
```
Hera (Intel): /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
Hera (GNU): /scratch2/NCEPDEV/stmp1/role.epic/spack-stack/spack-stack-1.6.0_gnu13/envs/fms-2024.01/install/modulefiles/Core
Orion (Intel): /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
Hercules (GNU & Intel): /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.02/install/modulefiles/Core
```
Jet and Derecho are down, Gaeas are unstable right now. When they become available I'll install it on those as well.

**Comment by zach1221** [comment]
> @zach1221 Yes. It should be compiled the same way as the intel version of the test. Since these tests are not run anywhere right now, I think Dan missed updating the compile lines in his last update
> 
> https://github.com/ufs-community/ufs-weather-model/blob/706219146401bec7a29e7384eb1a642392ca47fe/tests/rt.conf#L40-L42

@DeniseWorthen so both cases cpld_control_p8 and cpld_debug_p8 gnu actually failed due to timeout. Even if wallclock is set to over an hour or more, they time out.

**Comment by DeniseWorthen** [comment]
@zach1221 Where is your run directory?

**Comment by zach1221** [comment]
> @zach1221 Where is your run directory?
@DeniseWorthen 
/work/noaa/nems/zshrader/hercules/ufs-weather-model
/work2/noaa/stmp/zshrader/stmp/zshrader/FV3_RT/rt_3631656

**Comment by DeniseWorthen** [comment]
They're timing out because the run is hanging with this error

```
 16: pe=00016 FAIL at line=00045    NetCDF4_get_var.H                        <Unable to get variable: biomass from file: ExtData/QFED/2021/03/qfed2.emis_nh3.006.20210323.nc4>
 16: pe=00016 FAIL at line=00726    ServerThread.F90                         <status=1>
 16: pe=00016 FAIL at line=00471    ServerThread.F90                         <status=1>
 16: pe=00016 FAIL at line=01117    ServerThread.F90                         <status=1>
 16: pe=00016 FAIL at line=00091    MessageVisitor.F90                       <status=1>
 16: pe=00016 FAIL at line=00115    AbstractMessage.F90                      <status=1>
 16: pe=00016 FAIL at line=00107    SimpleSocket.F90                         <status=1>
 16: pe=00016 FAIL at line=00427    ClientThread.F90                         <status=1>
```

This same message was noted in https://github.com/ufs-community/ufs-weather-model/issues/2350 in July. It is still not fixed.

**Comment by zach1221** [comment]
> @zach1221 I installed fms@2024.01 addons on more machines:
> 
> ```
> Hera (Intel): /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
> Hera (GNU): /scratch2/NCEPDEV/stmp1/role.epic/spack-stack/spack-stack-1.6.0_gnu13/envs/fms-2024.01/install/modulefiles/Core
> Orion (Intel): /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
> Hercules (GNU & Intel): /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.02/install/modulefiles/Core
> ```
> 
> Jet and Derecho are down, Gaeas are unstable right now. When they become available I'll install it on those as well.

@RatkoVasic-NOAA it looks like jet/derecho are up today, are you able to work on those machines? Also what is the issue you're having on Gaea? CSPs as well.

**Comment by RatkoVasic-NOAA** [comment]
@zach1221 it is finished. Here are [directories](https://github.com/ufs-community/ufs-weather-model/issues/2358#issue-2395541743). You can start testing.

**Comment by zach1221** [comment]
> @zach1221 it is finished. Here are [directories](https://github.com/ufs-community/ufs-weather-model/issues/2358#issue-2395541743). You can start testing.

Hercules intel/gnu, hera intel/gnu, orion and derecho are done. Testing confirming jet, gaea and CSPs now. @jkbk2004

**Comment by zach1221** [comment]
Ok jet, GaeaC5, and AWS looks good for fms/2024.01. Azure is frozen currently due to low allocation. 
Looks like we can't test on GaeaC6 right now because there's no epic group in gpfs/f6, and world-shared is locked off. @FernandoAndrade-NOAA if this is not accurate let me know.

**Comment by zach1221** [comment]
@RatkoVasic-NOAA should hercules/gnu be fms/2024.02? /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.02/install/modulefiles/Core
@jkbk2004

**Comment by jkbk2004** [comment]
> @RatkoVasic-NOAA should hercules/gnu be fms/2024.02? /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.02/install/modulefiles/Core @jkbk2004

@zach1221 @RatkoVasic-NOAA it should be fms 2024.01.

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA should hercules/gnu be fms/2024.02? /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.02/install/modulefiles/Core @jkbk2004

@zach1221 - that installation was a test. I tested both 2024.01 and 2024.02 on Hercules. It was decided to install 2024.01 on all other machines.
