### ISSUE TITLE
Add support for Intel LLVM-based compilers

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#2361]
## Description
I was experimenting UFS Weather Model under TACC Frontera as a part of UFS coastal project. I could able to run model configurations using spack-stack 1.5.1 along with `intel/19.1.1` and `impi/19.0.9` but when I try to upgrade the compiler and MPI to their newer versions (`intel/23.1.0` and `impi/21.9.0` - intel-oneapi), I started to get following error,

```
CMake Error at CMakeLists.txt:149 (include):
  include could not find requested file:

    cmake/IntelLLVM.cmake
```

I think that the reason is the Intel compiler. In my case, `${CMAKE_Fortran_COMPILER_ID}` is returning `IntelLLVM` and model build is failing since there is no `cmake/IntelLLVM.cmake` (https://github.com/ufs-community/ufs-weather-model/blob/8e7b61b197f777328464eb2e7dbd006c6c148829/CMakeLists.txt#L139). I am seeing usage of `IntelLLVM` along with `Intel` in some places of the code but it is not a standard and used in everywhere.

## Solution
I think, the top level CMake file as well as CMake interfaces of the components needs to be extended to allow `IntelLLVM`.

## Alternatives
Not sure

## Related to
N/A

**Comment by DusanJovic-NOAA** [comment]
See #2224

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA Thanks. I was not aware of it. Do you want me to close this issue? or you prefer to keep it open.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Thanks. I was not aware of it. Do you want me to close this issue? or you prefer to keep it open.

Keep it open. We can use this issue to track the progress.
