### ISSUE TITLE
unable to run rt.sh compiling job on wcoss2

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#2364]
## Description

I am unable to compile job on wcoss2 with error:

Lmod has detected the following error: Cannot load module "hdf5-C/1.14.0"
because these module(s) are loaded:
   hdf5

While processing the following module(s):
    Module fullname   Module Filename
    ---------------   ---------------
    hdf5-C/1.14.0     /apps/prod/lmodules/INTEL_cray_mpich/19.1.3.304/cray-mpich/8.1.4/hdf5-C/1.14.0.lua
    ufs_wcoss2.intel  /lfs/h2/emc/couple/noscrub/Jiande.Wang/MOM6-update/20240531-clean/ufs-weather-model/modulefiles/ufs_wcoss2.intel.lua

the UWM I cloned is based on July 11th commit 0b59ad3db
### To Reproduce:
clone latest UWM and compile one of the job on wcoss2

**Comment by BrianCurtis-NOAA** [comment]
It could be that your environment has hdf5 loaded prior to trying to load ufs_wcoss2.intel.lua. I've had a similar issue in the past when I had a library auto loaded for me from my .bashrc.

**Comment by jiandewang** [comment]
@BrianCurtis-NOAA I did module purge and still got the same issue. Let me try to comment out that from my bashrc file. Thanks

**Comment by jiandewang** [comment]
@BrianCurtis-NOAA it works fine after I removed all module load from my bashrc file. Simply do module purge won't work. Thanks.
