### ISSUE TITLE
missing BL on  cactus

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#2366]
## Description

latest UWM BL is
bl_date.conf:export BL_DATE=20240624
but this BL directory doesn't exist on cactus

**Comment by DusanJovic-NOAA** [comment]
There was an emergency production switch from cactus to dogwood over the weekend. I just started syncing develop-20240624 from dogwood to cactus.

**Comment by jiandewang** [comment]
@DusanJovic-NOAA let me konw when its done as I need to run some tests on cactus

**Comment by jiandewang** [comment]
works now

**Comment by jiandewang** [comment]
it appeared there are also some input files missing on cactus.
I got error when I ran rt.sh:
/lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/input-data-20240501/FV3_input_data/INPUT_L127_gfsv17/oro_data_ls*'
: No such file or directory

looked at dogwood we have 
/lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/input-data-20240501/FV3_input_data/INPUT_L127_gfsv17

but this directory doesn't exist on cactus

**Comment by DusanJovic-NOAA** [comment]
I just synced 'input-data-20240501'. Can you please try again.

**Comment by jiandewang** [comment]
my jobs are running now. Thanks
