### ISSUE TITLE
Switch SFS test to 64-bit

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2376]
## Description

The SFS application plans to use 64-bit version of the S2SWA app. The current RT is compiled in 32-bit mode. 

## Solution

Switch the compile for the ``cpld_control_sfs`` test to 64-bit.

**Comment by DeniseWorthen** [comment]
The switch to 64-Bit is on hold while further testing conducted.

**Comment by junwang-noaa** [comment]
Let's close the issue and open a new issue when the change is confirmed.
