### ISSUE TITLE
Use hpc-stack container for CI test

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#240]
## Description
User hpc-stack container for actions CI test

## Solution
hpc-stack container with gnu tool chain will be used as a base container within which utest is built and run.

## Alternatives
N/A

**Comment by climbfuji** [comment]
Fixed in https://github.com/ufs-community/ufs-weather-model/pull/297 ?

**Comment by MinsukJi-NOAA** [comment]
> Fixed in #297 ?

Yes. Closing.
