### ISSUE TITLE
permissions not set correctly for cpld_control_sfs test on hercules (please check orion also)

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2409]
## Description

```
cp: cannot open '/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/MOM6_IC/mom6.mx100.2021032206.warmstart.nc' for reading: Permission denied
```

### To Reproduce:

Try to run ``cpld_control_sfs_intel`` from current develop

**Comment by jiandewang** [comment]
my test on orion also failed 
cannot open '/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/CICE_IC/cice.mx100.2021032206.warmstart.nc' for reading: Permission denied

**Comment by DusanJovic-NOAA** [comment]
Same. My tests are failing on Hercules:

```
++ cp /work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/MOM6_IC/mom6.mx100.2021032206.warmstart.nc ./INPUT/mom6.warmstart.nc
cp: cannot open '/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/MOM6_IC/mom6.mx100.2021032206.warmstart.nc' for reading: Permission denied
+ '[' 1 -eq 0 ']'
+ write_fail_test
+ echo 'cpld_control_sfs_intelllvm failed in run_test'
```

**Comment by DusanJovic-NOAA** [comment]
This issue has been open for 3 days. Yesterday was labeled as high priority. How hard is it to run chmod command?
Please fix this issue ASAP.

**Comment by DusanJovic-NOAA** [comment]
Please fix this issue ASAP.

**Comment by junwang-noaa** [comment]
@jkbk2004 @FernandoAndrade-NOAA Would you please change the permission so that everyone can run the RT on Hercules?

**Comment by zach1221** [comment]
Hello, working to fix this now.

**Comment by jkbk2004** [comment]
@junwang-noaa @DeniseWorthen can you check permission again on orion/hercules: develop-20240821 ?

**Comment by DeniseWorthen** [comment]
```
hercules:/work/noaa/nems/dworthen> cp /work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/MOM6_IC/mom6.mx050.2021032206.warmstart.nc .
cp: cannot open '/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/MOM6_IC/mom6.mx050.2021032206.warmstart.nc' for reading: Permission denied
```

**Comment by DeniseWorthen** [comment]
@jkbk2004 The issue is with the *input-data* directory, not the baseline directory.

**Comment by jkbk2004** [comment]
> @jkbk2004 The issue is with the _input-data_ directory, not the baseline directory.

@DeniseWorthen Please, try one more time.

**Comment by DeniseWorthen** [comment]
@jkbk2004 No, still get permission-denied on Hercules.

**Comment by jkbk2004** [comment]
sorry! try one more time.
```
-rw-rw-r--  1 jongkim epic 1499629152 Aug  2 13:15 mom6.mx050.2021032206.warmstart.nc
-rw-rw-r--  1 jongkim epic  416564832 Aug  2 13:15 mom6.mx100.2021032206.warmstart.nc
```

**Comment by DeniseWorthen** [comment]
OK, that works for me on Hercules for both the MOM6 and CICE6 warmstarts.
