### ISSUE TITLE
cpld_control_p8/cpld_restart_p8 does not restart reproduce if fhrot=3

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2410]
## Description

The ``cpld_restart_p8`` test fails to reproduce the control run if the restart file from the control run is at hour=3

### To Reproduce:

Make the following change and run the control and restart p8 tests. 

```
diff --git a/tests/tests/cpld_control_p8 b/tests/tests/cpld_control_p8
index 67243979..54fbbb4b 100644
--- a/tests/tests/cpld_control_p8
+++ b/tests/tests/cpld_control_p8
@@ -72,7 +72,7 @@ export LIST_FILES="sfcf021.tile1.nc \
 export_fv3
 export_cpl

-export RESTART_N=12
+export RESTART_N=3
 export RESTART_INTERVAL="${RESTART_N} -1"
 export OUTPUT_FH='0 21 24'

diff --git a/tests/tests/cpld_restart_p8 b/tests/tests/cpld_restart_p8
index edbba45c..44ddc1cb 100644
--- a/tests/tests/cpld_restart_p8
+++ b/tests/tests/cpld_restart_p8
@@ -60,7 +60,7 @@ export LIST_FILES="sfcf024.tile1.nc \
 export_fv3
 export_cpl

-export FHROT=12
+export FHROT=3
 export RESTART_N=$((FHMAX-$FHROT))

 export RESTART_FILE_PREFIX="${SYEAR}${SMONTH}${SDAY}.$(printf "%02d" $(( ${FHROT} + ${SHOUR} )))0000"
```

## Additional context

 
I found this during testing restart repro in a sandbox where I was trying to shorten the runs required for testing and retesting. I had removed the aerosol component, so it is not related to GOCART.

**Comment by junwang-noaa** [comment]
@DeniseWorthen In the cpld_control_p8 tests the diagnostic accumulation bucket (fhzero in gfs_physics_nml in input.nml) is set to 6 hrs, so this means that we need to restart the model at multiple of 6hrs. If we restart the model at 3hrs, the intermediate diagnostic fields are not saved and the restart run will not reproduce the control. If you set fhrot=3, please also set fhzero=3 in the control and restart runs. Thanks

**Comment by DeniseWorthen** [comment]
@junwang-noaa Thanks for looking into it. I had forgotten about the fhzero namelist setting. I'll go ahead and close this, since I'm sure your analysis is correct.
