### ISSUE TITLE
Remove the IFI tests

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#2416]
## Description
Due to security and intellectual property restrictions, the in-flight icing library (libIFI) tests are only run on Acorn. The library is expected to never be run in the inline post. Continuing to test it that way only adds unnecessary work. (This was decided at an August 27, 2024 meeting between libIFI stakeholders about libIFI testing.)

## Solution
Remove the tests.

## Alternatives
Keep testing a feature that won't be used.

**Comment by gspetro-NOAA** [comment]
Can this issue be closed? It looks like it was potentially resolved in #2395 .

**Comment by BrianCurtis-NOAA** [comment]
@gspetro-NOAA Thanks for the catch, you're correct it was addressed in a previous PR. Closing
