### ISSUE TITLE
alternate comparison method needed for mediator restart files

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#242]
## Description
In the current RT, the comparison of the mediator restart file will sometimes fail, even though all other files pass comparison. In these cases, manual comparison of the mediatory history files will show that the actual data in the file is identical. 

## Solution
When the mediator history file is the only file to fail comparison, we need a second comparison method for the mediator restart file in the RT system.

**Comment by MinsukJi-NOAA** [comment]
#261 addressing this issue has been merged into develop
