### ISSUE TITLE
Output 24 hour average instead if daily average for CICE output

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#2422]
## Description

Currently CICE can only output daily average. E.g. when model run starts from 2023032206 and run for 72 hours, and the history output is specified as:
```
    histfreq            = 'm','d','h','x','x'
    histfreq_n          = 0, 1, 0, 1, 1
```
the history output will be daily output. The first file iceh.2021-03-22.nc covers 2021032206-2021032300 (time bound 0-0.75hr), then the second file iceh.2021-03-23.nc covers 2021032300-2021032400 (time bound 0.75-1.75). In order to have consistent 24 hour average files as those other model components do, a new option needs to be added to CICE so that it can output 24 hour average. E.g. the file iceh.2021-03-22.nc covers 2021032206-2021032306 (time bound 0-1.0hr) and iceh.2021-03-23.nc covers 2021032306-2021032406 (time bound 1.0-2.0hr).

## Solution

Add an option in CICE to output 24 hour average history files.

**Comment by NickSzapiro-NOAA** [comment]
May I ask if a "forecast day" history stream would work? 
Like:
```
histfreq            = 'h'
histfreq_n          = 24
hist_avg            = .true.
```
before looking to workaround calendar days.

**Comment by NeilBarton-NOAA** [comment]
@NickSzapiro-NOAA see my test run on hercules at /work/noaa/marine/nbarton/RUNS/UFS/run_CICE_24h_OUTPUT

The output in the history directory is at 00Z

**Comment by NickSzapiro-NOAA** [comment]
Instead of one of the calendar-based options then, a timestep stream seems to work, like
```
histfreq            = '1'
histfreq_n          = 96
hist_avg            = .true.
```
for datm_cdeps_gfs (on hercules at /work/noaa/global/nszapiro/tasks/ice_24hrOutput/ufs-weather-model/tests/run_dir/datm_cdeps_gfs_intel/ . See time_bounds in history/iceh.*nc files)

You do need to have the ice timestep to know how many steps in 24h, like 96 n for 900s dt

**Comment by NeilBarton-NOAA** [comment]
Thanks @NickSzapiro-NOAA . Tagging @aerorahul as I think this was a feature request for g-w.

**Comment by junwang-noaa** [comment]
@NickSzapiro-NOAA I got permission denied when accessing your directory on Hercules. 
Also can you update the GFSv17 RT tests to use this feature (number of time steps for ice daily output)? Currently it's 6hourly output. It might be good to use the same ice_in from GFSv17 HR4. Thanks

**Comment by NickSzapiro-NOAA** [comment]
I started a draft PR https://github.com/ufs-community/ufs-weather-model/pull/2437 and run_dir on hera should be readable for all (/scratch1/NCEPDEV/nems/Nick.Szapiro/tasks/ice_24hrOutput/ufs-weather-model/tests/run_dir/cpld_control_gfsv17_intel/history/) 

For how to configure/exercise this stream:
1. It is currently only exercised in cpld_control_gfsv17 test. Do you want all gfsv17 tests to output?
2. Do you want to add history file to baselines?
3.  Which variables would you like switched on for forecast day output?
4. I understand workflow takes ice_in from ufs-weather-model. Is there something to change?

**Comment by junwang-noaa** [comment]
We'd like to have the same configurations in RT and GFS workflow. @RuiyuSun @aerorahul can you provide the ice_in file in G-W used in GFSv17 forecast?

**Comment by RuiyuSun** [comment]
@junwang-noaa @aerorahul An example is ice_in at /lfs/h2/emc/stmp/ruiyu.sun/RUNDIRS/HR46/gfs.2020012600/gfsfcst.2020012600/fcst.212569 and  /lfs/h2/emc/physics/noscrub/ruiyu.sun/ice_in. The file was created by https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/parsing_namelists_CICE.sh

**Comment by aerorahul** [comment]
Thanks @RuiyuSun 
Just to add to this info, the `ice_in` template comes from the ufs-weather-model [here](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/ice_in.IN).
The global-workflow script [parsing_namelists_CICE.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/parsing_namelists_CICE.sh), fills it with the values from the configuration in the global-workflow.
In case the file provided by @RuiyuSun disappears, I am attaching it in this comment
[ice_in](https://github.com/user-attachments/files/16968423/ice_in.txt)

**Comment by NickSzapiro-NOAA** [comment]
The ice_in files look consistent to me, differing only in history_dir and incond_dir
