### ISSUE TITLE
Build failure on Derecho: compile_s2sw_debug_intel

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#2429]
## Description

In the PR #2412, build failure is reported for the test case, s2sw_debug_intel. An issue is suspected in spack stack lib. Error message:
    use grib2_all_tables_module, only: g2sec0,g2sec1,                                    &
                           g2sec4_temp0,g2sec4_temp8,g2sec4_temp9,g2sec4_temp44,         &
                           g2sec4_temp46,g2sec4_temp48,g2sec5_temp0,g2sec5_temp2,        &
                           g2sec5_temp3,g2sec5_temp40,get_g2_sec5packingmethod,          &
                           g2sec4_temp49
/glade/derecho/scratch/jongkim/UFS-RT/rt-2412/FV3/upp/sorc/ncep_post.fd/grib2_module.f(502): error #6580: Name in only-list doe\
s not exist or is not accessible.   [G2SEC4_TEMP49]
                           g2sec4_temp49

### To Reproduce:

Build ufs weather model develop branch for s2sw_debug_intel case.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I'm also struggling with this issue on Derecho. It seems the updated modules from #2326 are not getting loaded.

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA can you take a look at this? wondering if an upstream module refresh is needed...

**Comment by RatkoVasic-NOAA** [comment]
Fixed. @DeniseWorthen , @jkbk2004 please test it now.

**Comment by zach1221** [comment]
Testing now.
Edit: my jobs are derecho have been queued for a while. Just waiting for them to run.
