### ISSUE TITLE
permissions not set correctly on hercules (probably orion also)

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2432]
## Description

Try to ls the current develop baseline:
```
/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs> ls develop-20240904/cpld_bmark_p8_intel
ls: cannot access 'develop-20240904/cpld_bmark_p8_intel': Permission denied
```

This means I will not be able to run RTs against this basline.

**Comment by dpsarmie** [comment]
Ran across the same bug in work for my PR. Zach went ahead and changed the permissions so Hercules should be good to go.
