### ISSUE TITLE
Updated aerosol climatology not reflected in fix files

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/ufs-weather-model#2441]
My latest C96mx100 test failed with the following:
```
+ forecast_predet.sh[501]: /bin/cp -p /groups/BCASH/global-workflow/fix/aer/merra2.aerclim.2014-2023.m01.nc aeroclim.m01.nc
/bin/cp: cannot stat '/groups/BCASH/global-workflow/fix/aer/merra2.aerclim.2014-2023.m01.nc': No such file or directory
```
The updated climatology file that the workflow is looking for is not present in `fix/aer/20220805`, which is the version of `aer/fix` set in `fix.ver`. The updated climo files do not appear to be present in https://noaa-nws-global-pds.s3.amazonaws.com/index.html#fix/aer/ or  /work/noaa/global/glopara/fix/aer on Hercules. 

Where can I find the updated climo files, and can the fix version be updated so that they can be located correctly?

**Comment by NickSzapiro-NOAA** [comment]
Maybe this is a global-workflow issue instead? From this PR https://github.com/ufs-community/ufs-weather-model/pull/2273 , MERRA2 aerosol climatology is at @[INPUTDATA_ROOT]/FV3_input_data_INCCN_aeroclim/

**Comment by benjamin-cash** [comment]
Whoops! @NickSzapiro-NOAA yes, I meant to put this in global-workflow, too many tabs open....
