### ISSUE TITLE
Regression tests are failing on Hercules due to permission error

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#2452]
```
+ cp '/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/FV3_fix/*.txt' .
cp: cannot stat '/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/FV3_fix/*.txt': Permission denied
+ '[' 1 -eq 0 ']'
+ write_fail_test
+ echo 'control_stochy_debug_intelllvm failed in run_test'
```
Please fix this issue ASAP.

**Comment by DusanJovic-NOAA** [comment]
These are some of the previous issues, all related to permission error:

https://github.com/ufs-community/ufs-weather-model/issues/1930

https://github.com/ufs-community/ufs-weather-model/issues/2031

https://github.com/ufs-community/ufs-weather-model/issues/2120

https://github.com/ufs-community/ufs-weather-model/issues/2152

https://github.com/ufs-community/ufs-weather-model/issues/2409

https://github.com/ufs-community/ufs-weather-model/issues/2432

This still seems like an unsolvable computer science problem.

**Comment by DeniseWorthen** [comment]
Agreed. I've just had entire test RT fail because of this. Not.for.the.first.time.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA can you try a test on hercules?

**Comment by junwang-noaa** [comment]
@jkbk2004 maybe you can consider adding a line in the script to change permission on Hercules when a new baseline/input_data is created?

**Comment by DeniseWorthen** [comment]
@jkbk2004 Another idea---since we can't reliably count on being able to read from the baseline and inputdata on Hercules/Orion (*why* we can't reliably do that is another issue), please consider adding a check in rt.sh to verify that a user can read from the baseline and input-data directories before wasting time compiling everything and then failing when the run directory cannot be created.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA can you try a test on hercules?

It works now.
