### ISSUE TITLE
Update of UPP into UFS weather model 

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [ufs-community/ufs-weather-model#2477]
## Description

UPP was recently updated with additional output for SFS. https://github.com/NOAA-EMC/UPP/pull/1066. UFS weather model needs to be updated to easily use these updates in the weather model and g-w. 

## Solution

Update UPP to the latest dev. 

## Related to

. https://github.com/NOAA-EMC/UPP/pull/1066

**Comment by WenMeng-NOAA** [comment]
@NeilBarton-NOAA The FV3 PR #[880](https://github.com/NOAA-EMC/fv3atm/pull/880) has been submitted for updating upp submodule hash.
