### ISSUE TITLE
Compiler update is needed on Derecho: Intel ICC

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#2479]
## Description

icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second
 half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use
 this compiler. Use '-diag-disable=10441' to disable this message.
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second
 half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use
 this compiler. Use '-diag-disable=10441' to disable this message.
=>> PBS: job killed: walltime 1828 exceeded limit 1800

**Comment by ulmononian** [comment]
@rickgrubin-noaa fyi

**Comment by ulmononian** [comment]
@jkbk2004 is the title meant to imply moving to LLVM on derecho?

**Comment by jkbk2004** [comment]
> @jkbk2004 is the title meant to imply moving to LLVM on derecho?

@ulmononian Its good idea to pursue llvm on derecho. But be aware some build issues now. I think we will merge https://github.com/ufs-community/ufs-weather-model/pull/2458 next week. I think it's good timing to update compiler options on derecho.

**Comment by rickgrubin-noaa** [comment]
```
derecho2% module available

-------------------------------------- Module Stack Environments --------------------------------------


 [...]  intel-oneapi/2024.2.1     

derecho2% module show intel-oneapi/2024.2.1
------------------------------------------------------------------------------------------------------------------------
   /glade/u/apps/derecho/modules/23.09/Core/intel/2024.2.1.lua:
------------------------------------------------------------------------------------------------------------------------
whatis("Name : intel-oneapi-compilers")
whatis("Version : 2024.2.1")
whatis("Target : x86_64_v3")
[...]
setenv("CC","/glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/2024.2/bin/icx")
setenv("CXX","/glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/2024.2/bin/icpx")
setenv("F77","/glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/2024.2/bin/ifort")
setenv("FC","/glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/2024.2/bin/ifort")
[...]
setenv("OMPI_CC","icx")
setenv("OMPI_CXX","icpx")
setenv("OMPI_F77","ifort")
setenv("OMPI_FC","ifort")


derecho2% module load intel/2024.2.1

derecho2% which icx icpx ifx
/glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/2024.2/bin/icx
/glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/2024.2/bin/icpx
/glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/2024.2/bin/ifx

derecho2% icx --version
Intel(R) oneAPI DPC++/C++ Compiler 2024.2.1 (2024.2.1.20240711)

derecho2% icpx --version
Intel(R) oneAPI DPC++/C++ Compiler 2024.2.1 (2024.2.1.20240711)

derecho2% ifx --version
ifx (IFX) 2024.2.1 20240711

```

**Comment by ulmononian** [comment]
@jkbk2004 the error shows the job being killed to to wallclock time being exceeded. compiler message just seems to be a deprecation warning. is there another error log that shows more details? what test was this from?

**Comment by NickSzapiro-NOAA** [comment]
I think there is something wrong with build/system on derecho before updating compiler. My compile takes 30 minutes to get only to here and then times out:
```
entire contents of run_dir/compile_s2swa_intel/out:
Compile started:   Fri 25 Oct 2024 08:56:04 AM MDT
Compiling -DAPP=S2SWA -D32BIT=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 into fv3_s2swa_intel.exe on derecho
CMAKE_FLAGS = -DAPP=S2SWA -D32BIT=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DMPI=ON -DCMAKE_BUILD_TYPE=Release -DMOM6SOLO=ON
UFS MODEL DIR: /glade/work/szapiro/tasks/gefs_RT/uwm_tinker
-- The C compiler identification is Intel 2021.10.0.20230609
```

**Comment by DeniseWorthen** [comment]
I ran all compile jobs from the top of develop on Derecho after commenting out all RUN jobs in rt.conf. All jobs compiled with the exception of ``s2swa_faster_intel``. I then compiled that job separately

```
./compile.sh derecho "-DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DFASTER=ON" test intel NO NO 2>&1 | tee test.log
```

and it successfully compiled and reported

```
+ echo 'Elapsed time 2119 seconds. Compiling -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DFASTER=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release -DMOM6SOLO=ON finished'
Elapsed time 2119 seconds. Compiling -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DFASTER=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release -DMOM6SOLO=ON finished
+ echo 'Compile test elapsed time 2119 seconds. -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DFASTER=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release -DMOM6SOLO=ON'
```

**Comment by NickSzapiro-NOAA** [comment]
Compile for s2swa_32bit_pdlib intel times out for me now but I do see `[100%] Linking Fortran executable ufs_model` in run_dir/compile_s2swa_32bit_pdlib_intel/out

**Comment by jkbk2004** [comment]
Rocoto is slow though on Derecho but regression test runs ok on Derecho.
