### ISSUE TITLE
coupled model does not build with esmf-debug libraries when debug=Y

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#249]
## Description
The coupled model should build using the fv3_debug module when DEBUG=Y

### To Reproduce:
Check compile log for the coupled model debug test (cpld_debug)

@aerorahul was provided a fix for compile.sh which appears to work:
<img width="776" alt="Screen Shot 2020-10-27 at 11 29 40 AM" src="https://user-images.githubusercontent.com/40498404/97323983-b5fe0400-1847-11eb-9c36-c79723e3c62d.png">

**Comment by climbfuji** [comment]
Do we have debug module files for all platforms? I only see hera.intel, orion.intel and wcoss_dell_p3, none of the others.

**Comment by DeniseWorthen** [comment]
Would it work then to trigger fv3_debug with DEBUG=Y &&  S2S=Y ? Would that be a solution, since we're testing the coupled model only on those three platforms that you list.

**Comment by aerorahul** [comment]
more appropriate would be if `fv3_debug` is present then load it, if not `fv3` regardless of S2S=ON|OFF for DEBUG=Y

**Comment by aerorahul** [comment]
Something like this:
```
diff --git i/tests/compile.sh w/tests/compile.sh
index c5d0df4..4300685 100755
--- i/tests/compile.sh
+++ w/tests/compile.sh
@@ -57,7 +57,11 @@ if [[ $MACHINE_ID == macosx.* ]] || [[ $MACHINE_ID == linux.* ]]; then
   source $PATHTR/modulefiles/${MACHINE_ID}/fv3
 else
   module use $PATHTR/modulefiles/${MACHINE_ID}
-  module load fv3
+  modulefile="fv3"
+  if [[ "${MAKE_OPT}" == *"DEBUG=Y"* ]]; then
+    [[ -f $PATHTR/modulefiles/${MACHINE_ID}/fv3_debug ]] && modulefile="fv3_debug"
+  fi
+  module load $modulefile
   module list
 fi
 set -x
```

**Comment by junwang-noaa** [comment]
does datm model also load the fv_debug module?

**Comment by aerorahul** [comment]
All debug regression tests `DEBUG=Y`, for all configurations of the UFS model will use the `fv3_debug` modulefile, if this modulefile is present/available for that machine.  Otherwise, it will use the `fv3` modulefile.

**Comment by DeniseWorthen** [comment]
> All debug regression tests `DEBUG=Y`, for all configurations of the UFS model will use the `fv3_debug` modulefile, if this modulefile is present/available for that machine. Otherwise, it will use the `fv3` modulefile.

We do want DATM to use fv3_debug, so this seems like the right solution.

**Comment by binli2337** [comment]
Right now, we don't have a debug test for datm yet. We can add one using fv3_debug.
