### ISSUE TITLE
Regression tests are failing on Hercules due to permission error

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#2490]
Here we go. Again.

```
$ ls -l /work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/develop-20241028/
ls: cannot open directory '/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/develop-20241028/': Permission denied
```

These are some of the previous issues, all related to permission error:

https://github.com/ufs-community/ufs-weather-model/issues/1930

https://github.com/ufs-community/ufs-weather-model/issues/2031

https://github.com/ufs-community/ufs-weather-model/issues/2120

https://github.com/ufs-community/ufs-weather-model/issues/2152

https://github.com/ufs-community/ufs-weather-model/issues/2409

https://github.com/ufs-community/ufs-weather-model/issues/2432

https://github.com/ufs-community/ufs-weather-model/issues/2452

https://github.com/ufs-community/ufs-weather-model/issues/2476

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA can you check? permission is released.

**Comment by DusanJovic-NOAA** [comment]
Thanks.
