### ISSUE TITLE
baseline permissions on hercules (and probably orion) AGAIN

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#2499]
/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/develop-20241112/’: Permission denied

**Comment by FernandoAndrade-NOAA** [comment]
That was my mistake, permissions should be opened up now please try again.

**Comment by DeniseWorthen** [comment]
I can now "ls" the directory which is tells me it should work.
