### ISSUE TITLE
Permission errors on Hercules with newest baselines

### ISSUE THREAD

**Issue by dpsarmie** [ufs-community/ufs-weather-model#2526]
> ******Regression Testing Script Started******
> hercules-login-2.hpc.msstate.edu
> Machine: hercules
> Account: nems
> rt.sh: Setting up hercules...
> Linking /work2/noaa/stmp/dsarmien/stmp/dsarmien/FV3_RT/rt_2853351 to /work/noaa/stmp/dsarmien/clean-weather-model/tests/run_dir
> Run regression test in: /work2/noaa/stmp/dsarmien/stmp/dsarmien/FV3_RT/rt_2853351
> rt.sh: Checking & Updating test configuration...
> find: ‘/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/develop-20241127/’: Permission denied

Similar issue to #2499 #2490 #2476 etc.

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA @dpsarmie JFYI, I also hit to same issue.

**Comment by junwang-noaa** [comment]
@jkbk2004 @FernandoAndrade-NOAA Would you please add a script to fix the permission issue on the baselines on Hercules? This happened many times already. Thank you!

**Comment by FernandoAndrade-NOAA** [comment]
@dpsarmie Please try again, permissions should be open for develop-20241127

**Comment by jkbk2004** [comment]
I set a crontab on orion/hercules to check and release baseline files on daily basis.
