### ISSUE TITLE
FV3 input restart data contains unmatched resolution

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#257]
## Description
On Hera, FV3_input_data_c192/RESTART and FV3_input_data_c768/RESTART contain C96_grid.tile*.nc. This is problematic when restart test is done at these resolutions. These can be seen, for example, under /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201022/INTEL

**Comment by junwang-noaa** [comment]
removed. The grid tile files can be found in FV3\*data\*/INPUT. Please let me know if there is still any issue.

**Comment by MinsukJi-NOAA** [comment]
Thanks. Closing this issue.
