### ISSUE TITLE
Adde a debug test, a 6-hr test, a 12-hr test, and a restart test for the DATM-MOM6-CICE6 application

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#260]
## Description
A debug test, a 6-hr test, a 12-hr test, and a restart test will be added to the DATM-MOM6-CICE6 regression test system.

## Solution
The following three new tests will use 1-degree MOM6 and CICE6. The atmospheric forcing data will be from GEFS:

1.  6-hr test
2. 12-hr test
2. restart test. The model will run from hour 6 to hour 12.
3. debug test.

Related issue:
#281

**Comment by junwang-noaa** [comment]
Could we also add the following?
1. MPI tasks adjustment for 1 degree runs
2.  hera.gnu and wcoss_dell_p3 tests 

(see [PR#256](https://github.com/ufs-community/ufs-weather-model/pull/256)) Thanks
