### ISSUE TITLE
update wiki page on making code changes in ufs-weather repo

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#264]
## Description
Update the ufs-weather wiki: 

https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents

with the slides presented at today's EIB meeting.

**Comment by BrianCurtis-NOAA** [comment]
Updates and fixes finished.
