### ISSUE TITLE
update Noah MP codes

### ISSUE THREAD

**Issue by HelinWei-NOAA** [ufs-community/ufs-weather-model#267]
* add kind=kind_phys to Noah MP-related subroutines to have them running with the same precision as the other parts of the model
* solve some inconsistency issues inside and outside Noah MP (sfc_diff, surface albedo, surface emissivity)
* some bug fixes 
* add some conditions to stop model from crashing

**Comment by junwang-noaa** [comment]
Helin, may I ask whom you recommend to work on this issue?

**Comment by HelinWei-NOAA** [comment]
Hi Jun,

Mike, Rongqian and I are going to work on this issue. Thanks.

Helin

**Comment by HelinWei-NOAA** [comment]
I have put the updates in both ipd and ccpp physics. Please take a look at these two forks. 
https://github.com/HelinWei-NOAA/fv3atm
https://github.com/HelinWei-NOAA/ccpp-physics
for ccpp, I use this branch https://github.com/HelinWei-NOAA/ccpp-physics/tree/feature/noahmp

I have make a one 7-day forecast test for both ipd and ccpp. It seems to me the difference is okay.
 https://www.emc.ncep.noaa.gov/mmb/gcp/gfs/ccppnoahmp/

**Comment by junwang-noaa** [comment]
@HelinWei-NOAA The code changes were committed, can we close this issue? Thanks

**Comment by HelinWei-NOAA** [comment]
Yes. Thanks.
