### ISSUE TITLE
updating git submodules

### ISSUE THREAD

**Issue by jedwards4b** [ufs-community/ufs-weather-model#27]
I would like to update the ufs_public_release branch to use 1e3cdc1d of https://github.com/NOAA-EMC/fv3atm
It's not at all clear to me how to do that, google pointed me to a command
git submodule update --remote --merge
which did not appear to do what I wanted as it also gave me updates for all the other submodules.  @climbfuji can you clarify the process for me?  Thanks

**Comment by DusanJovic-NOAA** [comment]
@jedwards4b 

1) In your ufs-weather-model fork, make sure ufs_public_release branch is even with ufs-community:ufs_public_release. Right now it's 7 commits behind.

2) Once your ufs_public_release branch is even with ufs-community:ufs_public_release create a new branch off of ufs_public_release.

3) Clone that branch:
```
git clone -b <YOUR_NEW_BRANCH_NAME> --recursive https://github.com/jedwards4b/ufs-weather-model
```
4) In ufs-weather-model/FV3, run:
```
git checkout ufs_public_release
```
which should update FV3 from 2765a1f to 1e3cdc1.

5) in ufs-weather-model
```
git add FV3

git commit -m "......"

git push origin <YOUR_NEW_BRANCH_NAME>
```
6) Create new pull request from jedwards4b/ufs-weather-model:<YOUR_NEW_BRANCH_NAME> to ufs-community/ufs-weather-model:ufs_public_release

**Comment by jedwards4b** [comment]
Thank you
