### ISSUE TITLE
UFS weather model port to JET

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-weather-model#271]
## Description

UFS weather model will be needed for multiple experiments that will be run on JET. For that reason we need to elevate JET to Tier -1 support. 

## Solution

Port UFS weather model built to use hpc-stack on JET

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

This is related to hpc-stack being installed on JET. Please see issue 
https://github.com/NOAA-EMC/hpc-stack/issues/54

**Comment by EricRogers-NOAA** [comment]
Hi Arun, there is a Redmine task for this ([](https://vlab.ncep.noaa.gov/redmine/issues/67680), assigned to Kate, that has been On Hold for 8 months. What should be done with it? If it is again active, who should it be assigned to? Thanks, Eric

**Comment by EricRogers-NOAA** [comment]
The link to the Redmine task is https://vlab.ncep.noaa.gov/redmine/issues/67680

**Comment by climbfuji** [comment]
@kgerheiser and @Hang-Lei-NOAA from the NCEPLIBS team will be taking over the installation of the prerequisite libraries (in particular hpc-stack) as per discussion in https://github.com/NOAA-EMC/hpc-stack/issues/83.

I currently maintain the ecflow installation on the machine, we can think about switching this over to EMC as well, following what @MinsukJi-NOAA did for the other tier-1 platforms.

The ufs-weather-model port and tier-1 regression testing should not be confused with the global workflow port, which has been assigned to Kate as it seems. But making jet a tier-1 system for the ufs-weather-model will facilitate Kate's task.

**Comment by MinsukJi-NOAA** [comment]
@climbfuji, I am okay with that.

**Comment by climbfuji** [comment]
Fixed in https://github.com/ufs-community/ufs-weather-model/pull/304
