### ISSUE TITLE
Create a pre-processing package that contains the ncl scripts and input data required to create CICE initial condition files

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#275]
## Description
Create a pre-processing package that contains scripts and input data to create CICE initial condition files from CPC input data.

## Solution
Move all grid related input data and scripts to a single directory on Hera.
A test case will be provided.

**Comment by DusanJovic-NOAA** [comment]
Why is _"pre-processing package that contains scripts and input data"_ being added to this repository?

**Comment by binli2337** [comment]
The scripts have been created and tested.
