### ISSUE TITLE
use new nceplibs hpc stack libraries in CI test

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#277]
## Description
It is found that the CI test failed at compile time for the [PR #274](https://github.com/ufs-community/ufs-weather-model/pull/274): Bring GFS.v16 features back to develop branch. Since the upp library is updated in hpc-stack in PR #274, the hpc stack needs to be updated in docker container in order to compile the code.  

## Solution
Update the hpc stack lib in docker container for CI test

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to:

-  ufs-weather-model [PR #274](https://github.com/ufs-community/ufs-weather-model/pull/274)

**Comment by MinsukJi-NOAA** [comment]
@Hang-Lei-NOAA, is there anyway to build hpc-stack with upp using build_stack.sh on linux (gnu, mpich) machine?

**Comment by Hang-Lei-NOAA** [comment]
Hi, Minsuk

There should be fine.
I have not try the develop.
But I installed the feature/hpc-stack-nco on several other machines.
Dom is updating that branch.
After his merge, you can try it, and let me know if any issue raise.

Thanks,
Hang

**Comment by climbfuji** [comment]
Fixed in https://github.com/ufs-community/ufs-weather-model/pull/297 ?

**Comment by junwang-noaa** [comment]
Yes, I think we can close the issue.
