### ISSUE TITLE
rt.sh ecflow does not work properly on orion when hpc stack path is changed

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#279]
## Description
On orion when the hpc stack path is changed, running RT using rt.sh -fe shows that all the debug tests failed. The compile log files show that for debug tests the ESMF debug module is loaded to replace the ESMF module during compile time, but then ESMFMKFILE is pointing to a wrong path. However manually reloading esmf debug module after esmf module does not have this problem, the ESMFMKFILE is pointing to correct path. Also rt.sh -l rt.conf does not have this issue either.

### To Reproduce:
on orion, checkout following branch which uses a new hpc-stack path:
git clone --recursive --branch gfsv16_20201015 https://github.com/junwang-noaa/ufs-weather-model
cd ufs-weather-model
*create a new rt.conf2:

COMPILE | CCPP=Y SUITES=FV3_GFS_2017                                                                                                     | standard    |                | fv3         |

RUN     | fv3_ccpp_control                                                                                                               | standard    |                | fv3         |

COMPILE | CCPP=Y SUITES=FV3_GFS_2017,FV3_GFS_2017_stretched 32BIT=Y DEBUG=Y                                                              | standard    |                | fv3         |
RUN     | fv3_ccpp_control_debug                                                                                                         | standard    |                | fv3         |

then run: "rt.sh -e -l rt.conf2", the compile in second test will fail with ESMFMKFILE points to a non-existing file:

++ ESMFMKFILE=/apps/contrib/NCEP/test/hpc-stack-nco/intel-2018.4/impi-2018.4/esmf/8_1_0_beta_snapshot_27-debug/lib/esmf.mk 

however running: rt.sh -l rt.conf2  will be successfully with:
++ export ESMFMKFILE=/apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/esmf/8_1_0_beta_snapshot_27-debug/lib/esmf.mk

A test directory is on orion at:
/work/noaa/nems/junwang/ufs-weather/20201103/ufs-weather-model/tests

Related PRs:

This is related to [PR #274](https://github.com/ufs-community/ufs-weather-model/pull/274)

**Comment by climbfuji** [comment]
I think this is the same issue as https://github.com/ufs-community/ufs-weather-model/issues/235 - the ecflow server is loaded with a certain environment (variables, modules) and remembers this information if it survives the `rt.sh` call (i.e. if it is not terminated correctly, which seems to happen under certain conditions).

**Comment by DusanJovic-NOAA** [comment]
I believe this will be fixed in PR #273.

**Comment by junwang-noaa** [comment]
That's good, let me do a test by getting the rt.sh and rt_utils.sh changes
in PR#273.

**Comment by junwang-noaa** [comment]
The test is done, the ecflow on Orion is now working fine with the the rt.sh and rt_utils.sh changes in PR#273.

**Comment by junwang-noaa** [comment]
Dusan's fix in PR#273 resolved the issue. Close ticket.
