### ISSUE TITLE
Compile error on WCOSS2

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#282]
## Description
Compilation fails on wcoss2 with this error message:

```
[ 98%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/fv3_cap.F90.o
/lfs/h2/emc/ptmp/Dusan.Jovic/ufs-weather-model/FV3/fv3_cap.F90(604): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [ATTRECONFLAG]
    call ESMF_StateReconcile(fcstState, attreconflag= ESMF_ATTRECONCILE_ON, rc=rc)
----------------------------------------^
compilation aborted for /lfs/h2/emc/ptmp/Dusan.Jovic/ufs-weather-model/FV3/fv3_cap.F90 (code 1)
make[2]: *** [FV3/CMakeFiles/fv3atm.dir/build.make:96: FV3/CMakeFiles/fv3atm.dir/fv3_cap.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:508: FV3/CMakeFiles/fv3atm.dir/all] Error 2
make: *** [Makefile:172: all] Error 2

```

## Additional context
I am loading `esmf/8_1_0_beta_snapshot_36` module from `/lfs/h2/emc/nceplibs/noscrub/hpc-stack/test/noaa/modulefiles/stack` which is different than esmf version used on wcoss_cray or wcoss_dell_p3 (esmf/8_1_0_beta_snapshot_27).

**Comment by climbfuji** [comment]
Same problem on gaea when building the stack with BS36 (as per feature/hpc-stack-nco yaml files). We should also remove the whitespace right off `attreconflag=` for consistency reasons.

**Comment by DusanJovic-NOAA** [comment]
On wcoss2 these are the compiler versions:
```
C       compiler: Intel 19.1.0.20200306 (cc)
CXX     compiler: Intel 19.1.0.20200306 (CC)
Fortran compiler: Intel 19.1.0.20200306 (ftn)
```
what version do you use on gaea?

**Comment by climbfuji** [comment]
> On wcoss2 these are the compiler versions:
> 
> ```
> C       compiler: Intel 19.1.0.20200306 (cc)
> CXX     compiler: Intel 19.1.0.20200306 (CC)
> Fortran compiler: Intel 19.1.0.20200306 (ftn)
> ```
> 
> what version do you use on gaea?

Still 18.0.6.288 because I know that the ufs-weather-model compiles and runs with this one. Don't want to make 2 changes (compiler version and software stack) at the same time. But I will upgrade to the latest version afterwards:
```
intel/18.0.6.288
intel/19.0.5.281(default)
intel/19.1.1.217
intel/19.1.4.304
```
Based on everything I heard, 19.0.x versions have a lot of issues, hence I want to avoid them.

**Comment by junwang-noaa** [comment]
Please use esmf810bs27 at this time. We need code changes in the model in order to use esmf810bs36. Please see [fv3atm PR #280](https://github.com/NOAA-EMC/fv3atm/pull/180)

**Comment by DusanJovic-NOAA** [comment]
Fixed by switching to esmf/8_1_0_beta_snapshot_27

**Comment by XianwuXue-NOAA** [comment]
@junwang-noaa @DusanJovic-NOAA  I also encountered such issue when I build fv3gfs on global-workflow v15 for GEFS using esmf/8.1.0 on WCOSS2/Acorn, I tried to use esmf/8_1_0_beta_snapshot_27, but I got more errors. However, when I use esmf/8_1_0_beta_snapshot_26, I successfully built the FV3.  In the future, the WCOSS2 will use esmf/8_1_0_beta_snapshot_26 in production or esmf/8.1.0? If they will use esmf/8.1.0, how should I fix the issue?
