### ISSUE TITLE
can't build coupled model in debug mode on orion

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#287]
## Description
Building the coupled model with DEBUG=Y fails on orion. The same commands build the model on hera successfully.

### To Reproduce:
Checkout ufs-weather develop branch:

module use modulefiles/orion.intel
module load fv3_debug
CMAKE_FLAGS="-DS2S=ON -DDEBUG=ON" CCPP_SUITES="FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled" ./build.sh >output 2>&1 &

## Output
 Build fails:

<img width="1587" alt="Screen Shot 2020-11-19 at 9 07 04 AM" src="https://user-images.githubusercontent.com/40498404/99676513-9ae97300-2a46-11eb-93c1-cc5d441c5a9c.png">

Build directory on Orion:

/work/noaa/marine/dworthen/ufs_tod

**Comment by DeniseWorthen** [comment]
Has anyone else been able to replicate this? I tried running the cpld_debug test for the currrent develop branch. The err log (in rt_number/compile_3) shows:

  3) esmf/8_1_0_beta_snapshot_27

The esmf debug library on orion is esmf/8_1_0_beta_snapshot_27-debug

Any ideas on why this is getting set incorrectly?

**Comment by junwang-noaa** [comment]
In compile.sh, we have:
module use $PATHTR/modulefiles/${MACHINE_ID}
modulefile="fv3"
if [[ "${MAKE_OPT}" == *"DEBUG=Y"* ]]; then
[[ -f $PATHTR/modulefiles/${MACHINE_ID}/fv3_debug ]] && modulefile="
fv3_debug"
fi
module load $modulefile
module list

Would you please check in compile.sh command, if it has "DEBUG=Y"?

**Comment by DeniseWorthen** [comment]
My build directory on orion is: 

/work/noaa/marine/dworthen/ufs_dw. In there, I have rt.conf reduced to just the cpld_debug compile and run.

One output directory is here: /work/noaa/stmp/dworthen/stmp/dworthen/FV3_RT/rt_112174

I just noticed that in the compile_1/err I see:

The following have been reloaded with a version change:
  1) esmf/8_1_0_beta_snapshot_27 => esmf/8_1_0_beta_snapshot_27-debug

**Comment by junwang-noaa** [comment]
So that looks to me you are loading esmf810bs27 debug.

**Comment by DeniseWorthen** [comment]
Yes, I agree that it seems to be loading the right esmf debug module, but the compile immediately fails on 'use esmf', as if it is actually trying to use the non-exisistent "_debug."

**Comment by DeniseWorthen** [comment]
I can compile in debug mode on orion if I do not use ecflow.

**Comment by junwang-noaa** [comment]
Not sure if we have the same problem with debug tests. Please see Issue #279
<https://github.com/ufs-community/ufs-weather-model/issues/279>. Can you
check the ESMF lib path when you use ESMF debug lib in ecflow on orion?

**Comment by climbfuji** [comment]
@DeniseWorthen can you check if you have an old version of the ecflow server running (`ps ux`)? If so, kill it with `kill -9 PID` and try again.

**Comment by DeniseWorthen** [comment]
Yes thanks. I did find a very old ecflow job running which I killed. I'll try again.

**Comment by DeniseWorthen** [comment]
It seems that the old ecflow server was the issue. I've been able to repeat the same test now and am able to build in debug mode. Thanks all!
