### ISSUE TITLE
Need low resolution files to run basic tests on a workstation and workflow

### ISSUE THREAD

**Issue by aerorahul** [ufs-community/ufs-weather-model#289]
## Description
Development on an HPC is not always possible and takes too much time and resources.
For the cycled workflow infrastructure development, the lowest possible resolutions of the UFS are needed so that the infrastructure can be developed and tested on a local workstation.
We are not looking for scientifically valid or correct results, but something that we can cycle for 4-6 assimilation cycles without the model blowing up.

The configurations of the model that will be run are:
weather, coupled and data atmosphere.
waves are not expected to be part of the system at this point.

## Solution
Ideally a C24 atmosphere + 4 deg ocean (and sea ice)

## Alternatives
C48 atmosphere with a 2 deg ocean (and sea ice)

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support cycled workflow development in JEDI applications

**Comment by climbfuji** [comment]
@aerorahul I am regularly running C96 on my Macbook pro with 16GB memory. It's not fast, but for a few cycles acceptable. C48 would be better, and @MinsukJi-NOAA is/was working on this for the CI tests. I don't think we need to go down to C24.

**Comment by aerorahul** [comment]
I am talking ensembles.

**Comment by climbfuji** [comment]
Oh okay, different story. Have never seen a C24 grid, not sure if this exists.

**Comment by MinsukJi-NOAA** [comment]
I don't have a timeline for C48 tests. I don't know much about ensemble, but what would be the objective of the tests?

**Comment by aerorahul** [comment]
Like I said in the description, we need initial conditions for an ensemble to do data assimilation and test the workflow infrastructure around it.

**Comment by DeniseWorthen** [comment]
I am aware of this thread (https://github.com/NOAA-GFDL/MOM6-examples/issues/252) which talks about generating a 3deg/28 level MOM6. The thread starts back in Nov 2018 but the latest post was in Oct. If the ocean_hgrid is available (from which we can make the cice6 grid), then w/ that and the input settings posted in that thread, it seems it should be doable from the ocean/ice side.

**Comment by junwang-noaa** [comment]
I think most likely we can start with an atmosphere C48 with 3degree/28
levels ocean/ice then.

**Comment by DeniseWorthen** [comment]
For the DATM, we could also create low-resolution forcing files; currently we are using ~ 0.2deg forcing for the 1deg ocean/ice. For non-science purposes (this includes the RTs) I think using DATM resolution that matches the ocean/ice resolution makes more sense.

**Comment by whuiskamp** [comment]
Hi all, 
If you're interested in utilising my MOM6-SIS2 coarse configuration, I'm happy to provide it to you. It's not publicly available yet, because scientific tuning and evaluation is still ongoing, but I can give you my current stable build.

**Comment by DeniseWorthen** [comment]
@whuiskamp Thanks. That would be very helpful. Is the package small enough to email or share in a google drive? My email is Denise.Worthen at noaa.gov.

**Comment by DeniseWorthen** [comment]
Willem kindly provided the files for his 3x3 MOM6 setup and I've been able to create the CICE6 grid and ICs from those.  The 3x3 deg grid has a lot less land around Antarctica for example, so the July2011 IC for ice concentration shows open water along most of the coast. I'll probably need to work on a regridding solution but I may try to see if it will run in the ufs-datm first.

1/4 deg CICE6 IC 
<img width="770" alt="Screen Shot 2020-12-14 at 4 41 57 PM" src="https://user-images.githubusercontent.com/40498404/102140267-00096c00-3e2d-11eb-8440-d8c8939e3dce.png">


3deg CICE6 IC
<img width="771" alt="Screen Shot 2020-12-14 at 4 42 44 PM" src="https://user-images.githubusercontent.com/40498404/102140340-17485980-3e2d-11eb-8eae-553c35762ee7.png">

**Comment by arunchawla-NOAA** [comment]
Hello

The request for low resolution coupled model test case has risen to the top again. Can we get a coupled atm - ocean model test case ? Looking back at this thread there was a possibility of having C48 - 3deg ocean system. Can we resuscitate this effort @junwang-noaa @MinsukJi-NOAA and @DeniseWorthen ? 

We only need this for technical testing so need it to run for 24 hour at least.

**Comment by junwang-noaa** [comment]
I will set up a C48L127 atmosphere run with ICs 20210322, and will try to
keep the namelist consistent with higher resolutions.

**Comment by arunchawla-NOAA** [comment]
If we can start with an atmosphere only then that is fine. If we can put together a plan and LOE for doing low resolution coupled model for testing then that would be great. Long term this would be very helpful for testing

**Comment by aerorahul** [comment]
The JEDI/SOCA team routinely has been running a 4 degree MOM6 (with/without seaice) in their CI.  
Their data directory is https://github.com/JCSDA-internal/soca/tree/develop/test/Data/72x35x25
Please let me know how I can help.

**Comment by rsdunlapiv** [comment]
@uturuncoglu is planning for the exchange grid implementation in CMEPS.  Access to a low resolution test case like this will be very helpful for the early stages of development.

**Comment by whuiskamp** [comment]
@aerorahul I'd be interested in the MOM_parameter.all file for that setup, if available. Have the runs been validated? What kind of AMOC does this configuration produce? In mine (and other's) experience with coarse MOM6, the AMOC tends to be quite weak (~12 Sv), and I can't seem to find a solution.

**Comment by rsdunlapiv** [comment]
It is great to see the C48 atmosphere only case @junwang-noaa. 
https://github.com/ufs-community/ufs-weather-model/issues/716

Has any progress been made by anyone for the coupled case w/ 3-deg ocn/ice?

**Comment by DeniseWorthen** [comment]
For either then C48-4deg or C48-3deg, I need the ATM ICs created for the coupled model. I have the mapped ocean-mask that we need, but I don't have the time to delve into how to create the ATM ICs consistent w/ those files.

**Comment by aerorahul** [comment]
@DeniseWorthen 
What datetime do you wish to have ATM initial conditions?
Will these be GFS cold start or warm start?
Can you reuse the atm initial conditions from the C48L127 case added by @junwang-noaa ?

**Comment by DeniseWorthen** [comment]
@aerorahul It is my understanding that there is an additional step after generation of the ATM ICs for the standalone that is required to correct for the fractional land (that is why we need the mapped ocean mask). Jun added the atm-only test for 2021032206, which is what I had assumed we'd be using. I'm able to create a MOM6 T-S file IC (from CFS) and  CICE6 IC (from CPC reanalysis) for that date.

**Comment by aerorahul** [comment]
And who should we ask about this "additional step"?

**Comment by DeniseWorthen** [comment]
Someone who understands chgres or who has the time to figure it out.

**Comment by sanAkel** [comment]
> It is great to see the C48 atmosphere only case @junwang-noaa.
> #716
> 
> Has any progress been made by anyone for the coupled case w/ 3-deg ocn/ice?

Hi All,
Just as an FYI: at GMAO we have a 5-deg `ocean-only` case running; our resolutions are listed [at](https://github.com/GEOS-ESM/GEOSgcm_App/issues/219#issue-871182278). If anyone wants to explore `5-deg` case for **technical** purposes (PR, testing, debugging, etc), I can provide what I have.

**Comment by DeniseWorthen** [comment]
This is almost running now in the regression tests as a coupled_c48 case. I'm tracking down a MOM_parameter parser error now but I hope to be able to commit with PR #765

**Comment by arunchawla-NOAA** [comment]
@junwang-noaa and @DeniseWorthen 

do we have low resolution runs now ? Can this issue be considered closed ?

**Comment by junwang-noaa** [comment]
We have low resolution C48 for atmosphere only in ufs-weather-model, but
not for the coupled system.  @DeniseWorthen
<https://github.com/DeniseWorthen> do we have 4 degree mom6 running now?

**Comment by DeniseWorthen** [comment]
I have not be able to run the 4deg MOM6 configuration. It is not initializing the T,S fields correctly and immediately implodes. I have not worked further on the issue since it was viewed as a waste of time by the coupled group.

**Comment by JessicaMeixner-NOAA** [comment]
Is there a branch @jiandewang and I should use to run a few more tests?  We've talked with @guillaumevernieres and Travis offline and they pointed us to a set-up which on second read of this whole chain is perhaps the same starting point but there were a few differences between what I saw and an older run directory @jiandewang pointed me to.  It might be worth looking to see if a few of those settings differences could get us past the imploding point.

**Comment by jiandewang** [comment]
@JessicaMeixner-NOAA I think @DeniseWorthen may have a new workdir than the one I pointed to you which is half year ago stuff

**Comment by DeniseWorthen** [comment]
I don't know what directory you may be looking at. The last time I worked on this was Aug 2021. The initial config was obtained from the soca 72x35x25 files.

**Comment by jiandewang** [comment]
this is what I got from you
/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_17269/cpld_control_c48_p7

**Comment by DeniseWorthen** [comment]
Thanks @jiandewang, that appears to be about the last time I worked on the issue.

**Comment by DeniseWorthen** [comment]
A coupled C48-5deg ocean/ice test has been added via PR #1287
