### ISSUE TITLE
Update UFS weather model user's guide information in preparation for the SRW App release

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-weather-model#298]
## Description
Documentation preparation for the SRW Application release

## Solution
There is a need to simplify the "App" specific sections (Intro, SDF, I/O) and adds more detail to the Inputs/Outputs chapter now that we have two applications that will be released

## Related to
UFS SRW Application User's Guide issue: https://github.com/ufs-community/ufs-srweather-app/issues/4

**Comment by jwolff-ncar** [comment]
Update the i/o section: From Chan-Hoo - You can find the description of output options by 'quilting' in Chapter 3.4.1 (page 70) of my documentation.

**Comment by jwolff-ncar** [comment]
Ensure that there are appropriate links (to correct versions) 
 - NEMS
 - FMS
 - NUOPC 
 - ESMF 
documentation as needed

**Comment by llpcarson** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/340

**Comment by arunchawla-NOAA** [comment]
@jwolff-ncar is this complete now that the release has been made ? Is there a PR to bring back release branch to develop? 

I am also adding @junwang-noaa and @DusanJovic-NOAA for their information

**Comment by llpcarson** [comment]
@arunchawla-NOAA We (DTC) just discussed this yesterday, and I will be creating a PR for the documentation updates to develop in the next week or so.

**Comment by llpcarson** [comment]
Closed via https://github.com/ufs-community/ufs-weather-model/pull/521
