### ISSUE TITLE
Enable runs that use RRTMGP with 127 vertical levels

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-weather-model#300]
## Description
The UFS Weather Model cannot run a 127-level configuration with RRTMGP. It is expected to error out with message `array plev has values outside range`. This configuration is needed for the test toward GFSv17/GEFSv13.

## Solution
A one-line change is needed in submodule https://github.com/earth-system-radiation/rte-rrtmgp/, in branch dtc/ccpp. Note that rte-rrtmgp is a submodule of ccpp-physics.
The change is described in https://github.com/earth-system-radiation/rte-rrtmgp/commit/be10425fbe72532c66c25cd6c670630ac6066834

## Alternatives
Apply the one-line change manually until the problem is resolved.

## Related to
An issue will be created in the ccpp-physics repository

**Comment by junwang-noaa** [comment]
The code is committed in [PR #378](https://github.com/ufs-community/ufs-weather-model/pull/378), close issue.
