### ISSUE TITLE
compile flags set for CICE and MOM6 are different when compiled as ufs-datm vs ufs-cpld

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#302]
## Description

The compiler flags used to compile CICE in ufs-datm are different than when compiled for ufs-cpld. This is the source of the non-reproducibility of the ufs-datm noted in issue #281.

### To Reproduce:

Build ufs-weather either as ufs-cpld or ufs-datm outside of the rt system (ie, a direct build using build.sh). Examine build/CICE-interface/CMakeFiles/cice.dir/flags.make. 

For ufs-cpld:

```Fortran_FLAGS = -g -traceback -FR -convert big_endian -assume byterecl -ftz -align array64byte -xHOST -O2 -fp-model precise -module mod   -qopenmp```

For ufs-datm:

```Fortran_FLAGS = -g -traceback -FR -convert big_endian -assume byterecl -ftz -align array64byte -xHOST -module mod   -qopenmp```

The use of ``-fp-model precise`` is required for restart reproducibility in CICE6. It had been present in the machine macros for all supported platforms. I believe the issue is that when compiled as ufs-cpld, it is getting some set of flags set in the FV3 compile; in the DATM this does not happen.

**Comment by DeniseWorthen** [comment]
The same issue is present in the MOM6 compile for ufs-datm vs ufs-cpld (build/MOM6-interface/CMakeFiles/mom6.dir/flags.make):

ufs-cpld:

```Fortran_FLAGS = -g -traceback -i4 -r8 -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -sox -O2 -debug minimal -fp-model source```

ufs-datm:

```Fortran_FLAGS = -g -traceback -i4 -r8 -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -sox```

Searching intel documentation leads me to understand that for Fortran, ``fp-model source`` is equivalent to ``fp-model precise`` but I defer to those with a much better understanding of compile options.

**Comment by aerorahul** [comment]
@DeniseWorthen 
Line 11 in https://github.com/ufs-community/ufs-weather-model/blob/develop/CICE-interface/CMakeLists.txt adds the `-fp-model precise` flag in CICE.

In MOM6, however Line 12 https://github.com/ufs-community/ufs-weather-model/blob/develop/MOM6-interface/CMakeLists.txt adds `-fp-model source`.

I will try and reproduce your `build.sh` instructions on Orion.
Do you have a build log that I can cross reference with?

**Comment by DeniseWorthen** [comment]
Aren't those only if CMAKE_Fortran_FLAGS_RELEASE are used (presumably through some setting like for DEBUG=Y), which I interpreted as building a release version. A normal build would just use CMAKE_Fortran_FLAGS.

**Comment by DeniseWorthen** [comment]
I've have two build directories, one for datm (build.datm) and one for cpld (build.cpld) in /work/noaa/marine/dworthen/ufs_dw. 

These were created using:
module use modulefiles/orion.intel
module load fv3

and either

CMAKE_FLAGS="-DS2S=ON -DDATM=ON" ./build.sh >output 2>&1 &
CMAKE_FLAGS="-DS2S=ON" CCPP_SUITES="FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled" ./build.sh >output 2>&1 &

**Comment by DusanJovic-NOAA** [comment]
Try making this change in the top-level CMakeLists.txt
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a00e147..ac62757 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -39,6 +39,8 @@ set(DATM            OFF CACHE BOOL "Enable Data Atmosphere")
 ###############################################################################
 if(DEBUG)
   set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Set type of build to Debug." FORCE)
+else()
+  set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Set type of build to Release." FORCE)
 endif()
 
 if(CMAKE_Platform)
```

**Comment by DeniseWorthen** [comment]
That seems to have worked. In CICE-interface/CMakeFiles/cice.dir/flags.make I now see for ufs-datm:

CICE:

```Fortran_FLAGS = -g -traceback -FR -convert big_endian -assume byterecl -ftz -align array64byte -xHOST -O2 -fp-model precise -module mod   -qopenmp```

MOM6:

```Fortran_FLAGS = -g -traceback -i4 -r8 -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -sox -O2 -debug minimal -fp-model source```

I also did a diff between the flags.make for the new datm build and the original cpld build directories for both MOM6 and CICE and they compare as being the same. My ufs-datm restart test also passes without manually adding the ``-fp-model precise`` to the CICE CMakelist.txt.
