### ISSUE TITLE
UGWP needed for UFS-R2O Physics Test

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-weather-model#308]
Additional changes in uGWP will be needed for the UFS-R2O Physics Test toward GFS v17. These innovations will be coming from Valery Yudin and @mdtoyNOAA and will enable aspects of uGWP v1. A PR to master ccpp-physics is expected in mind-December.

**Comment by junwang-noaa** [comment]
Ligia, may I ask who will be making the PR?

**Comment by ligiabernardet** [comment]
Should be coming from Valery or @mdtoyNOAA. 
@yangfanglin is also in the loop, as we all met a couple days ago and identified that these innovations were still needed.

**Comment by junwang-noaa** [comment]
@ligiabernardet we have ccpp PR#532 committed in ufs-weather-model PR#319, can we close the issue?
