### ISSUE TITLE
Undefined symbols on macOS and Intel compiler

### ISSUE THREAD

**Issue by kgerheiser** [ufs-community/ufs-weather-model#309]
I'm trying out building with the Intel compiler (2021.1) on macOS (11.0) and I'm getting undefined symbols when the executable is linked.

The problem is how Intel marks module variable symbols in static libraries. When you run `nm` Intel marks them as `C` (common symbols) which aren't included by macOS's linker by default, and GCC marks them as `S` (small data), which are.

Adding this line in the top level CMakeLists fixes the problem. It passes `-c` to ranlib so that the linker will see common symbols.

```
if(APPLE)
  # The linker on macOS does not include `common symbols` by default
  # Passing the -c flag includes them and fixes an error with undefined symbols
  set(CMAKE_Fortran_ARCHIVE_FINISH "<CMAKE_RANLIB> -c <TARGET>")
endif()
```

However, then another issue arises with duplicate symbols in `gfsphysics`

See: https://github.com/NOAA-EMC/fv3atm/issues/206

**Comment by climbfuji** [comment]
> I'm trying out building with the Intel compiler (2021.1) on macOS (11.0) and I'm getting undefined symbols when the executable is linked.
> 
> The problem is how Intel marks module variable symbols in static libraries. When you run `nm` Intel marks them as `C` (common symbols) which aren't included by macOS's linker by default, and GCC marks them as `S` (small data), which are.
> 
> Adding this line in the top level CMakeLists fixes the problem. It passes `-c` to ranlib so that the linker will see common symbols.
> 
> ```
> if(APPLE)
>   # The linker on macOS does not include `common symbols` by default
>   # Passing the -c flag includes them and fixes an error with undefined symbols
>   set(CMAKE_Fortran_ARCHIVE_FINISH "<CMAKE_RANLIB> -c <TARGET>")
> endif()
> ```
> 
> However, then another issue arises with duplicate symbols in `gfsphysics`
> 
> See: [NOAA-EMC/fv3atm#206](https://github.com/NOAA-EMC/fv3atm/issues/206)

The problem with undefined symbols will go away once IPD is removed and we did the first round of cleanup to the code. You should be able to work around it by making exactly the same change in `FV3/ccpp/CMakeLists.txt` (at least that always worked for me).

Question: is the `-c` general enough to also work with GNU, or does it work with Intel only?

**Comment by kgerheiser** [comment]
> You should be able to work around it by making exactly the same change in FV3/ccpp/CMakeLists.txt (at least that always worked for me).

Yes, that worked. So `IPD_SOURCE` will be going away at some point? 

> Question: is the -c general enough to also work with GNU, or does it work with Intel only?

It works at the library level when `ranlib` is called. It's just that GCC doesn't mark those symbols as common symbols so it doesn't make a difference. I haven't tried building with GCC with those changes. I don't anticipate any difference, but I'll give it a try.

I tried all this to see if the ESMF bug exists with Intel (haven't gotten to that point yet).

**Comment by junwang-noaa** [comment]
@kgerheiser May I ask if you still have issues to compile the model?

**Comment by kgerheiser** [comment]
The duplicate symbols are fixed, but the top-level CMakeLists.txt still needs this to build with Intel compilers on macOS.

```
if(APPLE AND CMAKE_Fortran_COMPILER_ID MATCHES "^(Intel)$")
  # The linker on macOS does not include `common symbols` by default
  # Passing the -c flag includes them and fixes an error with undefined symbols
  set(CMAKE_Fortran_ARCHIVE_FINISH "<CMAKE_RANLIB> -c <TARGET>")
endif()
```

**Comment by climbfuji** [comment]
@kgerheiser Sorry that we keep coming back. Can you confirm that this is still an issue? If so, I will fix it in https://github.com/ufs-community/ufs-weather-model/pull/897. Thanks!

**Comment by kgerheiser** [comment]
Yep, can confirm it's still an issue. 

```
Undefined symbols for architecture x86_64:
  "_namelist_soilveg_mp_bare_", referenced from:
      _gfssflx_IP_redprm_ in libccpp_physics.a(sflx.f.o)
      _set_soilveg_mod_mp_set_soilveg_ in libccpp_physics.a(set_soilveg.f.o)
  "_namelist_soilveg_mp_bb_", referenced from:
      _gfssflx_IP_redprm_ in libccpp_physics.a(sflx.f.o)
      _set_soilveg_mod_mp_set_soilveg_ in libccpp_physics.a(set_soilveg.f.o)
```

But also getting duplicate symbols, after applying that fix:

```
duplicate symbol '_gfs_typedefs._' in:
    FV3/ccpp/libfv3ccpp.a(GFS_typedefs.F90.o)
    FV3/ccpp/physics/libccpp_physics.a(GFS_typedefs.F90.o)
duplicate symbol '_gfs_typedefs_mp_statein_create_' in:
    FV3/ccpp/libfv3ccpp.a(GFS_typedefs.F90.o)
    FV3/ccpp/physics/libccpp_physics.a(GFS_typedefs.F90.o)
...
duplicate symbol '_ccpp_data._' in:
    FV3/ccpp/libfv3ccpp.a(CCPP_data.F90.o)
    FV3/ccpp/physics/libccpp_physics.a(CCPP_data.F90.o)
duplicate symbol '_ccpp_data_mp_gfs_control_' in:
    FV3/ccpp/libfv3ccpp.a(CCPP_data.F90.o)
    FV3/ccpp/physics/libccpp_physics.a(CCPP_data.F90.o)
...
```

**Comment by climbfuji** [comment]
How about we move this into `cmake/Intel.cmake` as follows, will that work?
```
if(APPLE)
  # The linker on macOS does not include `common symbols` by default
  # Passing the -c flag includes them and fixes an error with undefined symbols
  set(CMAKE_Fortran_ARCHIVE_FINISH "<CMAKE_RANLIB> -c <TARGET>")
endif()
```

**Comment by kgerheiser** [comment]
Yep, that should work.

**Comment by climbfuji** [comment]
Wonder where the duplicate symbols come from. Let me check ...

**Comment by climbfuji** [comment]
Can you try if this fixes the problem, please? (in fv3atm)

```
diff --git a/ccpp/CMakeLists.txt b/ccpp/CMakeLists.txt
index 3ebc40ed..7ac77947 100644
--- a/ccpp/CMakeLists.txt
+++ b/ccpp/CMakeLists.txt
@@ -105,9 +105,9 @@ add_subdirectory(physics)
 add_library(
     fv3ccpp

-    data/CCPP_typedefs.F90
-    data/GFS_typedefs.F90
-    data/CCPP_data.F90
+    #data/CCPP_typedefs.F90
+    #data/GFS_typedefs.F90
+    #data/CCPP_data.F90

     driver/GFS_diagnostics.F90
     driver/GFS_restart.F90
```

**Comment by kgerheiser** [comment]
That fixed it

**Comment by climbfuji** [comment]
> That fixed it

Thanks for letting me know. I will add both to the PR I mentioned above unless the changes break the code everywhere else. I will have to ask you to test the PR again when it is time to commit. Thanks again!
