### ISSUE TITLE
Create baselines on Gaea for the coupled and datm tests

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#317]
## Description
RT baseline will be created for the coupled tests and datm-mom6-cice6 tests on Gaea.

## Solution
The RT baseline will be located at /lustre/f2/pdata/esrl/gsd/ufs/ufs-weather-model on Gaea.

In the future, new baseline directories will be created whenever simulation results are changed due to updates in the develop branch of ufs-weather-model.

**Comment by junwang-noaa** [comment]
Bin, can you create new baseline for datm-mom6-cice6 on gaea?

**Comment by junwang-noaa** [comment]
@binli2337 May I ask if there is any update on running datm-mom6-cice6 on gaea?

**Comment by binli2337** [comment]
New baselines for datm-mom6-cice6 and the coupled model have been created on Gaea.
