### ISSUE TITLE
Place holder for upcoming RRTMGP improvements

### ISSUE THREAD

**Issue by dustinswales** [ufs-community/ufs-weather-model#321]
This Issue is for upcoming improvements to RRTMGP. 
For v16beta physics there are improvements to allow for LW scattering in RRTMGP and the use of RRTMGP cloud optics. There is also an initial coupling of RRTMGP to the GSL physics using the Thompson MP scheme.

**Comment by junwang-noaa** [comment]
The code is committed in PR#323. close ticket.
