### ISSUE TITLE
rt.sh not running last test in rt*.conf when newline is missing at the end of the file

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#329]
## Description

If the last test in `rt*conf` is not followed by a newline character, it is skipped by `rt.sh`.

### To Reproduce:
What compilers/machines are you seeing this with?
- hera.intel
Give explicit steps to reproduce the behavior.
1. Remove newline at end of `rt.conf` (or a smaller test version of it)
2. Run `rt.sh`
3. Check `log_hera.intel/` - the last test will be missed completely
4. then, oops, look at the bug!

**Comment by DusanJovic-NOAA** [comment]
@climbfuji My editor (vim) always adds newline character at the end of each line. But try this:
```
diff --git a/tests/rt.sh b/tests/rt.sh
index 1bb2eff..b78e7ec 100755
--- a/tests/rt.sh
+++ b/tests/rt.sh
@@ -538,7 +538,7 @@ in_metatask=false
 
 [[ -f $TESTS_FILE ]] || die "$TESTS_FILE does not exist"
 
-while read -r line; do
+while read -r line || [ "$line" ]; do
 
   line="${line#"${line%%[![:space:]]*}"}"
   [[ ${#line} == 0 ]] && continue
```

**Comment by climbfuji** [comment]
> @climbfuji My editor (vim) always adds newline character at the end of each line. But try this:
> 
> ```
> diff --git a/tests/rt.sh b/tests/rt.sh
> index 1bb2eff..b78e7ec 100755
> --- a/tests/rt.sh
> +++ b/tests/rt.sh
> @@ -538,7 +538,7 @@ in_metatask=false
>  
>  [[ -f $TESTS_FILE ]] || die "$TESTS_FILE does not exist"
>  
> -while read -r line; do
> +while read -r line || [ "$line" ]; do
>  
>    line="${line#"${line%%[![:space:]]*}"}"
>    [[ ${#line} == 0 ]] && continue
> ```

Thanks for this suggestion.I tried it, but it didn't work, the test still wasn't run.

**Comment by DusanJovic-NOAA** [comment]
Please point me at your rt.conf.

**Comment by climbfuji** [comment]
> Please point me at your rt.conf.

Please check this one (and copy it, because I will delete this directory by the end of the week)
```
/scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/b4b_restart_last_time_20201207/from_fanglin/rt/tests/rt_one.conf
```

**Comment by DusanJovic-NOAA** [comment]
Did you use /scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/b4b_restart_last_time_20201207/from_fanglin/rt/tests/rt.sh?
If you did, then you need to add "` || [ "$line" ]`" at line `while read -r line; do` in the main script. See the diff above.

**Comment by climbfuji** [comment]
I thought I did that, but will try again.

**Comment by climbfuji** [comment]
> I thought I did that, but will try again.
> […](#)

I think I know what happened. I made the change in the `rt_single` routine (where it should probably also be made, just in case the test that should be run is the last one in the file?). Made the change in the other place in `rt.sh`, trying again.

**Comment by climbfuji** [comment]
Ok, making the change in both places seems to be the right thing to do:
```
diff --git a/tests/rt.sh b/tests/rt.sh
index 3379c2a9..44878fc5 100755
--- a/tests/rt.sh
+++ b/tests/rt.sh
@@ -31,7 +31,7 @@ usage() {
 rt_single() {
   local compile_line=''
   local run_line=''
-  while read -r line; do
+  while read -r line || [ "$line" ]; do
     line="${line#"${line%%[![:space:]]*}"}"
     [[ ${#line} == 0 ]] && continue
     [[ $line == \#* ]] && continue
@@ -571,7 +571,7 @@ in_metatask=false

 [[ -f $TESTS_FILE ]] || die "$TESTS_FILE does not exist"

-while read -r line; do
+while read -r line || [ "$line" ]; do

   line="${line#"${line%%[![:space:]]*}"}"
   [[ ${#line} == 0 ]] && continue
```
