### ISSUE TITLE
DEBUG_LINKMPI

### ISSUE THREAD

**Issue by aerorahul** [ufs-community/ufs-weather-model#330]
https://github.com/ufs-community/ufs-weather-model/blob/9bd6b59b3c5a230558430f238e32ca60d2844e57/cmake/Intel.cmake#L42

This needs to be addressed correctly.

There have been numerous discussions on an incorrect implementation of debugging with MPI.
Most recently in PR #291 and [this](https://github.com/ufs-community/ufs-weather-model/pull/291#discussion_r527711989) comment specifically.

**Comment by climbfuji** [comment]
I would like to revive this issue. Besides all the other points raised, the implementation assumes that anyone using the Intel compiler also uses Intel MPI. That is not necessarily true. I was building the model with Intel and MPICH in debug mode, and the error I get is:
```
ld: library not found for -link_mpi=dbg_mt
```
For many good reasons mentioned in the links in the description of this PR, I would prefer this DEBUG_LINKMPI logic to be removed. At the very least, it should be OFF by default, and folks who want to use it should enable it explicitly.

**Comment by arunchawla-NOAA** [comment]
Is this still an issue that needs work @climbfuji @aerorahul @junwang-noaa ? Should this be moved to a discussion if we still do not have a path forward ?

**Comment by climbfuji** [comment]
Yes, it is still an issue in my opinion.

**Comment by climbfuji** [comment]
@arunchawla-NOAA @junwang-noaa @DusanJovic-NOAA @aerorahul Any chance that we can we get rid of this `debug_linkmpi`?

It's been discussed controversially since when it was added, and now I am also getting errors with Intel oneAPI MPI:
```
...
ld: cannot find -link_mpi=dbg_mt
...
```
Has anyone else run into this with the new oneAPI MPI library?

**Comment by DusanJovic-NOAA** [comment]
In my personal opinion we should get rid of all debug versions of all libraries (esmf, mapl, mpi). In rare cases, when it turns out that we suspect there's a bug in esmf and/or MPI, we can temporarily switch to debug versions, debug the issue, fix the code and continue to use release version of all libraries.
