### ISSUE TITLE
Add regression test fv3_ccpp_gsd_RRTMGP to rt.conf

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#335]
## Description
The test configuration files for test `fv3_ccpp_gsd_RRTMGP` where added to the ufs-weather-model develop branch in PR https://github.com/ufs-community/ufs-weather-model/pull/323, but the test wasn't added to `rt.conf`.

## Solution
I suggest to add it in  one of the next commits, possibly only for hera.intel (like `fv3_ccpp_rap` and `fv3_ccpp_hrrr`).

## Alternatives
Add for all machines, or don't add (not a good idea, untested code = broken code).

## Related to
https://github.com/ufs-community/ufs-weather-model/pull/323

**Comment by junwang-noaa** [comment]
The code is committed, close issue.
