### ISSUE TITLE
Inconsistent output file interval settings

### ISSUE THREAD

**Issue by llpcarson** [ufs-community/ufs-weather-model#339]
## Description
A user reported an issue with the output files while using the UFS-MRWEATHER_APP which had inconsistent settings for the output file intervals in one case.  

The issue occurs when the settings for output frequency in the input.nml atmos_model_ nml do not match those in the model_configure file, and the write-component is used.  In this case, the write component was writing files more frequently than the atmos_model.F90 was updating the data structure (Diag DDT).

### To Reproduce:
What compilers/machines are you seeing this with?  compiler/machine independent
Give explicit steps to reproduce the behavior.
1. Run the ufs-mrweather-app, selecting the GFSv16beta SDF
2. look at the resulting output netcdf files (atm, sfc)
3. the files at forecast hours 0,1,2 are identical.  the files at forecast hours 3,4,5 are identical, etc.

Alternatively, set the following values in input.nml and model_configure:
input.nml: 
fdiag=3
fhmax=240
fhmaxhf=0
fhout=3
fhouthf=1
model_configure:
nfhmax_hf: 12
nfhout_hf: 1
nfhout: 3

## Additional context
- ufs-mrweather-app needs to correct the default settings for this case:
-  [](https://github.com/ESCOMP/FV3GFS_interface/issues/17)
- recommend a check or warning on this in the ufs-weather-model, so that misleading output files are not created

## Output

**Screenshots**
The file sizes are identical, and the contents as well.
-rw-r--r-- 1 carson ncar 16874881 Dec 18 11:44 sfcf000.nc
-rw-r--r-- 1 carson ncar 16874881 Dec 18 11:44 sfcf001.nc
-rw-r--r-- 1 carson ncar 16874881 Dec 18 11:44 sfcf002.nc
-rw-r--r-- 1 carson ncar 17932500 Dec 18 11:44 sfcf003.nc
-rw-r--r-- 1 carson ncar 17932500 Dec 18 11:44 sfcf004.nc
-rw-r--r-- 1 carson ncar 17932500 Dec 18 11:45 sfcf005.nc
-rw-r--r-- 1 carson ncar 18461607 Dec 18 11:45 sfcf006.nc

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

**Comment by junwang-noaa** [comment]
This issue will be fixed in fv3atm issue [#136](https://github.com/NOAA-EMC/fv3atm/issues/136)
