### ISSUE TITLE
add new suite file for regional fv3 test

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#344]
## Description
Regional RT tests were updated to use [suite_FV3_GFS_v15_thompson_mynn.xml](https://github.com/NOAA-EMC/fv3atm/blob/develop/ccpp/suites/suite_FV3_GFS_v15_thompson_mynn.xml) CCPP suite file. It turns out that the LAM parallel is using a modified suite_FV3_GFS_v15_thompson_mynn.xml. It is good to add a LAM3km suite suite_FV3_GFS_v15_thompson_mynn_lam3km.xml that matches LAM parallel run and use it in regional RT tests.

## Solution
Add a new suite file suite_FV3_GFS_v15_thompson_mynn_lam3km.xml and use it in regional RT tests.

## Related to
A new suite file suite_FV3_GFS_v15_thompson_mynn_lam3km.xml will be added in FV3/ccpp/suite, so a PR from fv3atm is required.

**Comment by junwang-noaa** [comment]
4 lines are commented out in suite_FV3_GFS_v15_thompson_mynn.xml used in LAM parallel:

```
      <scheme>GFS_GWD_generic_pre</scheme>
<!--   <scheme>cires_ugwp</scheme>  -->
      <scheme>cires_ugwp_post</scheme>
      <scheme>GFS_GWD_generic_post</scheme>
      <scheme>rayleigh_damp</scheme>
      <scheme>GFS_suite_stateout_update</scheme>
      <scheme>ozphys_2015</scheme>
      <scheme>h2ophys</scheme>
      <scheme>get_phi_fv3</scheme>
      <scheme>GFS_suite_interstitial_3</scheme>
      <scheme>GFS_DCNV_generic_pre</scheme>
<!--      <scheme>samfdeepcnv</scheme> -->
      <scheme>GFS_DCNV_generic_post</scheme>
      <scheme>GFS_SCNV_generic_pre</scheme>
<!--      <scheme>samfshalcnv</scheme> -->
      <scheme>GFS_SCNV_generic_post</scheme>
      <scheme>GFS_suite_interstitial_4</scheme>
<!--      <scheme>cnvc90</scheme> -->
<scheme>GFS_MP_generic_pre</scheme>
```

@climbfuji @ligiabernardet would you please confirm if we also need to comment out the pre and post schemes for cires_ugwp, deep convection, shallow convection and convection clouds?

**Comment by climbfuji** [comment]
> 4 lines are commented out in suite_FV3_GFS_v15_thompson_mynn.xml used in LAM parallel:
> 
> ```
>       <scheme>GFS_GWD_generic_pre</scheme>
> 
>       <scheme>cires_ugwp_post</scheme>
>       <scheme>GFS_GWD_generic_post</scheme>
>       <scheme>rayleigh_damp</scheme>
>       <scheme>GFS_suite_stateout_update</scheme>
>       <scheme>ozphys_2015</scheme>
>       <scheme>h2ophys</scheme>
>       <scheme>get_phi_fv3</scheme>
>       <scheme>GFS_suite_interstitial_3</scheme>
>       <scheme>GFS_DCNV_generic_pre</scheme>
> 
>       <scheme>GFS_DCNV_generic_post</scheme>
>       <scheme>GFS_SCNV_generic_pre</scheme>
> 
>       <scheme>GFS_SCNV_generic_post</scheme>
>       <scheme>GFS_suite_interstitial_4</scheme>
> 
> <scheme>GFS_MP_generic_pre</scheme>
> ```
> 
> @climbfuji @ligiabernardet would you please confirm if we also need to comment out the pre and post schemes for cires_ugwp, deep convection, shallow convection and convection clouds?

I think you can get rid off the entire block
```
      <scheme>GFS_DCNV_generic_pre</scheme>
<!--      <scheme>samfdeepcnv</scheme> -->
      <scheme>GFS_DCNV_generic_post</scheme>
      <scheme>GFS_SCNV_generic_pre</scheme>
<!--      <scheme>samfshalcnv</scheme> -->
      <scheme>GFS_SCNV_generic_post</scheme>
```
but please run a test to confirm that the results are still the same.
