### ISSUE TITLE
Incorporation the changes in fv3atm and ccpp/physics for the NSST model in the coupled system

### ISSUE THREAD

**Issue by XuLi-NOAA** [ufs-community/ufs-weather-model#350]
This issue is open to incorporate the changes in submodule fv3atm and ccpp/physics into ufs-weather-model. See https://github.com/NOAA-EMC/fv3atm/issues/219 and https://github.com/NCAR/ccpp-physics/issues/537

**Comment by climbfuji** [comment]
Thanks, @XuLi-NOAA. I added it to the commit queue so that it doesn't have to sit forever. Please make sure that the changes in ccpp-physics are ok with @junwang-noaa and @SMoorthi-emc.

**Comment by XuLi-NOAA** [comment]
I merged my branch with the updated upstream and then the compiled failed (rt, and the I checked build_ufs_coupled.sh as follows):

-- Found sigio: /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")
-- Found MPI: TRUE (found version "3.1")
-- Found w3emc: /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/w3emc/2.7.3/lib/libw3emc_4.a (found version "2.7.3")
-- Found crtm: /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/crtm/2.3.0/lib/libcrtm.a (found version "2.3.0")
-- Found upp: /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/upp/10.0.0/lib/libupp.a (found version "10.0.0")
Found Python: /bin/python2.7
Calling CCPP code generator (ccpp_prebuild.py) for suites --suites=FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled,FV3_GFS_v15p2_couplednsst ...
CMake Error at FV3/CMakeLists.txt:22 (message):
  An error occured while running ccpp_prebuild.py, check
  /work/noaa/da/xli/git/ufs_nst_1.0/sorc/ufs_coupled.fd/build/FV3/ccpp_prebuild.{out,err}


-- Configuring incomplete, errors occurred!
See also "/work/noaa/da/xli/git/ufs_nst_1.0/sorc/ufs_coupled.fd/build/CMakeFiles/CMakeOutput.log".
=====================================

Anybody can help me with this?

By the way, I added a new ccpp suite:  FV3_GFS_v15p2_couplednsst

**Comment by climbfuji** [comment]
This is from your CCPP error log file (as per your cmake error above):
```
INFO: Logging level set to INFO
INFO: Found TYPEDEFS_NEW_METADATA dictionary in config, assume at least some data is in new metadata format
INFO: Parsing suite definition files ...
INFO: Parsing suite definition file ccpp/suites/suite_FV3_GFS_2017_coupled.xml ...
INFO: Parsing suite definition file ccpp/suites/suite_FV3_GFS_2017_satmedmf_coupled.xml ...
INFO: Parsing suite definition file ccpp/suites/suite_FV3_GFS_v15p2_coupled.xml ...
INFO: Parsing suite definition file ccpp/suites/suite_FV3_GFS_v15p2_couplednsst.xml ...
CRITICAL: Suite definition file ccpp/suites/suite_FV3_GFS_v15p2_couplednsst.xml not found.
ERROR: Parsing suite definition file suite_FV3_GFS_v15p2_couplednsst.xml failed.
Traceback (most recent call last):
  File "ccpp/framework/scripts/ccpp_prebuild.py", line 842, in <module>
    main()
  File "ccpp/framework/scripts/ccpp_prebuild.py", line 760, in main
    raise Exception('Parsing suite definition files failed.')
Exception: Parsing suite definition files failed.
/work/noaa/da/xli/git/ufs_nst_1.0/sorc/ufs_coupled.fd/build/FV3/ccpp_prebuild.err (END)
```
Look at the `ERROR:` line - the suite can't be found. Maybe in the wrong place or misspelled?

**Comment by DeniseWorthen** [comment]
Also, are you using your feature/ufs_nst_1.0 branch? You are 15 commits behind develop in that branch, so first bring it up to the current develop and try again?

**Comment by XuLi-NOAA** [comment]
The problem was that I did not checkout to my branch for fv3atm, thanks, Dom.

And thanks for Denise's remind of the 15 commits behind develop (for ccpp/physics?). I did the following, but I got a problem (anybody can help, I am still relatively new to GitHub):



git remote -v
origin  https://github.com/XuLi-NOAA/ccpp-physics (fetch)
origin  https://github.com/XuLi-NOAA/ccpp-physics (push)
upstream        https://github.com/NCAR/ccpp-physics (fetch)
upstream        https://github.com/NCAR/ccpp-physics (push)

git fetch upstream
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 13 (delta 10), reused 12 (delta 10), pack-reused 0
Unpacking objects: 100% (13/13), 1.90 KiB | 27.00 KiB/s, done.
From https://github.com/NCAR/ccpp-physics
   9ae4cea..e19fe2a  master     -> upstream/master

git checkout master
M       physics/rte-rrtmgp
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Orion-login-1[304] xli$ git merge upstream/master
Updating 9ae4cea..e19fe2a
Fast-forward
 physics/GFS_rrtmg_setup.meta        | 3 ++-
 physics/GFS_rrtmgp_pre.meta         | 2 +-
 physics/GFS_rrtmgp_setup.meta       | 3 ++-
 physics/module_SGSCloud_RadPre.meta | 2 +-
 4 files changed, 6 insertions(+), 4 deletions(-)
Orion-login-1[305] xli$ git push origin master
Username for 'https://github.com': XuLi-NOAA
Password for 'https://XuLi-NOAA@github.com':
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/XuLi-NOAA/ccpp-physics
   9ae4cea..e19fe2a  master -> master
Orion-login-1[306] xli$ git branch
  feature/ufs_nst_1.0
* master
Orion-login-1[307] xli$ git checkout feature/ufs_nst_1.0
Switched to branch 'feature/ufs_nst_1.0'

After update the ccpp/physics, I continue doing the follows:

/work/noaa/da/xli/git/ufs_nst_1.0/sorc/ufs_coupled.fd/FV3
Orion-login-1[319] xli$ git remote -v
origin  https://github.com/XuLi-NOAA/fv3atm (fetch)
origin  https://github.com/XuLi-NOAA/fv3atm (push)
upstream        https://github.com/NOAA-EMC/fv3atm (fetch)
upstream        https://github.com/NOAA-EMC/fv3atm (push)
Orion-login-1[320] xli$ git branch
  develop
* feature/ufs_nst_1.0
Orion-login-1[321] xli$  git fetch upstream
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Total 12 (delta 8), reused 8 (delta 8), pack-reused 4
Unpacking objects: 100% (12/12), 61.87 KiB | 287.00 KiB/s, done.
From https://github.com/NOAA-EMC/fv3atm
   45618a9..ae4c8bf  develop    -> upstream/develop
Orion-login-1[322] xli$ git checkout develop
M       atmos_cubed_sphere
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
Orion-login-1[323] xli$ git merge upstream/develop
Failed to merge submodule ccpp/physics (commits don't follow merge-base)
Auto-merging ccpp/physics
CONFLICT (submodule): Merge conflict in ccpp/physics
Failed to merge submodule ccpp/framework (commits don't follow merge-base)
Auto-merging ccpp/framework
CONFLICT (submodule): Merge conflict in ccpp/framework
Failed to merge submodule atmos_cubed_sphere (commits don't follow merge-base)
Auto-merging atmos_cubed_sphere
CONFLICT (submodule): Merge conflict in atmos_cubed_sphere
Automatic merge failed; fix conflicts and then commit the result.

It means the ccpp/framework needs to be updated. 

Then, I did, 

 cd framework
Orion-login-1[329] xli$ ls
cmake  CMakeLists.txt  CODEOWNERS  doc  LICENSE  README.md  README_TODO.txt  scripts  src  test  tests
Orion-login-1[330] xli$ git branch
* (HEAD detached at f1dc8d6)
  master
Orion-login-1[331] xli$ git remote -v
origin  https://github.com/NCAR/ccpp-framework (fetch)
origin  https://github.com/NCAR/ccpp-framework (push)
Orion-login-1[332] xli$ get pull origin master
-bash: get: command not found
Orion-login-1[333] xli$ git pull origin master
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

From https://github.com/NCAR/ccpp-framework
 * branch            master     -> FETCH_HEAD
Updating f1dc8d6..612dd1a
Fast-forward
 scripts/ccpp_prebuild.py   |   7 +++++--
 scripts/common.py          |  12 +++++++++++-
 scripts/metadata_parser.py |  48 +++++++++++++++---------------------------------
 scripts/mkstatic.py        | 104 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------
 4 files changed, 97 insertions(+), 74 deletions(-)

This may not be good, but what I can do better? I don't have a branch of ccpp/framework.

Then, I went back to /work/noaa/da/xli/git/ufs_nst_1.0/sorc/ufs_coupled.fd/FV3, and did the following:

 git branch
* develop
  feature/ufs_nst_1.0
Orion-login-1[343] xli$ git merge upstream/develop
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

What I should go ahead (sorry for the long comment)?

**Comment by DeniseWorthen** [comment]
This is what I do: I keep any component fork where I am doing develop work up-to-date with the current develop branch. So, if I am making FV3 changes, I make sure that I keep my fork of FV3 up-to-date and I keep my feature branch of FV3 up-to-date. I do the same thing w/ the ufs-weather repo. Things get complicated really quickly if you don't keep up-to-date with the current develop of either a component or the ufs-weather itself.

To update ufs-weather, I do this:

```
git clone https://github.com/DeniseWorthen/ufs-weather-model.git
git submodule update --init --recursive
git remote add upstream https://github.com/ufs-community/ufs-weather-model.git
git fetch upstream
git merge upstream/develop
```

At this point, I might see something like:

```
Updating 22c39c5..e7bcc2d
Fast-forward
 FV3                                                        |    2 +-
 MOM6-interface/MOM6                                        |    2 +-
 WW3                                                        |    2 +-
```

So I know the submodules hashes have been updated. At that point I manually refresh the submodules (I don't think this is required) and then push the updated develop to my fork:

```
git submodule update --init --recursive 
git push
```
Now my ufs-weather develop branch is up-to-date w/ the upstream repo. I can then update my own branches of using this:

```
git checkout myfeaturebranch
git merge develop
```

When I look at your ufs-weather develop, it looks like you're missing the updates to MOM6 and FV3 plus other changes that have been made to the RT files (new tests etc). Your nst branch is behind more---in cmeps, datm, ww3 etc. You're aiming to have your feature branch be identical to develop except for just the changes you are making in whichever sub-component. And in that sub-component, you should be as close as possible to the current develop. 

Once you're up-to-date, tracking down where your error message (Configuring incomplete, errors occurred!) is coming from is a lot more straightforward.

**Comment by XuLi-NOAA** [comment]
Denise,

Thanks!

I think I understand the issues. The conflicts can be resolved by merging my branch (feature/ufs_nst_1.0) with the repositories. 
There are two ways to handle this: 1) Rebase my branch; 2) Merge my current branches to the repositories. I understand usually we go with option two for the history and the final resolved version. However, considering my current branches are used in a frozen coupled model package to run some cases, and actually the scheme to incorporate the NSST model into MOM6 and therefore the coupled model is still a moving piece, it is appropriate to wait for a while to commit the changes in the issue, with more possible changes in the near future (there are a few changes only overall).

**Comment by junwang-noaa** [comment]
The code is committed, close issue.
