### ISSUE TITLE
CMake 32BIT build crashes without DYN32 ON

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-weather-model#358]
## Description
When trying to build in 32Bit mode with CMake, the setting DYN32 ON also needs to be set for successful build.

### To Reproduce:

Both @JamesAbeles-NOAA and I ran tests on Hera with Intel building from the UFS SR Weather App CMake build and found that changing CMakeList.txt to 32BIT ON crashed. To avoid the crash, we needed to add the line:

```
set(DYN32           ON  CACHE BOOL "Enable 32BIT dycore")
```
It was our understanding that DYN32 is the flag used by CCPP to interact with the 32 Bit dycore.

Steps:
1. Clone UFS SR Weather App and cd
2. source docs/README_hera_intel.txt
3. mkdir build && cd build
4. cmake .. -DCMAKE_INSTALL_PREFIX=..
5. make -j 8
6. Observe crash (output below)

## Additional context

This impacts building with 32 Bit from https://github.com/ufs-community/ufs-srweather-app. 
I opened [Issue #84](https://github.com/ufs-community/ufs-srweather-app/issues/84) there as a reference.

## Output

```
/scratch2/NCEPDEV/fv3-cam/James.A.Abeles/ufs-srweather-app/src/ufs_weather_model/FV3/atmos_cubed_sphere/model/fv_dynamics.F90(363): error #6633: The type of the actual argument differs from the type of the dummy argument.   [CAPPA]
              cappa, &
--------------^
/scratch2/NCEPDEV/fv3-cam/James.A.Abeles/ufs-srweather-app/src/ufs_weather_model/FV3/atmos_cubed_sphere/model/fv_dynamics.F90(388): error #6633: The type of the actual argument differs from the type of the dummy argument.   [CAPPA]
               ,cappa                                             &
----------------^
/scratch2/NCEPDEV/fv3-cam/James.A.Abeles/ufs-srweather-app/src/ufs_weather_model/FV3/atmos_cubed_sphere/model/fv_dynamics.F90(516): error #6633: The type of the actual argument differs from the type of the dummy argument.   [CAPPA]
         call prt_mxm('cappa', cappa, is, ie, js, je, ng, npz, 1., gridstruct%area_64, domain)
```

**Comment by climbfuji** [comment]
The compile script `tests/compile.sh` does set the flags correctly. I think the logic in there should be moved into `CMakeLists.txt`.

**Comment by climbfuji** [comment]
@christinaholtNOAA this has been fixed in develop (in a slightly different way than in the public release branches), see https://github.com/NOAA-EMC/fv3atm/blob/c2fc3de2cb6c51f85f98ee0e69f25cffd68bc9dd/CMakeLists.txt#L86

**Comment by christinaholtNOAA** [comment]
Thanks for the followup, @DomHeinzeller. Should I close this issue, then?

**Comment by DomHeinzeller** [comment]
Yes please.
