### ISSUE TITLE
Add regional DEBUG regression test

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [ufs-community/ufs-weather-model#361]
## Description
Add one regional DEBUG test for implementation candidate.

## Solution
Simply add one test. 
Add new file: tests/tests/fv3_ccpp_regional_control_debug
Modify one file: tests/rt.conf

## Related to
Branch is opened at https://github.com/RatkoVasic-NOAA/ufs-weather-model/tree/debug_RT

**Comment by climbfuji** [comment]
Closed via https://github.com/ufs-community/ufs-weather-model/pull/421
