### ISSUE TITLE
reduce the initialization time on atm wave connector in GFS.v16

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#362]
## Description
There is a request to further reduce the time taken in the model initialization for GFS.v16 implementation, especially the initialization time on atm-wave connector becomes longer when larger number of nodes are used. Following the suggestion from ESMF group, the number of export/import fields in fv3 and ww3 have been reduced to the coupled fields required by atm->ww3.

**Comment by yangfanglin** [comment]
Jun, is there anything else I need to do regarding this issue ?

**Comment by junwang-noaa** [comment]
No, I will create a tag after you approve the PRs.

**Comment by junwang-noaa** [comment]
Code is committed in PR #363, close issue.
