### ISSUE TITLE
the coupled model requires FV3 and CMEPS updates for frac grid normalization

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#366]
## Description

Both FV3 and CMEPS will have an update to normalize the fluxes being sent from FV3 through CMEPS for the ocean and ice. When these are ready, the coupled model will need to be updated and tested.

## Related Issues

FV3 [#230](https://github.com/NOAA-EMC/fv3atm/issues/230)
CMEPS [#29](https://github.com/NOAA-EMC/CMEPS/issues/29)

**Comment by DeniseWorthen** [comment]
This change will involve normalizing the fluxes from ATM to the OCN by the open water fraction that ATM used to calculate those fluxes. In CMEPS, the field imported from the ATM will have the name ``Sa_ofrac`` and will be carried in the fractional FieldBundle with the name ``aofrac``. 

The normalization change will be implemented in esmFieldsExchange_nems when the fluxes are mapped from ATM to OCN by changing the normalization from  ``none`` to ``aofrac``.  

Because the packed field bundles can have only one normalization type, with this change I needed to change the ``maptype`` for the sea level pressure from consf to bilinear. This is actually the correct mapping type for sea level pressure since it is a global unmasked field. (I believe that consf mapping type was carried over from the NEMS mediator, when all fields mapped from ATM to OCN used nearest neighbor conservative.)

When the mapping type is changed from consf to bilinear for sea level pressure, the fields of sea level pressure exported to the OCN are in fact different (by small amounts). Two effects are seen. First, in the 1deg ocean configuration, the answers were bit identical to mapping sea level pressure conservatively. This can only be true if the 1deg configuration is not actually using this field. See MOM6 issue [#58](https://github.com/NOAA-EMC/MOM6/issues/58).

Secondly, the creation of the bilinear routehandle resulted in a small number of points now being mapped from OCN to land points (on the ATM grid) when those fields were mapped with conservative destination. This indicates some cross-contamination of the routehandles, either at the ESMF or CMEPS level. Following a suggestion by @rsdunlapiv, I added the retrieval of the ``dstStatusField `` from the ``RegridStore`` in CMEPS. This field contains a flag for reporting the type of masking which is done at each point in the destination grid when the routehandle is being created. The values contained in this field are described [here](http://earthsystemmodeling.org/docs/nightly/develop/ESMF_refdoc/node9.html#SECTION090150000000000000000). In the case where a bilinear routehandle is being created, the points which now appear as OCN->ATM land are all associated with a ``dstStatusField`` of 5. When no bilinear routehandle is created, these points all contain a ``dstStatusField`` of 0. Since these points are in fact land, the correct value in this case is in fact 0. 

We're continuing to debug this issue now, with additional help from the ESMF team.

**Comment by junwang-noaa** [comment]
@Denise Worthen - NOAA Affiliate <denise.worthen@noaa.gov> While reading
this, may I ask if we can have wind stress interpolated through vector
bilinear rather than scalar bilinear? It will make significant differences
near the pole region.

**Comment by DeniseWorthen** [comment]
@junwang-noaa I would need to understand more before giving a certain answer. I only have a very vague memory of this from very early days when we were coupling GSM and HYCOM.

**Comment by junwang-noaa** [comment]
Please see the link below on the impact interpolation on wind related
fields and surface pressures.

https://docs.google.com/presentation/d/1I47QQsxC8dH1FIsGJmwiKPg4We9j8Ytw/edit#slide=id.p20

**Comment by DeniseWorthen** [comment]
CMEPS has this mapping type available:

mappatch_uv3d     = 9  ! rotate u,v to 3d cartesian space, map from src->dest, then rotate back

**Comment by junwang-noaa** [comment]
Great, it's good to use that mapping method for wind related fields (any
vector component fields).
