### ISSUE TITLE
Correct field table in the coupled V16 tests

### ISSUE THREAD

**Issue by ShanSunNOAA** [ufs-community/ufs-weather-model#387]
(1) Correct the field table used in the coupled V16 tests to "field_table_suite2";
(2) Ignore fractional lakes in the oro data until these small water bodies can be initialized realistically. 

(1) will change results in all the V16 coupled tests. (2) will changes results in all tests that use oro data under "input-data-.../FV3_input_frac/".

**Comment by junwang-noaa** [comment]
@shansun6 field_table was corrected in ufs-weather-model in PR #378, please check.

**Comment by ShanSunNOAA** [comment]
Thanks Jun for pointing this out. I will close this issue and list (2) under "feature".
