### ISSUE TITLE
Inconsistencies between FV3 cap configuration parameters and atmos model namelist parameters

### ISSUE THREAD

**Issue by lamrx** [ufs-community/ufs-weather-model#4]
For the CMEPS implementation in the directory UFSCOMP/components/fv3/FV3GFS are two files: fv3_cap.F90, which processes the configuration file model_configure and atmos_model.F90 which reads namelist values from atm_in (sym linked as input_nml) in the run directory.  Key output control parameters found in each need to be consistent.  While both have a high frequency option, there are missing values in atmos_model.F90 for this to work correctly.  The short term fix is to disable the high frequency output and select a single frequency for a given experiment.  Long term fixes will likely require significant revision to atmos_model.F90 and possibly fv3_cap.F90.  For now several parameters and namelist values should be set to the same number.
  For fv3_cap.F90 the values to set are: nfhout, nfhout_hf, nfhmax, nfhmax_hf
  For atmos_model.F90 the values to set are:   fhout, fhout_hf, fhmax, fhmax_hf, fdiag  In the file UFSCOMP/components/fv3/FV3GFS/gfsphysics/GFS_layer/GFS_typedefs.F90
is another key namelist variable of fhzero.  Note that there is no fhzero_hf.
At the moment fhzero determines the frequency that the atmosphere diagnostic accumulators are reset to zero.  Since there is no fhzero_hf, using the high frequency options will not work correctly.  For consistent output for now fhzero should have the same value as fhout.  While having high frequency output is desirable, the output file labels need to be changed so that subhourly times can be used.  To set everything consistently within the CMEPS implementation the file user_nl_fv3gfs found in the job submission subdirectory can be used to set all key values.  Others can default or were set correctly earlier.  For example to get all 6-hourly output the user_nl_fv3gfs should be:
!----------------------------------------------------------------------------------
! Users should add all user specific namelist changes below in the form of
!   namelist_var = new_namelist_value
! Note - that it does not matter what namelist group the namelist_var belongs to
!----------------------------------------------------------------------------------
 nfhout = 6
 nfhmax_hf = 0
 nfhout_hf = 0
 fhzero = 6.0
 fdiag = 6.0
 fhout = 6.0

**Comment by junwang-noaa** [comment]
fhzero_hf is not needed for high frequency output. fhzero is the bucket that model uses to do accumulation, it does not have to be associated with the output data frequency. E.g. with fhzero=6, we can still have high frequent hourly history files, which contain field accumulated from 0-1,0-2,0-3,....0-6, then, 6-7, 6-8...etc.

**Comment by lamrx** [comment]
Jun,
     If the accumulators are not zeroed at high frequency output, the flux output variables such as prate and various radiation fluxes will not be correct.   Instant state fields are not affected by fhzero, but are not enough for a full evaluation.

Larry Marx
lmarx@gmu.edu<mailto:lmarx@gmu.edu>
Center for Ocean-Land-Atmosphere Studies
277B Research Hall  Mail Stop 6C5
George Mason University
4400 University Drive
Fairfax, VA    22030
USA
Tel: (703) 993-5746
Fax: (703) 993-5770

On Oct 31, 2019, at 3:30 PM, junwang-noaa <notifications@github.com<mailto:notifications@github.com>> wrote:


fhzero_hf is not needed for high frequency output. fhzero is the bucket that model uses to do accumulation, it does not have to be associated with the output data frequency. E.g. with fhzero=6, we can still have high frequent hourly history files, which contain field accumulated from 0-1,0-2,0-3,....0-6, then, 6-7, 6-8...etc.

**Comment by junwang-noaa** [comment]
Larry,

May I ask why "If the accumulators are not zeroed at high frequency output, the flux output variables such as prate and various radiation fluxes will not be correct"? 

The flux outputs such as prate are the bucketed precipitation rate. E.g, fhzero=6, at high frequency output fh=03, the prate is the precipitation rate from 0-3, which is computed by total precip accumulated from 0-3 hr/(3*3600).

**Comment by lamrx** [comment]
Jun,
   Why is this closed without further explanation on my part?

Larry Marx
lmarx@gmu.edu<mailto:lmarx@gmu.edu>
Center for Ocean-Land-Atmosphere Studies
277B Research Hall  Mail Stop 6C5
George Mason University
4400 University Drive
Fairfax, VA    22030
USA
Tel: (703) 993-5746
Fax: (703) 993-5770

On Nov 1, 2019, at 3:30 PM, junwang-noaa <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #4<https://secure-web.cisco.com/1wgpJhpWlWrAPRsKlNWkLX5EPgUgJ2c4Oby3p7kZuodSf3wrhL2RrTof7jhp7ZM9xGyBcE0lAuSap_PGe_XzN6FLGaWWjWgVXr7CKwSHP65_g8m7Bv4kzBaziytonb7jheOrGvX36SaaTA0ofx3iJDIp4xq0Mb1Rw5xTohkkd50T8FQdqoDzdWanI3LrjqqtY_EhuWCe3yCm1383JbhCPTqQlsxulZgLkjCeMaAnYfOX2_8hUU7VTIKDjcpIMUaMjQ6ghYc3YXUBEj3UuoCIbzPrQ7lOEcyUn_lGRPF34i8ZJQfYQC3HezzUg_3fZs2B7Zw_BXwXW4KVVwLwvmqkDY1ApU0s8232eFTUkUOoxY-R3lB4ES1J3IojgW31cI2JepSXm4e2dxpcy9DwUdZOuStJcgv95NSCZKWhsY9p7SsHBWozdUpaVlKYalg6PFkLI/https%3A%2F%2Fgithub.com%2Fufs-community%2Fufs-weather-model%2Fissues%2F4>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1KNBLQIOSNbVabW5tW2i13zIxlt1WiNS49k9RBfKeMWaIWJdR08muRd9aoaTCiafTd3QbRdE39Owmcj0wNLbjSt3bLyZOsE8e8LQFVyTkUdkGqndpFmkqxTP1A2-3LzMfHjOVWUco20dWOUqE5s-0Ya3TqmOCQOADETwB6-Wdo9O3oBD47BsLAGdcucYaKOGH2ct_-9Us60QvxTNFynWQL3fforzGD77MvyPLNUvyqwTKDzu8fg45UUs6OL_mACfBNXR8irvYuuC578xIAHLqsPu5VM87pqviRugAcR7yRaJwWi-YiY-ajtdLbZ__Vq7aswtdbPeo_LhJitYtAWII4-lKsL0YYqdGcoMWl6a2jwB2irx1ZpPtZYlKvMe6WF8YLOrjwAqviXbCOFSevxUqfrlDnib18eiQbEwehJb8SoGT9U64_OSHoY-BPWnhedw0/https%3A%2F%2Fgithub.com%2Fufs-community%2Fufs-weather-model%2Fissues%2F4%3Femail_source%3Dnotifications%26email_token%3DAMEOTYYSQHU2BJGMUKUTUHTQRR7WRA5CNFSM4JHODZ42YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUTBUBUY%23event-2764259539>, or unsubscribe<https://secure-web.cisco!
%20.com/1xVyrQNOqOuYA2WYGmLbrtlM27SErE-gd-ishh00VcC0RP2CgwfDH9NQWBK0-vHtNXDl4JNjk2CjMlYD2k-ABcCKWYjj2_SeyuOiBLwB-q5ipRWBG8YJZxZ1cS5D140JGAlWmEeC1a-gl1vDi-3MgW-5IgNpiO7Ub2kQlIiE2w-c0wsHMK5gd5csgIA1NhtapenNId8tA9zsz9UUdfAx5RAvN3CMFhxvGi8qI-ILL3c6-KKncm-t_GKNHtDRD-l2fAnscVSVUrU2FgM6eypQxW6aeRcTUQt-GKMk0aKef1rN9U7Si0bPvdmJk8ebzweGk38Vk_OOCJXnVaaRz8mOBBHWf-viaFqP8EDZLW2NmZr-jGKiASGfc9JiwFbAXAOvLCd7AbeE6wn9csFHWCLsYJ7lnKCel4aH-s0a2JFu9td98-1TRIoNYH-kyC-iDjgCj/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMEOTYZ5LWY4U766ZDI5HIDQRR7WRANCNFSM4JHODZ4Q>.

**Comment by junwang-noaa** [comment]
Oops, I must have clicked wrong button.Sorry about it, I will find a way to
re-open it or copy the ticket to new issue. Thanks for letting me know.

Jun

**Comment by lamrx** [comment]
Jun,
    Thank you,  I feel this needs discussion by phone to explain what I encountered so far on this problem.  Perhaps we and others can arrange something next week.

Larry Marx
lmarx@gmu.edu<mailto:lmarx@gmu.edu>
Center for Ocean-Land-Atmosphere Studies
277B Research Hall  Mail Stop 6C5
George Mason University
4400 University Drive
Fairfax, VA    22030
USA
Tel: (703) 993-5746
Fax: (703) 993-5770

On Nov 1, 2019, at 4:07 PM, junwang-noaa <notifications@github.com<mailto:notifications@github.com>> wrote:

Oops, I must have clicked wrong button.Sorry about it, I will find a way to
re-open it or copy the ticket to new issue. Thanks for letting me know.

Jun

**Comment by junwang-noaa** [comment]
Sure. Tuesday and Wednesday morning works for me. Please let me know
what time works for you. Thanks,

Jun

**Comment by lamrx** [comment]
Jun,
   How about Wesday at 10AM?  I should have material ready for you by that time.

Larry Marx
lmarx@gmu.edu<mailto:lmarx@gmu.edu>
Center for Ocean-Land-Atmosphere Studies
277B Research Hall  Mail Stop 6C5
George Mason University
4400 University Drive
Fairfax, VA    22030
USA
Tel: (703) 993-5746
Fax: (703) 993-5770

On Nov 2, 2019, at 11:37 PM, junwang-noaa <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure. Tuesday and Wednesday morning works for me. Please let me know
what time works for you. Thanks,

Jun

**Comment by junwang-noaa** [comment]
Hello, Larry,

I set up a google hangout meeting, just to check  that you received the
google calendar notification on our meeting today at 10AM, please let me
know if you won't be able to make it. Thanks.

Jun

**Comment by lamrx** [comment]
Jun,
     I will be able to make it.  I will send you a figure soon for the meeting.

Larry Marx
lmarx@gmu.edu<mailto:lmarx@gmu.edu>
Center for Ocean-Land-Atmosphere Studies
277B Research Hall  Mail Stop 6C5
George Mason University
4400 University Drive
Fairfax, VA    22030
USA
Tel: (703) 993-5746
Fax: (703) 993-5770

On Nov 6, 2019, at 9:33 AM, junwang-noaa <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello, Larry,

I set up a google hangout meeting, just to check that you received the
google calendar notification on our meeting today at 10AM, please let me
know if you won't be able to make it. Thanks.

Jun
