### ISSUE TITLE
mushy cice physics

### ISSUE THREAD

**Issue by rgrumbine** [ufs-community/ufs-weather-model#402]
From Avichal email to Bob:

Other than numerical stability, how does this [mushy physics] impact our results in the Polar regions? What influence does it have on Sea Ice-Atmosphere fluxes, Sea Ice-Ocean fluxes? We are far away from any code freeze, so all these questions have merit for P6 and subsequent prototypes. Are there relevant pubs which can provide some clues? How should we approach a decision on its inclusion?

## Description
Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Solution
Add a clear and concise description of what you want to happen.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by JoshuaFu-NOAA** [comment]
hi, Bob: Just to let you know that I run into the well-known ice model 'thermo iteration error' in P5 with initial condition on 20140101. This error exists even reducing the time step from 450s to 300s and increasing iteration step from 100 to 200 as suggested by some one from ice model group at NCAR. However, the 'thermo iteration error' was resolved by changing the 'ktherm' from 1 (no mushy physics) to 2 (with mushy physics). It is still a mystery why the 'mushy physics' helps resolve the 'iteration error' issue.

**Comment by rgrumbine** [comment]
Thanks for the word Joshua. That sounds consistent with the DA group's experience. Good to have an independent confirmation.

**Comment by junwang-noaa** [comment]
@rgrumbine @DeniseWorthen is this issue fixed in PR#610?

**Comment by DeniseWorthen** [comment]
The script changes required to set mushy optionally were included in PR #623 

The original issue created apparently was for an evaluation of the impact of using mushy, so I think that will only be resolved after the P7 is run.
