### ISSUE TITLE
diag_table changes model results in coupled run

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#413]
## Description
It is found that in the coupled run when diag_table is changed in coupled run, model forecast results will change. This happened in coupled run where both fv3 and mom6 uses the same diag_table to output fields. 

### To Reproduce:
To run a coupled model test case, then change the diag_table (say only contain the atmosphere history files), the forecast results will change.

**Comment by mlee03** [comment]
@junwang-noaa do you have any outputs available on Hera, Orion or Gaea that we could look into while trying to reproduce the issue?  Are the diagnostic data different?

**Comment by DeniseWorthen** [comment]
@junwang-noaa Did we determine that this issue is related to the removal of the FMS files in the diag_table for v16? In that case, we found the v16 configuration would either pass or fail during because of the temperature limit violation in determining sat vapor pressure.

**Comment by junwang-noaa** [comment]
It turns out the diag_table itself does not change model results. However if the diag_table includes rh/spfh in lower pressure levels, then computation of these fields may fail with error message, e.g. "compute_qs: saturation vapor pressure table overflow, nbad=      1" because of the temperature limit violation, and model will stop. If diag_table does not contain those fields, then model integration will continue even though the temperature is very high. This is a instability issue. and diag_table itself does not change model results, I will close the ticket.
