### ISSUE TITLE
WW3 not reproducing for different number of pets

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#427]
## Description
If you change the number of pets the WW3 model is using, the results do not reproduce the same answers as before.  For the wav-atm cases, just the restart file is different however, for the fully coupled case the output from the wave model, and the restarts are different.   This was discovered when trying to make a PR to put in the fix for the thread-safe issue, which is why that PR has not yet been submitted.  Details of the fixing this issue, since they are in WW3 will be in the WW3 issue that is related to this: https://github.com/NOAA-EMC/WW3/issues/317 

### To Reproduce:
Change the number of pets in a test with waves, the results will be different than before.

**Comment by JessicaMeixner-NOAA** [comment]
So the fv3_ccpp_gfdlmprad_atmwav and fv3_ccpp_gfdlmprad tests reproduce themselves even with different number of MPI tasks, however, there are no restart checks in these tests. 

For the cpld_control_wave test, everything but the wave restart file is the same when using different number of MPI tasks for waves. 

For the cpld_bmarkfrac_wave and cpld_bmarkfrac_wave_v16 tests (and likely their non-frac counter parts), the tests does not pass when using different number of MPI tasks and even the atm files along with wave gridded output and restarts are different in this case.

**Comment by JessicaMeixner-NOAA** [comment]
For the cpld_bmarkfrac_wave_v16 test here is an example of the magnitude of differences after 12 hours: 
<img width="566" alt="Screen Shot 2021-02-24 at 9 46 14 AM" src="https://user-images.githubusercontent.com/22549231/109017470-35300700-7685-11eb-960f-18dcf55fd8c0.png">
<img width="564" alt="Screen Shot 2021-02-24 at 9 45 22 AM" src="https://user-images.githubusercontent.com/22549231/109017480-36613400-7685-11eb-9791-b611f6905542.png">
<img width="563" alt="Screen Shot 2021-02-24 at 9 44 08 AM" src="https://user-images.githubusercontent.com/22549231/109017485-382af780-7685-11eb-85d1-8057204ae139.png">

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA May I ask if this issue is resolved in WW3?

**Comment by JessicaMeixner-NOAA** [comment]
Not yet, but @MatthewMasarik-NOAA has been looking into what might be causing this just from the WW3 standalone side and has an idea of what one issue there is.  Hopefully solving that problem will also solve this issue.

**Comment by JessicaMeixner-NOAA** [comment]
I have added tests for this issue here: https://github.com/jessicameixner-noaa/ufs-weather-model/tree/feature/addwavetests note the C96 does not have this issue, but C384 does.  Updates on progress on the underlying WW3 issue are being updated here: https://github.com/NOAA-EMC/WW3/issues/317 still no solution, but the issue has been narrowed down to the fact that when ice is updated during a wave forecasts, the restart files do not reproduce in VA after that, but it's still not clear how to fix this issue.
