### ISSUE TITLE
Develop a coupled mom6_cice6_cdeps_cmeps application

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#433]
## Description
The purpose of this project is to develop a coupled mom6_cice6_cdeps_cmeps application. When the application works as expected. It will replace the existing mom6_cice6_nems_datm application within the ufs-weather-model system.

## Solution
1. Update NEMS component: 
MAIN_NEMS.F90 and module_EARH_GRID_COMP.F90 will be updated to add pio initialization and new NUOPC atmosphere componet "datm_cfsr".
2. Update CDEPS code to include CFSR data stream.
3. Update CMEPS code to revise land-sea mask for the CFSR data source and remove pio initialization procedure.
4. Update CMakeLists.txt to revise existing conditional blocks in order to build mom6_cice6_cdeps_cmeps application. 
5. Add new tests for the mom6_cice6_cdeps_cmeps application to the ufs-weather-model regression test system.

## Related issues:
- https://github.com/NOAA-EMC/NEMS/issues/88
- https://github.com/NOAA-EMC/CMEPS/issues/34
- https://github.com/NOAA-EMC/CDEPS/issues/6
- https://github.com/NOAA-EMC/CDEPS/issues/7

**Comment by uturuncoglu** [comment]
@binli2337 will you use the current implementation done under HAFS for this work?

**Comment by binli2337** [comment]
@uturuncoglu Right now, I have some results when the pio is initialized in the NEMS driver. I will revise this issue page when the new implementation done under HAFS is ready for testing for the mom6_cice6_cdeps application.

**Comment by uturuncoglu** [comment]
@binli2337 thanks. it is almost ready and I could merge CMEPS and CDEPS PR in ESCOMP side today or maybe tomorrow. Then I'll update the HAFS model CDEPS branch.

**Comment by binli2337** [comment]
The following two 30-day runs have been performed:
1) Using mom6_cice6_nems_datm model (executable built using ufs-weather-model develop branch (#d6a0b8c, 02/12/21 version)
2) Using  mom6_cice6_cdeps_cfsr_datm model (executable built using feature/add_cdeps branch at https://github.com/binli2337/ufs-weather-model)

The CFSR data is used both data atmosphere model components. The horizontal grid used in mom6/cice6 is 1 degree tripolar grid.

The attached figures show a few fields from those two runs.
Fig.1 NINO3.4 SST
![Fig 1_NINO3 4](https://user-images.githubusercontent.com/29778188/109044371-55b98a80-76a0-11eb-8d0b-d0fcad1fe54c.gif)
Fig.2 SST on day 30 of the simulations
![Fig 2_SST_day_30_of_the simulations](https://user-images.githubusercontent.com/29778188/109044594-95807200-76a0-11eb-82e3-b07c9455fd92.gif)
Fig.3 Ocean potential temperature on day 30 of the simulations (cross-sections along the equator)
![Fig 3_ocean_temperature_day30](https://user-images.githubusercontent.com/29778188/109044774-cf517880-76a0-11eb-8b29-cd9bd1906470.gif)
Fig.4 Ocean salinity on day 30 of the simulations (cross-sections along the equator)
![Fig 4_ocean_salinity_day30](https://user-images.githubusercontent.com/29778188/109044855-e6906600-76a0-11eb-87d1-e7acdad11bd5.gif)
Fig.5 Seaice thickness on day 30 of the simulations
![Fig 5_seaice_thickness](https://user-images.githubusercontent.com/29778188/109044928-ff008080-76a0-11eb-8344-91fe38db9594.gif)

**Comment by DeniseWorthen** [comment]
@binli2337 Are the T and S cross-sections at the equator?

**Comment by binli2337** [comment]
@DeniseWorthen Yes.

**Comment by DeniseWorthen** [comment]
Thanks. Also, I've always suspected the NEMS DATM was very inefficient. What was the wall clock time for the CDEPS vs DATM run?

**Comment by binli2337** [comment]
@DeniseWorthen For the 30-day run using NEMS DATM, the wall clock time is 54 minutes. For the 30-day run using CDEPS DATM, the wall clock time is 52 minutes. The petlist bounds are:
datm: 0-11
nems: 0-11
mom6: 12-27
cice6: 28-39

**Comment by jiandewang** [comment]
@binli2337 you are running 1x1 C96, right ?

**Comment by binli2337** [comment]
@jiandewang The ocean resolution is 1x1. The atmospheric forcing data is from CFSR.

**Comment by DeniseWorthen** [comment]
@binli2337 Can we can close this issue?

**Comment by DeniseWorthen** [comment]
@binli2337 Can we close this issue?
