### ISSUE TITLE
FMS I/O for regional native model grid output

### ISSUE THREAD

**Issue by panll** [ufs-community/ufs-weather-model#442]
## Description

The model will crash for "cubed_sphere" grid output for the regional run. Here is the error message on Hera:

 0:  in fcst,init total time:    6.30594396591187
24: application called MPI_Abort(comm=0x84000002, 1) - process 24
25: application called MPI_Abort(comm=0x84000002, 1) - process 25
27: application called MPI_Abort(comm=0x84000002, 1) - process 27
26: application called MPI_Abort(comm=0x84000002, 1) - process 26
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
 0: slurmstepd: error: *** STEP 16574588.0 ON h11c51 CANCELLED AT 2021-02-25T16:23:23 ***
srun: error: h11c51: tasks 0-27: Killed
srun: launch/slurm: _step_signal: Terminating StepId=16574588.0

The model will not crash for "gaussian" grid output for the regional run; however, the output is in the global domain not the regional domain.

### To Reproduce:

The model was run on Hera with the setting file:
ufs-weather-model/modulefiles/hera.intel/fv3

The error message can be reproduce by having a regional run with setting output grid to "cubed_sphere_grid" 

## Additional context
The problem is related to FMS I/O.

## Output

![Screen Shot 2021-02-26 at 10 02 21 AM](https://user-images.githubusercontent.com/19392155/109331176-c46e2380-7819-11eb-919f-e75368b030ec.png)

**Comment by mlee03** [comment]
@panll, could you point us to the location of the input and output files on Hera?

**Comment by panll** [comment]
Here is my running directory on Hera: /scratch2/BMC/det/lpan/hera/v16/11132020/stmp2/Linlin.Pan/FV3_RT/rt_176596/fv3_ccpp_regional_quilt_prod_test
@mlee03

**Comment by mlee03** [comment]
@panll, thank you, we'll look into it.

**Comment by panll** [comment]
Thanks for checking that! @mlee03

**Comment by junwang-noaa** [comment]
@panll would you please confirm that you still have issue with the latest develop branch? Thanks.

**Comment by panll** [comment]
I'll check that. @junwang-noaa

**Comment by panll** [comment]
The code works now for  output "cubed_sphere_grid"; however, it crushed for "gaussian_grid" output. The error messages are:
 0:  in fcst run phase 2, na=          23
srun: error: h9c30: tasks 60-61,63-67: Exited with exit code 174
srun: launch/slurm: _step_signal: Terminating StepId=21359984.0
 0: slurmstepd: error: *** STEP 21359984.0 ON h2c56 CANCELLED AT 2021-08-06T22:44:50 ***
19: forrtl: error (78): process killed (SIGTERM)
19: Image              PC                Routine            Line        Source
19: fv3.exe            0000000003B61BEF  Unknown               Unknown  Unknown
19: libpthread-2.17.s  00002BA88FE6C630  Unknown               Unknown  Unknown
19: fv3.exe            000000000322FD55  rrtmg_sw_mp_spcvr        3766  radsw_main.F90
19: fv3.exe            000000000320CED4  rrtmg_sw_mp_rrtmg        1394  radsw_main.F90

The code is tested on Hera, and here is the running directory for "gaussian_grid" output:
/scratch2/BMC/fv3lam/lpan/test/v16/08022021/stmp2/Linlin.Pan/FV3_RT/rt_309012/regional_quilt_2
Thanks! @junwang-noaa @mlee03

**Comment by junwang-noaa** [comment]
@panll Regional application does not support "gaussian grid", it supports
"regional_latlon", "rotated_latlon" and "lambert_conformal" besides
"cubed_sphere_grid".

**Comment by panll** [comment]
Ok, thanks for the explanation! @junwang-noaa

**Comment by DeniseWorthen** [comment]
@panll Can we close this issue?
