### ISSUE TITLE
RT Automation fails to run multiple jobs correctly. Works for single jobs.

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#449]
## Description
Looks like the compiler env var doesn't get updated on multiple jobs

### To Reproduce:
Run multiple jobs where the second job starts before the next cron starts it

## Additional context
Looks to be a compiler env var isn't updated or is overwritten during runs.

**Comment by climbfuji** [comment]
This may have to do with the ecflow server.
