### ISSUE TITLE
Incorrect dimensional settings in datm_bulk_gefs regression test

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#456]
## Description

In the current datm_bulk_gefs test, IATM is set to 1760 and JATM is set to 880.

The correct settings should be:
IATM=1536
JATM=768

## Additional context
After the regression test for "datm_bulk_gefs" is done, the restart file "DATM_GEFS.cpl.r.2011-10-02-00000.nc" shows incorrect horizontal dimensions for variables from data atmosphere model.

**Comment by DeniseWorthen** [comment]
@binli2337 Were you going to provide a fix for this in Dom's PR #448 since new baselines were required?

**Comment by binli2337** [comment]
@DeniseWorthen My next PR will also change baselines. I will include the fix in my PR. Thanks.

**Comment by DeniseWorthen** [comment]
Thanks. I must have mis-heard in one of the meetings.

**Comment by junwang-noaa** [comment]
@binli2337 will this fix still go with CDEPS PR?
