### ISSUE TITLE
Timing information in the regression tests

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#459]
## Description
In the regression test log files, it would be good if the timing information can be added. This information will allow developers to track when code updates cause significant slowdown 

## Solution
In the run output files, there is a total wall clock time "The total amount of wall time", we can grab that line to the each test log information.  

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. 
-

**Comment by DusanJovic-NOAA** [comment]
```
$ git diff rt_utils.sh
diff --git a/tests/rt_utils.sh b/tests/rt_utils.sh
index 52f9dd8..a6e982a 100755
--- a/tests/rt_utils.sh
+++ b/tests/rt_utils.sh
@@ -327,6 +327,10 @@ check_results() {
 
   fi
 
+  echo                                               >> ${REGRESSIONTEST_LOG}
+  grep "The total amount of wall time" ${RUNDIR}/out >> ${REGRESSIONTEST_LOG}
+  echo                                               >> ${REGRESSIONTEST_LOG}
+
   echo "Test ${TEST_NR} ${TEST_NAME} ${test_status}" >> ${REGRESSIONTEST_LOG}
   echo                                               >> ${REGRESSIONTEST_LOG}
   echo "Test ${TEST_NR} ${TEST_NAME} ${test_status}"

```

**Comment by junwang-noaa** [comment]
Thanks for making this change.

**Comment by DeniseWorthen** [comment]
We could combine this with the change for Issue #228?

**Comment by junwang-noaa** [comment]
Do we have anything to change for issue #228?
