### ISSUE TITLE
Add build information to UFS weather model guide

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-weather-model#465]
## Description

UFS weather model guide does not provide any detailed information on how to build the model

## Solution

Remove the build information from the wiki page, update it to the latest way to build the model (including any reference to hpc-stack) and put that in the guide. The build information should move with the repository so that model releases have the correct information

**Comment by MinsukJi-NOAA** [comment]
Codes changes merged via #619
