### ISSUE TITLE
Update RT documentation with utest documentation

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-weather-model#467]
## Description

Utest documentation is not their in the UFS weather guide

## Solution

The Utest is a sub set of the full RT suite so this could be a section under the RT section in the Guide. It should be updated and moved there. It is not exactly unit tests in the strictest sense so that should probably be highlighted. 

## Related to

- should come after https://github.com/ufs-community/ufs-weather-model/issues/466

**Comment by MinsukJi-NOAA** [comment]
Codes changes merged via #619
