### ISSUE TITLE
Build and run production/GFS.v16 branch on Comet

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#470]
## Description
Build and run production/GFS.v16 branch on Comet. This will be used by the global workflow.

## Solution
Code changes will be made in ufs-weather-model, FV3, WW3, and NEMS repositories.

**Comment by arunchawla-NOAA** [comment]
@MinsukJi-NOAA is this activity finished?

**Comment by MinsukJi-NOAA** [comment]
@KateFriedman-NOAA did you come across any issues using these code changes for workflows on Comet?

**Comment by KateFriedman-NOAA** [comment]
The feature/comet branch is working well for us on Comet. I made the following changes when the hpc-stack was relocated but otherwise am using the branch as is:

```
diff --git a/modulefiles/comet/fv3 b/modulefiles/comet/fv3
index ecfcc1e..b44c8d2 100644
--- a/modulefiles/comet/fv3
+++ b/modulefiles/comet/fv3
@@ -18,7 +18,7 @@ module load intelmpi/2018.1.163
 ##
 ## NCEP libraries (temporary version to match the CCPP requirements)
 ##
-module use /oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/modulefiles
+module use /cw3e/mead/projects/csg103/hanglei/NCEP/libs/hpc-stack/modulefiles
 module load bacio/2.4.1
 module load ip/3.3.3
 module load nemsio/2.5.2
@@ -34,7 +34,8 @@ module load png/1.6.35
 module load zlib/1.2.11
 module load upp/10.0.0

-module load netcdf/4.6.1
+#module load netcdf/4.6.1
+module load netcdf/4.7.4
 module load esmf/8_1_0_beta_snapshot_27
```

Thanks!

**Comment by MinsukJi-NOAA** [comment]
Thanks @KateFriedman-NOAA for confirming. I seem to remember that you have had issue on WCOSS. Not quite sure why Comet changes affect WCOSS.

**Comment by KateFriedman-NOAA** [comment]
If I remember correctly, the WCOSS issue was related to mismatched libraries (mixed pre-hpc-stack with hpc-stack libraries). The hash that feature/comet was cut from worked on WCOSS.

**Comment by MinsukJi-NOAA** [comment]
As per discussion with @junwang-noaa and @KateFriedman-NOAA, I am closing this issue and associated PR's #478 and https://github.com/NOAA-EMC/NEMS/pull/93. In case Xingren needs to reclone it in the future, I will keep/maintain feature/comet branch in my personal repositories.
