### ISSUE TITLE
slowness of threading runs in ufs-weather-model

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#474]
## Description
Provide a clear and concise description of what the bug is.
A slowness was found when using the recent ufs-weather-model develop branch. It was identified that it is from ufs-weather-mode PR #425, so far it only impacts the threading test, it is not seen in the tests with 1 thread. In LAM parallel run when using this revision, the running time is increase from 4800s->7700s. It is also seen in the ufs-weather-model threading test fv3_ccpp_2threads test.

### To Reproduce:
What compilers/machines are you seeing this with?
Check out ufs-weather-model, run fv3_ccpp_2threads test, the run time is increased to 49s compared to 42s from previous revision.

**Comment by arunchawla-NOAA** [comment]
isnt there a PR related to this ?

**Comment by junwang-noaa** [comment]
Dom has an fv3atm PR #258 <https://github.com/NOAA-EMC/fv3atm/pull/258>
ready to fix the issue.

**Comment by DeniseWorthen** [comment]
Fix was merged in PR #383
