### ISSUE TITLE
Compiling UFS slow because code gets recompiled unnecessarily

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#485]
## Description

Some recent change (yet to be determined) reintroduced the problem that files get recompiled unnecessarily. If I run the same compile command twice, e.g.
```
./compile.sh cheyenne.intel 'APP=ATM SUITES=FV3_GFS_2017,FV3_GFS_2017_stretched,FV3_GFS_2017_stretched_nest 32BIT=Y' '' NO NO 2>&1 | tee compile.log
```
I see that the autogenerated CCPP physics caps, the entire GFDL_atmos_cubed_sphere directory and many files in fv3atm get compiled again.

This wasn't the case until recently - running the same compile command only compiled what had changed and what depended on it.

I am not aware of any changes on the CCPP side that would cause that, and any help from our cmake pros would be appreciated.

Update: this is with hash 37f0da7b82e32a15bf072eaa158399a6b0f2722c; the following hash of the model still seems to be fine:
```
commit 3be851d55572221d81a807d1c53dc909a4866154
Author: Denise Worthen <denise.worthen@noaa.gov>
Date:   Tue Mar 16 09:11:49 2021 -0400

    Updatetemplate; Fix model slowness when using threading; Update WW3 for porting and threading issues (#383)


    * CI passed at commit 464a90e prior to review.
    * Note: Orion RTs failed because of system work.

    Co-authored-by: Jessica Meixner <jessica.meixner@noaa.gov>
    Co-authored-by: Brian Curtis <brian.curtis@noaa.gov>
```

**Comment by aerorahul** [comment]
Thanks for reporting @climbfuji  I'll take a look at this.

**Comment by aerorahul** [comment]
I suspect it is because of the set of the components and the CACHE gets reset causing the directory to be recompiled.  It's just a hunch, but I'll look closely.

**Comment by climbfuji** [comment]
All, see here: https://github.com/NCAR/ccpp-framework/pull/357

This solves the immediate problem.

One thing that I am not certain about is the following: If I make a change in a single physics scheme, it updates libccppphys.a - as it should. But I believe this now triggers a recompile of the entire dycore if I am not mistaken, due to the dependency of the dycore on CCPP, even though only a few files in the dycore need something from CCPP?

**Comment by junwang-noaa** [comment]
Unless the interface of the CCPP subroutine used by dycore is changed, the
dycore lib does not need to recompile even though dyncore has dependency on
physics. I assume you do not change the ccpp physics interface used by
dycore, right?

**Comment by climbfuji** [comment]
> Unless the interface of the CCPP subroutine used by dycore is changed, the dycore lib does not need to recompile even though dyncore has dependency on physics. I assume you do not change the ccpp physics interface used by dycore, right?
> […](#)

That's correct. I haven't tested it, though, was just speculating/asking. Thanks!
