### ISSUE TITLE
Upcoming RRTMGP developments

### ISSUE THREAD

**Issue by dustinswales** [ufs-community/ufs-weather-model#486]
This is a placeholder for an upcoming PR to address advancements/issues in RRTMGP.

- Bug fix (indexing error) for temperature being passed to GP. (Only exercised in rare cases in EMC's C768L127 configuration). No changes to baselines.
- New coupling of RRTMGP to the RRFS physics. Based on fv3_regional_quilt using FV3_GFS_v15_thompson_mynn_RRTMGP. New RT and baseline needed.
- Revised approach to the LW flux adjustment using the **full** vertical profile of the Jacobian of the upwelling LW. Previously only the surface flux was adjusted. This is a namelist option which is not exercised in the v16 physics, so no changes to the baselines. This is turned on for the RRFS physics.
- Change v16 GP namelist parameter, ngauss_angle, from ngauss_angle=3 to ngauss_angle=1. This speeds up the LW RTE calculation by ~3x. New baselines needed for v16.
- Move allocation of GP interstitial DDTs from the LW scheme to GFS_typedefs.F90 interstitial_create/reset. No changes to baselines.

**Comment by RobertPincus** [comment]
The speedup from the change to the namelists is more like 50%. Still nothing to sneeze at.

**Comment by dustinswales** [comment]
> The speedup from the change to the namelists is more like 50%. Still nothing to sneeze at.

@RobertPincus The ~3X speedup is for the call to rte_lw(). Total radiation runtime speedup is ~50%

**Comment by junwang-noaa** [comment]
@dustinswales May I ask the status of the code updates or is the code already committed?

**Comment by dustinswales** [comment]
This has been merged already.
