### ISSUE TITLE
Add running baselines to automated regression testing suite

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#490]
## Description
Automated regression testing needs to automatically run the baseline jobs as well

## Solution
Add a job and label to start baseline jobs automatically

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA Can we close this issue?

**Comment by BrianCurtis-NOAA** [comment]
Yes, we can. Closing.
