### ISSUE TITLE
compile of ufs-weather-model on dell-p3 can exceed current wall time of 45 mins

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#495]
## Description

Recently, various compile jobs on dell-p3 have failed due to running out of wall clock time. This has been observed in both standalone, s2s and s2sw compile jobs, with no clear pattern. 

### To Reproduce:
What compilers/machines are you seeing this with? 

dell-p3 when using ``rt.sh -e`` in either baseline creation or verify mode.

Give explicit steps to reproduce the behavior. 

Seemingly random compile jobs will fail. 

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

For recent job, compile_016/out showed:

```
TERM_RUNLIMIT: job killed after reaching LSF run time limit.
Exited with exit code 140.

Resource usage summary:

    CPU time :                                   2648.00 sec.
    Max Memory :                                 2524 MB
    Average Memory :                             441.23 MB
    Total Requested Memory :                     8192.00 MB
    Delta Memory :                               5668.00 MB
    Max Swap :                                   -
    Max Processes :                              12
    Max Threads :                                14
    Run time :                                   2702 sec.
    Turnaround time :                            2702 sec.
```

The compile job wall clock time is current 45mins.

**Comment by DeniseWorthen** [comment]
For PR #498, the S2S and S2SW compiles (16,17) again timed out. I edited ``fv3_conf/compile_bsub.IN_wcoss_dell_p3`` to increase the wall clock to 1 hour. The compiles were then completed in 2762 sec or 2774 sec, so about 1 minute longer than the currrent 45min build time setting.

**Comment by climbfuji** [comment]
> For PR #498, the S2S and S2SW compiles (16,17) again timed out. I edited `fv3_conf/compile_bsub.IN_wcoss_dell_p3` to increase the wall clock to 1 hour. The compiles were then completed in 2762 sec or 2774 sec, so about 1 minute longer than the currrent 45min build time setting.

Do you wamnt me to make those changes in my PR, so that you can update your code afterwards and run the "verify" step?

**Comment by DeniseWorthen** [comment]
That would be great. Thanks. I've done creating baselines now, just need to run dell-p3 verify.

**Comment by climbfuji** [comment]
> That would be great. Thanks. I've done creating baselines now, just need to run dell-p3 verify.

Ok, hang on.

**Comment by climbfuji** [comment]
Done: https://github.com/ufs-community/ufs-weather-model/pull/498/commits/a8f564eef3c0af6a5e3fdac4b53f9fe3d911384c

**Comment by DeniseWorthen** [comment]
Using 01:00:00 caused the rt.sh to immediately abort. I'm not sure why. But I changed it to 00:50 and now it has started.

**Comment by climbfuji** [comment]
Maybe there is a walltime limit on Dell? The syntax I used is standard, not sure what is wrong. I would try 00:59.

**Comment by DusanJovic-NOAA** [comment]
I think the -W format is `-W hour:minute`

**Comment by junwang-noaa** [comment]
The issue is identified. We can't submit compile jobs on login node, all the compile jobs are done on transfer nodes which is shared by other jobs. When those nodes are busy, it could cause delay on the compile jobs. We have to either go back to run with one compile job in login node, or run several compile jobs on transfer queue but with slowness on some job. @DusanJovic-NOAA will check if it is possible to run compile jobs on compute nodes on dell (we could not do it before).

**Comment by DusanJovic-NOAA** [comment]
Compile jobs can not be executed on WCOSS Dell P3 compute nodes:

stderr:
```
CMake Error at /gpfs/dell1/usrx/local/prod/packages/cmake/3.16.2/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find MPI (missing: MPI_C_FOUND) (found version "3.1")
Call Stack (most recent call first):
  /gpfs/dell1/usrx/local/prod/packages/cmake/3.16.2/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /gpfs/dell1/usrx/local/prod/packages/cmake/3.16.2/share/cmake-3.16/Modules/FindMPI.cmake:1688 (find_package_handle_standard_args)
  CMakeLists.txt:130 (find_package)
```

stdout:
```
-- The C compiler identification is Intel 18.0.1.20171018
-- The Fortran compiler identification is Intel 18.0.1.20171018
-- Check for working C compiler: /usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/bin64/mpiicc
-- Check for working C compiler: /usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/bin64/mpiicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/bin64/mpiifort
-- Check for working Fortran compiler: /usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/bin64/mpiifort  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/bin64/mpiifort supports Fortran 90
-- Checking whether /usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/bin64/mpiifort supports Fortran 90 -- yes
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
-- Found MPI_Fortran: /usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/bin64/mpiifort (found version "3.1") 
-- Configuring incomplete, errors occurred!
See also "/gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_176849/compile_001/build_fv3_001/CMakeFiles/CMakeOutput.log".
See also "/gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_176849/compile_001/build_fv3_001/CMakeFiles/CMakeError.log".
```
CMakeError.log:
```
The MPI test test_mpi for C in mode normal failed to compile with the following output:                                                                                                                              
Change Dir: /gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_176849/compile_001/build_fv3_001/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_b2bdf/fast && /usr/bin/gmake -f CMakeFiles/cmTC_b2bdf.dir/build.make CMakeFiles/cmTC_b2bdf.dir/build
gmake[1]: Entering directory `/gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_176849/compile_001/build_fv3_001/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b2bdf.dir/test_mpi.c.o
/usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/bin64/mpiicc   -march=core-avx2 -qno-opt-dynamic-align -O2 -debug minimal -D__IFC -sox -fp-model source    -o CMakeFiles/cmTC_b2bdf.dir/test_mpi.c.o   -c /gpfs/dell1/usrx/local/prod/packages/cmake/3.16.2/share/cmake-3.16/Modules/FindMPI/test_mpi.c
In file included from /gpfs/dell1/usrx/local/prod/intel/2018UP01/compilers_and_libraries_2018.1.163/linux/compiler/include/stdint.h(75),
                 from /usrx/local/prod/intel/2018UP01/compilers_and_libraries/linux/mpi/intel64/include/mpi.h(81),
                 from /gpfs/dell1/usrx/local/prod/packages/cmake/3.16.2/share/cmake-3.16/Modules/FindMPI/test_mpi.c(1):
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h(9): catastrophic error: could not open source file "stdint.h" (no directories in search list)
  # include_next <stdint.h>
                           ^

compilation aborted for /gpfs/dell1/usrx/local/prod/packages/cmake/3.16.2/share/cmake-3.16/Modules/FindMPI/test_mpi.c (code 4)
gmake[1]: *** [CMakeFiles/cmTC_b2bdf.dir/test_mpi.c.o] Error 4
gmake[1]: Leaving directory `/gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_176849/compile_001/build_fv3_001/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_b2bdf/fast] Error 2

```

**Comment by junwang-noaa** [comment]
Dusan, thanks for confirming this. We will stay with 1 hr wall clock time
for compile jobs on dell then.
