### ISSUE TITLE
git submodule checkout error 

### ISSUE THREAD

**Issue by mlee03** [ufs-community/ufs-weather-model#497]
## Description
Cloning the develop branch in the ufs-weather-model repository gives the following errors:
<pre>Cloning into 'FV3'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 4673 (delta 6), reused 5 (delta 1), pack-reused 4650
Receiving objects: 100% (4673/4673), 8.39 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3350/3350), done.
fatal: reference is not a tree: 0e05075456800f0c5abd7bfb1ce6f89b26dd7989
</pre>

### To Reproduce:
git clone --recursive -b develop https://github.com/ufs-community/ufs-weather-model

## Output

**Screenshots**

**output logs**

**Comment by BrianCurtis-NOAA** [comment]
We noticed the same thing yesterday and will fix it with the merge of the linked pull request. Thanks for letting us know!

**Comment by mlee03** [comment]
Thank you!

**Comment by DeniseWorthen** [comment]
I just tried to reproduce using your clone command and received no error.

**Comment by mlee03** [comment]
@DeniseWorthen,
It's very hard not to believe in magic :D.  I just tried it again and got 
<pre>Unable to checkout '0e05075456800f0c5abd7bfb1ce6f89b26dd7989' in submodule path 'FV3'</pre>
The ufs-weather-model/FV3 directory is empty.

**Comment by mlee03** [comment]
@DeniseWorthen, I'm getting the above mentioned error on Orion, but not on Gaea.  On Gaea, I'm only getting this warning message: 
<pre>
From https://github.com/NOAA-EMC/fv3atm
 * branch            0e05075456800f0c5abd7bfb1ce6f89b26dd7989 -> FETCH_HEAD
warning: 30051d59f7ce5e410e2d689777c771470c2905cb:.gitmodules, multiple configurations found for 'submodule.ccpp/physics.path'. Skipping second one!
warning: 30051d59f7ce5e410e2d689777c771470c2905cb:.gitmodules, multiple configurations found for 'submodule.ccpp/physics.url'. Skipping second one!
warning: 30051d59f7ce5e410e2d689777c771470c2905cb:.gitmodules, multiple configurations found for 'submodule.ccpp/physics.branch'. Skipping second one!
Submodule path 'FV3': checked out '0e05075456800f0c5abd7bfb1ce6f89b26dd7989'
</pre>

**Comment by DeniseWorthen** [comment]
I get that same warning message; I'm not sure when it started to appear (maybe 2 weeks ago?) and I haven't been able to figure out what is causing it. 

I don't understand the FV3 commit issue. I did 

```
git clone --recursive -b develop https://github.com/ufs-community/ufs-weather-model
```

And I get

```
 f773ef3892615da4b4af26b4be3e57c9f29b9343 CICE-interface/CICE (CICE6.0.0-194-gf773ef3)
 db2a4778970ae340b6bdd62eb03f60cd37a13f75 CICE-interface/CICE/icepack (Icepack1.1.0-87-gdb2a477)
 0658dde477b92348bc8608a8c1d20485843bf4a4 CMEPS-interface/CMEPS (cmeps_v0.4.1-555-g0658dde)
 18658695a0b87ad6fcf33982b9cb13e6d7373911 CMakeModules (v1.0.0-18-g1865869)
 1e9ab6ed1763c981dc8e294c737c449644a9d1fe DATM (heads/develop)
 d4724fa36ead10bfd818b7e3092a4824eff7f323 FMS (2020.04.03)
 0e05075456800f0c5abd7bfb1ce6f89b26dd7989 FV3 (remotes/origin/production/HREF.v3beta-45-g0e05075)
 306ff31371e74694e5d9f4a57584295c7122b9ac FV3/atmos_cubed_sphere (heads/dev/emc)
 9a5c9ce5e35f311f3d6f25da6e85ad8ae9bbc6a1 FV3/ccpp/framework (ccpp_transition_to_vlab_master_20190705-247-g9a5c9ce)
 b6ef6c32e51b4e3c28ca8b49a4e8401f11e55fd9 FV3/ccpp/physics (ccpp_transition_to_vlab_master_20190705-1198-gb6ef6c3)
 33c8a984c17cf41be5d4c2928242e1b4239bfc40 FV3/ccpp/physics/physics/rte-rrtmgp (1.2.1-23-g33c8a98)
 3703ca7ddc3dbd18d205581d32e47aa828fed976 MOM6-interface/MOM6 (dev/master/repository_split_2014.10.10-8012-g3703ca7dd)
 534fc38e759fcb8a2563fa0dc4c0bbf81f758db9 MOM6-interface/MOM6/pkg/CVMix-src (v0.92-beta)
 29e64d652786e1d076a05128c920f394202bfe10 MOM6-interface/MOM6/pkg/GSW-Fortran (v3.05-beta-13-g29e64d6)
 b80b5b18805302290f821e960d820e99e0bcd9ef NEMS (heads/develop)
 fc509248a1cd397e138e65d57c1b10183fc64e2f WW3 (6.07.1-67-gfc509248)
 d0e62eb2996b363862fd543fe9ec910bd75bf004 stochastic_physics (ufs-v2.0.0-68-gd0e62eb)
```

The reference to ``remotes/origin/production/HREF.v3beta-45-g0e05075`` seems odd.
