### ISSUE TITLE
Updates to WW3 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#5]
* Updated WW3 which includes updates for:
-- hera support
-- Adding capability for interpolation from regular grid to curvilinear grids
-- Switch WRST for storing wind in the restart and using it for the first time step in the NUOPC cap.
* NEMSCompsetRun tests with WW3 run on hera
* updates so that wave coupling is tested in the rt.sh tests
* WW3 output added to baselines for checking results

Currently these updates can be found in: https://github.com/JessicaMeixner-NOAA/ufs-weather-model/tree/ww3update

**Comment by junwang-noaa** [comment]
This is committed to the repo. Close the issue.
