### ISSUE TITLE
compare_ncfile error on cray

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#500]
## Description
Bug reported by @junwang-noaa and @DeniseWorthen. compare_ncfile.py exits with 1 when comparing two netcdf files. Manual testing does not result in this problem, if python3 library is used.

**Comment by DeniseWorthen** [comment]
Was this resolved in PR #475? You provided a fix to move the python module load for wcoss-cray.

**Comment by MinsukJi-NOAA** [comment]
Yes. Closing the issue.
