### ISSUE TITLE
Update software environment on gaea and jet - move to emc.nemspara space

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#501]
## Description
The software environment for the ufs (hpc-stack, Python) is currently maintained by @climbfuji in GSL space. This needs to be moved to a place that also EMC has write access to, and the maintenance needs to be handed over to EMC.

## Solution
Install next major or minor version of hpc-stack (i.e. when moving from 1.1.0 to m.n.r) and Python conda distribution in emc.nemspara space.

**Comment by arunchawla-NOAA** [comment]
Is this still an issue @climbfuji and @DeniseWorthen ? What is the disk location for nems on Gaea and Jet ? 

Current locations for hpc-stack are available here

https://github.com/NOAA-EMC/hpc-stack/wiki/Official-Installations

**Comment by climbfuji** [comment]
jet has been done. On gaea, the install location and responsibilities will be shifted to EMC when we roll out hpc-stack v1.2.0 in the next few weeks.

**Comment by DeniseWorthen** [comment]
Do we have a timeline for v1.2.0? I have a vague memory that it was going in sometime after Rusty's dycore commit although I don't remember why they're related.

**Comment by climbfuji** [comment]
This is a tricky question ... close to switching from 1.1.0 to 1.2.0 it was decided by the hpc-stack team that version numbers don't make sense for hpc-stack and that they will add a generic hpc-stack (versionless) metamodule to load. The stack will evolve and is installed in version-independent directory on most machines, so that makes sense.

It doesn't make sense so much for systems w/o modules, where everything gets installed in a flat directory structure and one can only have a single version for each library. But increasing stack version numbers and creating tags every time a single library gets bumped up isn't the best use of our/their time either.

Long story short. Most systems have version-independent directory hpc-stack install locations, but still load a version-specific hpc-stack metamodule. jet hpc-stack maintenance has been transferred to @kgerheiser a while ago. With one of my upcoming ufs-weather-model PRs, we will also make the switch on gaea.

I decided for the system that I maintain (cheyenne) that I will keep using version-dependent install locations as long as the hpc-stack metamodule carries a version number. Cheyenne is therefore the only system that has a `1.2.0` in the install location. Once the version-independent metamodule gets used, I will also switch to a version-independent install location on Cheyenne.

Regarding the RT baseline directories, both jet and gaea are using the emc.nemspara space.

I can refer to this issue and close it when we merge my PR that transfers hpc-stack ownership on gaea.

**Comment by climbfuji** [comment]
Correction! We already made the switch to the hpc-stack maintained by EMC on gaea in #804. @DeniseWorthen you can close the issue if you think it is ok to do so.

**Comment by DeniseWorthen** [comment]
@climbfuji Thanks for the explanation. I will close.
