### ISSUE TITLE
release/public-v1: threading issue in stochastic_physics

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#51]
This is an issue encountered on a Redhat 8 Amazon node using the UFS public release NCEPLIBS-external and NCEPLIBS installations, the ufs-weather-model build.sh build script and the simple test case described on the wiki.

When running the model as
```
mpiexec --verbose -n 8 ./ufs_weather_model 2>&1 | tee ufs_weather_model.log
```
the model hangs during the first timestep. My assumption is that this is a problem with the fast physics called from CCPP, but I have no proof for this yet.

Using
```
OMP_NUM_THREADS=1 mpiexec --verbose -n 8 ./ufs_weather_model 2>&1 | tee ufs_weather_model.log
```
solves the problem.

**Comment by climbfuji** [comment]
The issue is most likely not in CCPP. I added print statements to the autogenerated CCPP code, which tell me that the model is not anywhere near a CCPP physics scheme when it hangs.

**Comment by climbfuji** [comment]
I tracked this issue down and the deadlock occurs in the call to `run_stochastic_physics` in `atmos_model.F90` (around line 300). Even if I set the last argument `nthreads` to 1, it still hangs. I am going to check where in stochastic_physics the problem is, but for the UFS release I assume we could simply remove all !$omp pragmas from the stochastic_physics code. Unless @pjpegion has time to investigate this and find a better solution.

**Comment by pjpegion** [comment]
@climbfuji is this hang only occurring when stochastic physics in enabled?  I'm not sure if I will be of any help with the openmp in the stochastic physics code.  All of it was written for the spectral GFS many years ago, and I don't know what is going on.

**Comment by climbfuji** [comment]
I do have one suspicion ... testing.

**Comment by climbfuji** [comment]
See https://github.com/NOAA-EMC/fv3atm/pull/62 and PRs referenced there for a solution/workaround.

**Comment by climbfuji** [comment]
The workaround has been committed.
