### ISSUE TITLE
release/public-v1: readlink error on macOS using build.sh

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#52]
When using build.sh on macOS, the script complains about readlink. This is because the default macOS readlink doesn't recognize the -f option used to determine MYDIR:
```
MYDIR=$(cd "$(dirname "$(readlink -f -n "${BASH_SOURCE[0]}" )" )" && pwd -P)
```
One can install the GNU readlink via homebrew, but this version is installed as greadlink. Two options: add logic to detect that the system is a macOS system and then call greadlink instead of readlink, or just try to do something less fancy (aka not working properly if `build.sh` is linked to somewhere else and then called from there - I don't think this is something we want anyway) and just use
```
MYDIR=`dirname "$BASH_SOURCE"`
MYDIR=$(realpath "${MYDIR}")
```
?

**Comment by junwang-noaa** [comment]
I'd vote the second way

**Comment by climbfuji** [comment]
Fixed in https://github.com/ufs-community/ufs-weather-model/pull/74.
