### ISSUE TITLE
Add namelist options to the changes made in ccpp-physics

### ISSUE THREAD

**Issue by RuiyuSun** [ufs-community/ufs-weather-model#540]
## Description
Changes have made to Thompson to add options and namelist variables. and correct how the conversion between moist mixing ratios and dry mixing ratios.  The description of the changes in the Thompson MP can be found at https://github.com/NCAR/ccpp-physics/issues/618. 

## Solution
 .gitmodules is changed relating to the changes made in the Thompson MP.

## Related to
required to support https://github.com/NCAR/ccpp-physics/issues/618.

**Comment by DeniseWorthen** [comment]
Closing (the corresponding issue in cccp-physics was closed).
