### ISSUE TITLE
Automatically checking if repos are up to date

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#547]
## Description
Automatically checking if the repos of a PR are up to date does not work properly when a submodule itself is being updated.

### To Reproduce:
Here (https://github.com/ufs-community/ufs-weather-model/pull/538), the notification by github-actions bot is incorrect.
@binli2337 is updating CDPES repo, and therefore it should recognize his branch is up to date.

**Comment by JessicaMeixner-NOAA** [comment]
@MinsukJi-NOAA I just ran into this issue too, but have a question.  For WW3 in general, we allow commits to WW3 before a commit to ufs-weather-model updating it to it's latest version is made.  Sometimes this is fine, but other times this might require other changes that the WW3 code managers (@aliabdolali & me as back-up) need to submit a PR for to ufs-weather-model.  So if someone is updating WW3, then it should be the latest, but if their PR is not related to WW3 it should be the same as what it is in ufs-weather-model, not necessarily the top of the WW3 develop branch.  Does this account for that?   I can explain more if that doesn't make sense.

**Comment by MinsukJi-NOAA** [comment]
@JessicaMeixner-NOAA thanks for reporting this issue. I modified the code to compare with the submodule version pointed to by the ufs-weather-model instead of the top of develop of the submodule. A comment was also left in your PR conversation.

**Comment by MinsukJi-NOAA** [comment]
Changes were merged via #527.
