### ISSUE TITLE
adjust some cpld v16 tests for forecast length and output type

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#551]
## Description

- The v16 cpld benchmark tests are seen to be coming close to the wall clock time of 30mins when fhmax=12.

- The v16 cpld benchmark test on gaea fails with a pio error (see Issue #509) when the ATM output is the tiled grid. 

## Solution

Reduce the fhmax for the cpld v16 test types to 6 hours.
Change the output type for the cpld v16 tests to ``gaussian_grid``

**Comment by DeniseWorthen** [comment]
@junwang-noaa I have a [branch](https://github.com/DeniseWorthen/ufs-weather-model/tree/feature/update_v16tests) for the updated tests that I'm testing on gaea. I created a baseline and then tried to verify against it. All tests pass except for the ``cpld_restart_bmarkfrac_v16`` test. This test is not reproducing the ``phyf006.nc`` forecast file but all other files do reproduce. The data is actually different in the ``phyf006.nc`` forecast file. 

```
baseline dir = /lustre/f2/scratch/Denise.Worthen/FV3_RT/test_v16_baseline2/cpld_bmarkfrac_v16
working dir  = /lustre/f2/scratch/Denise.Worthen/FV3_RT/rt_9502/cpld_restart_bmarkfrac_v16
Checking test 003 cpld_restart_bmarkfrac_v16 results ....
 Comparing phyf006.nc ............ALT CHECK......NOT OK
 Comparing dynf006.nc .........OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.tile1.nc .........OK
 Comparing RESTART/fv_core.res.tile2.nc .........OK
 Comparing RESTART/fv_core.res.tile3.nc .........OK
 Comparing RESTART/fv_core.res.tile4.nc .........OK
 Comparing RESTART/fv_core.res.tile5.nc .........OK
 Comparing RESTART/fv_core.res.tile6.nc .........OK
...
```

**Comment by junwang-noaa** [comment]
Is this  the cpld_restart_bmarkfrac_v16 test with fhmax changed from 12 to 6 using the top of develop branch?

**Comment by DeniseWorthen** [comment]
It is a branch of the upcoming PR #533 which includes the fix for building Waves on Gaea. It has the fhmax set to 6 and the gaussian output change.

**Comment by DeniseWorthen** [comment]
I repeated the restart test for the cpld v16 test using tiles and 3h/3h/6h. That restart test also fails comparison of the phy006.tileX.nc files but all restart files between the restart and control test are b4b.

**Comment by junwang-noaa** [comment]
Denise, I did cpld v16 test with Gaussian grid 6h/6h/12h, the results are
the same at fh012.
/lustre/f2/scratch/emc.nemspara/FV3_RT/rt_6970/cpld_bmarkfrac_v16
/lustre/f2/scratch/emc.nemspara/FV3_RT/rt_6970/cpld_restart_bmarkfrac_v16
cmp phyf012.nc ../cpld_bmarkfrac_v16/phyf012.nc

source code is at:
/lustre/f2/pdata/ncep/emc.nemspara/rttest/denise_pr533/tests
I got permission denied when looking your data:
>ls
/lustre/f2/scratch/Denise.Worthen/FV3_RT/rt_9502/cpld_restart_bmarkfrac_v16
ls: cannot access
'/lustre/f2/scratch/Denise.Worthen/FV3_RT/rt_9502/cpld_restart_bmarkfrac_v16':
Permission denied
May I ask where is your source code too?

**Comment by DeniseWorthen** [comment]
My code is located here: /lustre/f2/pdata/ncep/Denise.Worthen/ufs-weather-model/tests

I've updated since the original post; it is now up-to-date with develop. The current ``cpld_bmarkfrac_v16`` and ``cpld_restart_bmarkfrac_v16`` tests are using the tiled output because that is what I tested yesterday on Hera. 

I don't understand the permission issue. It shows my group as rstprod. Is that why you can't see into them?

**Comment by DeniseWorthen** [comment]
I've been able to get the 6/3/9 restart test with gaussian output to pass at c96 by also setting 

```
export NFHOUT=3
export FDIAG=3
```

I did also try these with 3/3/6 but the ``phy006.nc`` file still failed to reproduce. Currently the cpld v16 tests are run for 12h. I will need to test this in the actual v16 tests if we want to add this change to PR #544.

**Comment by junwang-noaa** [comment]
You will also need to change namelist variable fhzero in gfs_physics_nml in
input.nml to 3 if you would like to have reproducibility 3/3/6
