### ISSUE TITLE
Fix RRTMGP RTs

### ISSUE THREAD

**Issue by dustinswales** [ufs-community/ufs-weather-model#553]
The RRTMGP regression tests fv3_gfs_v16_c192l127 and fv3_gfs_v16_2thread are not working.
The issues are related to how the tests are configured, not the underlying code.

**Comment by DeniseWorthen** [comment]
@dustinswales Is this issue related to PR #820? If so, can we close it after 820 is committed?

**Comment by dustinswales** [comment]
@DeniseWorthen 
One of the RTs has been fixed in #820, c192, but I still need to figure out the issues with the "2thread" test.

**Comment by DeniseWorthen** [comment]
@dustinswales Thanks. We will leave the issue open then.

**Comment by climbfuji** [comment]
@dustinswales has this issue been fixed?

**Comment by dustinswales** [comment]
@climbfuji 
Resolved. Closing
