### ISSUE TITLE
Update GNU compiler on Cheyenne to 10.1.0

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#554]
## Description

Currently we are using GNU 9.1.0 on Cheyenne and GNU 9.2.0 on Hera. We should update the compiler on Cheyenne to 10.1.0, the changes in https://github.com/ufs-community/ufs-weather-model/pull/527 should make this possible.

I maintained hpc-stack v1.1.0 for GNU 10 in parallel to GNU 9 on Cheyenne, thus the prerequisites should all be there.

**Comment by DusanJovic-NOAA** [comment]
GCC 11 has been released: https://gcc.gnu.org/gcc-11/

**Comment by climbfuji** [comment]
Included in https://github.com/ufs-community/ufs-weather-model/issues/671.
