### ISSUE TITLE
remove cnvcf90 in suite_FV3_GFS_v15_thompson_mynn_lam3km.xml

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#578]
## Description
There is a difference in the suite_FV3_GFS_v15_thompson_mynn_lam3km.xml file in the current ufs-weather-model code and the LAM parallels. 

"<scheme>cnvc90</scheme>" is commented out in the code the parallels are using, while it is not commented out in the develop branch code. 

Need to remove <scheme>cnvc90</scheme> in ufs-weather-model/fv3atm/ccpp/suites/suite_FV3_GFS_v15_thompson_mynn_lam3km.xml
```
       <scheme>GFS_suite_interstitial_4</scheme>
-      <scheme>cnvc90</scheme>
       <scheme>GFS_MP_generic_pre</scheme>
```

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

**Comment by climbfuji** [comment]
Does it actually make a difference if it's in there or not?

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA @EricRogers-NOAA can you answer Dom's question?

**Comment by RatkoVasic-NOAA** [comment]
I believe it shouldn't change results, SDF is only for compilation purpose. Real calls are controlled in input.nml with variables such as shal_cnv and/or cnvcld.
