### ISSUE TITLE
Adding "-init=snan,arrays" to Intel DEBUG flags in top-level CMakeLists.txt leads to model crashes in FV3 dycore

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#580]
## Description

Before the recent CCPP cleanup PR (https://github.com/ufs-community/ufs-weather-model/pull/548), additional flags were used for CCPP when compiling with Intel in DEBUG mode: `-init=snan,arrays`.

These flags are useful to detect uninitialized data and we should add them to the entire ufs-weather-model code (in `cmake/Intel.cmake`).

However, doing so leads to crashes in the FV3 dycore, this is for the example of the regression test `fv3_gfs_v16_debug`, but it is the same for all debug tests with Intel:
```
+ srun ./fv3.exe
 in fcst comp init, ntasks=         144
 num_atmos_calls=          18 time_init=        2016          10           3
           0           0           0 time_atmos=        2016          10
           3           0           0           0 time_end=        2016
          10           3           6           0           0 dt_atmos=
        1200 Run_length=       21600
 INPUT source not found  F  set source=No Source Attribute
forrtl: error (182): floating invalid - possible uninitialized real/complex variable.
Image              PC                Routine            Line        Source
fv3.exe            0000000008B6392E  Unknown               Unknown  Unknown
fv3.exe            0000000008FD0760  Unknown               Unknown  Unknown
fv3.exe            000000000609E228  Unknown               Unknown  Unknown
fv3.exe            0000000005B56BF9  external_ic_mod_m        3300  external_ic.F90
fv3.exe            0000000008AD45F3  Unknown               Unknown  Unknown
fv3.exe            0000000008A81ADF  Unknown               Unknown  Unknown
fv3.exe            0000000008A4F335  Unknown               Unknown  Unknown
fv3.exe            0000000005B42107  external_ic_mod_m        3232  external_ic.F90
fv3.exe            0000000005A38200  external_ic_mod_m         734  external_ic.F90
fv3.exe            0000000005A216AD  external_ic_mod_m         290  external_ic.F90
fv3.exe            00000000053F87EC  fv_restart_mod_mp         321  fv_restart.F90
fv3.exe            000000000395FB47  atmosphere_mod_mp         432  atmosphere.F90
fv3.exe            00000000033AD771  atmos_model_mod_m         421  atmos_model.F90
fv3.exe            0000000002D98F95  module_fcst_grid_         383  module_fcst_grid_comp.F90
fv3.exe            0000000001ACAEF3  _ZN5ESMCI6FTable1        2036  ESMCI_FTable.C
fv3.exe            0000000001ACE89A  ESMCI_FTableCallE         765  ESMCI_FTable.C
fv3.exe            00000000021A8E19  _ZN5ESMCI2VM5ente        1211  ESMCI_VM.C
fv3.exe            0000000001ACC377  c_esmc_ftablecall         922  ESMCI_FTable.C
```
Note that there is no stack trace from the FMS library, because it is now an external library and not compiled with debug flags.

As a temporary workaround, until the dycore is fixed, I am going to add the missing flags back for CCPP only in PR https://github.com/NOAA-EMC/fv3atm/pull/300.

### To Reproduce:
Add the following line after line 10 in `cmake/Intel.cmake`:
```
set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -init=snan,arrays")
```
Run any of the DEBUG regression tests with Intel.

**Comment by DusanJovic-NOAA** [comment]
With this change in external_ic.F90:
```
diff --git a/tools/external_ic.F90 b/tools/external_ic.F90
index 5932d78..cfa20eb 100644
--- a/tools/external_ic.F90
+++ b/tools/external_ic.F90
@@ -603,7 +603,7 @@ contains
       allocate (zh(is:ie,js:je,levp+1))   ! SJL
       allocate (ps(is:ie,js:je))
       allocate (omga(is:ie,js:je,levp))
-      allocate (q (is:ie,js:je,levp,ntracers))
+      allocate (q (is:ie,js:je,levp,ntracers)) ; q=0.0
       allocate ( u_w(is:ie+1, js:je, 1:levp) )
       allocate ( v_w(is:ie+1, js:je, 1:levp) )
       allocate ( u_s(is:ie, js:je+1, 1:levp) )
```
model passes all regression tests with `-init=snan,arrays` added to `CMAKE_Fortran_FLAGS_DEBUG` in `cmake/Intel.cmake` and in all CMakeLists.txt in CDEPS, CMEPS, CICE and MOM6.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA Should this be tried again without your changes after all the updates to the dycore and the tracer initialization?

**Comment by DusanJovic-NOAA** [comment]
I added `-init=snan,arrays` to `CMAKE_Fortran_FLAGS_DEBUG` in `cmake/Intel.cmake` and in all `*interface/CMakeLists.txt`. control_debug test passed, but cpld_debug_p7 failed:
```
180: forrtl: error (65): floating invalid
180: Image              PC                Routine            Line        Source             
180: fv3.exe            000000000DD6329E  Unknown               Unknown  Unknown
180: libpthread-2.17.s  00002AC38A2E1630  Unknown               Unknown  Unknown
180: fv3.exe            000000000D40FFC3  icepack_flux_mp_m         220  icepack_flux.F90
180: fv3.exe            000000000D1E1B28  icepack_therm_ver        2956  icepack_therm_vertical.F90
180: fv3.exe            000000000CED4577  ice_step_mod_mp_s         346  ice_step_mod.F90
180: fv3.exe            000000000C5F5E7E  cice_runmod_mp_ic         209  CICE_RunMod.F90
180: libiomp5.so        00002AC3889F1A43  __kmp_invoke_micr     Unknown  Unknown
180: libiomp5.so        00002AC3889B52C6  __kmp_fork_call       Unknown  Unknown
180: libiomp5.so        00002AC388974BB0  __kmpc_fork_call      Unknown  Unknown
180: fv3.exe            000000000C5F4D69  cice_runmod_mp_ic         194  CICE_RunMod.F90
180: fv3.exe            000000000C5F3FC7  cice_runmod_mp_ci          91  CICE_RunMod.F90
180: fv3.exe            000000000BBDC766  ice_comp_nuopc_mp        1068  ice_comp_nuopc.F90               
```

**Comment by DeniseWorthen** [comment]
Thanks @DusanJovic-NOAA . It looks like these variables were added in the advanced snow physics [PR 360](https://github.com/CICE-Consortium/Icepack/pull/360/files) for icepack. 

This is probably obvious to you, but we already have ``-check uninit`` set. So what does this flag do specifically?

**Comment by climbfuji** [comment]
> Thanks @DusanJovic-NOAA . It looks like these variables were added in the advanced snow physics [PR 360](https://github.com/CICE-Consortium/Icepack/pull/360/files) for icepack.
> 
> This is probably obvious to you, but we already have `-check uninit` set. So what does this flag do specifically?

I've noted in the past that the Intel compiler (or any other compiler) has difficulties detecting if variables are potentially uninitialized. This is indeed a very difficult task, because they get passed around between subroutines and even model components. Initialization can happen as side effects in function calls, through pointers, ... impossible for the compiler to detect.

What is much more reliable is to use `-init=snan,arrays` (initalizes all variables and arrays on the heap to NaN) in conjunction with `-ftrapuv` (initializes stack local variables to an unusual value to aid error detection) and `-fpe0` (restricts floating-point exceptions by enabling the overflow, the divide-by-zero, and the invalid floating-point exceptions). The program will then print an error message and abort if any of these exceptions occurs.

**Comment by DeniseWorthen** [comment]
Thanks for the explanation. So, we'd use ``-init=snan,arrays`` instead of (rather than in addition to) ``check uninit`` ?

**Comment by climbfuji** [comment]
You can use both, it won't hurt.

**Comment by DeniseWorthen** [comment]
I've found that I can add a query for the logical flag ``tr_snow`` in the icepack_flux routine. Then modifying the offending line with 

```
-      meltsliq  = meltsliq  + meltsliqn * aicen
+      if(tr_snow)meltsliq  = meltsliq  + meltsliqn * aicen
```

allows the ``cpld_debug_p7`` to complete the 6hr run. It does change answers.

If I print the ``meltsliq`` and ``meltsliqn`` variables, I still see NaNs however. I'll work on a better solution.

**Comment by DeniseWorthen** [comment]
A PR is being made to Icepack [376](https://github.com/CICE-Consortium/Icepack/pull/376) implementing the above fix, which is their preferred solution. I've create the related CICE Issue [41](https://github.com/NOAA-EMC/CICE/issues/41) on our side and will make an intermediate PR to update our cap which allows further testing.
