### ISSUE TITLE
Updates to cellular automaton scheme

### ISSUE THREAD

**Issue by lisa-bengtsson** [ufs-community/ufs-weather-model#587]
Updates include:

Introduction of CA domain definition.
Read/Write and restart capability of CA
Significant cleaning of old ideas
Improved coupling to cumulus convection to be committed in coordination with this issue: NCAR/ccpp-physics#657
Test results with GFSv16 as a baseline (atmosphere only) can be found here: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/v16upcas2/ and https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/v16upcas2/

https://github.com/noaa-psd/stochastic_physics/issues/40

**Comment by DeniseWorthen** [comment]
Can this be closed (PR #589) ?

**Comment by lisa-bengtsson** [comment]
> Can this be closed (PR #589) ?

That is OK with me, thank you. Not sure who makes the decision of closing merged PR's (Jun?). Thank you all for all the help!

**Comment by DeniseWorthen** [comment]
Code has been committed.
