### ISSUE TITLE
compile on JET

### ISSUE THREAD

**Issue by hu5970** [ufs-community/ufs-weather-model#59]
release v1 branch to compile on JET:

now have to set CMakeplatform =jet but we want jet.intel.
@climbfuji

**Comment by climbfuji** [comment]
Thanks, Ming. For consistency with the other platforms, we should rename the cmake configuration file to jet.intel (just as we did for gaea). Will let you know when this is done.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA as part of your cleanup PR, can you rename `cmake/configure_jet.cmake` to `configure_jet.intel.cmake`, please? Thanks...

**Comment by climbfuji** [comment]
File `cmake/configure_jet.cmake` has been renamed to `configure_jet.intel.cmake`, the model compiles on Jet using `build.sh`. @hu5970 can this issue be closed (I can't close it, you'll have to do it)? Thanks.

**Comment by climbfuji** [comment]
@hu5970 can you please close this issue? The UFS public release compiles and runs on jet. Thanks!

**Comment by climbfuji** [comment]
Closing, since the both the UFS public release and the develop branch compile and run on jet.
