### ISSUE TITLE
Add UFS-Aerosols component to include prognostic aerosols

### ISSUE THREAD

**Issue by rmontuoro** [ufs-community/ufs-weather-model#590]
## Description
UFS P7 is scheduled to feature prognostic aerosols via an active aerosol component.

UFS-Aerosols is a new model component developed collaboratively by NASA and NOAA for the UFS to compute prognostic and diagnostic aerosols. The model is based on NASA's 2nd-generation GOCART model and features a NUOPC-compliant coupling interface for integration with the UFS weather model.

## Solution
UFS-Aerosols needs to be added as submodule pointing to NASA's authoritative repository. Changes need to be made to the UFS build system as well as to the atmospheric model to allow bidirectional coupling with this model component.

**Comment by junwang-noaa** [comment]
Notes on the meeting on 6/7/2021 with ESMF group and fv3 cap developers to discuss the path forward with this PR.

Currently with Raffaele's PR, we will still have two fv3 coupling interfaces, one for fv3 coupled with MOM6/CICE6/WAV and JEDI, the other for fv3-chem. The short term solution is to move forward with this method in Raffaele's PR. then we will have another meeting to discuss: 1) remove the coupled flags in namelist variables and set up proper conditions of computing the internal fv3 coupled fields in physics 2) ESMF group may need to update connector to make sure only certain fields in the fv3 export state are updated at appropriate run sequence coupling time.
