### ISSUE TITLE
reopen tickiet: Inconsistencies between FV3 cap configuration parameters and atmos model namelist parameters #4

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#6]
lamrx commented yesterday
For the CMEPS implementation in the directory UFSCOMP/components/fv3/FV3GFS are two files: fv3_cap.F90, which processes the configuration file model_configure and atmos_model.F90 which reads namelist values from atm_in (sym linked as input_nml) in the run directory. Key output control parameters found in each need to be consistent. While both have a high frequency option, there are missing values in atmos_model.F90 for this to work correctly. The short term fix is to disable the high frequency output and select a single frequency for a given experiment. Long term fixes will likely require significant revision to atmos_model.F90 and possibly fv3_cap.F90. For now several parameters and namelist values should be set to the same number.
For fv3_cap.F90 the values to set are: nfhout, nfhout_hf, nfhmax, nfhmax_hf
For atmos_model.F90 the values to set are: fhout, fhout_hf, fhmax, fhmax_hf, fdiag In the file UFSCOMP/components/fv3/FV3GFS/gfsphysics/GFS_layer/GFS_typedefs.F90
is another key namelist variable of fhzero. Note that there is no fhzero_hf.
At the moment fhzero determines the frequency that the atmosphere diagnostic accumulators are reset to zero. Since there is no fhzero_hf, using the high frequency options will not work correctly. For consistent output for now fhzero should have the same value as fhout. While having high frequency output is desirable, the output file labels need to be changed so that subhourly times can be used. To set everything consistently within the CMEPS implementation the file user_nl_fv3gfs found in the job submission subdirectory can be used to set all key values. Others can default or were set correctly earlier. For example to get all 6-hourly output the user_nl_fv3gfs should be:
!----------------------------------------------------------------------------------
! Users should add all user specific namelist changes below in the form of
! namelist_var = new_namelist_value
! Note - that it does not matter what namelist group the namelist_var belongs to
!----------------------------------------------------------------------------------
nfhout = 6
nfhmax_hf = 0
nfhout_hf = 0
fhzero = 6.0
fdiag = 6.0
fhout = 6.0

@junwang-noaa
Collaborator
junwang-noaa commented yesterday
fhzero_hf is not needed for high frequency output. fhzero is the bucket that model uses to do accumulation, it does not have to be associated with the output data frequency. E.g. with fhzero=6, we can still have high frequent hourly history files, which contain field accumulated from 0-1,0-2,0-3,....0-6, then, 6-7, 6-8...etc.

@lamrx
Author
 lamrx commented yesterday
Jun,
     If the accumulators are not zeroed at high frequency output, the flux output variables such as prate and various radiation fluxes will not be correct.   Instant state fields are not affected by fhzero, but are not enough for a full evaluation.

Larry Marx
lmarx@gmu.edu<mailto:lmarx@gmu.edu>
Center for Ocean-Land-Atmosphere Studies
277B Research Hall  Mail Stop 6C5
George Mason University
4400 University Drive
Fairfax, VA    22030
USA
Tel: (703) 993-5746
Fax: (703) 993-5770

On Oct 31, 2019, at 3:30 PM, junwang-noaa <notifications@github.com<mailto:notifications@github.com>> wrote:

fhzero_hf is not needed for high frequency output. fhzero is the bucket that model uses to do accumulation, it does not have to be associated with the output data frequency. E.g. with fhzero=6, we can still have high frequent hourly history files, which contain field accumulated from 0-1,0-2,0-3,....0-6, then, 6-7, 6-8...etc.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1neDoP0DNb23HX2urgPXRUv5yhMjp9i1ZLZReqEFHEkiyBJ4iyZe4qxsw7Qc7TnnPtXjmC9jcvxUv6tPua43wQRVWMvek5_Tv5CLCCE9VHPD87gQ4BxW9qU9zZh_R_K1AFX_sX9S_kWRuJ_9859oAppmsmO5UpZ3o7h83BUUFr6n5eVAZ-OG3zH7SncEg5eknHSyahRPFKNxTHl0PlOxqouaaOAO6FLRTNJpkEdv1SkMnVoL9CLXtKDFdmL4EhU6fT0AhxuulO6Ffi4OZ4a1wDd3GswAhHARraPkCjBMQlmsN3ZiemnrIfH8V8YvZtNqSfrT5uK43UVBLONvk_3tvNnq0sqg0idz6hVY88D5eqAfBzEI_lC7RWv0x6bnw5QVkTjMYyywrFJDB2TE2qXcZlOK2tWEltk6ESQxXWOkFm4ZgJB5x-rt4tncJhiEigFwe/https%3A%2F%2Fgithub.com%2Fufs-community%2Fufs-weather-model%2Fissues%2F4%3Femail_source%3Dnotifications%26email_token%3DAMEOTYZI7FQXWOQQP4KEOTTQRMW35A5CNFSM4JHODZ42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECY7JWY%23issuecomment-548533467>, or unsubscribe<https://secure-web.cisco.com/1ZjcQ5Gf9eWwK8zVV6C3Mv03mjT53qjYFJeSD-vbX-5B4wy3MAJoAYuTCKW7psLvAlpL420ZkNpU1hsgJmZgXLzMvJ4KTNERk12x5SVdElSDmcxSv6nQeDO_unE_uN2WGturE3F8wpB7vmYUBsmmD4F73nxJQm-Zvb6THaBdwci6kHVpae8-clXVOyJgPrtRM11lbey60Fug2rjcJ0o6AnS81A_OIHw6AY3YEaAAUeeG0701B1duqsogOq6lUx97ugXsRr_7RWX5j9EIj4KYJ7SDiRhMJ9EaRW6QuLHvznNxvG6w1lb-5KDB9ShfhNw9OUOlN7SUbpe6xTLMH9hpAg31ISleLwxweZM5RZP4fH5fYa0OinZ6NEbzjqlE8gy9ilV_eYHM2GRXRvdNI4qWEMWPj8D8NOrAb5ano0K53d-ncZAn8HGHiB1YB-gatvzOi/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMEOTYYOM5LSQET2HKPAC63QRMW35ANCNFSM4JHODZ4Q>.
@junwang-noaa
Collaborator
junwang-noaa commented 18 hours ago
Larry,

May I ask why "If the accumulators are not zeroed at high frequency output, the flux output variables such as prate and various radiation fluxes will not be correct"?

The flux outputs such as prate are the bucketed precipitation rate. E.g, fhzero=6, at high frequency output fh=03, the prate is the precipitation rate from 0-3, which is computed by total precip accumulated from 0-3 hr/(3*3600).

**Comment by junwang-noaa** [comment]
Hi, Larry,

Can we close the ticket? Please let me know if you have further question. Thanks.

**Comment by lamrx** [comment]
Jun,
     Yes, I think so since it seems there are larger issues in play here.

Larry Marx
lmarx@gmu.edu
Center for Ocean-Land-Atmosphere Studies
277B Research Hall  Mail Stop 6C5
George Mason University
4400 University Drive
Fairfax, VA    22030
USA
Tel: (703) 993-5746
Fax: (703) 993-5770

**Comment by junwang-noaa** [comment]
Thanks. Close ticket.
