### ISSUE TITLE
Update FMS to allow MOM6 to run at 64-bit and FV3 at 32-bit

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#618]
## Description
Both FV3 dynamic core and MOM6 use FMS. With enormous computational requirements required for GFSv17 implementation, it is desirable to allow MOM6 to run at 64-bit precision and FV3 at 32-bit. To do so, we need to implement a mixed mode FMS for UFS.

## Solution
It is expected that some module interfaces need to be revised or developed.

**Comment by arunchawla-NOAA** [comment]
@binli2337 and @junwang-noaa how is this different from issue 1036 ?

**Comment by junwang-noaa** [comment]
I think we can use issue #1036 to track current issues.

**Comment by arunchawla-NOAA** [comment]
so can we close this?
