### ISSUE TITLE
build ufs-weather-model on wcoss cray

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#62]
@BijuThomas-NOAA from EMC hurricane group found two potential issues when building hafs forecast (ufs-weather-model) on wcoss cray.

1. In modulefiles/wcoss_cray/fv3, it loads a old version cmake/3.6.2
module load cmake/3.6.2
which is not available on wcoss cray anymore. A newer version is available here:
module use /gpfs/hps3/emc/nems/noscrub/emc.nemspara/soft/modulefiles
module load cmake/3.16.3
Also, the cmake module is loaded two times in the module file. So, should this be updated in the corresponding fv3 module file?

2. There is an issue when building the system in CCPP mode and choose clean before the build on wcoss cray. For example,
./compile.sh .... YES NO
The distclean will not work properly and exit with errors like:
gmake: Target `distclean' not remade because of errors.
And Biju found out, if we pre-load a newer version of python:
module unload python/2.7.14
before the compile.sh step, then everything will work fine. (The default python version on wcoss cray is 2.6.9). For this, we are not very sure what is the best way to work around this. Maybe we should load the corresponding module (e.g., modulefiles/wcoss_cray/fv3) before the make distclean?

**Comment by BijuThomas-NOAA** [comment]
In continuation of Bin's comments, 

1. The forecast model build failed at ccpp_build.sh with the message 
_**CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 2.8.11 or higher is required**._.
It appears it tries to load cmake/3.6.2, as there is module load cmake/3.6.2 in modulefiles/wcoss_cray/fv3 file. However, at the default of location on wcoss_cray, 
cmake/3.6.2 is not available.  The forecast model  build is successful with the use of module load cmake/3.16.3 in the modulefiles/wcoss_cray/fv3.  cmake/3.16.3 is available in /gpfs/hps3/emc/nems/noscrub/emc.nemspara/soft/modulefiles

2. The Python 2.6.9 (default on wcoss_cray it seems) does not recognize Dictionary  Comprehension statements. There are few Dictionary Comprehension statements in FV3/ccpp/framework/scripts/ccpp_prebuild.py. The forecast model build will fail unless the user uses a later version of python(example python/2.7.14)

**Comment by junwang-noaa** [comment]
Biju and Bin,

Thanks for the explanation. I checked the cmake module cmake/3.6.2, it is
on cray.
LUNA-llogin1 > pwd
/u/Jun.Wang
LUNA-llogin1 > module avail
...
--------------------------------------------- /usrx/local/dev/modulefiles
----------------------------------------------
ESMF-cray-sandybridge/7_0_0                  gsl-gnu-sandybridge/1.15
ESMF-gnu-haswell/7_0_0                       idl/8.5sp1
ESMF-gnu-sandybridge/7_0_0                   libXft/2.1.13
ESMF-gnu-sandybridge/7_1_0                   met/8.1(default)
ESMF-intel-haswell/7_0_0(default)            metplus/2.1(default)
ESMF-intel-haswell/7_0_0-ics1603             ncarg-intel-sandybridge/6.1.0.1
ESMF-intel-sandybridge/7_0_0(default)        ncarg-intel-sandybridge/6.3.0.1
ESMF-intel-sandybridge/7_0_0-ics1603         nco-gnu-haswell/4.4.4
ESMPy/7_0_0                                  nco-gnu-sandybridge/4.4.4
ESMPy/7_1_0                                  netcdf4-python/1.2.2
GrADS/2.0.2                                  python/2.7.13(default)
HDF5-serial-intel-haswell/1.8.9(default)     python/2.7.14
HDF5-serial-intel-sandybridge/1.8.9(default) python/3.6.3(default)
NetCDF-intel-haswell/4.2(default)            rsync/3.1.2
NetCDF-intel-sandybridge/4.2(default)        subversion/1.7.16
antlr-gnu-haswell/2.7.7                      subversion/1.8.16
antlr-gnu-sandybridge/2.7.7                  svn/1.7.16
cfp/cfp-intel-sandybridge/2.0.0              svn/1.8.16
cfp/cfp-intel-sandybridge/2.0.1              udunits-gnu-haswell/2.1.24
*cmake/3.6.2 *
 udunits-gnu-sandybridge/2.1.24
git/2.18.0
zlib-intel-haswell/1.2.7(default)
gsl-gnu-haswell/1.15
zlib-intel-sandybridge/1.2.7(default)
LUNA-llogin1 > module load cmake/3.6.2
LUNA-llogin1 > module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.3
  2) eswrap/1.3.3-1.020200.1280.0
...
 30) cmake/3.6.2

could it be possible that the  /usrx/local/dev/modulefiles is not in your
module path?

**Comment by BinLiu-NOAA** [comment]
Hi @junwang-noaa ,

You are right, 
module use /usrx/local/dev/modulefiles
is not in my default module path (probably is not default on the wcoss cray machine).

If that is the case and the build system has not add this module path somewhere else, then it probably makes sense to add this line:
module use /usrx/local/dev/modulefiles
in the modulefiles/wcoss_cray/fv3 file before loading the cmake module.

Thanks!

Bin
