### ISSUE TITLE
output SST at hourly increment for P7b

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#633]
## Description
output SST and ePBL at hourly increment for P7b

## Solution
modify current diag_table in P7b branch.

## Related to
UFS P7b

**Comment by jiandewang** [comment]
@junwang-noaa you can assign this task to me. I am making a 2 day testing now, shall have PR ready soon.

**Comment by DeniseWorthen** [comment]
What is the status of this @jiandewang ?

**Comment by jiandewang** [comment]
the branch works fine
https://github.com/jiandewang/ufs-weather-model/tree/feature/P7b-non-MERRA-hourly-SST
