### ISSUE TITLE
move diag_table/field_table from input directory to tests/parm in the repository 

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#644]
## Description
Currently the diag_table and field_table are located in the input data directory. There are some discussion to move those small model test related configuration files to test/parm directory so that updates in those files can be better tracked. 
Another updates are to clean up the template variable replacement. Currently there are two different ways to replace the variable values in the template, it would be good if we can clean them up to avoid confusion.

## Solution
1. Move diag_table/field_table from input data directory to tests/parm directory and modify RT script to copy correct table in the run directory.
2. Use @[] in the templates for variable replacement.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by junwang-noaa** [comment]
@BinLiu-NOAA I noticed in your last commit, the field_table was changed back to the one in input directory (input-data-20210930/FV3_hafs_input_data/field_table), while in the PR [#870](https://github.com/ufs-community/ufs-weather-model/pull/870) the field_table is from ufs-weather-model/tests/parm/field_table/field_table_hafs. I am not removing all the field_tables in the input directory, but the HAFS tests will change due to the difference in the two field_tables. Do you want to change the ufs-weather-model/tests/parm/field_table/field_table_hafs to input-data-20210930/FV3_hafs_input_data/field_table?

**Comment by BinLiu-NOAA** [comment]
@junwang-noaa, please help to delete the FV3_hafs_input_data/field_table file when preparing a new version INPUT DATA. We would like to use this one (ufs-weather-model/tests/parm/field_table/field_table_hafs) instead. BTW, please also help to delete this FV3_hafs_regional_input_data directory (which is no longer needed). Thanks!

**Comment by junwang-noaa** [comment]
Bin, thanks for the clarification on the field_table.
The FV3_hafs_regional_input_data is deleted in the input
directory input-data-20211015 on hera, the input data directory will be
synced to other platforms when all the testing is done.

**Comment by BinLiu-NOAA** [comment]
Thanks @junwang-noaa!

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa we could remove all of the older WW3_input_data_* directories, except for the most recent one if you are working to clean-up and create a new input directory.

**Comment by junwang-noaa** [comment]
Sure, I will keep only the WW3_input_data_20211101 in the latest input data
repository.
