### ISSUE TITLE
missing baseline data on orion

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#651]
## Description
current baseline is develop-20210615, but this directory doesn't exist on orion. Below are the latest 3 on orion

drwxrwsr-x  3 dheinzel nems  4096 Jun  9 22:02 develop-20210609/
drwxrwsr-x  3 bcurtis  nems  4096 Jun 10 15:14 develop-20210610/
drwxrwsr-x  3 jminsuk  nems  4096 Jun 11 11:23 develop-20210611/

But on HERA, the latest 3 are:
drwxr-sr-x   4 emc.nemspara nems  4096 Jun 11 12:23 develop-20210611
drwxr-sr-x   4 emc.nemspara nems  4096 Jun 15 11:21 develop-20210615
drwxr-sr-x   4 emc.nemspara nems  4096 Jun 17 13:13 develop-20210616

**Comment by DeniseWorthen** [comment]
Thru put on Orion has been extremely slow recently. When the next commit will create a new baseline anyway, we sometimes abandon the attempt on Orion. It looks like in this case neither the 0615 or 0616 baseline was created on orion because of excessive wait times.

**Comment by DeniseWorthen** [comment]
@jiandewang Is this still a problem for you? We will hopefully have a new baseline on orion today.

**Comment by jiandewang** [comment]
@DeniseWorthen I think we can close this once new baseline is created on orion.

**Comment by DeniseWorthen** [comment]
New baseline was created for PR #591
