### ISSUE TITLE
move diag_table and field_table from input data directory to parm directory in RT

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#653]
## Description
diag_table and field_table are model configuration related files, it's good to move these two table files in ufs-weather-model/tests/parm where the configuration files are located.

## Solution
Move the diag_table and field_table to  ufs-weather-model/tests/parm and update RT scripts to copy the corresponding files to test run directories.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- a ufs-weather-model PR will be created.

**Comment by DusanJovic-NOAA** [comment]
Is this duplicate of #644?

**Comment by junwang-noaa** [comment]
Sorry, I was searching for the issue, but somehow missed it. Close the issue, thanks.
