### ISSUE TITLE
update coupled regression tests for gfs_v16

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#655]
## Description

The current non-benchmark coupled RTs are using GFS 2017 physics (v14). We need to update to GFS_v16 

## Solution

Update required namelists, ICs and tests to use GFS_v16 settings.

**Comment by DeniseWorthen** [comment]
@jiandewang @JessicaMeixner-NOAA For the non-benchmark tests, the MOM6 ICs are copied in fv3_conf/cpld_control_run.IN. The ICs are non-resolution dependent; the file it is copying in is ``MOM6_IC_TS.nc``.

```
  cp  @[INPUTDATA_ROOT]/MOM6_IC/MOM*.nc ./INPUT
```

**Comment by JessicaMeixner-NOAA** [comment]
I remember the MOM6_IC_TS.nc as being generated from CFS/CFSR for the specific date.

**Comment by jiandewang** [comment]
@JessicaMeixner-NOAA correct. I don't think any climatological T/S files were being generated from EMC to be used in MOM6.

**Comment by DeniseWorthen** [comment]
I do not believe the file is created from any CFS/CFSR restart for any specific date. It is a 1/2x1/2 regular lat/lon file with 40 vertical levels defined on z-levels.

**Comment by jiandewang** [comment]
@DeniseWorthen 40L 0.5x0.5 is exactly the format that CFSR data being processed to feed for MOM6.

**Comment by DeniseWorthen** [comment]
OK, I stand corrected. But if it is for a specific date, it should have a date in the name. 

Can that file be created for this setting:

export SYEAR=2021
export SMONTH=03
export SDAY=22
export SHOUR=06

**Comment by jiandewang** [comment]
> OK, I stand corrected. But if it is for a specific date, it should have a date in the name.
> 
> Can that file be created for this setting:
> 
> export SYEAR=2021
> export SMONTH=03
> export SDAY=22
> export SHOUR=06

OK will do that.
