### ISSUE TITLE
Add 3D diagnostics for Thompson scheme

### ISSUE THREAD

**Issue by ericaligo-NOAA** [ufs-community/ufs-weather-model#659]
## Description
Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Solution
Add a clear and concise description of what you want to happen.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by SamuelTrahanNOAA** [comment]
@ericaligo-NOAA Is this issue resolved by #660, which added 3d diagnostic tendencies for all tracers and schemes? It added diagnostic tendencies for the microphysics scheme in its entirety; not any processes within the scheme.

**Comment by ericaligo-NOAA** [comment]
I'm not familiar with these changes.  There was a separate issue that 
added 3D Thompson scheme diagnostics.

**Comment by SamuelTrahanNOAA** [comment]
That would be "no" then. PR #660 did not add any diagnostics inside the Thompson scheme.

**Comment by climbfuji** [comment]
> That would be "no" then. PR #660 did not add any diagnostics inside the Thompson scheme.

EDIT: Misunderstanding. The special Thompson diagnostics were added in a previous PR, this issue is resolved.
