### ISSUE TITLE
3D diagnostic tendencies for all tracers

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#662]
## Description
Many users have requested 3D diagnostic tendencies for tracers, and a more efficient method to store the tracer tendencies.

## Solution
Store the tendencies in a 4D sparse array using a 3D array and a 2D indexed array:

```dtend(i,k,dtidx(variable,process))```

## Alternatives
The next CCPP framework, which will come sometime in the future.

## Related to
Fixed by PR #660 
May be related to https://github.com/ufs-community/ufs-weather-model/issues/659 which is not clearly defined.

**Comment by MinsukJi-NOAA** [comment]
@SamuelTrahanNOAA was this issue resolved by #660 ?

**Comment by SamuelTrahanNOAA** [comment]
Yes.
