### ISSUE TITLE
Ocean model incremental analysis update (IAU)

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-weather-model#667]
## Description
 We need to implement IAU in the ocean in order to reduce initialization shocks during the data assimilation cycle
## Solution
 Alex Bozec at COAPS/FSU has coded up the solution in MOM6
## Alternatives
non needed.
## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/68

**Comment by junwang-noaa** [comment]
@pjpegion Is this the same issue as [#617](https://github.com/ufs-community/ufs-weather-model/issues/617)?

**Comment by pjpegion** [comment]
Oops.  Yes it is.  I will delete #617
