### ISSUE TITLE
Turn on tests on jet.intel

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#680]
## Description
The cpld_decomp and control_decomp were turned off on Jet in PR #396 (8dabdb44). Using the current develop, all 4 tests passed (control_decomp vs control and cpld_decomp vs cpld_control). These comparisons did not rely on nc_compare.py, but on direct comparison w/ cmp.

Additional testing for standalone FV3 shows that all tests except ``regional_quilt_2threads`` can be turned on for jet.intel. The ``regional_quilt_2threads`` test runs but times out.

See attached log:

[RegressionTests_jet.intel.log](https://github.com/ufs-community/ufs-weather-model/files/6742638/RegressionTests_jet.intel.log)

## Solution

Turn cpld_decomp and control_decomp tests on in rt.conf

**Comment by DeniseWorthen** [comment]
@junwang-noaa @climbfuji I turned on all standalone tests for jet.intel, created a baseline and tested against it. All tests passed w/ the exception of the following two which timed out. 

```
control_2threads 003 failed in run_test
regional_quilt_2threads 027 failed in run_test
```

**Comment by climbfuji** [comment]
> @junwang-noaa @climbfuji I turned on all standalone tests for jet.intel, created a baseline and tested against it. All tests passed w/ the exception of the following two which timed out.
> 
> ```
> control_2threads 003 failed in run_test
> regional_quilt_2threads 027 failed in run_test
> ```

Thanks for testing this! Are these tests just running slow, or are they hanging right at the beginning? Or not start at all?

**Comment by DeniseWorthen** [comment]
They both almost complete--the last file written is the hour 21 forecast in both cases.

**Comment by climbfuji** [comment]
Too bad, wondering why they are running so slow.

**Comment by junwang-noaa** [comment]
@deniseWorthen, we may need the fix of the jet job card template in Ali's
WW3 PR  for threading test on jet. Currently the job_card does not specify
the number of tasks per node, so I think there might be some issue with jet
threading test

**Comment by DeniseWorthen** [comment]
So I need 

```
#SBATCH --nodes=@[NODES]
#SBATCH --ntasks-per-node=@[TPN]

and

srun --label -n @[TASKS] ./fv3.exe
```

in fv3_slurm.IN_jet ?

**Comment by junwang-noaa** [comment]
Yes

**Comment by DeniseWorthen** [comment]
Making that change to fv3_slurm.IN_jet allowed the control_2threads test to pass (850s wall time). The regional_quilt_2threads still timed out.

**Comment by junwang-noaa** [comment]
Can I take a look at the regional_quilt_2threads run directory?

**Comment by DeniseWorthen** [comment]
It is here /lfs4/HFIP/h-nems/Denise.Worthen/RT_RUNDIRS/Denise.Worthen/FV3_RT/rt_283179/regional_quilt_2threads
