### ISSUE TITLE
WRITE_DOPOST error when running in debug mode

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#686]
## Description
Current control_debug regression test specifies the parameter WRITE_DOPOST=.false. If this value is changed to .true., an error results during run time. However, this error does not occur if gnu compiler is used.

### To Reproduce:
On Hera
1. Edit tests/tests/control_debug to include `export WRITE_DOPOST=.true.`
2. ./rt.sh -n control_debug >out 2>&1
3. This will result in error during the run
4. export RT_COMPILER=gnu
5. ./rt.sh -n control_debug >out 2>&1
6. This will run successfully

## Output
```
144:  post_fname=GFSPRS.GrbF00
  0:  in fcst run phase 2, na=           1
145: forrtl: error (65): floating invalid
145: Image              PC                Routine            Line        Source     
145: fv3.exe            000000000A1F819E  Unknown               Unknown  Unknown
145: libpthread-2.17.s  00002B3AD6C8D630  Unknown               Unknown  Unknown
145: fv3.exe            0000000009DF1AD2  bndlyr_                   311  BNDLYR.f
145: libiomp5.so        00002B3AD539DA43  __kmp_invoke_micr     Unknown  Unknown
145: libiomp5.so        00002B3AD53612C6  __kmp_fork_call       Unknown  Unknown
145: libiomp5.so        00002B3AD5320BB0  __kmpc_fork_call      Unknown  Unknown
145: fv3.exe            0000000009DF70CE  bndlyr_                   272  BNDLYR.f
145: fv3.exe            0000000009D5C9D9  miscln_                  1712  MISCLN.f
145: fv3.exe            0000000009AAA697  process_                  116  PROCESS.f
145: fv3.exe            0000000003169875  post_gfs_mp_post_         201  post_gfs.F90
145: fv3.exe            000000000316512E  inline_post_mp_in          43  inline_post.F90
145: fv3.exe            000000000310333A  module_wrt_grid_c        1489  module_wrt_grid_comp.F90
```

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA Would you please take a look at this?

**Comment by WenMeng-NOAA** [comment]
I will look that.

**Comment by WenMeng-NOAA** [comment]
In UPP code, the line 311 in BNDLYR.f :
`IF(UBND(I,J,LBND)<spval.and.VBND(I,J,LBND)<spval.and.PVSUM(I,J,LBND)<spval)THEN`

I don't see any issue in it.
I would like reproduce the error via running rt test in ufs-weather-model. My test failed at the line 631 in rt.sh as:
```
+ ./compile.sh hera.intel '-DAPP=ATM -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v16_RRTMGP,FV3_GFS_v16_csawmg,FV3_GFS_v16_flake,FV3_GFS_v16_ugwpv1,FV3_GFS_v16_ras,FV3_GFS_v16_noahmp -D32BIT=ON' 001
++ echo 'rt.sh error on line 631'
rt.sh error on line 631
``` 
@MinsukJi-NOAA Could you advise the fix in rt.sh? Thanks!

**Comment by MinsukJi-NOAA** [comment]
> In UPP code, the line 311 in BNDLYR.f :
> `IF(UBND(I,J,LBND)<spval.and.VBND(I,J,LBND)<spval.and.PVSUM(I,J,LBND)<spval)THEN`
> 
> I don't see any issue in it.
> I would like reproduce the error via running rt test in ufs-weather-model. My test failed at the line 631 in rt.sh as:
> 
> ```
> + ./compile.sh hera.intel '-DAPP=ATM -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v16_RRTMGP,FV3_GFS_v16_csawmg,FV3_GFS_v16_flake,FV3_GFS_v16_ugwpv1,FV3_GFS_v16_ras,FV3_GFS_v16_noahmp -D32BIT=ON' 001
> ++ echo 'rt.sh error on line 631'
> rt.sh error on line 631
> ```
> 
> @MinsukJi-NOAA Could you advise the fix in rt.sh? Thanks!

@WenMeng-NOAA could you share your working directory so I can take a look? Thanks!

**Comment by WenMeng-NOAA** [comment]
@MinsukJi-NOAA Please see /scratch2/NCEPDEV/ovp/Wen.Meng/ufs_develop/ufs-weather-model/tests on Hera.
The runtime log file  is out. My account uses c-shell.  Thanks!

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA Please see /scratch2/NCEPDEV/ovp/Wen.Meng/ufs_develop/ufs-weather-model/tests on Hera.
> The runtime log file is out. My account uses c-shell. Thanks!

@WenMeng-NOAA  I am not getting the error you are getting. Is it possible for you try using the bash shell?

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa and @MinsukJi-NOAA I did a test of building upp lib with as additional debug option in file EMC_post/sorc/ncep_post.fd/CMakeLists.txt as:
Change
   -g -traceback -fp-model source -free -convert big_endian
into
    -g -traceback -fp-model source -free -convert big_endian -check all,noarg_temp_created

The rt test for control_debug was successfully completed. My testing upp lib is at 
/scratch1/NCEPDEV/stmp2/Wen.Meng/upp_lib/EMC_post/tests/install

The log file  of my ufs-weather-model test is at  /scratch1/NCEPDEV/stmp2/Wen.Meng/ufs/ufs-weather-model/tests/wen.log.
The working directory of the test is /scratch1/NCEPDEV/stmp2/Wen.Meng/FV3_RT/rt_3467

Please let me know your comments.

**Comment by MinsukJi-NOAA** [comment]
@WenMeng-NOAA I tested the upp debug library you built.

control_debug successfully completed with intel, but failed to build with gnu. Log file is at /scratch2/NCEPDEV/stmp1/Minsuk.Ji/ufs-weather-model-latest/tests/log_hera.gnu

@junwang-noaa  Even if gnu also completes successfully, do we want to use upp debug library for debug test? Or just leave WRITE_DOPOST='false' for control_debug test?

**Comment by junwang-noaa** [comment]
Thanks, Minsuk for confirming the debug test is working.
@WenMeng-NOAA I want to confirm with you that you did not make any code changes, only compiled upp lib in debug mode ( -check all,noarg_temp_created ), with the debug mode upp lib the control_debug test case passed, is that correct? There were some discussions on if we should use debug mode libraries, this may be a good example. @DusanJovic-NOAA @aerorahul @arunchawla-NOAA @DeniseWorthen

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa That's right. The only change is building upp lib in debug mode in EMC_post/sorc/ncep_post.fd/CMakeLists.txt.

**Comment by DusanJovic-NOAA** [comment]
The line 311 in BNDLYR.f  is in this if test:

`IF(gridtype=='E' .or. gridtype=='B')THEN`

why is model executing code in this if block. Isn't `gridtype = 'A'` in fv3?

**Comment by DusanJovic-NOAA** [comment]
Why is the if test at line 277 in BNDLYR.f checking the values of T,Q,UH,VH when those arrays are not used in this loop?
When I comment out this if test (and else block) model finishes successfully.
```
!            IF(T(I,J,LBND)<spval.and.Q(I,J,LBND)<spval.and.&
!               UH(I,J,LBND)<spval.and.VH(I,J,LBND)<spval) THEN
```

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA You are right. These changes were added from the UPP PR [306](https://github.com/NOAA-EMC/EMC_post/pull/306) for restricting the computation on undefined points. It looks further modifications are needed in this subroutine. Can you or any one from ufs weather model team open a new issue at the UPP repository? Thanks!
