### ISSUE TITLE
Use input data on aws s3 for CI testing

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#690]
## Description
Currently, the input data used in CI testing is saved in a personal docker hub, which is not a good practice.

## Solution
Use the input data on S3.

## Alternatives
None

## Related to
None

**Comment by climbfuji** [comment]
@MinsukJi-NOAA are you thinking of the S3 bucket I have maintained so far, or another one (either way is fine with me).

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA are you thinking of the S3 bucket I have maintained so far, or another one (either way is fine with me).

Yes, I was thinking of your S3 bucket for this purpose.

**Comment by junwang-noaa** [comment]
@MinsukJi-NOAA Is this still the plan to use s3 for CI testing?

**Comment by MinsukJi-NOAA** [comment]
@junwang-noaa There is no immediate plan for this. I think this issue can be closed for now -- maybe a new issue can be opened in the future as part of EPIC?

**Comment by junwang-noaa** [comment]
Thanks, I will close the issue. I agree EPIC may open an issue for further updates on CI test.
