### ISSUE TITLE
control_2threads test fails on Expanse

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#705]
## Description
2 threads runs fail with segfault on SDSC Expanse
Tried the following regression tests: control_2threads, cpld_2threads, cpld_bmark_wave_v16_p7b, control_2threads_debug

### To Reproduce (with the caveat that Expanse is not available for most people)
$ git clone --branch feature/expanse-develop --recurse-submodules https://github.com/MinsukJi-NOAA/ufs-weather-model
$ cd ufs-weather-model/tests
$ ./rt.sh -n control_2threads

## Additional context
#602 

## Output

```
munmap_chunk(): invalid pointer
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source     
fv3.exe            000000000945628B  Unknown               Unknown  Unknown
libpthread-2.28.s  0000155552677DC0  Unknown               Unknown  Unknown
libc-2.28.so       00001555520C18DF  gsignal               Unknown  Unknown
libc-2.28.so       00001555520ABCF5  abort                 Unknown  Unknown
libc-2.28.so       0000155552104C17  Unknown               Unknown  Unknown
libc-2.28.so       000015555210B53C  Unknown               Unknown  Unknown
libc-2.28.so       000015555210B804  Unknown               Unknown  Unknown
libucs.so.0.0.0    000015540B1D5E50  Unknown               Unknown  Unknown
libucs.so.0.0.0    000015540B1D6A51  Unknown               Unknown  Unknown
libucs.so.0.0.0    000015540B1C70F9  Unknown               Unknown  Unknown
libucs.so.0.0.0    000015540B1C7C3A  Unknown               Unknown  Unknown
libucs.so.0.0.0    000015540B1CA598  ucs_handle_error      Unknown  Unknown
libucs.so.0.0.0    000015540B1CA7CC  Unknown               Unknown  Unknown
libucs.so.0.0.0    000015540B1CA99A  Unknown               Unknown  Unknown
libpthread-2.28.s  0000155552677DC0  Unknown               Unknown  Unknown
fv3.exe            000000000943CBD8  Unknown               Unknown  Unknown
fv3.exe            000000000669C7B7  gfs_rrtmg_pre_mp_          19  GFS_rrtmg_pre.F90
fv3.exe            000000000615226C  ccpp_fv3_gfs_v16_         202  ccpp_FV3_GFS_v16_radiation_cap.F90
fv3.exe            00000000056F6AD1  ccpp_static_api_m         940  ccpp_static_api.F90
fv3.exe            00000000056E1942  ccpp_driver_mp_cc         192  CCPP_driver.F90
libiomp5.so        00001555548C8CC3  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        000015555484E283  Unknown               Unknown  Unknown
libiomp5.so        000015555484D24E  Unknown               Unknown  Unknown
libiomp5.so        00001555548C919C  Unknown               Unknown  Unknown
libpthread-2.28.s  000015555266D2DE  Unknown               Unknown  Unknown
libc-2.28.so       0000155552186133  clone                 Unknown  Unknown

```
Also, message such as:
```
[exp-7-44:16540:0:17160] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x155400f77000)
```

**Comment by climbfuji** [comment]
One of the variables passed to `GFS_rrrtmg_pre` seems to be not allocated or not allocated correctly.

Darn, I was planning on implementing a debugging feature to catch such kind of errors in the auto-generated cap before calling the schemes, per variable (so you know exactly which one it is). I am tempted to add this feature today/this weekend
because it will really help in this situation.

**Comment by junwang-noaa** [comment]
If I remember correctly, we are waiting for some code updates to fix rrtmgp
threading issue? The issue #553
<https://github.com/ufs-community/ufs-weather-model/issues/553> is still
open.

**Comment by climbfuji** [comment]
@junwang-noaa the issue you mentioned is for RRTMGP, @MinsukJi-NOAA was talking about control_2threads which uses RRTMG.

**Comment by benjamin-cash** [comment]
@junwang-noaa @climbfuji I am planning to make a set of P7 production runs on Expanse so it would be good to have this resolved if possible. I should be able to get developers access to the machine as part of our project if it would help speed things along.

**Comment by climbfuji** [comment]
@benjamin-cash Yes it would be good to have access to Expanse for debugging this issue.

**Comment by climbfuji** [comment]
@MinsukJi-NOAA Is this working now?

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA Is this working now?

@benjamin-cash could you confirm if you are using 2 threads on Expanse now?

**Comment by arunchawla-NOAA** [comment]
@benjamin-cash can you confirm if this is working for you ? In the meanwhile we will move this to the icebox

**Comment by benjamin-cash** [comment]
@arunchawla-NOAA - Unfortunately I can't, my account on Expanse has expired. :(

**Comment by arunchawla-NOAA** [comment]
ok we will close this ticket for now
