### ISSUE TITLE
Failed global-nesting forecast with latest ufs-weather-model develop branch

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#718]
## Description
The HAFS application level global-nesting regression tests failed with after syncing with the ufs-weather-model develop as of 07/23/2021. 
With some further tests with different recent commits of ufs-weather-model develop branch, it is identified that the PR #654 was the first version that failed the global-nesting forecast.
When using the ufs-weather-model PR592 version source code package (merged on 20210716), the global-nest forecast was able to run through, for example:
/scratch1/NCEPDEV/hwrf/scrub/Bin.Liu/hafs_sync_20210716_rt_globnest_static/2020082512/00L/forecast_ufs0716pr592
However, when using the PR654 version (merged on 20210716), the global-nest forecast cannot run through, for example:
/scratch1/NCEPDEV/hwrf/scrub/Bin.Liu/hafs_sync_20210716_rt_globnest_static/2020082512/00L/forecast_ufs0716pr654

### To Reproduce:
To repeat the failed test, you can do the following on Hera:
git clone https://github.com/ufs-community/ufs-weather-model.git ./
git checkout 6ccea3e
git submodule update --init --recursive
cd tests
./compile.sh "hera.intel" "-DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16 -D32BIT=ON" 32bit YES NO > & compile.log &
copy over the test dir
cp -rp /scratch1/NCEPDEV/hwrf/scrub/Bin.Liu/hafs_sync_20210716_rt_globnest_static/2020082512/00L/forecast_ufs0716pr654 ./
There is a jobcard to run the forecast (of course you can modify to use your new built forecast exe):
sbatch jobhafsforecast_globnest.sh

The same failure happen on Orion. Did not test on other platforms yet.

## Additional context
According to @junwang-noaa's suggestion, tried also to revert back to use an earlier version of GFDL_atmos_cubed_sphere (May 12th version):
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/commit/3720aeae54eeed54d4e8274756857542b3e5dccc
but the global-nesting forecast failed in the same way with the same error messages.

## Output
Here are the example run dir and log:
/scratch1/NCEPDEV/hwrf/scrub/Bin.Liu/hafs_sync_20210716_rt_globnest_static/2020082512/00L/forecast_ufs0716pr654/hafs_forecast.err
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
hafs_forecast.x    00000000039D06DC  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B510546B630  Unknown               Unknown  Unknown
hafs_forecast.x    0000000002F8AF77  fv_sat_adj_mp_wqs        1248  gfdl_fv_sat_adj.F90
hafs_forecast.x    0000000002F86F7E  fv_sat_adj_mp_fv_         658  gfdl_fv_sat_adj.F90
hafs_forecast.x    0000000002F83B5D  fv_sat_adj_mp_fv_         336  gfdl_fv_sat_adj.F90
hafs_forecast.x    0000000002E5F095  ccpp_fv3_gfs_v16_         164  ccpp_FV3_GFS_v16_fast_physics_cap.F90
hafs_forecast.x    0000000002D8B68D  ccpp_static_api_m         269  ccpp_static_api.F90
hafs_forecast.x    0000000001DC09CD  fv_mapz_mod_mp_la         842  fv_mapz.F90
libiomp5.so        00002B5103873A43  __kmp_invoke_micr     Unknown  Unknown

**Comment by BinLiu-NOAA** [comment]
@bensonr and @junwang-noaa, I tested with a newer version (09/09/2021) of ufs-weather-model under the HAFS application (which I believe uses new versions of FV3dycore and fms2_io). However, when using the 40x30 PE layout for the nested domain, it still failed in the same way as previously.  Using 30x40 PE layout for the nest worked fine (same as previously).

**Comment by bensonr** [comment]
@BinLiu-NOAA - what are the contents of your .bashrc file on hera?

**Comment by BinLiu-NOAA** [comment]
@bensonr, this happened on both Orion and Hera previously. Maybe also on other platforms.

Here are the related shrc file contents on Hera:
limit stacksize    unlimited
limit cputime      unlimited
limit filesize     unlimited
limit datasize     unlimited
limit memoryuse    unlimited
limit vmemoryuse   unlimited
limit descriptors  unlimited

and on Orion:
 ulimit -s 6000000


Bin

**Comment by bensonr** [comment]
@BinLiu-NOAA - thanks for that information.  Please add the following argument as srun may not propagate env vars by default "--export=OMP_STACKSIZE=1024M" and let me know if that helps.

**Comment by bensonr** [comment]
@BinLiu-NOAA upon further reading, it says it is supposed to be exporting them by default.  The reason I was going for limits and stacksizes is that sigsegvs during initialization are usually related to not having properly set/propagated these values.  For the shell 'limit/uilimit' commands, having them in the runscript isn't enough as they aren't properly propagated.

After looking at the code, I can conceive of one case where an FP operation could lead to an index bug here.  But it would require a temperature of less than 113K being fed into table lookup - which may not be considered physical.

**Comment by BinLiu-NOAA** [comment]
@bensonr, I reran the global-nesting forecast by using the 40x30PE (instead of 30x40PE) for the nested domain in the HAFS workflow (instead from a job card script) by using the 09/09/2021 version of ufs-weather-model. And it actually ran through and produced the byte-wise identical results to those from the 30x40PE configuration. So, I think this issue has been fixed with the newer version of Fv3dycore and/or FMS. I will close this bug report if there is no further comments. Thanks!

**Comment by bensonr** [comment]
@BinLiu-NOAA - Just want to make sure I understand the situation.  The failures in this ticket are related to the HAFS workflow/jobcard and not the model code itself.  The reproducibility issue in the nested system for different domain decompositions, being tracked on the UFS app and component spreadsheet, is no longer a concern as your testing has demonstrated b4b reproducibility for different layouts.

What about the b4b restart reproducibility for nests within the UFS - has that been solved/tested?

**Comment by BinLiu-NOAA** [comment]
@bensonr, to clarify, this bug/issue reported here in July always happen regardless workflow/jobcard scripts. And that's always repeatable back to then. Only for the test with the new version fv3dycore and fms (09/09/2021) I did yesterday through a jobcard, there was an issue in my jobcard, so you can just ignore that test. My second test did yesterday with the new version of fv3dycore and fms (09/09/2021) went through successfully. So, most likely the new version of fv3dycore or fms fixed the issue/bug reported here. But, again, I don't know what specific change(s) fixed this bug/issue reported here.

Regarding the b4b restart reproducibility for regional standalone (LAM) configuration within UFS, I am not sure who identified/reported that issue. Maybe @junwang-noaa or @BenjaminBlake-NOAA knows it, probably from the SRW application team. So, it's better to ask them to test the b4b restart reproducibility from their side.

Thanks!

Bin

**Comment by bensonr** [comment]
@BinLiu-NOAA - thanks for the clarification on what the tests prove.  If your issue is solved, then I think you can safely close this issue with the note it is fixed in X version use workflow Y.

**Comment by BinLiu-NOAA** [comment]
Closing issue #718, since it is no longer an issue with the ufs-weather-model develop (version of 09/09/2021 or later), which has the fv3dycore and fms updated recently.
