### ISSUE TITLE
Add documentation for HAFS HYCOM/WW3/CDEPS coupling related developments

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#735]
## Description

Since the HAFS HYCOM/WW3/CDEPS coupling related developments have been integrated back to ufs-weather-model develop branch through this PR #715, we need to update the ufs-weather-model documentation page:
[https://ufs-weather-model.readthedocs.io/en/latest/](https://ufs-weather-model.readthedocs.io/en/latest/)
The corresponding code for the documentation is under ufs-weather-model/doc/UsersGuide/source,
CodeOverview.rst   InputNML.inc  InputsOutputs.rst

## Solution
Add documentation for the HAFS HYCOM/WW3/CDEPS coupling related developments
Work ongoing in this feature branch:
https://github.com/hafs-community/ufs-weather-model/tree/feature/doc_hafs_hycom_docn

## Related to
- ufs-community/ufs-weather-model/pull/864

**Comment by junwang-noaa** [comment]
@BinLiu-NOAA Do you have any update on this?

**Comment by danrosen25** [comment]
Hi @junwang-noaa, I'm going to set aside some time to draft this with @uturuncoglu this week. Can you point me to a good template/sample?

**Comment by DeniseWorthen** [comment]
Hi Dan. If you could update section 4 (Inputs and Outputs) for HYCOM and then also add any updated/changed model configuration files are required that would be useful. We recognize that the structure of the document needs updating now that there are multiple coupled components (vs just the standalone) but getting the information entered is a first step.

**Comment by danrosen25** [comment]
I think you specifically mean editing this file with MarkDown, right?
[https://github.com/ufs-community/ufs-weather-model/blob/develop/doc/UsersGuide/source/InputsOutputs.rst](https://github.com/ufs-community/ufs-weather-model/blob/develop/doc/UsersGuide/source/InputsOutputs.rst)

**Comment by DeniseWorthen** [comment]
We actually need the file to be updated using RST so that we can host the documentation on RTD (read the docs).

**Comment by uturuncoglu** [comment]
@BinLiu-NOAA and @JessicaMeixner-NOAA I updated CDEPS documentation in the PR to reflect new global and regional datasets. I think WW3 part also needs to be updated but I have no detailed information about the used new grids and input files for the WW3 HAFS configuration. If you give more information about it while looking to the relevant section in the UFS documentation, I could also add it. Thanks.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA @BinLiu-NOAA Would you please add WW3 related documentation for WW3 HAFS configuration? Please let us know if you need more time, we can create a new issue for ww3 documentation for HAFS WW3 runs and commit PR#864 with HYCOM&CDEPS DOCN documentation, thanks.

**Comment by danrosen25** [comment]
Hi @junwang-noaa 
@JessicaMeixner-NOAA @aliabdolali @BinLiu-NOAA @uturuncoglu and I met this morning to discuss the documentation changes for WW3. We added changes for PR#864 and we are going to internally review them before we mark that PR ready (I converted it to a draft).

**Comment by junwang-noaa** [comment]
Thanks, Dan!

**Comment by danrosen25** [comment]
@junwang-noaa @BinLiu-NOAA 
We've updated documentation for HAFS HYCOM/WW3/CDEPS in PR #864, which is now ready.
