### ISSUE TITLE
Building and running the model on S4

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [ufs-community/ufs-weather-model#738]
## Description
To support development and data assimilation efforts, the UFS model should be ported to run on SSEC's S4 system.

## Solution
The machine-related scripts should be updated to include S4 and additional module files should be added to support S4 builds.

## Related to
Work is underway to port the entire global workflow: NOAA-EMC/global-workflow#138

**Comment by DavidHuber-NOAA** [comment]
I have completed the bulk of this work based on revision [9350745](https://github.com/ufs-community/ufs-weather-model/commit/9350745855aebe0790813e0ed2ba5ad680e3f75c).  S4 is only capable of supporting the workflow up to C384 resolution.  A test run has completed at C192/C96 resolution (running from 2020073118 through 2020081000) and both log files and data files are available on Orion:
logs - /work/noaa/nesdis-rdo2/dhuber/s4_logs/test_dev
comrot (for 2020081000 only) - /work/noaa/nesdis-rdo2/dhuber/s4_data/comrot/test_dev
archive - /work/noaa/nesdis-rdo2/dhuber/s4_data/archive/test_dev

A test run at C384/C192 resolution, from 2020073118 through 2020080400, is ongoing.  When complete, I will upload logs and data to Orion for review.

**Comment by DavidHuber-NOAA** [comment]
I've completed the test run and uploaded the log files to Orion:
logs - /work/noaa/nesdis-rdo2/dhuber/s4_logs/test_dev_384
comrot (for 2020081000 only) - /work/noaa/nesdis-rdo2/dhuber/s4_data/comrot/test_dev_384
archive - /work/noaa/nesdis-rdo2/dhuber/s4_data/archive/test_dev_384

@WenMeng-NOAA @JessicaMeixner-NOAA 
After this step, I pulled in the current develop branch and ported the regression tests to S4.  All of the tests complete successfully except control_atmwav, which fails with a 'double free or corruption' error:
```
147: *** Error in `/scratch/users/dhuber/FV3_RT/rt_99014/control_atmwav/./fv3.exe': double free or corruption (!prev): 0x000000000ebcad10 ***
146: *** Error in `/scratch/users/dhuber/FV3_RT/rt_99014/control_atmwav/./fv3.exe': corrupted size vs. prev_size: 0x000000000f9a5190 ***
```

I'm not sure what the issue with this test on S4 is.  I've uploaded the control_atmwav test folder to Hera (/scratch1/NESDIS/nesdis-rdo2/s4_data/FV3_RT/control_atmwav).  Would it be possible for someone to take a look at the test and advise on a solution?  Please let me know if you need any additional files uploaded.

**Comment by JessicaMeixner-NOAA** [comment]
@DavidHuber-NOAA I don't have access to /scratch1/NESDIS/nesdis-rdo2/s4_data/FV3_RT/control_atmwav but it's surprising to me if all the other tests run (such as the fully coupled S2SW tests) and this test fails.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA Apologies, the correct directory is /scratch1/NESDIS/nesdis-rdo2/David.Huber/s4_data/FV3_RT/control_atmwav.

**Comment by JessicaMeixner-NOAA** [comment]
@DavidHuber-NOAA I've looked at the run directory and to be honest I don't have any ideas of what went wrong or how to fix it.  The other tests using waves passed?

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA Yes, the other wave tests passed.  In fact, this is the only test of the 111 that ran that did not pass.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA Would it be helpful to upload one or more of the wave tests?

**Comment by JessicaMeixner-NOAA** [comment]
Sometimes errors that cannot otherwise be explained end up being memory issues, which seems unlikely given the output at the end of the job, but since I'm at a loss for other things maybe try to give it more memory?  I don't think another run directory will help, but thanks.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA Indeed, the test passes when run with `TPN=16` instead of 32.  Interestingly, the 1-min average memory usage for the job shows a maximum of 11% on one of the nodes.  Unfortunately, I cannot get any finer resolution than that.  Do you think it's fine to move on with this solution?

**Comment by JessicaMeixner-NOAA** [comment]
@DavidHuber-NOAA I'd make sure you also add threads to off-set the lower TPN, but otherwise I'd say it's not completely surprising that one of the waves tests needed more memory.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA Alright, I'll do that and continue with the port.  Thanks!
