### ISSUE TITLE
Coupling Thompson microphysics with MERRA2 aerosol dataset

### ISSUE THREAD

**Issue by AnningCheng-NOAA** [ufs-community/ufs-weather-model#750]
MERRA2 aerosol dataset is used to activate IN and CCN in Thompson microphysics. Results will be compared with Grell et al.'s approach, forecasting number concentration of ice friendly and liquid friendly aerosols and using sinks and sources embedded in Thompson microphysics by Thompson. Three pull requests will be put when passing regression tests.

**Comment by DeniseWorthen** [comment]
@AnningCheng-NOAA This issue is nearly a year old. Has it been resolved?

**Comment by AnningCheng-NOAA** [comment]
The issue was closed by Jun a few months ago due to staying in the queue
for too long.  I will submit a new PR in a few weeks when I get some time
to work on it.
