### ISSUE TITLE
Make RT restart test setup more consistent

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#754]
## Description
Setting up restart tests is not consistent for different tests and applications. By making it more consistent, it will be easier to set up and run restart tests for those tests that are currently without one (e.g. via utest script for reproducibility check).

## Solution
Make the setup of environment variables, fv3_conf file, test file, etc. more consistent.

## Alternatives
Leave as they are.

## Related to
N/A

**Comment by MinsukJi-NOAA** [comment]
Consider the following hypothetical case:
SYEAR=2013
SMONTH=04
SDAY=01
SHOUR=02

Control runs for 9 hrs. Restart is after 3 hours, and runs for 6 hours. Comparison between control and restart is made after 9 houurs. In this case, do these make sense @DeniseWorthen ? I am a little confused about RESTART_N and FHZERO as they are not explained in the RTD pages; how are they calculated?

FHMAX = 9
FHROT = 3
RESTART_N = 3 (same as fhrot) ?
RESTART_INTERVAL = "3 -1"
OUTPUT_FH = "3 -1"
FHZERO = 3 ?
RESTART_FILE_PREFIX=20130401.050000 ?
RESTART_FILE_SUFFIX_HRS=2013-04-01-05?
RESTART_FILE_SUFFIX_SECS=2013-04-01-18000?

**Comment by DeniseWorthen** [comment]
FHZERO is used internally by ATM for when to zero out accumulated fields. So to compare a 9hour run vs a 6hour run (3+6), you need the forecast fields zero'd consistently. 

The ATM model uses FHROT and FHMAX to set the number of hours to integrate on restart. When we do a restart test, the starting time (day+hour) is the same as the control run but FHROT specifies how far advanced you are (in hours) from that start time. RESTART_INTERVAL specifies how often the ATM will write a restart file. 

CMEPS doesn't have any equivalent concept of internally adjusting the integration length. We just specify the actual number of hours to integrate. We calculate that as RESTART_N=FHMAX-FHROT; that is the number of hours CMEPS will run before CMEPS (and CICE and MOM6) write a restart file. 

RESTART_N functions the same way RESTART_INTERVAL does for FV3. It is the restart writing frequency. In our cpld_bmark_v16 test, the RESTART_N is set at 3. We could use 6 instead I think.

There is another use of RESTART_N in the ICE configuration. That isn't associated with restarting, it is used by CICE to report internal timings. We could set it independently from the restart configuration. Setting it to RESTART_N just means that it will report timings over the entire length of the integration.

**Comment by MinsukJi-NOAA** [comment]
Closing. It will be reopened if necessary.
