### ISSUE TITLE
CA fails debug mode with GNU compiler

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#770]
## Description
The coupled RTs are tested with GNU on both Hera and Cheyenne. The cpld_control_p7 test from PR [765](https://github.com/ufs-community/ufs-weather-model/pull/765) fails in debug mode with GNU. This seems to be a known issue, since in rt_gnu.conf, the test is commented out with a note that # Both stochy and ca debug tests crash with GNU. 

For the coupled P7 tests to include CA, this will need to be addressed.

### To Reproduce:

Tested on hera.gnu. Compile the cpld_control_p7 test in debug mode for GNU. The run fails with ``Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.``  and the err log points here:

```
 68: #0  0x2b42939e73ff in ???
 70: #0  0x2aba00fa13ff in ???
125: #1  0x21ca6d4 in __update_ca_MOD_update_cells_sgs
125:    at /scratch2/NCEPDEV/climate/Denise.Worthen/WORK/ufs_cpldv16_gnu/stochastic_physics/update_ca.F90:249
 71: #0  0x2b9d3a2ab3ff in ???
 72: #0  0x2ad2d44333ff in ???
```

Line 249 is:

```
 else
    ! don't rely on compiler to truncate integer(8) to integer(4) on
    ! overflow, do wrap around explicitly.
    count4 = mod(kstep + mype + iseed_ca + 2147483648, 4294967296) - 2147483648
 endif
```

**Comment by DeniseWorthen** [comment]
@lisa-bengtsson

**Comment by lisa-bengtsson** [comment]
Hi @DeniseWorthen I recall this issue from Dom's test. It seems the gnu compiler doesn't like this arithmetic. We are updating this line in the new PR that addresses MPI reproducibility, and will ensure the gnu debug test works in this update.

**Comment by DeniseWorthen** [comment]
@lisa-bengtsson I expected that to be the case, but I wanted to make sure that since you were changing the code for MPI reproducibility that this issue didn't get overlooked.

**Comment by lisa-bengtsson** [comment]
I'm on it!
