### ISSUE TITLE
update fms lib on hera to use the version installed with avx

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#777]
## Description
When the FMS was moved out of ufs-weather-model repository, the compile options to build fms library should be the same as the fms was built inside ufs-weather-model. The avx compile option was missed on hera. This needs to be fixed.

With the FMS library built with avx, the MOM6 results will change. This change as impact on all the regression test with mom6. New baseline needs to be created. There is no impact on all other platforms.

**Comment by arunchawla-NOAA** [comment]
was this resolved ?

**Comment by climbfuji** [comment]
Closed via #778
