### ISSUE TITLE
Executable should use ESMF static library

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#78]
The default behavior of the ufs-weather-model build is to link against the dynamic ESMF library if found. This causes problems on systems like orion. Even though this is a bug on orion and not in the ESMF library, it would be safer if we could link against the static ESMF library by default and make the dynamic ESMF library a fallback option.

**Comment by DusanJovic-NOAA** [comment]
@climbfuji Are there any changes need to fix this?

**Comment by climbfuji** [comment]
> @climbfuji Are there any changes need to fix this?

This is an old issue that never got addressed, will need to go back and look at the current FindESMF.cmake. Maybe it solved itself by now.

**Comment by climbfuji** [comment]
It seems we fixed this in July as part of your "imported targets" commit, see https://github.com/ufs-community/ufs-weather-model/blob/f3db58eca511175ec1813895f1f0a2b25415f0f3/cmake/FindESMF.cmake#L83 and https://github.com/ufs-community/ufs-weather-model/pull/172/files#diff-4c909119d56908050b315d340567c7fc.

**Comment by junwang-noaa** [comment]
Thanks Dom for the update, will close the issue.
