### ISSUE TITLE
Prepare read the docs documentation on automated testing

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#793]
## Description

Include a section in the read the docs documentation on automated testing.

**Comment by MinsukJi-NOAA** [comment]
Section 5 will be used for CI/CD and auto RT.

![rtd-automated-testing](https://user-images.githubusercontent.com/57227195/132892080-da78d119-8cb6-4c03-8cf3-c698281f5383.png)

**Comment by MinsukJi-NOAA** [comment]
@BrianCurtis-NOAA, this is my branch: https://github.com/MinsukJi-NOAA/ufs-weather-model/tree/feature/auto-test-doc. Currently, Auto RT is section 5.2. Please let me know if this works for you.

**Comment by BrianCurtis-NOAA** [comment]
@MinsukJi-NOAA I've pasted you the AutoRT documentation.

**Comment by MinsukJi-NOAA** [comment]
Issue completed via #794.
