### ISSUE TITLE
GOCART configuration documentation 

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#795]
## Description
Aerosol component GOCART was integrated in UFS in [PR#591 ](https://github.com/ufs-community/ufs-weather-model/pull/591), but GOCART configuration documentation is missing at the ufs-weather-model [documentation page]( https://ufs-weather-model.readthedocs.io/en/latest/InputsOutputs.html#gocart). 

## Solution
Add GOCART configuration information in ufs-weather-model documentation.

## Related to
ufs-weather-model PR will come up later.

**Comment by lipan-NOAA** [comment]
@junwang-noaa [PR#1182](https://github.com/ufs-community/ufs-weather-model/pull/1182) was created
