### ISSUE TITLE
use role account on orion

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#799]
## Description
The role account is now available on orion. The RT needs to use this role account, instead a personal account with group access. 

## Solution
Update RT script to use role-nems account for baseline, input data directory, and autoRT will be changed to run from role-nems.

## Related to
PR will be submitted when the work is done.

**Comment by BrianCurtis-NOAA** [comment]
Are we moving the emc.nemspara directory contents into /work/noaa/nems/role-nems/ ? i.e. the miniconda python installation?

**Comment by junwang-noaa** [comment]
Yes, all the software needs to be moved to role-nems.

**Comment by junwang-noaa** [comment]
An update on role account on orion. From orion admin: Per Orion security policy, there should only be one role account per project, this policy has been reimplemented with the removal of role-nems from stmp. 
Basically role-nems can't write to stmp on orion. Because of that we may not be able to run auto RT using role-nems account.

**Comment by climbfuji** [comment]
@junwang-noaa I think this issue can be closed, since we now have a role account on orion.

**Comment by junwang-noaa** [comment]
Close issue
