### ISSUE TITLE
How to get FV3, FMS, etc after the initial clone

### ISSUE THREAD

**Issue by aoloso** [ufs-community/ufs-weather-model#8]
Should

git submodule update --init --recursive

be added somewhere in the instructions so all relevant code could be downloaded?

**Comment by junwang-noaa** [comment]
It is on the wiki:

https://github.com/ufs-community/ufs-weather-model/wiki

**Comment by junwang-noaa** [comment]
@aoloso  Please let us know if you have further questions on this issue. Thanks.

**Comment by junwang-noaa** [comment]
Did not hear from aoloso for a month, close the issue.
