### ISSUE TITLE
Port GFS v16 to WCOSS2

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#806]
Operational version of ufs-weather-model, at this moment tag [GFS.v16.0.16](https://github.com/ufs-community/ufs-weather-model/releases/tag/GFS.v16.0.16), must be ported to WCOSS2.

This branch, https://github.com/DusanJovic-NOAA/ufs-weather-model/tree/gfs_v16.0.16_on_cactus_dogwood, contains necessary updates for WCOSS2 (Cactus/Dogwood).

To build it on Cactus run:
```
$  git clone --recursive --branch gfs_v16.0.16_on_cactus_dogwood https://github.com/DusanJovic-NOAA/ufs-weather-model
$  cd ufs-weather-model/tests
$  ./compile.sh $(pwd)/../FV3 wcoss2 "WW3=Y 32BIT=Y" 1
```

**Comment by WenMeng-NOAA** [comment]
The official upp lib for GFSV16 inline post is not installed on wcoss2 yet.
To test GFSV16 inline post on Cactus, user may add changes in their ufs-weather-model version for upp/8.0.11  as:
In modulefiles/wcoss_phase2/fv3:
change
  module load upp/10.0.4
into
  module use /u/Wen.Meng/noscrub/ncep_post/LIBS/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.4
  module load upp/8.0.11

**Comment by arunchawla-NOAA** [comment]
@DusanJovic-NOAA are we still keeping this issue open ? The model is running as part of GFS. There may be small updates but the majority of the work is done right ?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA are we still keeping this issue open ? The model is running as part of GFS. There may be small updates but the majority of the work is done right ?

This issue is mentioned in https://github.com/NOAA-EMC/global-workflow/issues/398 which is still open.

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA Since the GFSv16 model code is ported to wcoss2, let's close the issue. If there is any problem with workflow, we will open a new issue.
