### ISSUE TITLE
cpld_bmark_v16 regression test ice_in inconsistency

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-weather-model#815]
## Description
When cpld_bmark_v16 regression test runs, the block_size_y seems incorrect.
```
    nprocs            = 48
    nx_global         = 1440
    ny_global         = 1080
    block_size_x      = 60
    block_size_y      = 160 
```
Shouldn't block_size_y be 540?

Nevertheless, the simulation completes successfully.

### To Reproduce:
```
$ git clone --recurse-submodules https://github.com/ufs-community/ufs-weather-model
$ cd ufs-weather-model/tests
$ ./rt.sh -n cpld_bmark_v16 -k >out 2>&1 &
```
Go to ``$RUNDIR`` and take a look at lines 158 to 162 of ``ice_in``

**Comment by DeniseWorthen** [comment]
Yes, of course. Good catch.  I'm amazed it ran and reproduced. Previously using edit.inputs, only the nproc needed to be changed if the default was changed. When I switched to atparse, I need to also export a new ``np2`` and then a new ``BLCKX`` and ``BLCKY`` values when these are changed from the defaults. Does that seem right?

**Comment by MinsukJi-NOAA** [comment]
I see that ``tests/tests/cpld_bmark_v16`` has ``export_cpl``. Also that ``ice_in_template`` has ``BLCKX`` and ``BLCKY``: looks like they should work -- a little confused now.

**Comment by MinsukJi-NOAA** [comment]
FYI, block_size_y is correct here: ``/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/REST_V16``

**Comment by DeniseWorthen** [comment]
Yes, I made that sandbox prior to the atparse commit I believe. 

Since we're using slenderx2, the Y-dimension should be split in 2; the X-dimension gets 1/2 of the total number of procs. After the atparse commit, for test where we've change ``NPROC_ICE``,  the test needs to have these lines added:

```
export np2=`expr $NPROC_ICE / 2`
export BLCKX=`expr $NX_GLB / $np2`
export BLCKY=`expr $NY_GLB / 2`
```

**Comment by MinsukJi-NOAA** [comment]
> Yes, I made that sandbox prior to the atparse commit I believe.
> 
> Since we're using slenderx2, the Y-dimension should be split in 2; the X-dimension gets 1/2 of the total number of procs. After the atparse commit, for test where we've change `NPROC_ICE`, the test needs to have these lines added:
> 
> ```
> export np2=`expr $NPROC_ICE / 2`
> export BLCKX=`expr $NX_GLB / $np2`
> export BLCKY=`expr $NY_GLB / 2`
> ```

That makes sense.

**Comment by MinsukJi-NOAA** [comment]
Will this require input data change?

**Comment by DeniseWorthen** [comment]
no
