### ISSUE TITLE
Add control_p7 test

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#817]
## Description

We need a test for the standalone ATM which combines physics features planned for the coupled prototypes. This will allow the features to be tested for decomp, threading, restart, debug and reproducibility prior to being implemented in the coupled model.

## Solution

Add a test for ``APP=ATM`` using the P7 configuration.

## Related to

Issue #766

**Comment by junwang-noaa** [comment]
Could we use the coupled fractional grid ICs for this test? Basically it
uses the coupled executable compiled with the standalone suite file.

**Comment by DeniseWorthen** [comment]
The test I built uses the same initial conditions that the control test (``FV3_input_data/INPUT_L127``) uses. It have tested it with both frac_grid both on and off and it runs w/ either. I'm not 100% which we should be using though. 

I built a ``FV3_GFS_v16_nsstNoahmpUGWPv1`` suite from the coupled version by removing the call to sfc_cice. I'm not sure that is all I need to do.
