### ISSUE TITLE
Optimization/tuning of cellular automata scheme across resolutions

### ISSUE THREAD

**Issue by lisa-bengtsson** [ufs-community/ufs-weather-model#818]
## Description
The CA scheme does not scale well across resolutions. The impact is currently larger in C768 than C384 and coarser.

**Comment by lisa-bengtsson** [comment]
@junwang-noaa @DeniseWorthen 

Is it OK that I update the namelist parameters with this PR for P8? In addition to a model tag, is there a global workflow tag that goes with P7, so that P7 could still be ran even after I update the code and namelist associated with the CA?

**Comment by junwang-noaa** [comment]
Currently we are waiting for the ww3 issues to be fixed for P7 regression tests. We plan to create a model tag after that. My understanding is that global_workflow P7 is using the feature/coupled-crow workflow branch with revision ac39d00, and it is pointing to model revision b26a896. So the P7 will still run with these revisions after you update the code and namelist, unless someone updates the feature/coupled-crow workflow branch to point to the new revisions associated with your updates.

**Comment by junwang-noaa** [comment]
The code was merged in PR#896.
