### ISSUE TITLE
fix the filename for non-integer output frequency

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#826]
## Description
It was found that the filename does not reflect the correct output time when the non-integer output frequency is used. This is true for both model history files and post process files from inline post.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. checkout ufs-weather-model
2. just run control test: cd ufs-weather-model/tests; rt.sh -n "control"
3. in the control run directory, change the line of output_fh: in model_configure
 output_fh: 0.4 -1
4. run the test by: sbatch job_card
5. the results show the history files at non-integer forecast hours are missing

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA do we need any changes in post to get full time stamp (e.g. fhour-fhmin-fsec) in the post output file names?

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa Let me look into the UPP code and get back to you later.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa The changes might be needed in UPP routine get_postfilename.f 
https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/get_postfilename.f#L102
How do you like to change model history file  and post output file naming conventions?

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA Currently model history file names with full time stamp are using 3 digits for hours, 2 digits for minutes and 2 digits for seconds. E.g.:
atmf000-12-00.nc
atmf001-12-00.nc
sfcf000-12-00.nc
sfcf001-12-00.nc

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I will test the changes in UPP code.

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA The issue with model history file names was fixed and committed to ufs-weather-model repository. Do you want me to create an issue at UPP repo? So once UPP has this issue fixed, we will update ufs to use the UPP lib with the fix.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa Yes, please open an issue in UPP repos..

**Comment by junwang-noaa** [comment]
Post issue [#401](https://github.com/NOAA-EMC/UPP/issues/401) was created. I will close this issue.
