### ISSUE TITLE
ufs rt.sh in wcoss-dell-p3

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#834]
the total disk usage for rt.sh is ~1.5T. When running on P3, we always encounter disk full issue even though my disk usage on ptmp or stmp is almost zero except for those from rt.sh. I wonder whether there is a hard limit setup from SA side on this.

**Comment by junwang-noaa** [comment]
Thanks for creating the issue. I am making some changes to reduce the output frequency to reduce total disk space.

**Comment by jiandewang** [comment]
I think cpld benchmark runs are the guys that use a lot of disk

**Comment by junwang-noaa** [comment]
Here are some tests taking lots of space:

131694687       ./cpld_bmark_v16

132167775       ./cpld_bmark_v16_nsst

101847448       ./cpld_bmark_wave_v16_p7b

86615924 ./cpld_bmark_wave_v16

154701393       ./control_c384

66974769        ./control_c384gdas

81915487        ./cpld_control_c384

**Comment by junwang-noaa** [comment]
@jiandewang we removed some tests, please check if the disk space is reduced with the latest develop branch

**Comment by jiandewang** [comment]
@junwang-noaa I ran the whole set of current rt.conf, total disk usage dropped to 1.2T, it was 1.5T before.

**Comment by junwang-noaa** [comment]
Was the RT finished successfully? If yes, can we close this issue?

**Comment by jiandewang** [comment]
my last job failed due to time out reason, no disk quota exceed warning in all runs, so I think you can close this issue now.
