### ISSUE TITLE
Remove DATM and related files

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-weather-model#839]
## Description
The CDEPS has been integrated into the UFS. The DATM submodule and related files can be removed.

## Solution
The DATM submodule and related tests will be removed. Scripts and configuration files related to DATM tests will also be removed.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related.

**Comment by DeniseWorthen** [comment]
@binli2337 Would you please close Issue #565  if it is a duplicate issue?
