### ISSUE TITLE
Fix regression tests on S4

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [ufs-community/ufs-weather-model#842]
## Description
Five regression tests are failing on S4 as the `compare_ncfile.py` script is failing to load the `netcdf` module.  This is because the netcdf module is not included in the miniconda distribution that is loaded with `ecflow`.  The tests that fail are `control_fhzer`, `control_wrtGauss_netcdf_parallel`, `regional_quilt_netcdf_parallel`, `control_wrtGauss_netcdf_parallel_debug`, and `hafs_regional_atm`.

### To Reproduce:
After creating a baseline, rerun the regression tests on S4.

## Solution
Load the `miniconda/3.8-s4` module after loading `ecflow` in `rt.sh` so `compare_ncfile.nc` can load `netcdf`.

**Comment by junwang-noaa** [comment]
Code was committed, close issue.
