### ISSUE TITLE
missing baseline directory on wcoss dell-p3

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#867]
## Description
Provide a clear and concise description of what the bug is.
Also give a description of what behavior you expected to happen.
current ufs baseline is stamped as "develop-20211006" but this directory doesn't exist on dell-P3

### To Reproduce:
ls -l /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/RT/NEMSfv3gfs/, you will only have

drwxr-sr-x 94 emc.nemspara emcmodel 8192 Sep  1 22:02 develop-20210901
drwxr-sr-x 95 emc.nemspara emcmodel 8192 Sep  8 07:43 develop-20210907
drwxr-xr-x 95 emc.nemspara emcmodel 8192 Sep 15 19:02 develop-20210915
drwxr-sr-x 95 emc.nemspara emcmodel 8192 Sep 26 21:02 develop-20210924
drwxr-sr-x 95 emc.nemspara emcmodel 8192 Sep 26 15:10 develop-20210924.a
drwxr-xr-x 95 emc.nemspara emcmodel 8192 Sep 28 18:21 develop-20210928
drwxr-xr-x 96 emc.nemspara emcmodel 8192 Sep 30 05:18 develop-20210929
drwxr-xr-x 75 emc.nemspara emcmodel 4096 Sep 30 20:15 develop-20210930
drwxr-xr-x 75 emc.nemspara emcmodel 4096 Oct  1 16:07 develop-20211004

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

**Comment by DeniseWorthen** [comment]
@jiandewang  Please see this note on the relevant PR #820

```
[n/a] wcoss_dell_p3 - skip this time due to ongoing network hardware issues
```
