### ISSUE TITLE
Provide option to compile all available CCPP suites into the executable

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#87]
Similar to what DTC did for the single column model, we should provide an option/mechanism to simply compile all available suites into the executable.

My suggestion would be - once the dynamic build has been removed and the static build is the only option - that the SUITES=... argument becomes optional. If it is not provided, grab all suites from FV3/ccpp/suites/ and compile them into the executable.

**Comment by junwang-noaa** [comment]
That sounds good, so we need to remove dynamic build first.

**Comment by climbfuji** [comment]
Next on my list!

**Comment by climbfuji** [comment]
Merged with https://github.com/ufs-community/ufs-weather-model/pull/126
