### ISSUE TITLE
radiation_aerosols error when running with suite_FV3_GFS_v15_thompson_mynn.xml.

### ISSUE THREAD

**Issue by nickcctong** [ufs-community/ufs-weather-model#88]
I'm using a non-NOAA machine for running this latest version of SAR-FV3 codes.
I kept running into this error:
**!!! (1) Error in subr radiation_aerosols: unrealistic surface pressure =
           1                     NaN**
, that causes the model abort.
I noticed that under /tests/ in the **rt_wcoss_cray.conf** file, a comment is put by someone that looks quite relevant to this issue I met. As it states that **the issue can be avoided in PROD mode**, 
can someone help explain what does this mean?
I have tried either setting REPRO=N, or simply omitted the REPRO option in my compilation, but none of them fixed my problem.
Many thanks!

**Comment by junwang-noaa** [comment]
@nickcctong May I ask if you still have problem running SAR-FV3? If you do, please write down the steps on how to reproduce your failed case

**Comment by climbfuji** [comment]
We haven't heard back for more than a month - close?

**Comment by climbfuji** [comment]
@ericaligo-NOAA you just reported the same error for your regional restart runs, correct?

**Comment by ericaligo-NOAA** [comment]
Yes, I believe so.

**Comment by BrianCurtis-NOAA** [comment]
@climbfuji 
@ericaligo-NOAA

Has this been resolved?

**Comment by junwang-noaa** [comment]
@climbfuji @ericaligo-NOAA Is this issue resolved?

**Comment by ericaligo-NOAA** [comment]
I have not been encountering this issue lately.

**Comment by arunchawla-NOAA** [comment]
@junwang-noaa I suggest closing this issue as no further errors have been encountered
