### ISSUE TITLE
Correct regional regression tests

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [ufs-community/ufs-weather-model#881]
## Description
Regional regression tests were not testing functionality correctly. There was issue with variable TREF (nstf_name values) which caused restart not to reproduce results.

## Solution
I plan on restructuring regional regression tests. I'll put correct values for nstf_name variable,

## Related to
This will fix the bug #408

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA I run the regional_quilt test (nstf_name='1,1,1,0,5') and then a restart run from that (nstf_name='2,0,0,0,0' along with other warm start settings), but it looks to me the regional_quilt_restart can't reproduce the results from regionl_quilt. Can you take a look if the configuration is correct? Thanks
control run:  /scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_24336/regional_quilt
restart run:  /scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_24336/regional_quilt_restart

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA I run the regional_quilt test (nstf_name='1,1,1,0,5') and then a restart run from that (nstf_name='2,0,0,0,0' along with other warm start settings), but it looks to me the regional_quilt_restart can't reproduce the results from regionl_quilt. Can you take a look if the configuration is correct? Thanks control run: /scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_24336/regional_quilt restart run: /scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_24336/regional_quilt_restart

Jun, you still have old nstf_name in original:
#> grep nstf_name /scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_24336/regional_quilt*/inp*
/scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_24336/regional_quilt/input.nml:       nstf_name      = 1,1,1,0,5
/scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_24336/regional_quilt_restart/input.nml:       nstf_name      = 2,0,0,0,0

In my branch that is fixed:
https://github.com/RatkoVasic-NOAA/ufs-weather-model/tree/debug_RT

I renamed regional tests and now I just need to create new test for restart.

**Comment by RatkoVasic-NOAA** [comment]
Changes committed in PR #918
