### ISSUE TITLE
Module file load failing on Hera due to module version of bacio and w3nco

### ISSUE THREAD

**Issue by LarissaReames** [ufs-community/ufs-weather-model#882]
## Description
When attempting to load ufs_hera.intel on Hera, the load fails on bacio and w3nco. @JeffBeck-NOAA experienced similar issues with the Hera Intel module file in the SRW App. His PR for that is [here](https://github.com/ufs-community/ufs-srweather-app/pull/186/)

### To Reproduce:
Intel compiler on hera, modules loaded using ufs_hera.intel

## Additional context
When I copied the contents of the ufs_common module file in to the ufs_hera.intel module file and removed the specific version numbers for the bacio and w3nco libraries, I successfully loaded the module file and successfully compiled ATM using build.sh. 

## Output

Problem:
```
Lmod has detected the following error:  Cannot load module "upp/10.0.9" without these module(s) loaded:
   bacio w3nco

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    upp/10.0.9       /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/18.0.5.274/impi/2018.0.4/upp/10.0.9.lua
    ufs_hera.intel   /scratch1/BMC/gsd-fv3/Larissa.Reames/ufs-weather-model-develop/modulefiles/ufs_hera.intel
```

My Solution:  Make the following change to ufs_hera.intel
```
#module load ufs_common
module load jasper/2.0.22
module load zlib/1.2.11
module load png/1.6.35
module load hdf5/1.10.6
module load netcdf/4.7.4
module load pio/2.5.2
module load esmf/8_2_0_beta_snapshot_14
module load fms/2021.03
module load bacio
module load crtm/2.3.0
module load g2/3.4.2
module load g2tmpl/1.10.0
module load ip/3.3.3
module load sp/2.3.3
module load w3nco
module load upp/10.0.9
```

**Comment by junwang-noaa** [comment]
@LarissaReames-NOAA Thanks for reporting the issue. Can you list the steps how you built the ufs-weather-model? I don't see compile issue in Jeff's PR in which he adds new libraries in the srw app, I don't think the ufs-weather-model requires those new libraries.

**Comment by LarissaReames** [comment]
> @LarissaReames-NOAA Thanks for reporting the issue. Can you list the steps how you built the ufs-weather-model? I don't see compile issue in Jeff's PR in which he adds new libraries in the srw app, I don't think the ufs-weather-model requires those new libraries. 

Hi Jun, I actually mis-titled the PR. I never got to the build because the module load was failing. I've fixed the title now to be more accurate.

**Comment by WeiguoWang-NOAA** [comment]
We got the same errors on Orion. All hafs runs stopped. Not sure why.

**Comment by junwang-noaa** [comment]
The issue may be related to your own environment. I have no issue loading the hera and orion module files. Here is what I got on hera and orion:

on hera:
[Jun.Wang@hfe05 ufs-weather-model]$ module use modulefiles
[Jun.Wang@hfe05 ufs-weather-model]$ module load ufs_hera.intel

The following have been reloaded with a version change:
  1) netcdf/4.7.0 => netcdf/4.7.4

[Jun.Wang@hfe05 ufs-weather-model]$

on orion:
Orion-login-3[12] junwang$ module use modulefiles
Orion-login-3[13] junwang$ module load ufs_orion.intel
Orion-login-3[14] junwang$

**Comment by WeiguoWang-NOAA** [comment]
No errors on/before Monday morning  (Orion).   Then we got errors starting in the afternoon. 

for example, rocoto commands run OK from terminals. But failed in the workflow (modules cannot be loaded).

**Comment by junwang-noaa** [comment]
@WeiguoWang-NOAA Model ran OK on Orion yesterday after orion PM. Please see the orion regression test log file:

https://github.com/ufs-community/ufs-weather-model/pull/821/files#diff-b10d348c8d23d360e998553e1464ec009d4de67af63ac7422657d925c3526af0R1

Maybe you need to submit a ticket to workflow?

**Comment by pjpegion** [comment]
@junwang-noaa @lisa-bengtsson I believe that Lisa is also having similar problems with running an older version of the model. We  must have the ability to run older versions of the models on the research computers.

**Comment by WeiguoWang-NOAA** [comment]
FYI.  Jobs can be run on Orion/Hera now.  Not sure what has happened.

**Comment by JeffBeck-NOAA** [comment]
@WeiguoWang-NOAA, it looks like RDHPCS admins added an automatic update for w3emc that solves the problem:

The following have been reloaded with a version change:
  1) w3emc/2.7.3 => w3emc/2.9.0

**Comment by LarissaReames** [comment]
> @WeiguoWang-NOAA, it looks like RDHPCS admins added an automatic update for w3emc that solves the problem:
> 
> The following have been reloaded with a version change:
> 
> 1. w3emc/2.7.3 => w3emc/2.9.0

Yep, they did an under-the-hood fix and it looks like this problem is now solved for everyone. Going to close the issue.
