### ISSUE TITLE
Compiling all CCPP suites fails with the Intel compiler, always successful with GNU

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#898]
## Description

Compiling all (or a certain number of) CCPP suites with Intel into the executable causes the compilation to about with an internal compiler error. For each version of the code, this happens above a certain number of CCPP suites, therefore the need to compile multiple versions of the code for regression testing. This also happens on all machines with different versions of the Intel compiler, from 18.0.5 (Hera, Jet, ...) to 2021.2.0 (Cheyenne).

Notes:
- This happens with both DEBUG and PROD flags.
- I tested the option `-qoverride-limits`, this did not help.
- I could **not** reproduce the problem on Intel's development cluster Endeavor using the latest version Intel 2021.4.0. I don't know if this is because of the compiler version or the machine.
- The problem does not and has never occurred with GNU.

### To Reproduce:
- clone the latest developmental code on any tier 1 system
- compile
```
./compile.sh machine.intel '-DAPP=ATM -DDEBUG=[ON|OFF]'
```

**Comment by climbfuji** [comment]
Update @DusanJovic-NOAA. As the text above says, I could not reproduce the problem with Intel oneAPI 2021.4.0 (using the classic compilers `icc`, `ifort`, ...) on Endeavor. To check if this is machine specific, I installed Intel oneAPI 2021.5.0 (latest release at that time) on Hera, built hpc-stack with it, and tried to compile the model. The compile job
```
./compile.sh hera.intel '-DAPP=ATM -DDEBUG=ON' '' NO NO 2>&1 | tee compile.log
```
succeeded, but the PROD version (`-DDEBUG=OFF`) aborted with
```
/scratch1/BMC/gsd-hpcs/Dom.Heinzeller/ufs-weather-model-intel-oneapi-2022.1.1-20220116/FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90(475): catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
Using 8-byte addressing
Using pure routines.
Using allocatable derived type array members.
Using cray pointers.
compilation aborted for /scratch1/BMC/gsd-hpcs/Dom.Heinzeller/ufs-weather-model-intel-oneapi-2022.1.1-20220116/FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90 (code 1)
make[2]: *** [FV3/atmos_cubed_sphere/CMakeFiles/fv3.dir/driver/fvGFS/atmosphere.F90.o] Error 1
make[2]: Leaving directory `/scratch1/BMC/gsd-hpcs/Dom.Heinzeller/ufs-weather-model-intel-oneapi-2022.1.1-20220116/tests/build_fv3'
make[1]: *** [FV3/atmos_cubed_sphere/CMakeFiles/fv3.dir/all] Error 2
make[1]: Leaving directory `/scratch1/BMC/gsd-hpcs/Dom.Heinzeller/ufs-weather-model-intel-oneapi-2022.1.1-20220116/tests/build_fv3'
make: *** [all] Error 2
Dom.Heinzeller@hfe06:/scratch1/BMC/gsd-hpcs/Dom.Heinzeller/ufs-weather-model-intel-oneapi-2022.1.1-20220116/tests [intel|gsd-hpcs]>
```
I added `-qoverride-limits` to both the C and Fortran flags, but that didn't help either. In short, it looks like the problem is still there, and as random as before.

**Comment by junwang-noaa** [comment]
@climbfuji Is this issue resolved?

**Comment by climbfuji** [comment]
No, this is still an issue.

**Comment by junwang-noaa** [comment]
@climbfuji Did you test the case after the new compile options from PR#1171?

**Comment by climbfuji** [comment]
> @climbfuji Did you test the case after the new compile options from PR#1171?

No, I didn't.

**Comment by junwang-noaa** [comment]
@climbfuji  Also the Intel compiler is now updated to 2021/2022. maybe give a try on hera.

**Comment by climbfuji** [comment]
> @climbfuji Also the Intel compiler is now updated to 2021/2022. maybe give a try on hera.

Sure, we'll have to make sure it works on all platforms, though.

**Comment by climbfuji** [comment]
@junwang-noaa FYI https://github.com/ufs-community/ufs-weather-model/pull/1230. So far the Intel tests passed on hera, cheyenne, orion, jet - still waiting on gaea (first attempt failed, trying again). One would also have to test manually on wcoss and wcoss2.
