### ISSUE TITLE
Coupled model fails with FSICS=0, FSICL=0

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#920]
## Description
When preparing for p7.2, we found that if you turn on FSICS=0, FSICL=0 5 cases out of 8 would fail.  This is not encountered when running atmosphere-only.  

### To Reproduce:
What compilers/machines are you seeing this with? On hera and orion 
Give explicit steps to reproduce the behavior.
1. Run the global-workflow feature/coupled-crow branch with IC dates: 2012-01-01 2012-04-01 2012-10-01 2013-01-01 or 2013-10-01  

If needed a canned case could be set-up. However, I think there might also be a commit soon of the 35 day tests that would also allow for easy testing of this. 

## Additional context
More details of this problem can be found in the presentation [here](https://docs.google.com/presentation/d/1XSxEc0Ku2XZoT3GN-oFyj7nhUm4TGZNtH_fd0pdmh6I/edit?usp=sharing) and document [here](https://docs.google.com/document/d/19-AocyiyjbD-0FYm2ZV_Ih0bnAZLJ3nndJVcouu39eo/edit?usp=sharing). 

## Output

The errors usually look something like this: 
```
Range_check Warning:PT UPDATE max =    4709475.78755988       min = 
  -11395352.8117109     
 Range violation on: 2012/ 1/ 2  0: 5: 0
NOTE from PE     0: ==> Error from range_check: data out of bound
Warn_K= 127 (i,j)=  122  373 (lon,lat)=279.392  45.599 PT UPDATE =1751.37098
     K= 126    273.14129
```

**Comment by JessicaMeixner-NOAA** [comment]
The goal of setting FSICS=0 and FSICL=0 is to have changing ice in lakes.  It was found that by turning off fractional grid, with either FSICS/L=0 or FSICS/L=99999 the ice coverage changes.  See the figure from @LydiaStefanova-NOAA below: 
<img width="889" alt="Screen Shot 2021-12-01 at 8 03 07 AM" src="https://user-images.githubusercontent.com/22549231/144239217-4c236ef7-97a6-4b1d-a1e4-8a3357114175.png">

The non-frac grid runs were only out to 2 days, which is before the frac-grid model failed for this IC date.  The non-frac grid runs have the same settings more/less as p7.2 except non-fractional grid, no aerosols and CA was turned back on.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Is this issue resolved?

**Comment by JessicaMeixner-NOAA** [comment]
It seems so, but we've still not been able to run p8b to confirm definitively.  It's unclear why this is now seems to be working, so it's possible problems still exist and might cause additional failures in the future.

**Comment by JessicaMeixner-NOAA** [comment]
P8b was run successfully with FSICS/L=0, so I'm closing this issue.  The cause of the original problem is still unknown.
