### ISSUE TITLE
add semi-lagrangian sedimentation of graupel and update the namelist variables

### ISSUE THREAD

**Issue by RuiyuSun** [ufs-community/ufs-weather-model#922]
The semi-Lagrangian sedimentation of graupel is added. The namelist variables controlling the semi-Lagrangian sedimentation of precipitation (rain and graupel) are modified. Now SEDI_SEMI and DECFL is the switch. DECFL is the deformed CFL factor.

Semi-Lagrangian sedimentation of precipitation is added as an option and does not change results before it is turned on.

## Related to

https://github.com/NOAA-EMC/fv3atm/pull/426

**Comment by climbfuji** [comment]
Closed by https://github.com/ufs-community/ufs-weather-model/pull/923
