### ISSUE TITLE
Is control_flake really using the flake model?

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#936]
## Description
I think the `control_flake` test is not using the flake model (but hopefully someone will correct me to be wrong).

The namelist used by the regression test is `control_flake.nml.IN`, which has no option `lkm`. According to `GFS_typedefs.F90`, the option `lkm` is zero by default, which means no flake model. It needs to be set to one to activate the flake model, in addition to `flake_driver` being in the suite definition file. The code in `GFS_surface_composites_pre_run` that decides whether to use the flake model for a given horizontal grid column is:
```
      do i = 1, im
        if ((wet(i) .or. icy(i)) .and. lakefrac(i) > zero) then
          lake(i) = .true.
          if (lkm == 1 .and. lakefrac(i) >= 0.15 .and. lakedepth(i) > one) then
            use_flake(i) = .true.
          else
            use_flake(i) = .false.
          endif
        else
          lake(i) = .false.
          use_flake(i) = .false.
        endif
      enddo
```

## Solution
If the above is true, do the following:
1. Add a consistency check in `flake_driver_init` that sets the CCPP error message and flag if `lkm` is not one. Test with currrent `control_flake` test. The model should abort during the physics init.
2. Add `lkm = 1` to the namelist template `control_flake.nml.IN` and try again. The model should not fail in the physics init, and hopefully run to completion.

**Comment by SamuelTrahanNOAA** [comment]
This is still a problem with the current version of ufs-weather-model. However, there is another problem: the mandatory lake input data is missing in both control_flake and rap_control_flake as described in #1075

**Comment by arunchawla-NOAA** [comment]
@HelinWei-NOAA @barlage any insights here ? What should we do ?

**Comment by arunchawla-NOAA** [comment]
is this different from issue #1075 ?

**Comment by barlage** [comment]
@YihuaWu-NOAA we need to address these two flake related github issues. 

Or in general, we need to review the testing related to flake, purge what isn't necessary and confirm that those tests that are necessary are working correctly.

**Comment by YihuaWu-NOAA** [comment]
No, Control_flake run does not use the flake model.




*Yihua----------------------------------------------------Yihua Wu, Ph D*I.M.
Systems Group
NOAA/NWS/NCEP/EMC
5830 University Research Court, Room: 2031
College Park, Maryland 20740, USA
Phone: (301)-683-3691
Fax:       (301)-683-3703

**Comment by barlage** [comment]
@YihuaWu-NOAA please provide more information. why is control_flake there? can it be removed?

**Comment by YihuaWu-NOAA** [comment]
The default lkm value is 0.  This means that even though the flake physics
is in the suite, it is not used.
Yes, it can be removed.




*Yihua----------------------------------------------------Yihua Wu, Ph D*I.M.
Systems Group
NOAA/NWS/NCEP/EMC
5830 University Research Court, Room: 2031
College Park, Maryland 20740, USA
Phone: (301)-683-3691
Fax:       (301)-683-3703

**Comment by arunchawla-NOAA** [comment]
@YihuaWu-NOAA will you be creating a PR to remove this ?

**Comment by junwang-noaa** [comment]
@YihuaWu-NOAA Can you remove the control_flake test? Thanks

**Comment by YihuaWu-NOAA** [comment]
These two suites were not created by me.  I need permission from him or her
who created these.



*Yihua----------------------------------------------------Yihua Wu, Ph D*I.M.
Systems Group
NOAA/NWS/NCEP/EMC
5830 University Research Court, Room: 2031
College Park, Maryland 20740, USA
Phone: (301)-683-3691
Fax:       (301)-683-3703

**Comment by SamuelTrahanNOAA** [comment]
This is corrected in @HelinWei-NOAA's clm_lake.v9 branch, and also in my branch off of his branch, where I added the CLM Lake Model.
