### ISSUE TITLE
Inconsistent 'calendar' parameter used in model_configure templates

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#942]
Various model_configure templates in tests/parm directory are setting calendar parameter to 'julian' while other are not (commented out):
```
esg_HAFS_v0_hwrf-model_configure.IN:calendar:                'julian'
model_configure_hafs_shared.IN:calendar:                'julian'
model_configure_hafs.IN:calendar:                'julian'
cpt.nml.IN:#       calendar = 'julian'
wam.nml.IN:#       calendar = 'julian'
model_configure_regional.IN:calendar:                'julian'
csawmg3shoc127.nml.IN:#       calendar = 'julian'
model_configure_fhout.IN:calendar:                'julian'
csawmgshoc.nml.IN:#       calendar = 'julian'
gsd_sar-model_configure.IN:calendar:                'julian'
stretched-nest-quilt-model_configure.IN:calendar:                'julian'
datm_cdeps_configure.IN:calendar:                'julian'
model_configure.IN:calendar:                'julian'
```
The default value is 'gregorian' (set in fv3_cap.F90) which is consistent with the default calendar set during ESMF initialization (see main program). Why are we using Julian calendar?

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA I think this is because the UFS is using GFS physics, in which the physics schemes such as radiation and land surface schemes are using Julian date. Unless we can use the 'Gregorian' date there, we have to use 'Julian' date for consistency.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA I think this is because the UFS is using GFS physics, in which the physics schemes such as radiation and land surface schemes are using Julian date. Unless we can use the 'Gregorian' date there, we have to use 'Julian' date for consistency.

Julian day and Julian calendar are different things. If physics schemes are using Julian calendar (which I doubt) they are incorrect and should be using Gregorian calendar.

**Comment by DusanJovic-NOAA** [comment]
I think we should remove:
`calendar:                'julian'`
from all model_configure files a just set 'gregorian' as a default.

**Comment by climbfuji** [comment]
We don’t use Julian calendar, that would be a mess. @dusanjovic-noaa is right, we (Noah MP amongst others) use Julian day, which corresponds to counting the number of days since the beginning of the year.

**Comment by junwang-noaa** [comment]
Thanks for the clarification. Do we want to get the physics developers to
clear this up before we remove the "Julian" as the calendar option?

**Comment by climbfuji** [comment]
I don’t understand, what do you want to clear up? Julian days can be used independently of the calendar, and there is no need to remove them.

**Comment by yangfanglin** [comment]
Julian days are used in astronomical / radiation calculations in the current physics.

**Comment by junwang-noaa** [comment]
@climbfuji Sorry, what I mean is to remove the following line as Dusan suggested:

```calendar: 'julian'```

**Comment by climbfuji** [comment]
I think that can be done anytime, the physics don’t care.

**Comment by DusanJovic-NOAA** [comment]
Are we ever going to use calendar that is not Gregorian? If not, then I suggest that we remove the code that reads this option from configure file. Also all history files have two attributes specifying calendar:
```
        double time(time) ;
                time:calendar = "JULIAN" ;
                time:calendar_type = "JULIAN" ;
```
which is redundant. One is enough. We can leave `calendar` and remove `calendar_type`, or simply remove both.

**Comment by junwang-noaa** [comment]
The PR was committed, the issue will be closed.

**Comment by junwang-noaa** [comment]
The PR was committed, the issue will be closed.

**Comment by DusanJovic-NOAA** [comment]
This was not resolved in #1265

https://github.com/ufs-community/ufs-weather-model/pull/1265#issuecomment-1161973755

**Comment by junwang-noaa** [comment]
Thanks, we may need to update the code to write out consistent calendar type in the restart files.

**Comment by DusanJovic-NOAA** [comment]
Consistent calendar type will be written out in the restart files. But because the restart files (coupler.res) in the baselines have 'incorrect' calendar type we need updated input data.

**Comment by junwang-noaa** [comment]
I see, maybe we need to update the input data directory then.

**Comment by DeniseWorthen** [comment]
Need update input data which is used for warm start tests (gdas, gdas-wave).
