### ISSUE TITLE
Model crashes in debug model with do_ca=True, warm_start=True, but without CA restarts

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-weather-model#955]
## Description
In debug mode, the model crashes, and in production mode, the model runs, but gives unphysical answers when warm starting the model and Cellular Automata active, but not not suppling the model CA restarts.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. Run a warm start case with DO_CA=True in debug mode without CA restarts, such as starting with GFSv16 initial conditions.
2. Model will SEGFAULT in update_ca.F90

## Additional context

Problem has been solved, and PR will be issued shortly.

**Comment by climbfuji** [comment]
Closed via https://github.com/ufs-community/ufs-weather-model/pull/943
