### ISSUE TITLE
fv3_esg_HAFS_v0_hwrf_thompson_debug fails when compiling with -init=snan,arrays on Cheyenne.intel

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#958]
## Description

In PR #935, the compile flag ``-init=snan,arrays`` was added for Intel debug. On Cheyenne, the 
``fv3_esg_HAFS_v0_hwrf_thompson_debug`` test failed with 

```MPT: shepherd terminated: r2i3n34.ib0.cheyenne.ucar.edu - job aborting```

which usually indicates an issue w/ memory. 

### To Reproduce:

Run ``fv3_esg_HAFS_v0_hwrf_thompson_debug`` test on Cheyenne.intel. The job fails as described. The  ``dynf000.nc`` is produced but not the phyf000.nc file. 

Adding additional resources for the job (e.g. ``#PBS -l select=6:ncpus=18:mpiprocs=18``) allows the job to complete.

**Comment by climbfuji** [comment]
We should consider removing the `fv3_*_HAFS_v0_hwrf_thompson*` tests entirely (including test setup files and input data), they are superseded by the new `*hafs*` (lowercase) tests.

**Comment by DeniseWorthen** [comment]
So that looks like these 4 tests both Intel and GNU:

```
fv3_HAFS_v0_hwrf_thompson
fv3_esg_HAFS_v0_hwrf_thompson
fv3_HAFS_v0_hwrf_thompson_debug
fv3_esg_HAFS_v0_hwrf_thompson_debug
```

**Comment by BinLiu-NOAA** [comment]
@climbfuji, Agreed! We can add a hafs_regional_atm_hwrf_thompson test (or something similar) in the HAFS RT section, and retire these following four RTs:
fv3_HAFS_v0_hwrf_thompson
fv3_esg_HAFS_v0_hwrf_thompson
fv3_HAFS_v0_hwrf_thompson_debug
fv3_esg_HAFS_v0_hwrf_thompson_debug

**Comment by climbfuji** [comment]
> So that looks like these 4 tests both Intel and GNU:
> 
> ```
> fv3_HAFS_v0_hwrf_thompson
> fv3_esg_HAFS_v0_hwrf_thompson
> fv3_HAFS_v0_hwrf_thompson_debug
> fv3_esg_HAFS_v0_hwrf_thompson_debug
> ```

Yes, I think these can go. Note that this will mean that some "flavors" of the PBL scheme (triggered by the HWRF_PBL switch) will no longger be tested.

**Comment by junwang-noaa** [comment]
@BinLiu-NOAA Can we remove those 4 tests and you can create a hafs_regional_atm_hwrf_thompson test  in HAFS RT section later? Thanks.

**Comment by BinLiu-NOAA** [comment]
@junwang-noaa, That sounds good to me. I can work with @ChunxiZhang-NOAA to add a hafs_regional_atm_hwrf_thompson test in the HAFS RT section later. Thanks!

**Comment by climbfuji** [comment]
The `fv3_*_HAFS_*` tests were removed in a recent PR (#963).
