### ISSUE TITLE
rt.sh Rocoto support is broken

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#980]
## Description
The bugs:
1. The "jet" platforms aren't detected since the code looks for "jet" instead of "jet.*"
2. The WW3 dependencies are broken
3. The job deleted the "out" and "err" files.

### To Reproduce:
Try to run the regression test system using Rocoto on Jet.

**Comment by junwang-noaa** [comment]
Code updates were merged in PR#981.
