### ISSUE TITLE
4DIAU bug when iau_filter_increments=T

### ISSUE THREAD

**Issue by jswhit** [ufs-community/ufs-weather-model#989]
## Description
The 4DIAU produces incorrect results when when the parameter iau_filter_increments=T and more than one increment file is specified.  The time bounds for the IAU interval are computed incorrectly, leading to incorrect filter weights that were applied outside the designated time range.   The 4DIAU with constant weights, and 3DIAU (with a single increment file specified) were not affected by this bug.

### To Reproduce:
set iau_filter_increments=T and specify more than one file in iau_inc_files.  In the model stdout, look for 'filter wt' and you will see that the weights are incorrect and applied outside the time range specified in iaufhrs.  If only a single file is specified in iau_inc_files, the results are correct, or if iau_filter_increments=F (the operational setting) the results are correct.

**Comment by jswhit** [comment]
FIx in https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/167

also see
https://github.com/ufs-community/ufs-weather-model/pull/990
https://github.com/NOAA-EMC/fv3atm/pull/458

**Comment by yangfanglin** [comment]
Jeff,  does this bug exist in current operation ?

**Comment by jswhit** [comment]
@yangfanglin yes the bug exists, but it is not activated with the current operational settings (since iau_filter_increments=F in operations)

**Comment by junwang-noaa** [comment]
The code was committed. The issue will be closed.
