### ISSUE TITLE
autort script deleted code directory when committing log file failed

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#994]
## Description
Currently the code directory will be removed when autort finishes running RT but fails to commit the RT log file to user's ufs-weather-model branch. A fix is needed to keep the code directory so that the RT log file can be sent to the developers and let them commit the log file to their ufs-weather-model branch. This only happened to certain developers with branches that can't be committed by the ufs-weather-model code managers.

## Additional context
When a fix is ready, a ufs-weather-model PR will be created.

**Comment by BrianCurtis-NOAA** [comment]
I've addressed this in the autort-bl branch of my ufs-weather-model fork. It's been tested and went live last week. Does this code need to get into develop branch before closing this @junwang-noaa ?

**Comment by BrianCurtis-NOAA** [comment]
The deletion of directories is moved into rt_auto.py and has been working as expected for a week now. Nothing has been getting deleted before a PR is finished. Closing.
