### ISSUE TITLE
disk quota issue when running regression test on dell

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#999]
## Description
Some users and code managers got disk quota issue when running the full regression test on dell. The total disk space required to run full set of regression test is 1.5T. Several tests failed with error "cat: write error: Disk quota exceeded". This happened in both baseline creation and the regular regression runs.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. Clean up ptmp: rm -rf /gpfs/dell2/ptmp/Jun.Wang/*
2. Checkout the ufs-weather-model develop branch
3. Run RT: ./rt.sh -e 
after that check tests/RegressionTests_wcoss_dell_p3.log

**Comment by SamuelTrahanNOAA** [comment]
What happens if you use the -d option to rt.sh? It appears run_test.sh will delete the run directory for each test that is not needed if you use `rt.sh -d`.

**Comment by junwang-noaa** [comment]
Yes, This is to reduce the disk space usage as we got the disk quota issue.

**Comment by junwang-noaa** [comment]
@binli2337 I think the issue is fixed. Can we close the issue? Thanks

**Comment by binli2337** [comment]
@junwang-noaa Yes, the issue has been fixed. Please close issue. Thanks.
